### ISSUE TITLE
Alias 'postgres' adapter name to 'postgresql'

### ISSUE THREAD

**Issue by rhymes** [jeremyevans/sequel#1004]
Is it possible to alias the adapter 'postgresql' to the adapter 'postgres' ?

The rationale for this is that Rails ( http://guides.rubyonrails.org/configuring.html#connection-preference ), libpq ( http://www.postgresql.org/docs/9.4/static/libpq-connect.html ) and other libraries use 'postgresql' as the adapter name for either connection strings or connection params. Sequel does not.

**Comment by jeremyevans** [comment]
I've previously rejected this, but that was before connection strings were supported in libpq.  Now that libpq supports connection strings and uses `postgresql://` and not `postgres://`, I agree that Sequel should support `postgresql://`.  I'll implement this today.

**Comment by jeremyevans** [comment]
Fixed by 1932854cc7def82b665bca80ba14cf38f660f617
