### ISSUE TITLE
jsonb_ops return json_op instead of jsonb_op

### ISSUE THREAD

**Issue by fluxlife** [jeremyevans/sequel#1005]
Firstly, I must disclaim that I may be doing this wrong. 

So as an example..I have a jsonb column called _people_. The structure looks like this:
```json
{
  "name": "Yoda",
  "friends":[{"name":"Obi-Wan", "rel":"fellow Jedi",....}]
}
```
I would like to query the the _friends_ property as a dataset.

So my first inclination was to 
```
Sequel.pg_jsonb_op(:people).to_recordset
```
which properly generates:
```
jsonb_to_recordset("people")
```
but as I mentioned before, I just want the _friends_ dataset... so then I do this
```
Sequel.pg_jsonb_op(:people)['friends'].to_recordset
```
which generates:
```
json_to_recordset(("people" -> 'friends'))
```
Notice that the function now went from **jsonb_to_recordset** to **json_to_recordset**

The way I have temporarily remedied this is by calling pg_json_op again on the array of friends like so:
```
Sequel.pg_jsonb_op(Sequel.pg_jsonb_op(:people)['friends'])).to_recordset
```
which then generates the expected:
```
jsonb_to_recordset(("people" -> 'friends'))
```
But it just seems unnecessary to call Sequel.pg_jsonb_op twice.

I think this is all happening because whenever I call:
```
Sequel.pg_jsonb_op(:people)['friends']
```
I get a `Sequel::Postgres::JSONOp` object back instead of a `Sequel::Postgres::JSONBOp`

**Comment by jeremyevans** [comment]
Thanks for the report. This is definitely a bug.  I have a fix prepared, it should be pushed to GitHub later today.

**Comment by fluxlife** [comment]
Thank you for all your hard work!
