### ISSUE TITLE
Bound checking on PG Ranges creates deprecation warnings on MRI 2.2.1.

### ISSUE THREAD

**Issue by fluxlife** [jeremyevans/sequel#1008]
I have a tstz range column in PG 9.4 named 'active'. It's being used in a model and I have the pg_range/ops extension.

Whenever I call active.unbounded_end? (or similar methods that check bounds) on the attribute of the model, I get this warning:
```
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/sequel-4.22.0/lib/sequel/model/base.rb:1202: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
```
immediately followed by:
```
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/sequel-4.22.0/lib/sequel/model/base.rb:1202: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```
Not sure if it's anything to worry about, but wanted to give a heads up just in case.

**Comment by jeremyevans** [comment]
I'd like to fix this if possible, but try as I might, I can't get that warning to show up.  The warning message you give is for code inside `Model#[]=`, which should only happen if you are calling a setter method (e.g. `active=`), it shouldn't happen by calling `unbounded_end?` on a getter method (`active`).  It also indicates `Comparable#==` being called, but `Sequel::Postgres::PGRange` does not include `Comparable`, and even if it did, it defines its own `#==` method which would take precedence.  Nowhere in Sequel is `Comparable` used or `<=>` defined.

Is it possible for you to submit a self contained example showing the issue?  Once I get an example that reproduces the issue, I should be able to figure out the cause.

**Comment by fluxlife** [comment]
So I created a new environment and went to test this and was not getting any errors. I went back to the environment where I was getting the error and it continued to have the error. I then ran a `bundle update` on the original environment and I no longer get the warning.

Sorry for the false alarm.
