### ISSUE TITLE
Can't use a subclass with Sequel::Model

### ISSUE THREAD

**Issue by grant-olson** [jeremyevans/sequel#1009]
This works:

```
class Foo < Sequel::Model
  self.db = NON_DEFAULT_CONN
  ...
end
```

But I need to add that line to 20 classes. I try:

```
class NonDefaultModel < Sequel::Model
  self.db = NON_DEFAULT_CONN
end

class Foo < NonDefaultModel
  ...
end
```

But now when I try to use the `Foo` model, it looks for a table `non_default_models` based on the superclass name.

**Comment by grant-olson** [comment]
I also tried to use this real code to fix my problem:

```
# Patch in correct sequel model, which might not be the default when, for example
# the gem is included in doofenschmirtz
models = Webkite::Radius::DB.constants.map { |c| Webkite::Radius::DB.const_get(c)}.
        select { |c| c.is_a?(Class)}.
        select { |c| c.ancestors.include? Sequel::Model}

puts "!" * 1000
puts models.inspect
models.each { |m| m.db = Webkite::Radius::DB::CONN }
```

But then it loses the settings I did in the original classes like `set_primary_key` and Sequel complains when I try to create records.

**Comment by jeremyevans** [comment]
If you want to use an abstract base class, you need to use anonymous class creation:

    NonDefaultModel = Class.new(Sequel::Model)
    NonDefaultModel.db = NON_DEFAULT_CONN

But you may just want to use the following form if you want to use implicit table names on a non-default database:

    class Foo < Sequel::Model(NON_DEFAULT_CONN)
    end

Note that as mentioned in the contribution guidelines, questions about how to use Sequel should be asked on the sequel-talk Google Group or IRC.  GitHub Issues should only be used for reporting bugs in Sequel.

**Comment by TSMMark** [comment]
In case anyone else ends up in this issue as I did,

I believe the modern way to do this is to define your custom abstract base class inside another model, as described in code comment here:

https://github.com/jeremyevans/sequel/blob/aecf74102692f4792f6925e6ecc7c49e3663d1cd/lib/sequel/model/base.rb#L117-L136
