### ISSUE TITLE
Removal from ::Sequel::DATABASES inconsistent

### ISSUE THREAD

**Issue by rboykin** [jeremyevans/sequel#1017]
In lib/sequel/database/connecting.rb, self.connect will handle the disconnect automatically if a block is passed into the method.  As part of the automatic disconnect logic when a block is present, there is a call to remove the database from the ::Sequel::DATABASES array.  Shouldn't this logic of removal from the ::Sequel::DATABASES array also occur in the disconnect method when no block is passed into the self.connect method and the client manually issues the disconnect method?  Or are you assuming the client will do the removal from the ::Sequel::DATABASES array in that case?

**Comment by jeremyevans** [comment]
Correct, the client is responsible for the removal if a block is not passed to `Sequel.connect`.  The main use case for `Database#disconnect` is in forking webservers, where automatic removal from `::Sequel::DATABASES` would be undesireable.

**Comment by rboykin** [comment]
This might be worth documenting within the disconnect logic.  I do not find anywhere in the documentation.

**Comment by jeremyevans** [comment]
I agree, I'll add a note about this to the documention.

**Comment by rboykin** [comment]
Thanks @jeremyevans for your quick responses.
