### ISSUE TITLE
IPAddr == broken for CIDR

### ISSUE THREAD

**Issue by andreas-kopecky** [jeremyevans/sequel#1021]
Hi,

I know it's generally out of scope for your library but i thought i'd put in an issue here too since pg_inet extension uses IPAddr:

The equality method (==) does not take netmask into account when handling CIDR types. Therefor IPAddr.new("10.0.0.0/8") == IPAddr.new("10.0.0.0/16) is true. You might want to monkey patch this or so til the standard lib is patched

**Comment by bjmllr** [comment]
`IPAddr#eql?` will correctly identify `IPAddr`s with different masks, you may wish to use that instead.

**Comment by jeremyevans** [comment]
You are correct, this is out of scope.  File a bug on the ruby bug tracker, or add a monkey patch to your app locally.  I don't think Sequel should monkey patch core classes to work around bugs in them.

**Comment by andreas-kopecky** [comment]
I agree. Just thought to bring it to your attention so you can make that
decision consciously :)
Am 16.06.2015 17:08 schrieb "Jeremy Evans" <notifications@github.com>:
