### ISSUE TITLE
AdapterNotFound using the binary

### ISSUE THREAD

**Issue by drwl** [jeremyevans/sequel#1032]
I'm getting `Error: Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/sqlite3` when trying to run migrations using the binary. Connecting with the binary in general throws the error, while using the gem does not.

```
alee:the_orb alee$ sequel sqlite3://mirari.db
Error: Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/sqlite3
/Users/alee/.rvm/gems/ruby-2.1.2/gems/sequel-4.22.0/lib/sequel/database/connecting.rb:97:in `require'
```

```
[2] pry(main)> require 'sequel'
=> true
[3] pry(main)> db = Sequel.connect('sqlite://mirari.db')
=> #<Sequel::SQLite::Database: "sqlite://mirari.db">`
```

Relevant information:
Ruby: 2.1.2
Sequel: 4.2.2
sqlite3 (1.3.10, 1.3.9)

**Comment by jeremyevans** [comment]
The sequel adapter is `sqlite`, not `sqlite3`.  Try `sequel sqlite://mirari.db` on the command line and it should work just as it does in irb.

**Comment by drwl** [comment]
I ran into this issue today. After some googling I found this answer on [stackoverflow](http://stackoverflow.com/questions/15118633/sequel-adapters-sequeladapternotfound). I added sequel to my gem file and ran the command with `bundle exec`
