### ISSUE TITLE
NoMethodError Exception: undefined method `each' for "name = 'John'":String when updating using strings.

### ISSUE THREAD

**Issue by zhaohanweng** [jeremyevans/sequel#1035]
I have a problem when updating postgres arrays.
```
class User < Sequel::Model
end

user = User.first
user.update(name: "John") # this is OK
```
if I try to use
```
user.update("name = 'John'") # this will give me error

NoMethodError Exception: undefined method `each' for "name = 'John'":String
```

In this case I can just use the former way. But when I try to update postgres array how can I do it properly?

My expected way will be this, but it gives me the same error.
```
user.update("array_column = array_column || '{1,2,3,}'")
```

One thing I notice is I can do this string update when calling from class.
```
User.update("array_column = array_column || '{1,2,3,}'") # notice User is class now.
```
This is fine.

**Comment by jeremyevans** [comment]
`Model#update` accepts a hash, not a string, unlike `Dataset#update`.  In general, models work with values, trying to use expressions will not work.  You need to drop down to the dataset level using `Model#this`:

```ruby
user.this.update("array_column = array_column || '{1,2,3,}'")
```

Alternatively, you can pass in a new array, if you have the existing array value:

```
user.update(:array_column=>existing_array_object + [1,2,3])
```

Note that as mentioned in the contribution guidelines, GitHub Issues should not be used as a help form.  General usage questions like this should be asked on the sequel-talk Google Group or on IRC.  You should only be adding an issue if you are sure the behavior is a bug in Sequel.

**Comment by zhaohanweng** [comment]
Thank you very much for the response.
and my apologies for this.
