### ISSUE TITLE
Is there a way to use Sequel and Active Record with the same underlying db connection / transaction?

### ISSUE THREAD

**Issue by akum32** [jeremyevans/sequel#1038]
Hi,

Is there a way to use Sequel and Active Record with the same underlying db connection / transaction?

Basically I have some existing code that persists data using active record, and some existing code that persists some other data using Sequel to build up and execute raw sql statements. Rather than convert the active record code to Sequel, is there a way I can build a wrapper class that can effectively call these two persistence mechanisms using the same underlying transaction?

Thanks

**Comment by mpalmer** [comment]
[This thread](https://groups.google.com/forum/#!searchin/sequel-talk/activerecord$20share$20connection/sequel-talk/kVdadGSitd0/viYDraOwOf0J) suggests that it isn't going to work well.  It's old, but I'd be surprised if the situation has changed.

**Comment by jeremyevans** [comment]
Some people have had some luck getting ActiveRecord to use Sequel's connection pool.  I don't know anyone that has gotten things to work by having Sequel use ActiveRecord's connection pool.  At least for the postgres adapter, it will definitely not work, but it may work for other adapters.

As the contribution guidelines state, general usage questions about Sequel should be asked on the sequel-talk Google Group or IRC.  You should only be opening an issue in GitHub Issues if you are sure it is a bug in Sequel itself.
