### ISSUE TITLE
Semicolons aren't sanitized

### ISSUE THREAD

**Issue by blinsay** [jeremyevans/sequel#1044]
I ran into an issue today where a semicolon in a `varchar` field isn't being properly sanitized. I'm using the JDBC connector and Amazon's [Redshift driver](http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html).

```sql
redshift => create table foo (thing varchar);
CREATE TABLE
```

```ruby
[84] pry(main)> db[:foo].insert(thing: "'hi';")
E, [2015-07-21T18:11:45.474000 #98200] ERROR -- : Java::JavaSql::SQLException: [Amazon](500310) Invalid operation: unterminated quoted string at or near "'''hi''";: INSERT INTO "FOO" ("THING") VALUES ('''hi'';')
Sequel::DatabaseError: Java::JavaSql::SQLException: [Amazon](500310) Invalid operation: unterminated quoted string at or near "'''hi''";
from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:483)
```

Does this look like a bug here or in the Redshift driver? I can work around it for now by stripping the semicolons out of my input.

Thanks a bunch!

**Comment by jeremyevans** [comment]
It looks like RedShift doesn't use SQL standard conforming strings.  I think that was added to PostgreSQL after RedShift forked.  You should probably override Dataset#literal_string for the database's datasets to do proper escaping.  Sequel doesn't officially support Redshift, only PostgreSQL, so this is not an issue with Sequel.

One possible way to work around the issue without modifying literalization is to use bound variables:

```ruby
db[:foo].call(:insert, {:n=>"'hi';"}, thing: :$n)
```

**Comment by blinsay** [comment]
> It looks like RedShift doesn't use SQL standard conforming strings. I think that was added to PostgreSQL after RedShift forked.

Ouch.

Thanks for taking the time to look into this! I'll take a look at messing with `Dataset#literal_string`.
