### ISSUE TITLE
Sequel::Error: can only parse the schema for a dataset with a single from table

### ISSUE THREAD

**Issue by gsdean** [jeremyevans/sequel#1045]
I'd love to understand what the fundamental limitation of this is. I understand with functions, cte, etc. the schema might be incomplete, but this seems like massively useful data for clients to display results.

Happy to work on this myself, just wanted to get a better understanding of the limitation before I dug too much into it...

**Comment by jeremyevans** [comment]
The fundamental limitation is that `Database#schema` doesn't execute a query and try to get schema information from it, it just takes a table name and looks up the table information using the system catalogs or system information functions.  There's no way it can handle an arbitrary query with multiple tables.
