### ISSUE TITLE
Docs: plugin validate_associated returns 404 on website

### ISSUE THREAD

**Issue by kematzy** [jeremyevans/sequel#1051]
Typo discovered in file: https://github.com/jeremyevans/sequel/blob/master/www/pages/plugins.html.erb#L21

Current code

````html
... href="rdoc-plugins/classes/Sequel/Plugins/ValidatesAssociated.html">validates_associated</a>...
````
but should be: 

````html
... href="rdoc-plugins/classes/Sequel/Plugins/ValidateAssociated.html">validate_associated</a>...
````

**Note** the wrongly added 's' in Validate(s) and validate(s).

**Comment by jeremyevans** [comment]
Thanks for the heads up, I'll fix this soon.
