### ISSUE TITLE
DateTime columns being returned as Strings from "jdbc:sqlite:" connections.

### ISSUE THREAD

**Issue by clonezone** [jeremyevans/sequel#1052]
Problem is happening with Sequel v4.24/jdbc-sqlite3 v3.8.10.1 on JRuby v9.0.0.0 when passing "jdbc:sqlite:file" to Sequel.connect(). Using the same code and identical database file with Sequel v4.24/sqlite3 v1.3.10 on Rubinius v2.5.7 and passing "sqlite:file" to Sequel.connect() results in appropriately typed column values.

Are there any alternatives to me manually invoking DB.to_appliction_timestamp() everywhere?

**Comment by jeremyevans** [comment]
SQLite doesn't support date/time columns, support is emulated by the driver/adapter, it's up to the driver/adapter how the emulation is done, and there are many cases where jdbc-sqlite3 emulates support differently than sqlite3 does.

So this isn't a bug, it's adapter-specific behavior.  Using jdbc-sqlite, you'll either have to manually convert, or you'll have to modify the jdbc-sqlite driver to emulate date/time support more similarly to how sqlite3 does.

I wish things were different, but IMO lack of date/time support is one of SQLite's biggest problems, along with lack of real ALTER TABLE support.  Even sqlite3 doesn't emulate date/time properly in all cases, such as expressions on date/time columns.
