### ISSUE TITLE
Any chance for mruby support?

### ISSUE THREAD

**Issue by dmajkic** [jeremyevans/sequel#1056]
Yes - mruby is far from full CRuby implementation. Yes - it lacks a lot of std lib. On the other hand - it is usable in embedded world and as a scripting extension to desktop type apps. 

Mruby supports mgems out of the box and there is nice sqlite driver. 

It would be great if Sequel core could run on it too.

**Comment by jeremyevans** [comment]
I haven't done any testing with mruby, and I don't currently have plans to do so.  I won't rule out future support, but it's not on the radar currently.

Note that as this is not a bug in Sequel, you should probably ask questions like this on the sequel-talk Google Group or IRC, as mentioned in the contribution guidelines.

**Comment by strcmp** [comment]
Sequel still supports 1.8 as far as I'm aware, that could make the effort a slightly easier one :)
