### ISSUE TITLE
How do I to prevent symbolization of column names?

### ISSUE THREAD

**Issue by thedeeno** [jeremyevans/sequel#1057]
I'm using the tinytds driver. When using the `tiny_tds` gem directly my camelCased column names are returned as strings unmodified. When using sequel's tiny_tds adapter all the column names are lowercased and symbolized.

Thus `'customerName' => :customername` which makes it difficult to automatically work with these names, especially if I want to automatically convert `'customerName' => :customer_name` for example.

How can I prevent this symbolization and downcasing? I know I can alias every column, but that's a little cumbersome given that the column names are already in a workable format if they weren't modified.

P.S. Great work on this library. It looks really powerful.

**Comment by jeremyevans** [comment]
You can turn off the uppercasing on input/lowercasing on output of identifiers via `DB.identifier_input_method = DB.identifier_output_method = nil`.

Note that as mentioned in the contribution guidelines, questions about how to use Sequel should be asked on the sequel-talk Google Group or IRC.  GitHub Issues should only be used to report bugs in the library.

**Comment by thedeeno** [comment]
Thank you. I'll post to the Google group in the future.
