### ISSUE TITLE
Validation problems

### ISSUE THREAD

**Issue by AlexCppns** [jeremyevans/sequel#1058]
Hello there,

My validation method stopped working after I placed a self.update inside my Model:
```
NoMethodError - undefined method `validates_unique' for #<Models::ModelName>
```
The code:
```
 def validate
      super
      validates_unique([:column_1, :column_2])
 end

...

def custom_update(params, other_params)
      self.update(params) # code breaks here
end
```

I am using sequel (4.22.0)

**Comment by jeremyevans** [comment]
Did you load the `validation_helpers` plugin?  `validates_unique` is not part of the base Sequel::Model code, it's contained in a plugin which you have to load separately.

Note that as mentioned in the contribution guidelines, questions such as this should be asked on the sequel-talk Google Group or IRC.  GitHub issues should only be used if you are sure you have found a bug in the library.
