### ISSUE TITLE
Documentation Conflict for delay option of association_pks plugin.

### ISSUE THREAD

**Issue by soupmatt** [jeremyevans/sequel#1062]
The [release notes for 4.24.0](http://sequel.jeremyevans.net/rdoc/files/doc/release_notes/4_24_0_txt.html) say to use `:delay_pks`, but the [currently published rdoc](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/AssociationPks.html) says to use `:delay`.

**Comment by jeremyevans** [comment]
:delay_pks is the correct one, I'll update the docs.  Thanks for the heads up!
