### ISSUE TITLE
Linux/PostgreSQL: Ruby Time and PostgreSQL Time have different precision on update

### ISSUE THREAD

**Issue by jonnyarnold** [jeremyevans/sequel#1063]
Hello!

We ran into a strange issue today: a test was failing on a Linux build of our Sequel-based project, but not on Mac.

It looks like Sequel stores timestamp values as `Time` instances. [This is accurate to the system clock precision,](http://ruby-doc.org/core-2.2.0/Time.html#method-c-new) which is different between Mac and Linux (1000 ns and 100 ns respectively, based on our quick test). 

In some cases the `Time` instance may store the time at a higher accuracy than the underlying database. We are using PostgreSQL, which stores time accurate to [1000 ns](http://www.postgresql.org/docs/9.1/static/datatype-datetime.html). As a result, equality comparisons between the same objects will fail:

```ruby
class MyModel < Sequel::Model
  # This class has a created_at timestamp.
end

in_memory_model = MyModel.create(created_at: Time.now)
model_from_db = MyModel.last

# The following statements are true on all instances
in_memory_model == model_from_db
in_memory_model.values[:created_at] == model_from_db.values[:created_at]

in_memory_model.update(created_at: Time.now)

# The following statements are true on Mac, false on Linux
in_memory_model == model_from_db
in_memory_model.values[:created_at] == model_from_db.values[:created_at]
```

I imagine what needs to happen is for Sequel to be aware of the underlying database's time precision and truncate in-memory values to this precision on update. It looks like this is done on creation already.

**Comment by jeremyevans** [comment]
This is expected behavior. If you want to make sure the values are the same after an update, use the `update_refresh` plugin. You may also want to use the `round_timestamps` extension if you want to round timestamp values to the database's precision when literalizing them.

**Comment by jonnyarnold** [comment]
Thank you!
