### ISSUE TITLE
Distinctive Name

### ISSUE THREAD

**Issue by jackdesert** [jeremyevans/sequel#1064]
I love this gem because it's lightweight and straight to the point. I only wish it had a name that was distinctive, as opposed to generic. 

A suggestion:

    gem "the-sequel-gem"

**Comment by jeremyevans** [comment]
Sorry, the gem name will not be changing.

**Comment by jackdesert** [comment]
I respect that---it's not trivial to change course. What have you found is the best way to talk about jeremyevans/sequel that does not confuse it with "SQL", which can also be pronounced "sequel"?

**Comment by jeremyevans** [comment]
By using the official pronunciation for SQL (S-Q-L) when referring to the language, and using the word sequel when referring to the ruby library.  That's what I do when I give presentations about Sequel.
