### ISSUE TITLE
"data too long for column" when converting from sqlite to MySQL

### ISSUE THREAD

**Issue by dtenenba** [jeremyevans/sequel#1072]
Hi,

I am trying to convert a sqlite database to MySQL using Sequel:

    sequel sqlite://$(pwd)/spb_history.sqlite -C mysql://root@localhost/packagebuilder

It fails like this:

    ...
    Begin copying records for table: viewhistory_package
    Error: Sequel::DatabaseError: Mysql::Error: Data too long for column 'name' at row 1
    /Users/dtenenba/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/sequel-4.22.0/lib/sequel/adapters/mysql.rb:175:in `query'

(I also tried it with the mysql2 adapter but that failed in the same way.

Does this mean that the sqlite database has data in it longer than the schema allows? How is that possible?

If you need me to I can post the sqlite database somewhere.

Thanks.
Dan

**Comment by jeremyevans** [comment]
SQLite doesn't support column lengths.  You can specific a length of 255, but you can add more than 255 characters.  In this case, you probably have a value in SQLite that is larger than the allowed length for the value in MySQL.

Note that the database copier is fairly simple, there are many situations that it does not handle correctly.

**Comment by dtenenba** [comment]
OK, that was helpful enough for me to find and fix several places where the actual column values were larger than what was stated in the schema. I changed the column types so they were larger than their largest actual value.

Except now I am getting an error saying that the data is too long for a column which is defined as a 'text' column in the schema. I'm not sure what to do here. There is no limit on the size of a text column, correct? So why is the conversion process complaining about it?

**Comment by jeremyevans** [comment]
The conversion process isn't complaining about it, MySQL is complaining about it.  Is it getting created as a text column in MySQL?  If so, it may be hitting the limit for a text column in MySQL (64kb).    You need to use mediumtext or longtext to get limits higher than that in MySQL, which the schema dumper/database copier is not going to use.
