### ISSUE TITLE
help with integrating seamusabshere/upsert

### ISSUE THREAD

**Issue by pschrammel** [jeremyevans/sequel#1073]
Hi,

can sombody hint me on how to integrate seamusabshere/upsert with sequel? I use postgresql db so all I would need is a postgresql connection to pass to Upsert.new. So the question is how to get access to a raw postgresql connection (in a thread save, multi db, ...manner)?

THX for your help

**Comment by jeremyevans** [comment]
You can get access to the PostgreSQL connection object via `Database#synchronize`.  Note that Sequel supports `Dataset#insert_conflict` on PostgreSQL 9.5+, which uses the native PostgreSQL support.

In the future, as mentioned in the contribution guidelines, please ask questions like this on IRC or the sequel-talk Google Group.  Only open an issue if you are sure it is a bug in Sequel itself.
