### ISSUE TITLE
Using Sequel with postgres-pr not possible

### ISSUE THREAD

**Issue by omensinger** [jeremyevans/sequel#1074]
It seems impossible to use Sequel with postgres-pr. See the first few lines of sequel/adapters/postgres.rb:

    Sequel.require 'adapters/shared/postgres'

    begin 
      require 'pg' 
      SEQUEL_POSTGRES_USES_PG = true
    rescue LoadError => e 
      SEQUEL_POSTGRES_USES_PG = false
      begin
        require 'postgres'

The problem: Even without pg installed, require 'pg' will be true and does not raise an exception because of file postgres-pr-0.7.0/lib/pg.rb, which is intended to be a compatibility layer to the C interface. 

Error message when trying to connect:
    Sequel::DatabaseConnectionError - ArgumentError: wrong number of arguments (1 for 7):
            c:/Ruby222/lib/ruby/gems/2.2.0/gems/postgres-pr-0.7.0/lib/postgres-pr/postgres-compat.rb:16:in `initialize'
            c:/Ruby222/lib/ruby/gems/2.2.0/gems/sequel-4.25.0/lib/sequel/adapters/postgres.rb:237:in `new'
            c:/Ruby222/lib/ruby/gems/2.2.0/gems/sequel-4.25.0/lib/sequel/adapters/postgres.rb:237:in `connect'

Or am I missing something?

Thank you in advance!

**Comment by jeremyevans** [comment]
postgres-pr upstream must have added the `pg` file in 0.7.0.  But they didn't make the interface compatible with ruby-pg, which seems like a bug in postgres-pr.  I recommend using my postgres-pr fork, it fixes issues in the mainstream version, and it's what I test Sequel with: `https://github.com/jeremyevans/postgres-pr`.  It's avaliable as a gem: `gem install jeremyevans-postgres-pr`.

Unfortunately, I'm not sure what other changes are in postgres-pr 0.7.0, as the upstream git is still at version 0.6.3.  They must have pushed a new gem without pushing the corresponding changes to GitHub.  Their 0.7.0 tag still has 0.6.3 as the version (see https://github.com/mneumann/postgres-pr/blob/0.7.0/lib/postgres-pr/version.rb).

I'll see if I can figure out a way to make Sequel differentiate real pg from postgres-pr's pg, so it still ends up in that rescue clause.  I'll also update the documentation to mention my postgres-pr fork.

**Comment by omensinger** [comment]
Great, thank you very much for your help! Your solution and jeremyevans-progres-pr driver works well!
