### ISSUE TITLE
Does Sequel support BIT datatype for MySQL?

### ISSUE THREAD

**Issue by kaltinril** [jeremyevans/sequel#1079]
I'm getting back an odd value for BIT fields instead of TRUE/FALSE (1/0).

 expected: false
      got: "\u0000"

I tried changed my test database to TinyInt instead of Bit, and this error goes away.

I see in the code it supports TinyInt, does it also support bit?

**Comment by jeremyevans** [comment]
How bit fields are returned depends on the underlying driver (mysql, mysql2, etc.).  BIT in MySQL can be used for more than true/false, it is designed for storing a bit-field, not just a single bit (https://dev.mysql.com/doc/refman/5.0/en/bit-type.html).

Sequel supports emulating boolean via tinyint in the mysql and mysql2 adapters, it does not support emulating boolean via BIT in either, I believe.

**Comment by kaltinril** [comment]
Ah, Thanks for the insight, I did not realize that.
