### ISSUE TITLE
Postgres foreign_key_list gets compound keys wrong.

### ISSUE THREAD

**Issue by raxoft** [jeremyevans/sequel#1081]
Hello, there is a problem with `foreign_key_list` method in Postgres adapter. When I create compound key like this (for the purposes of this testcase):
``` ruby
create_table(:compound) do
  Integer :a, :null=>false
  Integer :b, :null=>false
  primary_key [:a, :b]
  foreign_key [:b, :a], :compound, :key=>[:a, :b]
  index [:b, :a]
end
```
then `foreign_key_list` returns this:
``` ruby
[{:name=>:compound_b_fkey,
  :columns=>[:b, :a],
  :on_update=>:no_action,
  :on_delete=>:no_action,
  :deferrable=>false,
  :table=>:compound,
  :key=>[:b, :a]}]
```
That is, the referenced key is in wrong order, it should be `[:a, :b]` instead.

Postgres itself gets it right, though, as can be seen from output of `\dt+ compound`:
```
               Table "public.compound"
 Column |  Type   | Modifiers | Storage | Description 
--------+---------+-----------+---------+-------------
 a      | integer | not null  | plain   | 
 b      | integer | not null  | plain   | 
Indexes:
    "compound_pkey" PRIMARY KEY, btree (a, b)
    "compound_b_a_index" btree (b, a)
Foreign-key constraints:
    "compound_b_fkey" FOREIGN KEY (b, a) REFERENCES compound(a, b)
Referenced by:
    TABLE "compound" CONSTRAINT "compound_b_fkey" FOREIGN KEY (b, a) REFERENCES compound(a, b)
Has OIDs: no
```

Testing shows that its the `ref_ds` query which gets the sort order wrong, but I know too little about Postgres internals to dare to fix it.

Thanks for looking into this.

**Comment by jeremyevans** [comment]
This definitely looks like a bug.  I'll work on a fix right away.

**Comment by jeremyevans** [comment]
The fix is an addition of 1 character :).  I wrote another integration test for this, as soon as I have a chance to run against all of the test databases, I'll commit this.

**Comment by raxoft** [comment]
Great! Thanks for fixing this so quickly.
