### ISSUE TITLE
Association class options don't search constants in same scope they are defined

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/sequel#1082]
This is somewhat related to #298 (thus the riff on the title). If you need to specify a `:class` option on your association, and your `Sequel::Model` is in a namespace, it won't look in that namespace for the class. For example:

```ruby
module My::Models
  class Foo < Sequel::Model
    one_to_many :bars, :class => :FooBar
  end

  class FooBar < Sequel::Model
    many_to_one :foo
  end
end
```

Fails with:

```
/home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get': uninitialized constant FooBar (NameError)
```

The workaround/solution is to do `:class => :"My::Models::FooBar"` or something like `:class => FooBar.name.to_sym` (not sure if that's good Ruby or not).

**Comment by jeremyevans** [comment]
This is the expected and documented behavior (http://sequel.jeremyevans.net/rdoc/files/doc/association_basics_rdoc.html#label-Association+Scope).  If you specify the class explicitly, you need to specify the complete path to it, as lookup is done from top level.

**Comment by mwpastore** [comment]
Alrighty. Thank you!
