### ISSUE TITLE
Sequel is unable to load custom extension

### ISSUE THREAD

**Issue by ktimothy** [jeremyevans/sequel#1087]
I am writing an extension for my purposes. I have following files: 
- ```/config/sequel.rb``` - there I create a connection to db, and call ```DB.extension :my_extension```
- ```/lib/sequel/extensions/my_extension.rb``` - there an extension is defined.

I get an error:
```
.../sequel-4.25.0/lib/sequel/core.rb:137:in `require': cannot load such file -- sequel/extensions/get_shard_id (LoadError)
```

How to load my own extension?

**Comment by jeremyevans** [comment]
I see you loading `get_shard_id`, not `my_extension`.  However, if that isn't the problem, make sure that your `lib` directory is in your ruby load path at the time you load the extension.

As mentioned in the contribution guidelines, in the future, please ask questions regarding how to use Sequel on the sequel-talk Google Group or IRC.  Only add a GitHub Issue if you are sure you have found a bug in the library.

**Comment by ktimothy** [comment]
> However, if that isn't the problem
That's not.

Thanks, your solution helped me.

> please ask questions regarding how to use Sequel on the sequel-talk Google Group
Ok.
