### ISSUE TITLE
How to store enums / symbols with Sequel 

### ISSUE THREAD

**Issue by solyaris** [jeremyevans/sequel#1093]
Hi Jeremy!
First of all thank you for your great Sequel ORM! I'm just a beginner studying Sequel and I have a minor request (not an issue): 

I have to store in a column a Ruby symbol; let say an enum like field as describe in this gem: https://github.com/lwe/simple_enum

Do you maybe foresee something like that in Sequel ?
Any Idea to a clean approach to store enums ? 

It make sense the approach here:
http://stackoverflow.com/a/14466115/1786393

so storing symbols as simple Integers, with a Hash mapping stored in code ... mhhh ?

Sorry for my db ignorance
Respect
giorgio

**Comment by jeremyevans** [comment]
Personally, for enum-like functionality I prefer lookup tables with a foreign key in the main table.  Absent performance issues, I find this is the easiest way to handle enums, and it works on pretty much any database.

You can use the built in enums in PostgreSQL and MySQL, Sequel has support for both of those.

I recommend against purely application level enums, though it is pretty easy to implement those using the serialization plugin with a custom serializer/deserializer.

Defining scopes for each possible enum value is fairly easy.  However, needs are usually application specific and I'm not sure there's a good generic solution.

Note that as specified in the contribution guidelines, questions like this should be asked on the sequel-talk Google Group or IRC.  You should only be adding a GitHub Issue if you are confident you have found a bug in the library.

**Comment by solyaris** [comment]
thanks Jeremy for detailed/clear answer! 
Yes, you are right, sorry. No issue and I eventually ask on the sequel-talk Google Group.
