### ISSUE TITLE
Is there a shoulda style for sequel?

### ISSUE THREAD

**Issue by tansaku** [jeremyevans/sequel#1097]
I really like thoughbot's shoulda matchers for active_record.  Is there anything similar for sequel?

https://github.com/thoughtbot/shoulda-matchers

Many thanks in advance

**Comment by janko-m** [comment]
Kematzy created one recently, for Minitest: https://github.com/kematzy/minitest-sequel

Note that as per contribution guidelines it would be great if in future you could post questions to Google Group or the IRC channel, and use GitHub issues only for reporting bugs or creating PRs.

**Comment by tansaku** [comment]
apologies @janko-m

**Comment by tansaku** [comment]
I found an rspec one as well now https://github.com/openhood/rspec_sequel_matchers
