### ISSUE TITLE
checksum table isn't working

### ISSUE THREAD

**Issue by StephanieSunshine** [jeremyevans/sequel#1102]
How does one do a table checksum in Sequel?
```code
MariaDB [conductor]> checksum table servers;
+-------------------+------------+
| Table             | Checksum   |
+-------------------+------------+
| conductor.servers | 1760586297 |
+-------------------+------------+
1 row in set (0.00 sec)


ubuntu@ip-172-31-29-172:~/ha-minon$ irb 
2.2.1 :001 > require 'sequel'
 => true 
2.2.1 :002 > DB = Sequel.connect('mysql://xxxxx:xxxxx@mysite.lan:3306/conductor')
 => #<Sequel::MySQL::Database: "mysql://xxxxx:xxxxx@mysite.lan:3306/conductor"> 
2.2.1 :003 > DB.run 'checksum tables servers';
2.2.1 :004 > DB.run('checksum tables servers');
2.2.1 :005 > servers = DB[:servers]
2.2.1 :006 > servers.all
 => [{:server=>1, :address=>2130706433}] 
```
https://dev.mysql.com/doc/refman/5.7/en/checksum-table.html

No matter what I do I cannot get Sequel to give me the table checksum.  I can see it from the mysql console, but I get nothing in IRB.  Please advise.

**Comment by jeremyevans** [comment]
`DB['checksum table servers'].all`  This is mentioned in the README: http://sequel.jeremyevans.net/rdoc/files/README_rdoc.html#label-Arbitrary+SQL+queries

Note that as this is a question about how to do something in Sequel, and not a bug report, it should be asked on the sequel-talk Google Group or IRC, per the contribution guidelines.
