### ISSUE TITLE
Undefined method for "like" inside where clause

### ISSUE THREAD

**Issue by bobber205** [jeremyevans/sequel#1103]
README suggests writing code like this

```
APIDB[:callback_logs].where(:request.like('%summe%'))
```

But I get `undefined method 'like' for :request:Symbol`

whenever I do. I've resorted to just using ruby's match method to do this but that's super inefficient. What am I doing wrong? (On latest 4.28 version fwiw)

**Comment by jeremyevans** [comment]
That's a bug in the README.  `Symbol#like` is not defined by default.  You can use `where(Sequel.like(:request, '%summe%'))`, or `where{request.like('%summe%')}`.  I'll update the README shortly to fix this.

**Comment by bobber205** [comment]
oh man that's great thanks! <3
