### ISSUE TITLE
Oracle adapter (oci8) insert Blob

### ISSUE THREAD

**Issue by basex** [jeremyevans/sequel#1104]
I'm trying to insert some image data in a blob column.

If I use an bound variable I get "Sequel's oracle adapter does not currenctly support using a blob in a bound variable"
```ruby
Item.dataset.call(:update, {id: id, x: Sequel.blob(image_data)}, {imagedata: :$x})
```
If I try as a string I get "`encode': "\x89" from ASCII-8BIT to UTF-8"
```ruby
Item.dataset.call(:update, {id: id, x: image_data}, {imagedata: :$x})
```

If I do a regular update I get "string literal too long"
```ruby
item.update(imagedata: Sequel.blob(image_data))
```

The image data is around 800kb. Any idea how to do this?

**Comment by jeremyevans** [comment]
Unfortunately, Oracle blobs are not currently supported by Sequel.  I'll take another look at this and see if support can be added.

**Comment by basex** [comment]
Thanks a lot @jeremyevans. Working without any problem.
