### ISSUE TITLE
Updating model with Sequel.expr

### ISSUE THREAD

**Issue by tolhaje** [jeremyevans/sequel#1109]
Hi there,

I have an issue while trying to update model with Sequel.expr. 
This one doesn't work:
`Model[1].update(foo: Sequel.expr(:foo) + 1.0)`
And throws exception
`Sequel::DatabaseError: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type double precision: "#<Sequel::SQL::NumericExpression:0x007fe8c3114e60>"`

However, when I do this:
`Model.where(id: 1).update(foo: Sequel.expr(:foo) + 1.0)`
Everything works fine.

Is this a bug or feature?
Thanks!

**Comment by jeremyevans** [comment]
This is expected behavior.  Model objects require values, not expressions.  The second example works because it is a dataset, and you can pass expressions to datasets.

If you want to update a single model object with an expression, you have to use the model object's dataset:

    Model[1].this.update(foo: Sequel.expr(:foo) + 1.0)
