### ISSUE TITLE
Typing in keyword automatically adds a linebreak if auto-cap is on

### ISSUE THREAD

**Issue by hugorodgerbrown** [jeremyevans/sequel#1111]
Not sure if this is psequel, or some configuration on my machine (iMac, El Cap), but if I have "Auto-uppercase Keywords" selected and type in a keyword, not only is it capitalised, but a linebreak is added immediately afterwords, which make typing commands very tricky!

Is this the intended behaviour?

**Comment by jeremyevans** [comment]
I think you have the wrong project, this is a ruby library, not an editor.

**Comment by hugorodgerbrown** [comment]
Yup - was going for psequel - apologies.
