### ISSUE TITLE
does not find adapter when sequel is run from command line. But it works from irb console.

### ISSUE THREAD

**Issue by murtyk** [jeremyevans/sequel#1112]
murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ sequel sqlite:/
Error: Sequel::AdapterNotFound: LoadError: cannot load such file -- sqlite3
/home/murtykorada/.rvm/gems/ruby-2.2.0/gems/sequel-4.29.0/lib/sequel/adapters/sqlite.rb:1:in `require'
murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ irb
2.2.0 :001 > require 'sequel'
 => true 
2.2.0 :002 > DB = Sequel.connect('sqlite://app.db')
 => #<Sequel::SQLite::Database: "sqlite://app.db"> 
2.2.0 :003 > DB.tables
 => [] 
2.2.0 :004 > exit
murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ sequel -m migrations sqlite://app.db
Error: Sequel::AdapterNotFound: LoadError: cannot load such file -- sqlite3
/home/murtykorada/.rvm/gems/ruby-2.2.0/gems/sequel-4.29.0/lib/sequel/adapters/sqlite.rb:1:in `require'
murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$

**Comment by jeremyevans** [comment]
This is probably some issue in your local environment, such as an `.irbrc` file that adds additional entries to the ruby load path, or the `sequel` command using a different ruby than the `irb` command.  Can you replicate this on a different machine?

**Comment by murtyk** [comment]
See below they both are using ruby 2.2:

murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ irb
2.2.0 :001 > exit
murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ sequel -m migrations sqlite://app.db
Error: Sequel::AdapterNotFound: LoadError: cannot load such file -- sqlite3
/home/murtykorada/.rvm/gems/ruby-2.2.0/gems/sequel-4.29.0/lib/sequel/adapters/sqlite.rb:1:in `require'

murtykorada@murtykorada-Lenovo-Z480:~/.../cuba-states$ ls /home/murtykorada/.rvm/gems | grep ruby
ruby-2.1.2
ruby-2.1.2@global
ruby-2.1.3
ruby-2.1.3@global
ruby-2.2.0
ruby-2.2.0@global
ruby-2.2.3
ruby-2.2.3@globa

**Comment by jeremyevans** [comment]
Can you replicate this on a different machine?

**Comment by murtyk** [comment]
I tried on a different machine but not able to replicate. it works on the 2nd one. Can provide some direction on how to debug this issue?

**Comment by jeremyevans** [comment]
You are using rvm, it is problem an rvm issue.  Possibly related to rvm gemsets, though that's just a guess as I am not an rvm user.  You should probably ask the rvm maintainers.

**Comment by murtyk** [comment]
Resolved. For the benefit of others who might encounter this problem, make sure to install both sqlite3 and sequel gems using bundler.
