### ISSUE TITLE
Reference to table with underscore screws up SQL

### ISSUE THREAD

**Issue by leifg** [jeremyevans/sequel#1114]
I have the problem that I use tables that have a double underscore in it. So far no problem. But when I want to create a table with a foreign key to that table, I have to give the name as a symbol (otherwise sequel throws an exception). But when I convert the reference table into a symbol sequel I get another error:

```ruby
DB = Sequel.connect("sqlite://test.db", logger: Logger.new($stdout))
DB.create_table("name__of_reference_table"){ primary_key :id }
DB.create_table(:my_table){ foreign_key "name_of_colum", :name__of_reference_table  }
```

==>
```
SQLite3::SQLException: near ".": syntax error: CREATE TABLE `my_table` (`name_of_colum` integer REFERENCES `name`.`of_reference_table`)
```

I think the problem is that `name__of_reference_table` is converted in the dot notation and then the SQL doesn't work anymore.

Is there any particular reason why the reference key cannot be a string?

**Comment by jeremyevans** [comment]
If you want to include a double underscore in a table name, you should wrap it in `Sequel.identifer`:  `DB.create_table(:my_table){ foreign_key "name_of_colum", Sequel.identifer(:name__of_reference_table)  }`.  Otherwise, Sequel thinks you are trying to reference a schema qualified table.

**Comment by leifg** [comment]
Is `Sequel.identifer` really the correct method? I get the error `NoMethodError: undefined method `identifer' for Sequel:Module`

**Comment by jeremyevans** [comment]
Sorry, that's a typo. The method name is `Sequel.identifier`.

**Comment by leifg** [comment]
Nope, doesn't work. The same error as when I want to input a string:

```ruby
DB.create_table(:my_table){ foreign_key "name_of_colum", Sequel.identifier(:name__of_reference_table) }
Sequel::Error: The second argument to foreign_key should be a Hash, Symbol, or nil
```

**Comment by jeremyevans** [comment]
Ah, sorry, I should have tested it first.  Here's something that works:

    DB.create_table(:my_table){ foreign_key "name_of_colum", :table=>Sequel.identifier(:name__of_reference_table) }

or

    DB.create_table(:my_table){ foreign_key "name_of_colum", :table=>'name__of_reference_table' }
