### ISSUE TITLE
There is no doc, sample or api to introduce how to use auto_increment.

### ISSUE THREAD

**Issue by Gary-Xie** [jeremyevans/sequel#1118]
I just find there is a COLUMN_DEFINITION_ORDER modifiers name auto_increment. It looks like I can use it in column definition. But how to use it. Do I only set it true? Is it enough? Totally not. I think there is other relative configuration to be set, such as increment base( increment from 0 or something else), increment step(+1 or something).

**Comment by jeremyevans** [comment]
Sequel doesn't support autoincrement modifiers in any of the included adapters.  Sequel will automatically use autoincrement if the database needs it for autoincrementing primary keys, but there is no API that turns it on by itself.

If you want to support autoincrement modifiers such as base or step, you need to write a custom adapter or extension, or you need to drop down to raw SQL.

As mentioned in the contribution guidelines, questions about Sequel or how to use Sequel should be asked on the sequel-talk Google Group.  GitHub Issues should only be used for reporting bugs in the library.

**Comment by Gary-Xie** [comment]
OK,got it. Thank you very much.
