### ISSUE TITLE
Name mismatching with pg_row extension

### ISSUE THREAD

**Issue by soupmatt** [jeremyevans/sequel#1119]
I noticed that if I register a row type that is schema qualified, I have to make sure I qualify it the same way every time, otherwise sequel doesn't recognize that I have already registered it. I think this is best demonstrated with a runnable example script.

I am using sequel v4.29.0 under ruby 2.2.3.

```ruby
require 'rubygems'
require 'sequel'

DB = Sequel.postgres # assumes you can connect straight to your default database
DB.extension :pg_array, :pg_row

DB.create_table!(:outfit) do
  column :shirt, :varchar
  column :pants, :varchar
end

DB.register_row_type(Sequel.qualify('public', :outfit))

# this works fine
DB.row_type(Sequel.qualify('public', :outfit), { shirt: 'star wars', pants: 'jeans' })

# this does not
begin
  DB.row_type(:public__outfit, { shirt: 'star wars', pants: 'jeans' })
  raise 'we never get here'
rescue => e
  puts e
end

# neither does this
begin
  DB.row_type(Sequel.qualify(:public, :outfit), { shirt: 'star wars', pants: 'jeans' })
  raise 'we never get here'
rescue => e
  puts e
end
```

It appears that sequel uses the original type name that is passed in as the key to the hash of types that it stores (stored [here](https://github.com/jeremyevans/sequel/blob/4.29.0/lib/sequel/extensions/pg_row.rb#L491) and looked up [here](https://github.com/jeremyevans/sequel/blob/4.29.0/lib/sequel/extensions/pg_row.rb#L522))

This is by no means a show stopping bug, but it would be nice if the various ways of expressing the schema qualified type name found the type definition.

**Comment by jeremyevans** [comment]
I agree, this would be good to have, and it doesn't appear to be difficult to fix.  I'm testing a fix now, it should be pushed up to GitHub later today if the tests pass.

**Comment by soupmatt** [comment]
thx!
