### ISSUE TITLE
Array argument to prepared statement fails with jdbc

### ISSUE THREAD

**Issue by dekellum** [jeremyevans/sequel#1124]
The following test code passes using cruby \w pg driver, but fails with the exception shown at bottom on jruby \w jdbc driver. 

~~~ ruby
  def test
    sql = "SELECT ARRAY[1,2] = ? as t;"

    DB[ sql, :$a ].prepare( :select, :test_statement )
    vargs = { a: [ 1, 2 ] }
    assert_equal( true, DB.call( :test_statement, vargs ).first[:t] )
  end
~~~

Note pg_array and pg_json extensions are loaded. Explicitly wrapping the :a value in a PGArray as in the following  does not workaround the issue:

~~~ ruby
    vargs = { a: Sequel.pg_array( [1, 2] ) }
~~~

## Versions Tested

Works fine using: 
  * PostgreSQL 9.5rc1
  * ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
  * pg (0.18.4)
  * sequel (4.29.0)
  * sequel_pg (1.6.13)

Fails with:
  * PostgreSQL 9.5rc1 (9.4?)
  * jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on OpenJDK 64-Bit Server VM 1.8.0_66-b17 +jit [linux-amd64], or
  * jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa OpenJDK 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [linux-amd64]
  * rjack-jdbc-postgres (9.4.1204.0 or 9.4.1200.0)
  * sequel (4.29.0 or 4.21.0)

## Stack Trace

~~~ text
Java::OrgPostgresqlUtil::PSQLException: Can't infer the SQL type to use for an instance of org.jruby.RubyArray. Use setObject() with an explicit Types value to specify the type to use.
    org.postgresql.jdbc2.AbstractJdbc2Statement.setObject(org/postgresql/jdbc2/AbstractJdbc2Statement.java:1934)
    org.postgresql.jdbc3g.AbstractJdbc3gStatement.setObject(org/postgresql/jdbc3g/AbstractJdbc3gStatement.java:36)
    org.postgresql.jdbc4.AbstractJdbc4Statement.setObject(org/postgresql/jdbc4/AbstractJdbc4Statement.java:48)
    java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
    RUBY.set_ps_arg(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:586)
    RUBY.execute_prepared_statement(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:427)
    org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    RUBY.execute_prepared_statement(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:427)
    Sequel::ThreadedConnectionPool.hold(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/connection_pool/threaded.rb:103)
    Sequel::ThreadedConnectionPool.hold(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/connection_pool/threaded.rb:103)
    Sequel::ThreadedConnectionPool.hold(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/connection_pool/threaded.rb:101)
    Sequel::ThreadedConnectionPool.hold(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/connection_pool/threaded.rb:101)
    Sequel::Database.synchronize(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/database/connecting.rb:254)
    Sequel::Database.synchronize(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/database/connecting.rb:254)
    RUBY.execute_prepared_statement(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:415)
    Sequel::JDBC::Database.execute(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:244)
    Sequel::JDBC::Database.execute(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:244)
    Sequel::Dataset.execute(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:950)
    Sequel::Dataset.execute(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:950)
    RUBY.execute(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/prepared_statements.rb:31)
    Sequel::JDBC::Dataset.fetch_rows(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:721)
    Sequel::JDBC::Dataset.fetch_rows(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/jdbc.rb:721)
    RUBY.each(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:139)
    RUBY.all(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:45)
    RUBY._all(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:890)
    RUBY.all(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/actions.rb:45)
    RUBY.run(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/prepared_statements.rb:167)
    RUBY.run(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/adapters/shared/postgres.rb:1223)
    RUBY.call(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/dataset/prepared_statements.rb:53)
    RUBY.call(/home/david/.gem/jruby/1.9/gems/sequel-4.29.0/lib/sequel/database/query.rb:36)
    RUBY.search_all(/home/david/src/sqoop/tipsource/tipdb/lib/sqoop-tipdb/search.rb:47)
    RUBY.assert_search_all(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:126)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:99)
    org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:98)
    org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:96)
    org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:94)
    org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:92)
    org.jruby.RubyArray.combination(org/jruby/RubyArray.java:3597)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:91)
    org.jruby.RubyRange.each(org/jruby/RubyRange.java:479)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:90)
    org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
    RUBY.test_all_combinations(/home/david/src/sqoop/tipsource/tipdb/test/test_search.rb:89)

~~~

**Comment by jeremyevans** [comment]
This is expected, the pg_array extension does not add support using arrays as bound variables when using the jdbc adapter, just when using the postgres adapter.  You can use the postgres-pr driver on JRuby with the postgres adapter as one possible workaround. Note that this is true for pretty much all of the custom PostgreSQL types, the pg_* extensions only support bound variables when using the postgres adapter.

If you want to add support so this will work when using the jdbc adapter, you'll need to override the Database#set_ps_arg method in the pg_array extension and call the appropriate JDBC method to set the bound variable value.  I'm fine with such support being included with Sequel, please submit a pull request if you are able to get it to work.  There are already tests for the support, but they are only run when using the postgres adapter, not when using the jdbc adapter.

**Comment by dekellum** [comment]
In reading your comment and looking at the pg_array extension I get the impression that pg_array isn't really involved, at least currently? My understanding now is that this works with the pg driver because the driver handles it natively where as the java jdbc driver and Sequel's JDBC adapter does not.  I was able to get two array types working by modifying the Sequel JDBC adapter directly, see 744bcfa.

I'm sure this isn't quite ready to be a pull request, but:

* How far is necessary to go with guessing array types and how much compatibility risk is involved in these guesses with the type string passed to createArrayOf()? 

* Is pg_array extension still a best place for this?  One advantage might be to only support PGArray and set the above mentioned type based on the type facilities of PGArray?

**Comment by jeremyevans** [comment]
The pg_array extension is the correct place for this. Instead of checking for Array, it should be checking for PGArray (and that is defined in the pg_array extension), and to be included with Sequel, it needs to be able to handle all array types and multilevel arrays, not just int4 and text.

I don't think changing the set_ps_arg API is a good idea. If you need a connection, one should be checked out from the pool via synchronize, unless there is a requirement that the same connection that will be executing the statement must be used.

Is it possible to use the same bound variable serialization used for the postgres adapter with setObject?

**Comment by jeremyevans** [comment]
Here's the code I'm referring to: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pg_array.rb#L249

**Comment by dekellum** [comment]
I'm learning as I go here, but regarding setObject \w bound_variable_array, this for example:
~~~ java
setObject( 1, "{1,2}", java.sql.Types.ARRAY )
~~~

Fails with the about test case with:
~~~
PSQLException: Cannot cast an instance of java.lang.String to type Types.ARRAY
~~~

This also didn't work:
~~~ java
setString( 1, "{1,2}" ) 
~~~

Please let me know if you had something else in mind.

Regarding set_ps_arg API change, based on what little I have found about array bound variables via JDBC, it seems at the very least unexpected usage to use a different connection than is used for creating the prepared statement.  Also wouldn't be great resource wise to require two connections for every prepared statement call with an Array in it.

The `set_ps_arg` calls are jdbc localized but I do see there are some other implementations jdbc/db2 etc where this would also need to be changed if this were the route.

**Comment by dekellum** [comment]
…But can avoid set_ps_arg signature change, see 769dfc7..580712f.

**Comment by jeremyevans** [comment]
Does `setObject(1, '{1,2}')` work? If not, maybe try `setAsciiStream` with a java.io.InputStream containing the serialized data (https://jdbc.postgresql.org/development/privateapi/org/postgresql/jdbc2/AbstractJdbc2Statement.html).

If neither works, you may have to write your own handling, which could get quite complex.  Unfortunately, all documentation I can find regarding JDBC and PostgreSQL arrays assumes you know all types in advance, which makes it difficult to handle things generically as Sequel needs to do.

**Comment by dekellum** [comment]
`setObject(1, '{1,2}')` results in:

~~~
PSQLException: ERROR: operator does not exist: integer[] = character varying
~~~

I'm attempting to package my set_ps_arg mods as a database extension and I'll report back.

**Comment by dekellum** [comment]
So yes, I'm able to package 580712f effectively as a database extension for the subset of cases I need for my project, incl. its goal of maintaining jdbc and pg driver compatibility. Thanks again for the pointers.
