### ISSUE TITLE
Foreign key referencing same table

### ISSUE THREAD

**Issue by wmnnd** [jeremyevans/sequel#1126]
It seems that Sequel does not automatically set the column name of the referenced primary key if it is in the same table as the foreign key column.

Here is a quick example:

```ruby
Sequel.migration do
	change do
		create_table(:users) do
			binary :uuid, :size => 16, :primary_key => true
		end

		create_table(:items) do
			binary :uuid, :size => 16, :primary_key => true
			foreign_key :owner, :users, {:type => :binary, :size => 16}
			foreign_key :parent, :items, {:type => :binary, :size => 16}
		end
```
This will create the following SQL query where only the first foreign key has its column name correctly specified:
```sql
CREATE TABLE `items` (
	`uuid` binary(16) PRIMARY KEY,
	`owner` binary(16),
	`parent` binary(16),
	FOREIGN KEY (`owner`) REFERENCES `users` (`uuid`),
	FOREIGN KEY (`parent`) REFERENCES `items`
);
```

which results in the following error:
```
Mysql2::Error: Cannot add foreign key constraint
```

This can be easily circumvented by adding the ```:key``` property to the ```foreign_key``` definition like so:
```ruby
			foreign_key :parent, :items, {type => :binary, :size => 16, :key => :uuid}
```

However, I was wondering whether this behavior is expected considering the fact that Sequel usually sets the column name of the referenced primary key automatically.

**Comment by jeremyevans** [comment]
Sequel does usually set the primary key, but this particular case it doesn't handle.  It should be possible to handle it, though, so I'll see if I can get this working soon.

**Comment by wmnnd** [comment]
I am speechless. You rock, Jeremy!
