### ISSUE TITLE
Empty (or fully commented-out) migration file causes previous migration to run again

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [jeremyevans/sequel#1127]
I wanted to ignore a migration I was working on so I commented out the body of the migration (including the `Sequel.migration` call). I then started getting strange errors: it looks like if the migrator encounters a totally empty file, it tries to apply the previous migration again. We're using the `TimestampMigrator`.

**Comment by jeremyevans** [comment]
Empty migration files shouldn't be allowed.  I'll try to change things so an error is raised if a migration file doesn't have a valid migration in it.

**Comment by uhoh-itsmaciek** [comment]
Great, thanks. For what it's worth, including an empty `Sequel.migration` call seems to work around this.
