### ISSUE TITLE
Malformed ADO Query using Access

### ISSUE THREAD

**Issue by davide-cisco** [jeremyevans/sequel#1141]
Hello,
the following code produces a query that is not valid for MS Access ADO DB:

```ruby
    @db = Sequel.ado :conn_string => "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=source_db_file.mdb"
    @db[:table].order(:id).select([:id, :field_a, :field_b, :field_n]).sql
````

Here it is the result:

```sql
    SELECT ([id], [field_a], [field_b], [field_n]) FROM [table] ORDER BY [id]
```

The field list is wrapped by an extra (), not valid in MS Access.

**Comment by jeremyevans** [comment]
This isn't a bug, you should be passing separate arguments, not an array:

```ruby
@db[:table].order(:id).select(:id, :field_a, :field_b, :field_n).sql
```

**Comment by davide-cisco** [comment]
Thanks Jeremy, I'm sorry.
I'm trying to import from an MS Access DB to another, but I'm having some trouble, I cannot find a clear way to do that.

Here it is a [Stackoverflow Question](http://stackoverflow.com/questions/35243897/ruby-sequel-import-data-from-database-source-mdb-to-database-destination-mdb) where I'm explaining what I'm trying to do.

**Comment by jeremyevans** [comment]
You probably want:

```ruby
data = @db_source[table_name].select(*@table_fields[table_name])
```

**Comment by davide-cisco** [comment]
Almost...
I'm looking to import data, but I'm not sure how to fetch and process single rows, like Java datasource.
Something that could take some time, but works until rows are present in DB.

**Comment by jeremyevans** [comment]
Please read the Sequel documentation, it should hopefully answer questions: http://sequel.jeremyevans.net/documentation.html

If you have questions about particular issues after reading the documentation, please ask on the sequel-talk Google Group.

**Comment by davide-cisco** [comment]
Tanks
