### ISSUE TITLE
Passing OpenStruct to insert

### ISSUE THREAD

**Issue by bilus** [jeremyevans/sequel#1145]
I'm struggling with how to do this:

```ruby
x = OpenStruct.new(text: 'foo')
ds.insert(x)
```

instead of:

```ruby
ds.insert(text: 'foo')
```

I nailed it down to `insert_sql` in sql.rb but I'm stuck. Is there a super-obvious method to do that, something I'm missing? Thank you so much in advance!

UPDATE: I also tried this but it doesn't use the method override even after I install the extension:

```ruby
module Sequel
  module OpenStructValues
    # Set overrides/defaults for inserting Openstruct
    def insert_sql(*values)
      if values.size == 1 && (vals = values.first).is_a?(OpenStruct)
        super(vals.to_hash)
      else
        super
      end
    end
  end

  Dataset.register_extension(:open_struct_values, OpenStructValues)
end
```

**Comment by rohitn** [comment]
```ruby
$ irb
2.2.2 :001 > require 'ostruct'
 => true
2.2.2 :002 > x = OpenStruct.new(text: 'foo')
 => #<OpenStruct text="foo">
2.2.2 :003 > x.to_h
 => {:text=>"foo"}
```

I think `to_h` was added in 2.0, but I am not sure.

**Comment by jeremyevans** [comment]
That's right, this should work if you use `to_h` instead of `to_hash`.

Note that as mentioned in the contribution guidelines, GitHub Issues should only be used for reporting bugs in the library.  Questions like this are best asked on the sequel-talk Google Group or IRC.
