### ISSUE TITLE
Delete from multiple tables

### ISSUE THREAD

**Issue by andrewferk** [jeremyevans/sequel#1146]
I'm trying to create the following query:

```sql
DELETE person, pet FROM person LEFT JOIN pet ON pet.person_id = person.id WHERE person.id = 1
```

I cannot get the `delete_sql` to include `DELETE person, pet`.

`sql`:
```ruby
db[:person].select(:person, :pet).left_join(:pet, :person_id => :id).where(:id => 1).sql
```
=>
```sql
SELECT `person`, `pet` FROM `person` LEFT JOIN `pet` ON (`pet`.`person_id` = `person`.`id`) WHERE (`id` = 1)
```

`delete_sql`:
```ruby
db[:person].select(:person, :pet).left_join(:pet, :person_id => :id).where(:id => 1).delete_sql
```
=>
```sql
DELETE `person` FROM `person` LEFT JOIN `pet` ON (`pet`.`person_id` = `person`.`id`) WHERE (`id` = 1)
```

Is there a solution to this?

**Comment by jeremyevans** [comment]
Sequel doesn't support that type of SQL.  I'm not sure what database supports it.  With PostgreSQL and MySQL you can do a multi-table DELETE via a USING clause, which Sequel does support.

Note that as this is not a bug in Sequel, but a question about how to use Sequel, it should be asked on the sequel-talk Google Group or IRC, not GitHub Issues, per the contribution guidelines.

**Comment by jeremyevans** [comment]
Actually, it looks like MySQL does support that syntax (in addition to supporting the USING syntax).  However, Sequel doesn't support it.  Sequel currently only supports deleting from a single table.  It should be possible to add support for deleting from multiple tables.  Can you test this patch:

```
diff --git a/lib/sequel/adapters/shared/mysql.rb b/lib/sequel/adapters/shared/mysql.rb
index e40b483..72115e7 100644
--- a/lib/sequel/adapters/shared/mysql.rb
+++ b/lib/sequel/adapters/shared/mysql.rb
@@ -682,6 +682,10 @@ module Sequel
       def calc_found_rows
         clone(:calc_found_rows => true)
       end
+
+      def delete_from(*tables)
+        clone(:delete_from=>tables)
+      end
       
       # Return the results of an EXPLAIN query as a string. Options:
       # :extended :: Use EXPLAIN EXPTENDED instead of EXPLAIN if true.
@@ -847,7 +851,8 @@ module Sequel
       def delete_from_sql(sql)
         if joined_dataset?
           sql << SPACE
-          source_list_append(sql, @opts[:from][0..0])
+          tables = @opts[:delete_from] || @opts[:from][0..0]
+          source_list_append(sql, tables)
           sql << FROM
           source_list_append(sql, @opts[:from])
           select_join_sql(sql)
```

Example:

````
DB[:person].select(:person, :pet).left_join(:pet, :person_id =>:id).where(:id => 1).delete_from(:person, :pet).delete_sql
# => "DELETE `person`, `pet` FROM `person` LEFT JOIN `pet` ON (`pet`.`person_id` = `person`.`id`) WHERE (`id` = 1)"
```

**Comment by andrewferk** [comment]
Yes, that works and you do not need the `select(...)`. I do not mind using the the USING syntax if I can figure out how to apply it with Sequel.

Thank you!

**Comment by jeremyevans** [comment]
Actually, I checked and Sequel doesn't use USING on MySQL, only on PostgreSQL.  The existing support on MySQL works for joined dataset, but only deleting from one table, not for multiple tables.

I'll add a spec for this patch and after testing I'll merge it tomorrow.  Thanks for testing.

**Comment by nicolasiensen** [comment]
> With PostgreSQL and MySQL you can do a multi-table DELETE via a USING clause, which Sequel does support.

I searched everywhere on how to perform a multi-table DELETE using Sequel via a USING clause, but I couldn't find a reference for that.

Could someone point me to where this is documented? Or just respond with an example of how to perform this call?

Thanks!

**Comment by jeremyevans** [comment]
@nicolasiensen You should probably post a question on the sequel-talk Google Group and include the SQL you want to generate.
