### ISSUE TITLE
WHERE..IN with NULL elements

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/sequel#1151]
### Complete Description of Issue

The mysql2 adapter does not properly compose WHERE..IN statements in the special case where NULL elements are present in the passed array. 

### Simplest Possible Self-Contained Example Showing the Bug

This works great:

```ruby
DB[:table].where(:field => nil) # SELECT * FROM `table` WHERE `field` IS NULL
```

This, on the other hand, does not return any records where `field` is NULL:

```ruby
DB[:table].where(:field => [1, 2, nil]) # SELECT * FROM `table` WHERE `field` IN (1, 2, NULL)
```

Ideally, the composed query would look more like this:

```ruby
DB[:table].where(:field => [1, 2, nil]) # SELECT * FROM `table` WHERE (`field` IN (1, 2) OR field IS NULL)
```

Thank you in advance!

**Comment by jeremyevans** [comment]
This is expected default behavior. Please use the split_array_nil extension if you want the behavior you describe:

```ruby
DB.extension :split_array_nil
```

**Comment by mwpastore** [comment]
Ah, fantastic. Thanks Jeremy!
