### ISSUE TITLE
An easy way to update a column if it's empty in Sequel.migration?

### ISSUE THREAD

**Issue by mattcui** [jeremyevans/sequel#1152]
I have a requirement to write a DB migration (with Sequel) to set a value, like "{}" in String, in a column of all rows in a table if the value of the column is empty (""), Is there an easy way to retrieve the value of the a column and update it (if it's empty) in Sequel.migration? Thanks.

**Comment by jeremyevans** [comment]
```ruby
from(:table).where(:column=>'').update(:column=>'{}')
```

As mentioned in the contribution guidelines and in the default text when creating an issue, questions about Sequel should be asked on the sequel-talk Google Group or IRC.  GitHub Issues should not be used as a help forum.
