### ISSUE TITLE
PostgreSQL adapter method .tables return table names without schema

### ISSUE THREAD

**Issue by mailcorpo** [jeremyevans/sequel#1154]
Hi. I have a project that uses PostgreSQL 9.5, Rails 4.2 and Sequel 4.31.0. My database consists of multiple schemas with some number of tables with the same name, like this:

           Schema    |          Name           | Type    |  Owner   
    -----------------+-------------------------+---------+----------
     type1           | tasks                   | table   | user
     type1           | updates                 | table   | user
     type2           | tasks                   | table   | user
     type2           | updates                 | table   | user
     type3           | tasks                   | table   | user
     type3           | updates                 | table   | user
      ...

I am using `database_cleaner` (1.5.1) and `rspec` (3.4.0) for my tests. Database config contains _search_path_ for all the schemas. When I try to clear DB with :deletion method (or :truncate) - it didn't remove any records.

```ruby
DatabaseCleaner[:sequel, { connection: DB }]

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:deletion)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
```

Database contains all the data that was inserted during the tests. I open log files and see this:

> I,  INFO -- : (0.000349s) ALTER TABLE "updates" DISABLE TRIGGER ALL
> I,  INFO -- : (0.000444s) ALTER TABLE "tasks" DISABLE TRIGGER ALL
> I,  INFO -- : (0.000236s) ALTER TABLE "updates" DISABLE TRIGGER ALL
> I,  INFO -- : (0.000232s) ALTER TABLE "tasks" DISABLE TRIGGER ALL
> I,  INFO -- : (0.000202s) ALTER TABLE "updates" DISABLE TRIGGER ALL
> I,  INFO -- : (0.000200s) ALTER TABLE "tasks" DISABLE TRIGGER ALL
> ....
> I,  INFO -- : (0.000349s) DELETE FROM "tasks"
> I,  INFO -- : (0.000444s) DELETE FROM "updates"
> I,  INFO -- : (0.000249s) DELETE FROM "tasks"
> I,  INFO -- : (0.000314s) DELETE FROM "updates"
...

As you can see - no schema provided to PSQL, just raw table names. Ok, I open  `Sequel` adapter of  `database_cleaner` and learned how it tries to delete the data from the tables:

```ruby
    # database_cleaner/sequel/deleteion.rb : 30-46
    def delete_tables(db, tables)  # tables - connection.tables method of Sequel
      tables.each do |table|
        db[table.to_sym].delete
      end
    end

   # database_cleaner/sequel/truncation.rb : 64-67
    def tables_to_truncate(db)
       (@only || db.tables.map(&:to_s)) - @tables_to_exclude
    end
```

As we see, _db_cleaner_ gem get tables name with _sequel_ `.tables` method. Ok, go to `Sequel` code (`adapters/shared/postgres.rb` - 525 line of code) and see that `tables` method return table names WITHOUT schemas.

```bash
2.1.7 :004 > DB.tables # DB - sequel connection
 => [:updates, :tasks, :updates, :tasks, :updates, :schema_info, :tasks, :tasks, :tasks, :updates, :tasks, :updates]
```

Thats why no one record is removed and that is why `database_cleaner` doesn't remove any data.

Is it possible to return the names of the tables with the schema? (maybe with `with_schema` option to the tables method or in some separate method)?

For correct removing of the data from the tables with schema `database_cleaner` gem needs something like this:

```ruby
[:type1__updates, :type1__tasks, :type2__updates, :type2__tasks, :type3__updates, :type3__tasks ]
```

Thanks!

**Comment by mailcorpo** [comment]
I found that the same problem with tables names was discussed 2 years ago (see https://www.bountysource.com/issues/1239086-sequel-postgresql-truncate-strategy-fails-if-there-s-tables-in-other-schemas), but the solution (use `%only` option) is wrong. I think we need to rewrite some `Sequel` part of code and then use it in `database_cleaner`.

**Comment by jeremyevans** [comment]
This is expected behavior. On PostgreSQL, you can pass a `:qualify=>true` option to `DB.tables` and it will return qualified identifiers instead of symbols, which should fix your issue.

**Comment by mailcorpo** [comment]
@jeremyevans  I understand that it is an expected behavior. Using `qualify` is good, but it would be much better if Sequel can do it natively (not something like `tables(qualify: true).map { |table| "#{table.table}__#{table.column}".to_sym }`) and all of the developers can use it.

**Comment by janko-m** [comment]
Just to chip in, I personally would expect `:qualify=>true` to return `[:schema1__table1, :schema2_table2, ...]` instead of an array of `Sequel::SQL::Identifier` objects, as it would be consistent by type with what `DB.tables` returns (an array of symbols).

**Comment by jeremyevans** [comment]
Having `:qualify=>true` return symbols would break things if the table name contained a double underscore or ended in an underscore.  Note that that's true for `tables` by default, but that can't be fixed as the API requires that it return an array of symbols.  In general, you should not be dynamically constructing symbols to make qualified identifiers.  Use `Sequel::SQL::QualifiedIdentifier`, that's what it's for.

I don't agree that Sequel should automatically qualify in this case.  Most developers aren't using multiple schemas, and adding a schema (generally `public`) to all of the table names would  not be what most of them want.  Note that you can pass `:qualify=>true` on other databases, and if they don't support qualification, they will just ignore the option.
