### ISSUE TITLE
auto_valdiations is missing unique indexes due to indpred check

### ISSUE THREAD

**Issue by david-mccullars** [jeremyevans/sequel#1156]
In setting up a new model with the auto_validations plugin turned on, I was expecting it to apply unique validations for the unique keys on my table.  It was not, however, allowing it to pass through to Postgres and failing with a duplicate key error.

Digging in I discovered the problem to be at https://github.com/jeremyevans/sequel/blob/master/lib/sequel/plugins/auto_validations.rb#L153 -- `db.indexes(table)` was returning back an empty set even though there definitely was unique indexes on the table.

I tracked this down further to https://github.com/jeremyevans/sequel/blob/1e9137167faade311f2ee255aba775beecd26cd5/lib/sequel/adapters/shared/postgres.rb#L352 -- when I remove the `:indpred => nil` check it returns back the unique indexes as expected.  Looking at the db, I see the following in that column for the index:

```
NULLTEST :arg {VAR :varno 1 :varattno 18 :vartype 1114 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 18 :location 93} :nulltesttype 0 :argisrow false}
```

I'm using

```
PostgreSQL 9.4.5 on x86_64-apple-darwin15.2.0, compiled by Apple LLVM version 7.0.2 (clang-700.1.81), 64-bit
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

**Comment by david-mccullars** [comment]
For the time being I have just monkey patched the method to remove the `:indpred => nil`, and I'm happy to fork & create a PR, but I'm guessing that check was put in for a reason.

**Comment by jeremyevans** [comment]
The `indpred` check is needed, it filters out partial indexes.  The `auto_validations` plugin does not handle partial unique indexes, since partial indexes are not returned by `Database#indexes`.  In this case, you should just use `validates_unique` directly with a block that specifies the same conditions as the partial index.
