### ISSUE TITLE
error is not directly associated with a single attribute

### ISSUE THREAD

**Issue by kodram** [jeremyevans/sequel#1157]
In ActiveRecord

`person.errors.add(:base, "either name or email must be present")`

http://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-add

How to do it in sequel?

**Comment by jeremyevans** [comment]
Funnily enough: `person.errors.add(:base, "either name or email must be present")` (yes, the same exact code works).  Note that `:base` doesn't have any special meaning hear.

In the future, per the contribution guidelines, please ask questions like this on the sequel-talk Google Group or IRC.
