### ISSUE TITLE
Multiple thread-(un)safety issues on MRI with parallel

### ISSUE THREAD

**Issue by steakknife** [jeremyevans/sequel#1161]
Using parallel, it's trivial to break sequel using a file-backed sqlite db in a [million special ways](https://github.com/grosser/parallel/wiki/Sequel#other-sequel--parallel-errors).

**Ruby (MRI) 2.3.0**
sequel (4.32.0)
sqlite3 (1.3.11)
parallel (1.6.2)

Solved by using concurrent-ruby like this:

```ruby
# wrap your work in parallelize(long_list) { |elem| do_some_sequel_stuff(elem) }
def parallelize(array, &block)
  pool = Concurrent::ThreadPoolExecutor.new(
    min_threads: 0,
    max_threads: THREADS,
    max_queue: 0 # unbounded work queue
  )
  puts "starting pool #{pool}"
  array.each do |elem|
    pool.post(elem, block) do |data, blk|
      blk.(data)
    end
  end

  while pool.running? && (s = pool.scheduled_task_count) > (c = pool.completed_task_count) do
    puts "sleeping (threads: sched #{s}, done #{c}) #{pool}"
    sleep 1
  end
  puts "shutting down #{pool}"
  pool.shutdown
  puts "wait for term #{pool}"
  pool.wait_for_termination
  puts "done #{pool}"
=begin
  Parallel.each(array, :in_threads => THREADS) do |value|
    yield(value)
  end
=end
end   
```

**Comment by jeremyevans** [comment]
I know this was closed, but do you think this is a bug in Sequel, the sqlite3 gem, something else, or is this not actually a bug?

**Comment by steakknife** [comment]
I think there's a concurrency bug in parallel specifically, because concurrent-ruby with around 100 threads operating on about a million tasks works just fine with sequel.  Not using transactions or anything fancy, just a single global $DB with two models in 1:n association.  It's pretty solid now, whereas before it broke either instantly or after 1-2 minutes (serious nondeterminism in manifold ways).

**Comment by jeremyevans** [comment]
Thanks for letting me know.  That type of bug in Sequel would be very serious and require immediate attention.

**Comment by steakknife** [comment]
Yah, no worries.  +1 for concurrent-ruby which is used by Sprockets and Sidekiq and seems to handle the crunchy concurrency crapola across JRuby and MRI.

**Comment by steakknife** [comment]
**Pedantic update** Job running for about an hour without crashing, so I think it's solved to high probability.
