### ISSUE TITLE
Creating model classes inside a transaction - PG::InFailedSqlTransaction

### ISSUE THREAD

**Issue by xzo** [jeremyevans/sequel#1162]
I tested new Sequel master.

1) Method `get_db_schema` does not use a savepoint around `db.schema(dataset, :reload=>reload)`
2) Method `columns` does not use a savepoint. Plugins boolean_readers, boolean_subsets, class_table_inheritance use method `columns`

This causes PG::InFailedSqlTransaction.

**Comment by jeremyevans** [comment]
I'll try to take a look at this later today.  BTW, is there a reason you are creating model classes inside a transaction?  It's pretty out of the ordinary.

**Comment by xzo** [comment]
@jeremyevans 
Rails autoload.
