### ISSUE TITLE
Double quotes throwing error for hive

### ISSUE THREAD

**Issue by hariramesh9a** [jeremyevans/sequel#1164]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

Gem putting quotes around the tables is causing issue. I am using jruby and sequel gem to connect to hive. I manually loaded drivers and hoping to use sequel to connect. Since the queries has double quotes
SELECT * FROM "YANGL7"."STD_DRIVER_SUMMARY_EXT"
this throws an error . Is there a way I can remove double  quotes aroun.

**Comment by jeremyevans** [comment]
`DB.quote_identifiers = false`

As mentioned in the contribution guidelines and at the top of the issue report, please use the sequel-talk Google Group or IRC to ask questions like this in the future.
