### ISSUE TITLE
Default Sequel::CURRENT_TIMESTAMP vs Safe Prepared Statements

### ISSUE THREAD

**Issue by halostatue** [jeremyevans/sequel#1168]
### Complete Description of Issue

A table that has a default of `Sequel::CURRENT_TIMESTAMP` causes various exceptions when attempting to insert a row using safe prepared statements (`plugin :prepared_statements_safe`).

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
# frozen_string_literal: true

require 'sequel'

begin
  use_postgres = ARGV.include?('postgres')

  if use_postgres
    Template1 = Sequel.connect('postgres://localhost/template1')
    Template1 << 'CREATE DATABASE prepared_current_timestamp'
    DB = Sequel.connect('postgres://localhost/prepared_current_timestamp')
  else
    DB = Sequel.sqlite
  end

  DB.create_table :prepared_current_timestamps do
    DateTime :problem, null: false, default: Sequel::CURRENT_TIMESTAMP
  end

  class PreparedCurrentTimestamp < Sequel::Model(DB)
    # plugin :prepared_statements
    plugin :prepared_statements_safe
  end

  PreparedCurrentTimestamp.create
  puts 'Bug no longer occurs.'
rescue => ex
  p ex
ensure
  if use_postgres
    DB.disconnect
    Template1 << 'DROP DATABASE prepared_current_timestamp'
  end
end
```

### Full Backtrace of Exception (if any)

Different backtraces depending on the adapter. Postgres throws `#<Sequel::DatabaseError: PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type timestamp: "#<Sequel::SQL::Constant:0x…>">` while Sqlite throws `#<RuntimeError: can't prepare Sequel::SQL::Constant>`.

This should somehow be resolved by the time this hits the adapter’s `execute_prepared_statement` method, but I can’t quite figure out what it should resolve to. Somehow, when the table is created (`DB.create_table(:prepared_current_timestamps) { DateTime :problem, null: false, default: Sequel::CURRENT_TIMESTAMP }`), the column default is set properly to `now()` in Postgres. I presume that it does the right thing in Sqlite, but I can’t be 100% sure.

If I (manually, through the use of byebug and strategic breakpoints) convert the argument to the result of `#constant` on the `Sequel::SQL::Constant` instance, I get two different errors.  Under Postgres, I get `#<Sequel::DatabaseError: PG::FeatureNotSupported: ERROR:  date/time value "current" is no longer supported>`; under Sqlite, I get `#<RuntimeError: can't prepare Symbol>`.

If I just use `:prepared_statements` instead of `:prepared_statements_safe`…this problem goes away. I’m not even going to pretend that I understand what the difference is at the moment. (As a workaround, I am removing `:prepared_statements_safe` from my configuration, but it seems like it would be a good idea to use.)

**Comment by jeremyevans** [comment]
Thanks for reporting this.  This error is because you can only prepare values, and CURRENT_TIMESTAMP is an expression, not a value. prepared_statements_safe should just skip expression defaults. This patch should fix it:

```diff
diff --git a/lib/sequel/plugins/prepared_statements_safe.rb b/lib/sequel/plugins/prepared_statements_safe.rb
index 34109e8..2f09844 100644
--- a/lib/sequel/plugins/prepared_statements_safe.rb
+++ b/lib/sequel/plugins/prepared_statements_safe.rb
@@ -47,7 +47,8 @@ module Sequel
           if db_schema
             h = {}
             db_schema.each do |k, v|
-              h[k] = v[:ruby_default] if (v[:ruby_default] || !v[:default]) && !v[:primary_key]
+              default = v[:ruby_default]
+              h[k] = default if (default || !v[:default]) && !v[:primary_key] && !default.is_a?(Sequel::SQL::Expression)
             end
             @prepared_statements_column_defaults = h
           end

```

I'll have to add some tests for the behavior, but I should be able to commit this fix with specs on Monday after running them through the test suites.
