### ISSUE TITLE
Column 'id' in where clause is ambiguous if using ClassTableInheritance

### ISSUE THREAD

**Issue by okliv** [jeremyevans/sequel#1178]
### Complete Description of Issue

i have defined

    class Product < Sequel::Model
      plugin :class_table_inheritance, :key=>:entity_type
    end

and

    class Notebook < Product

    end

### Simplest Possible Self-Contained Example Showing the Bug

now if i try to search Notebook with id: 1

    >> Notebook.where(id: 1).to_a

it throws an error

### Full Backtrace of Exception (if any)

    Sequel::DatabaseError: Mysql2::Error: Column 'id' in where clause is ambiguous
    from gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
    from gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
    from gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
    from gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
    from sequel/lib/sequel/adapters/mysql2.rb:80:in `block in _execute'
    from gems/sequel-rails-0.9.12/lib/sequel_rails/sequel/database/active_support_notification.rb:16:in `block in log_yield'
    from gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
    from gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
    from gems/sequel-rails-0.9.12/lib/sequel_rails/sequel/database/active_support_notification.rb:10:in `log_yield'
    from sequel/lib/sequel/adapters/mysql2.rb:80:in `_execute'
    from sequel/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in `block in execute'
    from sequel/lib/sequel/database/connecting.rb:251:in `block in synchronize'
    from sequel/lib/sequel/connection_pool/threaded.rb:105:in `hold'
    from sequel/lib/sequel/database/connecting.rb:251:in `synchronize'
    from sequel/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in `execute'
    from sequel/lib/sequel/dataset/actions.rb:965:in `execute'
    from sequel/lib/sequel/adapters/mysql2.rb:197:in `execute'
    from sequel/lib/sequel/adapters/mysql2.rb:156:in `fetch_rows'
    from sequel/lib/sequel/dataset/actions.rb:139:in `each'
    from (irb):1:in `to_a'
    from (irb):1
    from gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
    from gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
    from gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
    from gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from buy/bin/rails:9:in `require'
    from buy/bin/rails:9:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'

i tried to figure out where the sql generates to change something like

     "where #{key} = #{value}"

to 

     "where #{table_name}.#{key} = #{value}"

but totally lost during 1.hour trip over the files (

help

P.S. I understand, i can use another syntax to come over the error, like

    >> Notebook.where('notebooks.id = 1').to_a

it would be great to fix it on gem side because i have described simplified version of my case and in my real situation it is not the solution... (i use elasticsearch + chewy gem and it can not index the row because it can not retrieve it by id)

**Comment by jeremyevans** [comment]
This is expected.  If you are using class table inheritance, you need to disambiguate the ambiguous column by qualifying it with the appropriate table.  I guess this isn't mentioned specifically in the documentation, I'll see if I can add a note about it.

**Comment by okliv** [comment]
If it is possible, can you, please, drop a line with an example what did you mean?

thank you!

(please, look at my P.S. above - i updated it later than you commented)

**Comment by jeremyevans** [comment]
`Notebook.where(:notebooks__id=>1).to_a`
