### ISSUE TITLE
A case for case-preserving but case-insensitive identifiers

### ISSUE THREAD

**Issue by bg** [jeremyevans/sequel#1180]
### Complete Description of Issue

I would like to be able to write readable, camel-cased column identifiers in my code, matching the camel-cased identifiers stored in our databases, while remaining forgiving about differences in case. That is, our databases themselves are case-preserving with respect to identifiers, but support case-insensitive lookups of identifiers. But in Sequel, a consequence of rows returned from Datasets being of type Hash is that lookups of identifiers in rows are case-sensitive. This means we can't implement the same policy across our whole codebase, which is to make all identifiers case-preserving but case-insensitive, i.e. a reference to a field 'LastName' or 'Lastname' within a row should both succeed. We can override the identifier_input_method and/or identifier_output_method, but that only forces the casing to be one way or the other and does nothing to support case-insensitive lookups of identifiers within the row Hash.

### Simplest Possible Self-Contained Example Showing the Bug

If the DB stores fields camel-cased, e.g. LastName, then if case-folding is disabled by setting the input/output methods to nil, you must use the original case stored in the database, and no variants are acceptable, e.g.

```ruby
DB.identifier_input_method = DB.identifier_output_method = nil
DB[:Person].first[:LastName]
# => "Smith"
DB[:Person].first[:Lastname]
# => nil (i.e. the row is a hash with key :LastName, but not :Lastname)
```

I can work around the issue using a row_proc and the insensitive_hash gem to return row.insensitive for each row, but this is kludging around Sequel's lack of this feature and I would like it formally supported instead of just hacked around (plus it increases my dependencies by one, which makes one more thing to worry about breaking).

Thanks,
Ben

**Comment by jeremyevans** [comment]
Sorry, but I don't think this is a good fit for Sequel.  While I'm sure it would make your application simpler, it adds unnecessary complexity for probably all other Sequel users.  As you already have a working approach to this using row_proc, you should probably just continue to use that.

**Comment by bg** [comment]
Fair enough. Since it interferes with "normal" usage of row_proc, it does complicate using it for its intended purpose, so I can see why it's not a wonderful solution in your view. However, as I didn't see any issue filed that addressed my use case, and reasoned that I might not be the first person ever to think of it, I thought I had better at least put my problem statement and workaround out there. Perhaps someone else would find my workaround interesting.

So for posterity, here's the complete workaround that we use:

## Workaround

```ruby
require 'insensitive_hash'

# Make identifiers case-preserving both on input and output,
# overridding DB defaults:
# - see https://github.com/jeremyevans/sequel/issues/1180
Sequel::Database.identifier_input_method = Sequel::Database.identifier_output_method = nil

module Sequel
  class Dataset
    alias :old_initialize :initialize

    # Make identifiers in row Hash case-insensitive:
    # - see https://github.com/jeremyevans/sequel/issues/1180
    def initialize *args, &block
      self.row_proc = proc{|row| row.insensitive}
      old_initialize *args, &block
    end
  end
end
```

## Caveats

- Note that if you override the monkey-patched Dataset with a different row_proc, it's up to you to make your replacement proc case-sensitive!
- Also, this only covers case-insensitive column identifiers within rows, not other identifiers, as that's the area where we're experiencing issues.
