### ISSUE TITLE
unexpected undefined instance method inside DB.alter_table block 

### ISSUE THREAD

**Issue by okliv** [jeremyevans/sequel#1181]
### Complete Description of Issue

i have this methods

    ...

    def table_exists
      DB.table_exists? name
    end

    def modification_method
      "#{table_exists ? 'alter' : 'create'}_table"
    end

    def sync_structure
      DB.public_send modification_method, name do
        primary_key :id unless table_exists
        absent_columns.each { |col_name| drop_column col_name; drop_index col_name }
        h_columns.each do |h_col|
          column h_col[:name], h_col[:type]||:string, *h_col[:options] #, unique: true, null: false, default: 1, index: true
          index h_col[:name] if h_col[:options].try(:[], :index)
        end
      end
    end

    ...

### Simplest Possible Self-Contained Example Showing the Bug

if i try to call instance method `sync_structure` i have this error 

     NameError: undefined local variable or method `table_exists' for #<Sequel::Schema::AlterTableGenerator:0x007fdbd60402e0>

but i expect that instance method `table_exists` has to exist - it defined above

the same is for `absent_columns` and `h_columns` methods (and, i guess, any others)

**Comment by jeremyevans** [comment]
This is expected, as `alter_table` uses `instance_eval`.  You would need to save a reference to self and use it when calling `table_exists` and other methods:

```ruby
def sync_structure
  s = self
  DB.public_send modification_method, name do
    primary_key :id unless s.table_exists
    s.absent_columns.each { |col_name| drop_column col_name; drop_index col_name }
    s.h_columns.each do |h_col|
      column h_col[:name], h_col[:type]||:string, *h_col[:options] #, unique: true, null: false, default: 1, index: true
      index h_col[:name] if h_col[:options].try(:[], :index)
    end
  end
end
```

**Comment by okliv** [comment]
ok, i got it. thanks

offtop: maybe you can advice a direction for a better solution to sync current db structure with any declared hash, especially in case of ClassTableInheritance... because all I can imagine for now - is `create/alter/drop` table by table  using `add/drop_column` syntax or change type and other options... maybe there is exists another solution?

thanks in advance

**Comment by jeremyevans** [comment]
I guess I don't understand the problem.  Why do you need to sync the schema?  Having to sync the structure (automigrate) should only be necessary if you don't consider the database the canonical source, which IMO indicates a poor design.  If you aren't using some kind of database migrations, I would recommend considering it.

**Comment by okliv** [comment]
for my particular case i will have a series of canonical excels with most correct db schema. it will be changed slightly during project development. so i decided to simplify db modifications using this kind of synchronisations... 

there is no problem in sense of any difficulties, but only in sense if i try to develop something that already exists... particular methods or libraries(gems)

but still thanks for the critical reading =)

**Comment by okliv** [comment]
and due to the fact that i use ClassTableInheritace it would be great to check for existing columns all parent tables of particular nested model somehow more simple than successively reading each `Model.cti_columns` of parent table(s)

**Comment by jeremyevans** [comment]
If you are still in development and not in production, it may be easier to just drop the existing tables and recreate the schema instead of trying to figure out what changed.  But there may be reasons that wouldn't work for your application.  Anyway, if you have something that works for you (now that the instance_eval issue has been worked around), there's probably not a good reason to change it.
