### ISSUE TITLE
create_enum in change migration fails

### ISSUE THREAD

**Issue by tobymao** [jeremyevans/sequel#1182]
Created a migration with the enum plugin using the change block. It fails on a reverse migration.

Manual up and downs work.

# Example
```ruby
Sequel.migration do
  change do
    create_enum :kind, %w[a b c]

    create_table :dogs do
      primary_key :id
      kind :kind
    end
end
```
I, [2016-05-07T22:21:32.335608 #28829]  INFO -- : (0.000185s) CREATE TABLE IF NOT EXISTS "schema_info" ("version" integer DEFAULT 0 NOT NULL)
I, [2016-05-07T22:21:32.335667 #28829]  INFO -- : (0.000185s) CREATE TABLE IF NOT EXISTS "schema_info" ("version" integer DEFAULT 0 NOT NULL)
I, [2016-05-07T22:21:32.336140 #28829]  INFO -- : (0.000350s) SELECT * FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.336165 #28829]  INFO -- : (0.000350s) SELECT * FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.336414 #28829]  INFO -- : (0.000095s) SELECT 1 AS "one" FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.336433 #28829]  INFO -- : (0.000095s) SELECT 1 AS "one" FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.336768 #28829]  INFO -- : (0.000192s) SELECT count(*) AS "count" FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.336788 #28829]  INFO -- : (0.000192s) SELECT count(*) AS "count" FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.336998 #28829]  INFO -- : (0.000099s) SELECT "version" FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.337016 #28829]  INFO -- : (0.000099s) SELECT "version" FROM "schema_info" LIMIT 1
I, [2016-05-07T22:21:32.337387 #28829]  INFO -- : Begin applying migration version 1, direction: down
I, [2016-05-07T22:21:32.337407 #28829]  INFO -- : Begin applying migration version 1, direction: down
I, [2016-05-07T22:21:32.337592 #28829]  INFO -- : (0.000073s) BEGIN
I, [2016-05-07T22:21:32.337630 #28829]  INFO -- : (0.000073s) BEGIN
I, [2016-05-07T22:21:32.337763 #28829]  INFO -- : (0.000071s) ROLLBACK
I, [2016-05-07T22:21:32.337786 #28829]  INFO -- : (0.000071s) ROLLBACK
rake aborted!
Sequel::Error: irreversible migration method used, you may need to write your own down method
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:178:in `block in reverse'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:106:in `apply'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:542:in `block (2 levels) in run'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/database/transactions.rb:141:in `_transaction'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/database/transactions.rb:115:in `block in transaction'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/database/transactions.rb:101:in `transaction'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:470:in `checked_transaction'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:541:in `block in run'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:538:in `each'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:538:in `run'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:397:in `run'
/Users/toby/.rvm/gems/ruby-2.3.1/gems/sequel-4.33.0/lib/sequel/extensions/migration.rb:368:in `apply'

**Comment by jeremyevans** [comment]
You need to load the migration extension before the pg_enum extension, then it should be reversible.  This is mentioned in the pg_enum documentation.  I tried with the code you provided and is does work correctly if migration is loaded before pg_enum.

**Comment by tobymao** [comment]
Ah, thanks, I didn't catch that. It does indeed work.
