### ISSUE TITLE
delay_add_association not working to many_to_one

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/sequel#1189]
I think this is related to my latest reported issue. Again, due to association setting in non-persisted objects. delay_add_association is now working for one_to_many, but not many to one. 

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'
require 'logger'

DB = Sequel.sqlite
DB.loggers = [Logger.new(STDOUT)]
Sequel::Model.plugin :delay_add_association

DB.create_table? :cars do
  primary_key :id
end
DB.create_table? :wheels do
  foreign_key :car_id, :cars
  column :number, Integer
end

class Car < Sequel::Model
  one_to_many :wheels
end
class Wheel < Sequel::Model
  many_to_one :car
end

puts "database is set..."


wheel = Wheel.new(number: 1)
car = Car.new
wheel.car = car #=> this is the line that blows

begin
  car.save
rescue
  puts "BOOM!!"
end

puts "car has #{car.wheels.size} wheels..."
puts "wheel car is #{car}..."

DB.drop_table :wheels, :cars
```

### Full Backtrace of Exception (if any)

```
app/.bundle/ruby/2.2.0/bundler/gems/sequel-11870929e696/lib/sequel/model/associations.rb:2432:in
 `set_associated_object': associated object #<Car @values={}> does not have a primary key **(Sequel::Error)
```

Somehow it expects the many_to_one relationship to already be persisted. We already discussed in the previous issue that it is expected that the "parent" to already be persisted, but what if it is a validation for the car to have >0 wheels (model validation)? I know that I could just turn it around and it would work, but again, factories, etc... 

Expecting not only for it to be "delayed" (like in the add_ methods), but also to "set" the association on the associated record (so that ```car.wheels``` returns the array with the wheel instance). Is this doable?

**Comment by TiagoCardoso1983** [comment]
I also don't think that the nested_attributes plugin is going to solve this one. The gist of it is:

* create the wheel instance using the factory
* the factory also creates an instance of car
* the car has an after build trigger; if the initialized car has no wheel, add an instance 

the problem is the last condition. even if I could add an unpersisted car to the wheel (```wheel.car = Car.new```), the new car will not reflect this association, in which ```car.wheels.length```` will return 0.

**Comment by jeremyevans** [comment]
As the plugin name indicates, delay_add_association only affects the add_ association methods, not the many_to_one/one_to_one setter methods.

It is expected that the associated object you pass to the many_to_one setter method is already persisted, just as it is expected that the receiver of the one_to_many add_ association method is already persisted.

To do what you want to do with unpersisted objects, you should probably manually set values in the association caches, as I explained in my comment to #1187

**Comment by TiagoCardoso1983** [comment]
I will retry this again next week. It does seem to work in this small script, but not really the app I'm trying to migrate... I'll see if I can come up with a solution.
