### ISSUE TITLE
pg_array extension not automatically making attributes work like arrays

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/sequel#1190]
In a previous [sequel-talk group post](https://groups.google.com/forum/#!topic/sequel-talk/CadWGUX82bQ), you told that pg_array extension automatically handles the attributes in the model. Maybe there was some configuration missing, but it doesn't work exactly outside-of-the-box. Here is the script:

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'
require 'logger'

%x{PGPASSWORD=root createdb -h localhost U root -O root test "some test db"}

DB = Sequel.connect('postgres://root:root@localhost/test')
begin
  DB.loggers = [Logger.new(STDOUT)]
  DB.extension(:pg_array)
  Sequel.extension :pg_array_ops # also tried with this one, didn't help

  DB.create_table? :cars do
    primary_key :id
    column :wheels, "text[]"
  end

  class Car < Sequel::Model
  end

  car = Car.new

  puts "car has #{car.wheels.size} wheels"
  car.wheels << "wheel"
  puts "car has #{car.wheels.size} wheels"

  DB.drop_table :cars
ensure
  DB.disconnect
  puts "deleting database..."
  %x{PGPASSWORD=pgadmin dropdb -h localhost -U root test}
end
```

### Full Backtrace of Exception (if any)

```
script.rb:22:in `<main>': undefined method `size' for nil:NilClass (NoMethodError)
```

My expectation was that wheels would return an empty array, and I could interact with it.

**Comment by jeremyevans** [comment]
The default value for columns in a new model object is nil, so this is expected behavior.  You should probably use `car.wheels = ["wheel"]` or `car.wheels ||= []` before `car.wheels << "wheel"`.

**Comment by TiagoCardoso1983** [comment]
Thx again. It did the trick, although it's a bit head-scratching in this case, but fair enough.
