### ISSUE TITLE
Problem with many_to_one association where the column name is mixed case

### ISSUE THREAD

**Issue by CyberFerret** [jeremyevans/sequel#1191]
Came across an issue when developing a new app that utilises a legacy MySQL database today.  I am trying to set up Sequel associations between Students and Mentors.

In the legacy tables, the Student database has a column called `MentorID` - note capitalisation.

I have my Sequel models set up as:

    class Student < Sequel::Model(:dbstudents)
      many_to_one :mentor, :key => :mentorid
    end

    class Mentor < Sequel::Model(:dbmentors)
      one_to_many :students, :key => :mentorid
    end

I can do `mentor = Mentor[1]` to get a mentor, and `mentor.students` works as expected, giving me all the students belonging to that mentor.

However, doing `student = Student[1]` and then `student.mentor` kept telling me that there was an `undefined method 'mentorid' for Students`.

I was tearing my hair out in frustration trying to resolve this, and eventually I just renamed the column name from `MentorID` to `mentorid` in the `dbstudents` table on our test database, and voila! it worked.

Have I missed another flag or plugin that will ignore the column name case, or is this a bug in Sequel?

**Comment by CyberFerret** [comment]
Ok, further testing has shown that if I set up the model as:

    class Student < Sequel::Model(:dbstudents)
      many_to_one :mentor, :key => :MentorID
    end

then it will work on the original legacy data.  No changes needed to the `Mentor` model though, it works with simply lowercase symbol name for `:mentorid`.

I am thinking it is not very 'Rubyish' to have mixed case symbol names?!?  But at least it works now, so I am guessing this ticket can be closed, unless there is a need to remove case sensitivity on the column/key names for future versions?

**Comment by jeremyevans** [comment]
This is expected behavior.  Sequel quotes identifiers by default in order to make it possible to use identifiers that conflict with keywords, and quoting identifiers makes them case sensitive on most databases.
