### ISSUE TITLE
Wrong type conversion during copy between sqlite3 and postgresql

### ISSUE THREAD

**Issue by dangusev** [jeremyevans/sequel#1192]
### Complete Description of Issue
Columns of type "bool" in sqlite3 became "text" in postgresql after copy using `sequel -C`.

### Simplest Possible Self-Contained Example Showing the Bug
For instance, I have a table "accounts_user" with bool columns "is_active" and "is_superuser". 
`sequel -d` gave me the following output:
```ruby
create_table(:accounts_user) do
      String :username, :size=>50, :null=>false
      String :first_name, :size=>30, :null=>false
      String :last_name, :size=>30, :null=>false
      String :is_superuser, :null=>false
      String :is_active, :null=>false
```
As you can see, these columns have type String.
After `sequel -C` in Postgresql db I have a column of type TEXT with value 'true'/'false'.
I think it's a bug.

**Comment by jeremyevans** [comment]
Thanks for the bug report. The schema_dumper extension currently only recognizes `boolean` as boolean, not `bool`.  This is different than the Database schema parser, which recognizes both `boolean` and `bool`.  I agree it would make sense for the schema_dumper extension to treat `bool` as boolean, I'll try to update it tomorrow.

**Comment by dangusev** [comment]
Thanks for your reply! I'll look forward to it.
