### ISSUE TITLE
transaction(rollback: :always) fails when inside another transaction

### ISSUE THREAD

**Issue by cyclotron3k** [jeremyevans/sequel#1193]
### Complete Description of Issue
I frequently use `DB.transaction(rollback: :always)` when testing code from a console. I'll use it to make sure everything is running as expected before removing the rollback and running it one more time.

### Simplest Possible Self-Contained Example Showing the Bug
I've noticed that in my set up, (Ruby 2.0.0, Postgres 5.4, sequel 4.28.0, sequel_pg 1.6.13), the rollback does not happen if the transaction happens to be inside another transaction:

```ruby
DB.transaction do
    DB.transaction(rollback: :always) do
        SomeModel.new(key1: "val1", key2: "val2").save
    end
end

# (0.002144s) BEGIN
# (0.038409s) INSERT INTO "my_table" ("key1", "key2") VALUES ('val1', 'val2') RETURNING *
# (0.006918s) COMMIT
```

vs.

```ruby
DB.transaction(rollback: :always) do
    SomeModel.new(key1: "val1", key2: "val2").save
end

# (0.002144s) BEGIN
# (0.038409s) INSERT INTO "my_table" ("key1", "key2") VALUES ('val1', 'val2') RETURNING *
# (0.001787s) ROLLBACK
```

Apologies if this has already been fixed, or it's expected behaviour

**Comment by janko-m** [comment]
I think Sequel's default behaviour is that the inner transaction will simply reuse the outer transaction. Try using `DB.transaction(rollback: :always, auto_savepoint: true)` instead, as suggested by the "Testing With Sequel" guide.

**Comment by jeremyevans** [comment]
Currently, the behavior of `:rollback=>:always` is unspecified if called inside another transaction.  If you want to use `:rollback=>:always` inside another transaction, you probably also want to include the `:savepoint=>true` option.

In terms of making things more usable, if `:rollback=>:always` is specified and the database supports savepoints, we might want to automatically use a savepoint.  However, if `:rollback=>:always` is specified and the database does not support savepoints, I'm not sure what the behavior should be.  It should either raise a Sequel::Error, or it should rollback the containing transaction.  I'll pick one of the two options and implement it later today.
