### ISSUE TITLE
sqldriver behaves differently in different platforms

### ISSUE THREAD

**Issue by lkfken** [jeremyevans/sequel#1194]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

Same code to load the adapter:
1. on Windows (10, jRuby 9.0.5.0), it works fine.
2. on Linux (Ubuntu 16.04, jRuby 9.1.0.0), it throws an exception.

The SQL driver was downloaded from https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'dotenv'
Dotenv.load!

require 'sequel'
require './driver/sqljdbc42.jar'

db = Sequel.connect({ "adapter"  => "jdbc",
                      "database" => "sqlserver://#{ENV['DB_SERVER']};database=#{ENV['DATABASE']};user=#{ENV['DB_USER']};password=#{ENV['PASSWORD']}" })

db.test_connection  # on Windows, it is true; on Linux, it raises an exception
```

### Full Backtrace of Exception (if any)
```ruby
user@LINUX-01:~/scripts/app$ ruby test.rb
Sequel::AdapterNotFound: com.microsoft.sqlserver.jdbc.SQLServerDriver not loaded
         load_driver at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/adapters/jdbc.rb:59
               <top> at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/adapters/jdbc/sqlserver.rb:3
             require at org/jruby/RubyKernel.java:944
             require at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
              (root) at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:1
        load_adapter at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:98
  adapter_initialize at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/adapters/jdbc.rb:361
          initialize at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/database/misc.rb:147
             connect at /home/user/.rbenv/versions/jruby-9.1.0.0/lib/ruby/gems/shared/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:67
               <top> at test.rb:9

```

**Comment by jeremyevans** [comment]
This doesn't appear to be a bug in Sequel, I think it's a general issue with JDBC.  Can you get a working connection using JDBC directly on Linux?  If so, this might be a bug in Sequel, but that seems very unlikely to me.

One other note is that when using the JDBC adapter, you should use a jdbc connection string instead of an options hash with :adapter and :database options:

```ruby
db = Sequel.connect("jdbc:sqlserver://#{ENV['DB_SERVER']};database=#{ENV['DATABASE']};user=#{ENV['DB_USER']};password=#{ENV['PASSWORD']}"
```

**Comment by lkfken** [comment]
Hi Jeremy,

I am not quite sure what you mean by "working connection using JDBC directly".  If you mean using `jdbc-jtds`, then it is working.
```ruby
Gemfile:
source 'https://rubygems.org' do
  gem 'rake'
  gem 'dotenv'
  gem 'jdbc-jtds', :platform => :jruby
end
```

```ruby
require 'dotenv'
Dotenv.load!

require 'sequel'
require 'pp'

jtds = Sequel.connect("jdbc:jtds:sqlserver://#{ENV['DB_SERVER']};database=#{ENV['DATABASE']};user=#{ENV['DB_USER']};password=#{ENV['PASSWORD']}")
pp jtds.test_connection  # true

require './driver/sqljdbc42.jar'
sqljdbc = Sequel.connect("jdbc:sqlserver://#{ENV['DB_SERVER']};database=#{ENV['DATABASE']};user=#{ENV['DB_USER']};password=#{ENV['PASSWORD']}")
pp sqljdbc.test_connection  # throw exception
```

**Comment by jeremyevans** [comment]
I mean using the sqlserver JDBC driver directly in ruby, without using Sequel.   Sequel's jdbc adapter just uses JDBC to make the connection, if JDBC is raising the error, there is nothing Sequel can do to fix things.

From the code you posted, you can see that the jtds driver works correctly, so I would just use that unless you have a requirement to use the sqlserver driver.

As your problem appears related to JDBC and not Sequel itself, I'm closing this now.  If you are able to get a working connection using the sqlserver JDBC driver on Linux using JDBC directly, please post details on how to do that here and I'll see if there are possible changes that could be made to Sequel to allow things to work.
