### ISSUE TITLE
Handling of default values in db not reflected in model instances

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/sequel#1196]
This might be just one of those "feature not a bug" quirks that I've posted before, but I'll report it nevertheless. Basically I'm setting a default value in the database for a column. When I'm creating an instance of it, the value is empty. After I save it, it magically appears.

Now, let's say I would like to use this default in a form. No problem, I can override the method and handle the nil case. But that means that I'm repeating the default value in the schema AND the model. 

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'
require 'logger'

%x{PGPASSWORD=root createdb -h localhost -U pgadmin -O root test "some test db"}

DB = Sequel.connect('postgres://root:root@localhost/test')
begin
  DB.loggers = [Logger.new(STDOUT)]

  DB.create_table? :rappers do
    primary_key :id
    String :name, default: "Slim Shady"
  end

  class Rapper < Sequel::Model
  end

  rapper = Rapper.new

  puts "Hi, my name is #{rapper.name}"
  rapper.save
  puts "Hi, my name is #{rapper.name}"

  DB.drop_table :rappers
ensure
  DB.disconnect
  puts "deleting database..."
  %x{PGPASSWORD=pgadmin dropdb -h localhost -U root test}
end
```

Now, imagine it's not a string, but a boolean. I think this might be an issue regarding the portability of sequel to rails and mapping of activemodel/forms/handling-of-default-checkbox-values etc.

**Comment by jeremyevans** [comment]
You can use the defaults_setter plugin if you want the behavior you describe.

As mentioned in the contribution guidelines, please do not post issues on GitHub unless you are sure there is a bug.  If there is any doubt about whether it is actually a bug, open up a thread on the sequel-talk Google Group, or ask on IRC.

**Comment by TiagoCardoso1983** [comment]
Thx again, it did the trick! Completely overlooked this one in the plugins list.
