### ISSUE TITLE
Congrats on closing 800 issues & retaining a zero count!

### ISSUE THREAD

**Issue by ylluminate** [jeremyevans/sequel#1199]
Congratulations on closing **800** issues here and being at **_ZERO_** still! :)

Would you mind chiming in on the possibility of a `reactive-sequel` gem as noted prior to [this remark](https://gitter.im/zetachang/react.rb?at=575087506bbc2d1d4df0ae8f)?

**Comment by jeremyevans** [comment]
Thank you for your support. :) However, as this isn't a bug in Sequel, this is not really the appropriate forum.

Not being a user of React or React.rb, I'm not sure what a reactive-sequel gem would do.  But if you want to discuss it in the Google Group or IRC, I'm available there.
