### ISSUE TITLE
:active_model plugin not extending to the dataset

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/sequel#1201]
### Complete Description of Issue

The ActiveModel plugin only works on the model level, but at least in ActiveRecord, it works on the Relation level. A small example would be:

```ruby
# activerecord
c = Car.new
c.model_name #=> "Car"
c.wheels.model_name #=> "Wheel"

# sequel
c = Car.new
c.model_name #=> "Car"
c.wheels.model_name #=> "undefined method"
```

From what I saw, the ActiveModel is a basic subset of a (way more bloated) list of methods that rails active model implements. Which is fine by me, I'm not expecting a full reimplementation. However, I had problems adding ```draper``` support for sequel, as although it works on the model level, the collection decorators (dataset decorators, in this case) can't be implemented in the same way. 

I'll be working around by injecting a dummy version of the #model_name method, although I don't know how to get the proper model name from dataset (what would be the proper API?). However, I think that the lack of ActiveModel support on the datasets might be an hinderance for "replace activerecord with sequel" in some corner cases. 

Note: just checked that #model_name implementation is directly done on the ActiveRecord_Associations_CollectionProxy, which might be a very ugly hack on the rails side. The ActiveRelation ancestors list contains ActiveModel extensions, though.

**Comment by jeremyevans** [comment]
This is not part of the ActiveModel API, as defined by the ActiveModel::Lint tests (https://github.com/rails/rails/blob/master/activemodel/lib/active_model/lint.rb). So `draper` is not ActiveModel compliant, it is using ActiveRecord specific code.  You may want to inform `draper` of that and see if they are willing to change to be ActiveModel compliant.

I don't plan to support this in Sequel's active_model plugin, unless it becomes part of the ActiveModel API and is added to the ActiveModel::Lint tests.

**Comment by TiagoCardoso1983** [comment]
fair enough, after writing my last comment I could see how this could be perceived as an Active Record hack around providing the missing API on the collections. I will open an issue under draper.
