### ISSUE TITLE
Inflections don't overwrite certain methods because it expects ActiveSupport

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/sequel#1202]
Concerns [this](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/model/inflections.rb#L159), but methods defined similarly in the same module. 

So basically sequel doesn't use it's custom inflection methods if they're already defined, because apparently it's expecting the string classes to be monkey patched, and the monkey patch to only be defined in ActiveSupport. 

Sadly this is not the case, as other gems might "monkey-patch" strings. One of them is [term-ansicolor](https://github.com/flori/term-ansicolor/), which isn't monkey-patching strings by default. We have this internal gem which depends on it and monkey-patches strings by default, as most people writing cli scripts expect the color methods to be defined (internal requirement). As some of the scripts also connect to the database with sequel, we found this odd behaviour, and affected people's impression of sequel, as they expected table names to be capitalized(?). This is a small reproduction:

```ruby```
require 'logger'               
# this is what the internal gem basically does             
require 'term/ansicolor'                    
String.send :include, Term::ANSIColor
require 'sequel'                            
DB = Sequel.sqlite                          
DB.create_table(:cars) {  primary_key(:id) }
class Car < Sequel::Model;;end              
puts "table name is #{Car.table_name}"      
DB.drop_table :cars
```

```#underscore``` method ansi-underscores strings, which is different from the behaviour Sequel defines or expects to be defined.

I don't necessarily think this is a "bug" in sequel, but the expectation that the method is defined is either unnecessary or incomplete. I'd either remove the checks completely or would complete them with a ```and defined?(ActiveSupport)``` if that is indeed the reason of the check's existence.

**Comment by jeremyevans** [comment]
It's expected that Sequel's inflections will not override existing inflections.  This is not specifically ActiveSupport's inflector, it could be you are using facets or another alternative gem.  You should define String#underscore manually in your application to do what you want, though I'm guessing fixing it for Sequel would break it for ansicolor.

**Comment by TiagoCardoso1983** [comment]
It shouldn't override existing inflections, when it's indeed an inflection. That's not the ansicolor case. 

I don't know whether the facets key couldn't be done another way, but assuming methods are defined on a top core class (String) which do not belong to core ruby (underscore) doesn't seem the best approach. This is indeed an edge case of monkey-patching.

**Comment by jeremyevans** [comment]
Note that you can just override `Sequel::Model.underscore` to do what you want.  This will keep ansicolor and Sequel both working at the same time.

**Comment by TiagoCardoso1983** [comment]
But I don't think I should override Sequel methods (unless I'd have to). Maybe I haven't expressed the issue clearly, sorry about that. Thing is, I have to monkey-patch the String class with ansicolor, I can't do anything about that. And sequel, when "underscoring" model classes, checks if there isn't an ```underscore``` method defined, and only after that check it proceeds to its own underscore. This means that sequel assumes that an ```underscore``` method in the string will always implement inflection API. 

I was arguing that this ```underscore``` check is unnecessary at least, and insecure at worst, because it exposes internal core sequel methods to "unexpected" API behaviour. Definition of unexpected in this case, means:

* not a core ruby API method
* not an API from a known dependency

for example, as activesupport is not a dependency from sequel, this method shouldn't be duck-typed against, same as facet, etc. Again, this might be a technicality and I'm being too fundamentalist, however I'd argue that this contract breach allowed term-ansicolor's String monkey patches to influence sequel core behaviour. I wouldn't be arguing about a possible bug if term-ansicolor had monkey-patched, I don't know, ```String#length```. Hope I cleared up what I meant. 

My workaround was simply to create the model classes before monkey-patching the string class, as sequel memoizes most of this information and doesn't break further.

**Comment by jeremyevans** [comment]
Yes, Sequel does assume that if you define `String#underscore`, it returns an underscored version of the string.  This is to allow it to be used correctly in applications that use a different inflections library and respect those inflections.  If Sequel didn't do this, many people would complain that they defined custom inflections and Sequel is not using them.

Looking at term-ansicolor, it doesn't even define `String#underscore`.  It defines `Term::ANSIColor#underscore`.  Unless you include `Term::ANSIColor` in String, it won't cause any problems.  It was your choice to include `Term::ANSIColor` in String.

This isn't the only place in Sequel where we check for existing methods and act differently if they are present.  If you define `Object#name` and then create a model class that has a column named `name`, you'll notice that calling `name` on an instance of the model class uses `Object#name`, it doesn't return the value of the column.

**Comment by TiagoCardoso1983** [comment]
yup, that's why I said before "..** I have to monkey-patch the String class with ansicolor**..". I don't want this to sound like a critique at all, it does seem to be a valid reason not to break other library's inflections, and rolling back this is probably not an option. I just think that the requirement "don't break other library's inflections" is not acurately represented by "check whether String#underscore is defined", that's all. How could it be done otherwise? I don't have an answer for that now, and we would have to agree on the first premise for anything to come up. In the end, taking the decision of monkey-patching a core class is usually a decision with implications, and I just experienced the impact of my decision in this sequel bit, because most inflection libraries work that way and sequel has to accomodate to that. Anyway, I already have a workaround, and will be probably working on a way to limit the extent of my monkey-patch more effectively.
