### ISSUE TITLE
Oracle adapter: not closing cursors in some cases

### ISSUE THREAD

**Issue by calamitas** [jeremyevans/sequel#1203]
### Complete Description of Issue

The Oracle adapter does not always close the cursor it opens when using bind variables, resulting in an ORA-01000 error after a while.

### Simplest Possible Self-Contained Example Showing the Bug

DB[:users].where(id: 10000).call(:update, { sign_in_count: 13 }, { sign_in_count: :$sign_in_count })

### Analysis

By logging when the leaked cursor is opened, I found out it is opened in Sequel::Oracle::Database#_execute.

In Sequel::Oracle::Database#_execute, there is a single call to OCI8::Cursor#close, namely when block_given? is true. When block_given? is false, the cursor is not closed in that method. I don't know enough of the internals of Sequel to know if it should be closed elsewhere. As the expression above returns 1 (or 0 if there is no such user), I have no way of closing it in the calling code. Also, if I pass a block to the call(:update), it is not yielded to, so it seems to be lost somewhere along the way to the _execute method.

The version of Sequel is 4.30.0 I'm using is.

**Comment by jeremyevans** [comment]
Thanks for the report. This looks like a bug to me.  I'm surprised GC doesn't close the cursors automatically, though. I should be able to fix this later today.

**Comment by calamitas** [comment]
The usual limit for open cursors per session in Oracle is a few hundred, so it's easy to hit that limit without triggering the GC if you only do insert/update statements because these don't generate a lot of objects on Ruby's heap. This kind of use case caused the problem in our application.

**Comment by jeremyevans** [comment]
Fixed by bb24a886233ab391e425413e20db180426872eba
