### ISSUE TITLE
Association using wrong ID 

### ISSUE THREAD

**Issue by goncalopereira** [jeremyevans/sequel#1204]
### Complete Description of Issue

When using a one_to_one association if I join and filter through the association table it will load the class through the wrong ID column.

### Simplest Possible Self-Contained Example Showing the Bug
```

class OrderLocation < Sequel::Model(:orderlocation)
end

class Order < Sequel::Model
  plugin :dataset_associations
  one_to_one :orderlocation, key: :order, class: :OrderLocation
end
```
```
database.create_table :orders do
    primary_key :id, :type => Bignum
end
database.create_table :orderlocation do
    primary_key :id, :type => Bignum
    foreign_key :order, :orders
    String :country_code
end

```

This will have the correct location (1)
```
orders = Order.all
orders.first.orderlocation 
```

This will have the wrong location (2)
```
orders = Order.join(:orderlocation,:order=>:id).where(:country_code=>'BE').all
orders.first.orderlocation
```

This will fix the issue (3)
```
orders = Order.join(:orderlocation,:order=>:id).where(:country=>'X').select_all(:orders).all
orders.first.orderlocation
```

### SQL Log (if any)

On (3) it will get the correct ID when loading orderlocation

```
SELECT "orders".* FROM "orders" INNER JOIN "orderlocation" ON ("orders"."id" = "orderlocation"."order") WHERE (("country_code" = 'BE')) ORDER BY "created" DESC LIMIT 30 OFFSET 0

 SELECT * FROM "orderlocation" WHERE ("orderlocation"."order" = 1135) LIMIT 1
```

On (2) it will pick ID column from orderlocation not order - Using ID 1126 from table OrderLocation instead of ID 1135 from Order

```
SELECT * FROM "orders" INNER JOIN "orderlocation" ON ("orders"."id" = "orderlocation"."order") WHERE (AND ("country_code" = 'BE')) ORDER BY "created" DESC LIMIT 30 OFFSET 0

, [2016-06-15T14:59:27.169646 #9604]  INFO -- : (0.001055s) SELECT * FROM "orderlocation" WHERE ("orderlocation"."order" = 1126) LIMIT 1
```

**Comment by jeremyevans** [comment]
This is unrelated to associations, and is not a bug.  The default selection in Sequel is `*`, so if you join tables that have columns with the same names, and do not override the default selection, later columns with the same names overwrite earlier columns.

If you want to automatically set selected columns on model datasets, try using either the table_select or column_select plugins.
