### ISSUE TITLE
Mistake in documentation: raise_on_typecast_failure (default: true)

### ISSUE THREAD

**Issue by zlobz** [jeremyevans/sequel#1206]
raise_on_typecast_failure is false by default.

> **raise_on_typecast_failure**
Whether to raise an error when unable to typecast data for a column **(default: true)**. This should be set to false if you want to use validations to display nice error messages to the user (e.g. most web applications). You can use the validates_schema_types validation (from the validation_helpers plugin) in connection with this setting to check for typecast failures during validation.

**Comment by jeremyevans** [comment]
Thanks for the report. This is a documentation bug, I'll fix it shortly.
