### ISSUE TITLE
raise_on_typecast_failure and literals

### ISSUE THREAD

**Issue by zlobz** [jeremyevans/sequel#1207]
raise_on_typecast_failure doesn't work with literals.

```ruby
model.update(:created_at => Sequel.lit("now()"))
```
Exception: Sequel::InvalidValue: ArgumentError: invalid date

**Comment by jeremyevans** [comment]
This is expected.  Sequel::Model operates with values, not SQL expressions.  You need to drop down to the dataset level to use expressions:

```ruby
model.this.update(:created_at => Sequel.lit("now()"))
```

**Comment by zlobz** [comment]
Thanks!
