### ISSUE TITLE
Using query string in postgres connection string with migrator

### ISSUE THREAD

**Issue by tjad** [jeremyevans/sequel#1211]
### Complete Description of Issue
If I use the user & password query string params , I get a no password supplied error
### Password in the following example is not used

`sequel -m db/migration -M 001 postgres://127.0.0.1/mydb?user=myuser&password=TdT2K#e84!`

```{bash}
Sequel::DatabaseConnectionError: PG::ConnectionBad: fe_sendauth: no password supplied

.rvm/gems/ruby-2.3.1/gems/sequel-4.36.0/lib/sequel/adapters/postgres.rb:243:in `initialize'

```

### Environment

pg (0.19.0.pre20160409114042) - I have tried 0.18.4 first
sequel (4.36.0)

Ubuntu 16.04 environment
Ruby 2.3.1

**Comment by jeremyevans** [comment]
Yep, `&` is a shell metacharacter that makes the previous command run in the background.
