### ISSUE TITLE
Can't qualify query with extract

### ISSUE THREAD

**Issue by ksenia-zalesnaya** [jeremyevans/sequel#1213]
Sequel::SQL::QualifiedIdentifier is not transformed into string when qualify happens anywhere in query after extract.

This works:
`DB.select(:created_at.qualify(:users).extract(:year))`
`=> #<Sequel::Postgres::Dataset: "SELECT extract(year FROM \"users\".\"created_at\")">`

But this doesn't:
`DB.select(:created_at.extract(:year)).qualify(:users)`
`=> #<Sequel::Postgres::Dataset: "SELECT extract(#<Sequel::SQL::QualifiedIdentifier:0x007fac8a078c88> FROM \"users\".\"created_at\")">`

**Comment by jeremyevans** [comment]
Thanks for the report. That certainly appears to be a bug.  I'll look into it tomorrow.
