### ISSUE TITLE
all method does not return correct instances when using  CTI subclasses 

### ISSUE THREAD

**Issue by farukg** [jeremyevans/sequel#1214]
### Complete Description of Issue

Hello,

When i issue `Users::Admin.all` in the console i would expect to get all users with `role=='Users::Admin'`, but this does not work because the plugin joins on the admins table. 
That means (for the `all` method) for a user to become an admin i need not only the correct role, but also need to have an empty record with only the correct id in the admins table.

Is this the correct behaviour?

#### Migrations ####
```ruby
# create_users.rb
Sequel.migration do
  change do

    create_table :users do
      primary_key :id
      String :role
      String :email
    end

  end
end
```

```ruby
# create_admins.rb
Sequel.migration do
  change do
    create_table :admins do
      foreign_key :id, :users
      String :extra
    end
  end
end
```
#### Models ####

```ruby
# user.rb
class User < Sequel::Model
  plugin :class_table_inheritance, key: :role
end
```

```ruby
# users/admin.rb
module Users
  class Admin < User
  end
end
```
### Steps for reproducing

in the console:
`User.create role: 'Users::Admin' `

then

`Users::Admin.all`
`=> []`

### SQL Query 

```
Users::Admin.dataset.sql
"SELECT `users`.`id`, `users`.`role`, `users`.`email`, `admins`.`extra` FROM `users` INNER JOIN `admins` ON (`admins`.`id` = `users`.`id`)"
```

**Comment by jeremyevans** [comment]
This is expected.  If you use CTI, you need to have a matching row in all descendant tables.  Use `Users::Admin.create` instead of `User.create role: 'Users::Admin'` and this should be taken care of for you.

**Comment by farukg** [comment]
Hey, thanks for response, but i still have one question left:
How would you repair those incorrect table entries?
How can I easily create the entry for the admin in the admins table? is there a manual way?

When i already do : `user = User.create role: 'Users::Admin'`
Do i have any possibility on that user instance to create that entry afterwards?

**Comment by jeremyevans** [comment]
To fix things, insert a row in `admins` for every admin entry in `users` not already in `admins`:

```ruby
DB[:admins].insert([:id],
  DB[:users].
    where(:role=>'Users::Admin').
    exclude(:id=>DB[:admins].select(:id)).
    select(:id))
```

If you really want to create the `admins` row manually, you can do that using an after_create hook.  But there seems little point if you can just change your code to do things correctly.

**Comment by farukg** [comment]
Unfortunatly, my code is more complex than the example i provided. The key-column in my case is a foreign_key to another table which holds the possible types. Additionally, i use the same code on another device which gets its types via an api call. So when the types table is empty, i can not have cti. Now i just added the types first, then refreshed model_maps and table_maps to solve this issue.
What is your opinion on this kind of using cti ? :)

**Comment by jeremyevans** [comment]
Well, personally I avoid both CTI and STI in my applications, preferring either separate tables and classes, a conditional-based approach with a single class, or a json column for additional fields.  But if CTI with :model_map and :table_map are working for you, I wouldn't make any changes.
