### ISSUE TITLE
Add `remove_column_default` to AlterTableGenerator

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [jeremyevans/sequel#1220]
AlterTableGenerator includes `set_column_default`, but has no way to remove a default. (Postgres has `ALTER column DROP DEFAULT`).

### Simplest Possible Self-Contained Example Showing the Bug

When adding a column to table, one may want to make the column be non-nullable for entries, but provide a value for the existing entries. This currently cannot be done.

```
up do
  alter_table(:table_name) do
    add_column :type, Integer, default 0
    set_column_not_null :type
    remove_column_default :default
  end
end
```

**Comment by jeremyevans** [comment]
You can do `set_column_default nil`, which has the same effect.  Is there a reason that wouldn't work for you?

**Comment by celsworth** [comment]
I'd suggest that needs adding to the documentation as it wasn't obvious to me either

**Comment by jeremyevans** [comment]
I guess a documentation update makes sense, I'll work on that.

**Comment by PaulJuliusMartinez** [comment]
Ah, yeah, I didn't realize using `nil` would work. Thanks!
