### ISSUE TITLE
Please set source_code_uri for the gem

### ISSUE THREAD

**Issue by amatsuda** [jeremyevans/sequel#1223]
Could you please set the source_code_uri for this gem as `https://github.com/jeremyevans/sequel`?

This attribute could be used from some external tools, scripts, or services (in my case, an rbenv plugin named [gem-src](https://github.com/amatsuda/gem-src)).

This should be able to be done via https://rubygems.org/gems/sequel => Edit

Thanks!

**Comment by jeremyevans** [comment]
Thanks for the suggestion. Change made on rubygems.org.

**Comment by amatsuda** [comment]
@jeremyevans Thank you!!
