### ISSUE TITLE
master slave connection with mri

### ISSUE THREAD

**Issue by wolli2710** [jeremyevans/sequel#1229]
### Complete Description of Issue
I need to use makara to be able to use a differentiation between master and slave. 
It is all fine when I'm using jruby and the jdbc adapter, but when I'm using mri it is not possible to pass options with a slave to the connection.
Ruby version is ruby-2.1.2.

### Simplest Possible Self-Contained Example Showing the Bug
After the parsing of the database.yml I create two strings, one for the master and one for the slave. In my test environment this two strings are identical.

the string for master and slave looks like this:
"mysql2://root:@localhost:3306/db_test"

### Full Backtrace of Exception (if any)

`connect': Mysql2::Error: Unknown MySQL server host 'mysql2://root:@localhost:3306/db_test' (0) (Sequel::DatabaseConnectionError)

[1] pry(#<Connection::MySQL>)> Sequel.connect(server(@master), options)
=> #<Sequel::Mysql2::Database: "mysql2://root:@localhost:3306/db_test" {:servers=>{:read_only=>{:host=>"mysql2://root:@localhost:3306/db_test"}}, :encoding=>nil, :max_connections=>nil}>
[2] pry(#<Connection::MySQL>)> Sequel.connect(server(@master), options).get(1)
Sequel::DatabaseConnectionError: Mysql2::Error: Unknown MySQL server host 'mysql2://root:@localhost:3306/db_test' (2)
from /Users/.../.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
[3] pry(#<Connection::MySQL>)>

I'm not sure if this is a bug or if I just make something wrong. Any help would be great.
Cheers

**Comment by jeremyevans** [comment]
You probably want to use :uri instead of :host in your options, as :host takes a hostname, not a URI.

This doesn't appear to be a bug in Sequel, so as specified by the contribution guidelines, please ask for help on the Google Group or on IRC.
