### ISSUE TITLE
Sequel::DatabaseError: Mysql2::Error: Can't create table 'thecloud.clients' (errno: 150)

### ISSUE THREAD

**Issue by marcozanger** [jeremyevans/sequel#1230]
Im trying to create a new table with foreign keys and now I'm getting an error I didn't get before. This is the command I'm trying to run

unless DB.table_exists?(:clients)
  DB.create_table(:clients) do
    primary_key :id
    foreign_key :editorial_id, :editorials
    foreign_key :coop_id, :coops
    Integer :coop_consignment_share, :default => 0
    Integer :coop_fair_share, :default => 0
    Integer :coop_sale_share, :default => 0
  end
end

and this is the error:

Sequel::DatabaseError: Mysql2::Error: Can't create table 'thecloud.clients' (errno: 150)
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/adapters/mysql2.rb:77:in `query'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/adapters/mysql2.rb:77:in `block in _execute'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/database/logging.rb:33:in `log_yield'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/adapters/mysql2.rb:77:in `_execute'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:34:in `block in execute'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/database/connecting.rb:229:in `synchronize'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:34:in `execute'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/adapters/mysql2.rb:56:in `execute_dui'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/database/query.rb:43:in `execute_ddl'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/database/schema_methods.rb:632:in `create_table_from_generator'
	from /home/deployer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.12.0/lib/sequel/database/schema_methods.rb:188:in `create_table'
	from (irb):4
	from /home/deployer/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'

**Comment by jeremyevans** [comment]
This error is being raised by MySQL, the error is probably in the database (e.g. a permissions error), it's unlikely to be caused by Sequel.  If you think this error is due to invalid SQL being generated, please post an SQL log (`DB.loggers << Logger.new($stdout)`.  You can also try executing that SQL directly using the mysql command, and see if you get an error.

**Comment by marcozanger** [comment]
Found the problem. I don't know why but the two tables I was trying to add a foreign key to had different engines. Thanks!
