### ISSUE TITLE
Models for tables with same table names, but on different databases have wrong DB set on them.

### ISSUE THREAD

**Issue by kmoschcau** [jeremyevans/sequel#1231]
When I have two separate databases, which hold some tables with equal table names, all of the models I create for them, get the database settings of the database that was set first. A detail that might be important: For both of these tables I have to supply the table name manually, since Sequel would not be able to figure them out on their own.

This can be fixed on my side, simply by force setting the database right after opening the model class, but I would like if I would not have to do this.

Here a simple example:
```ruby
db_config_1 = {
  adapter: 'mysql2',
  host: 'host1.mydomain.com',
  user: 'user1',
  password: 'pass1',
  database: 'db1',
  port: 3306
}
db_config_2 = {
  adapter: 'mysql2',
  host: 'host2.mydomain.com',
  user: 'user2',
  password: 'pass2',
  database: 'db2',
  port: 3306
}

db_1 = Sequel.connect(db_config_1)
db_2 = Sequel.connect(db_config_2)

Sequel::Model.db = db_1
module DB1
  class Table1 < Sequel::Model(:table_1)
  end
end

Sequel::Model.db = db_2
module DB2
  class Table1 < Sequel::Model(:table_1)
  end
end

puts DB1::Table1.db.inspect
# #<Sequel::Mysql2::Database: {:adapter=>"mysql2", :host=>"host1.mydomain.com", :user=>"user1", :password=>"pass1", :database=>"db1", :port=>3306}>

puts DB2::Table1.db.inspect
# #<Sequel::Mysql2::Database: {:adapter=>"mysql2", :host=>"host1.mydomain.com", :user=>"user1", :password=>"pass1", :database=>"db1", :port=>3306}>
```
As stated before, I can fix the problem on my side for now, by defining DB2::Table1 as follows:
```ruby
module DB2
  class Table1 < Sequel::Model(:table_1)
    self.db = db_2
  end
end
```
NOTE: I was not able to test this exact code snippet here, since it would require me to set up two databases accordingly. I was however able to reproduce it with my database setup at work.

Also if this is just simply not the way you are supposed to connect to multiple databases with Sequel at all, then please point me in the right direction, as I was not able to find anything else that works.

**Comment by jeremyevans** [comment]
You either need to set `Sequel::Model.cache_anonymous_models = false`, or you need to use separately configured base classes:

```ruby
  module DB1
    Model = Class.new(Sequel::Model)
    Model.def_Model(self)
    Model.db = db_1
    class Table1 < Model(:table1); end
  end

  module DB2
    Model = Class.new(Sequel::Model)
    Model.def_Model(self)
    Model.db = db_2
    class Table1 < Model(:table1); end
  end
```

**Comment by kmoschcau** [comment]
Your suggestion with the separately configured base classes worked perfectly. Additionally it also helped me to get rid of a lot of Yardoc warnings I was getting when generating my documentation.
