### ISSUE TITLE
add_methods does not populate timestamps (from timestamp plugin) when many to many associations are used

### ISSUE THREAD

**Issue by ashabbir** [jeremyevans/sequel#1242]
### Complete Description of Issue

i have three tables  accounts, users and memberships
all tables have time stamps and i am using sequel timestamp plugin
When i do a simple account.create(values) user.create(values) or membership.create(values) 
every thing works fine. 
i have added many to many association between accounts and users through membership

if i try to do Account.add_member(User) 
it adds the user but fails on join table insert

```
#account db migration

Sequel.migration do
  change do
    create_table :accounts do
      primary_key :account_id
      String :mongo_id, null: false
      Timestamp :created_at, null: false
      Timestamp :updated_at

      index :mongo_id, unique: true
    end
  end
end

#account model
class Account < Sequel::Model
  set_primary_key :account_id
  many_to_many :members, class: User, join_table: :memberships,
                         left_key: :membership_account_id, right_key: :membership_user_id

end

#member db migration
Sequel.migration do
  change do
    create_table :memberships do
      primary_key :membership_id
      foreign_key :membership_account_id, :accounts, on_delete: :cascade, null: false
      foreign_key :membership_user_id, :users, on_delete: :cascade, null: false
      Timestamp :created_at, null: false
      Timestamp :updated_at
      unique [:membership_account_id, :membership_user_id]
    end
  end
end

#member model
class Membership < Sequel::Model
  set_primary_key :membership_id
end

```

### Simplest Possible Self-Contained Example Showing the Bug
its not using models to generate the join table. Its also bypassing all hooks on model

### Full Backtrace of Exception (if any)

```
Account.last.add_member(User.last)
Sequel::NotNullConstraintViolation: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (13, 12, 18, null, null).
from /gems/gems/sequel-4.37.0/lib/sequel/adapters/postgres.rb:187:in `async_exec'
```

**Comment by jeremyevans** [comment]
This isn't a bug.  You are using a many_to_many association, and the association add_* for that just adds an entry to the join table, it doesn't save a model.  You probably want to use actually use the model you created for the join table:

```ruby
Account.one_to_many :memberships, :key=>:membership_account_id
Membership.plugin :timestamps
Account.last.add_membership(:membership_user_id=>User.last.id)
```

**Comment by ashabbir** [comment]
i think their is some confusion

```
[3] pry(main)> User.create(email: 'dev@mail.com', mongo_id: 'adfxcv')
=> #<User @values={:user_id=>3, :mongo_id=>"adfxcv", :email=>"dev@mail.com", :is_admin=>false, :created_at=>2016-10-07 21:31:43 UTC, :updated_at=>2016-10-07 21:31:43 UTC}>
[4] pry(main)> Account.last.add_member(User.last)
=> #<User @values={:user_id=>3, :mongo_id=>"adfxcv", :email=>"dev@mail.com", :is_admin=>false, :created_at=>2016-10-07 21:31:43 UTC, :updated_at=>2016-10-07 21:31:43 UTC}>
```

when i take out the time stamps from membership (join) table .. it works properly
but when i put the timestamp back on membership table it throws an exception

**Comment by jeremyevans** [comment]
Like I said, this is expected.  I apologize if you are confused, but unfortunately I can't really provide a better explanation and example code than what I provided in the previous post.  In general, you shouldn't use add_* for a many_to_many association unless the join table consists only of the two foreign key columns (or all remaining columns have default values).
