### ISSUE TITLE
Class Table Inheritance plugin configuration using non-symbols

### ISSUE THREAD

**Issue by kenaniah** [jeremyevans/sequel#1243]
In order to accomplish class table inheritance with namespaced models, class names currently need to be explicitly cast to symbols when passed as arguments to the plugin's configuration:

```ruby
class Test::Entity < Sequel::Model :test__entities
	plugin(
		:class_table_inheritance,
		key: :kind,
		model_map: {
			'vehicle' => 'Test::Vehicle'.to_sym,
			'person' => 'Test::Person'.to_sym
		},
		table_map: {
			'Test::Vehicle'.to_sym => :test__vehicles,
			'Test::Person'.to_sym => :test__people
		}
	)
end
```

Passing string keys for the table map silently fails as the plugin does not currently cast to symbols before performing hash lookups.

Please add `#to_sym` calls within the plugin itself as a safeguard. Thanks!

**Comment by jeremyevans** [comment]
The documentation already states table_map should have symbol keys, and gives examples doing so.  Making these kind of changes is a slippery slope, and prone to issues, I think it's better to use the hash as it is passed in instead of attempting to modify it or use a modified copy.
