### ISSUE TITLE
Sequel ignores parentheses in numeric expression with divisions

### ISSUE THREAD

**Issue by lx00st** [jeremyevans/sequel#1246]
Hi. Im using Sequel and Ive found the following

```
[63] pry(main)> DB[:test].select { a/ b / c }.sql
=> "SELECT (\"a\" / \"b\" / \"c\") FROM \"test\""
[64] pry(main)> DB[:test].select { a/ (b / c) }.sql
=> "SELECT (\"a\" / \"b\" / \"c\") FROM \"test\""
```
expected SQL is 

` "SELECT (\"a\" / (\"b\" / \"c\")) FROM \"test\""`

Thx.

**Comment by jeremyevans** [comment]
Thanks for the report. This is definitely a bug.  It's been around for a long time. It's due to an optimization that shouldn't be applied.  It should be fairly easy to fix, I'll work on it today.
