### ISSUE TITLE
WIth ADO, SQL Server, inclusion of some columns in column list causes others to show as nil

### ISSUE THREAD

**Issue by evanmorton** [jeremyevans/sequel#1247]
### Complete Description of Issue
This bug may well be in ADO, SQL Server, or some component other than Sequel.

I'm an experienced SQL programmer, but somewhat new to Ruby in general and Sequel in particular.

I'm running
    ruby 2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]
against
    SQL Server 12.0.2488

When I get results from the database, adding columns into the column list changes the values of other columns (in my dataset) to nil, depending on the columns.

### Simplest Possible Self-Contained Example Showing the Bug

First, the SQL to create the one table necessary for showing the problem.

DROP TABLE columbus.zzzshowbug
CREATE TABLE columbus.zzzshowbug (
    report_name varchar(max)
   ,client_name varchar(max)
   ,date_time datetime
   ,date_time_visible varchar(max)
   ,url varchar(max)
)

INSERT INTO columbus.zzzshowbug VALUES
('buffalo report','zebra client','Oct 10 2016  1:42PM','2016-10-10 13:42:27','http://this.is.not.a.real.url/uploads/0a88~110')

================================
Now the Ruby

require "sequel"

def initialize_db ()
    # Connecting without providing a username/password apparently gives us the equivalent of
    # SSMS's "Windows Authorization" feature, by which the user's credentials are passed through.
    # So if the user has the right permissions in the database, running this program should work.
    $database = Sequel.connect(
        :adapter=>'ado', 
        :host     =>'xxx this value obscured because we are paranoid xxx',
        :database=>'xxx this value obscured because we are paranoid xxx'
      )
end

def gen_one_report_page (column_list)
    sql_cmd = "select " +
         column_list +
          "from columbus.zzzshowbug ri1 " +
          "order by date_time"
    p "SQL command is " + sql_cmd
    results = $database[sql_cmd]

    results.each do |row|
      puts "date_time is " + row.fetch(:date_time).to_s
      puts "date_time_visible is " + row.fetch(:date_time_visible).to_s
    end
end

initialize_db

  # When column_list has the two values, it works correctly.  When it has three, it doesn't.
#column_list = "date_time, date_time_visible "
column_list = "date_time, date_time_visible, client_name "

gen_one_report_page(column_list)

================================

When you run the above code using "ruby <filename>", the last two lines of output are
date_time is 2016-10-10 13:42:00 -0400
date_time_visible is

which says that date_time_visible is nil.  (Looking at it in another way confirms this.)  But in the database, date_time_visible has a non-NULL value.  Near the end of the ruby script are two lines setting column_list.  If you uncomment the first one and comment out the second, you'll get a column list with only two elements rather than three.  This code runs correctly.  So the inclusion of the column "client_name" affects the values found for another column.

### Full Backtrace of Exception (if any)

(none)

### SQL Log (if any)

(none)

**Comment by jeremyevans** [comment]
This appears to be a bug in the WIN32OLE driver, not in Sequel:

```ruby
DB.run <<END
CREATE TABLE zzzshowbug (
report_name varchar(max)
,client_name varchar(max)
,date_time datetime
,date_time_visible varchar(max)
,url varchar(max)
)
END
# => nil
DB[:zzzshowbug].insert('a', 'b', Time.now, 'c', 'd')
# SET NOCOUNT ON; INSERT INTO [ZZZSHOWBUG] VALUES (N'a', N'b', '2016-10-11T11:00:59.113', N'c', N'd'); SELECT CAST(SCOPE_IDENTITY() AS INTEGER)
# => nil
DB[:zzzshowbug].all
# SELECT * FROM [ZZZSHOWBUG]
# => [{:report_name=>nil, :client_name=>nil, :date_time=>nil, :date_time_visible=>nil, :url=>"d"}]
res = DB.synchronize{|c| c.Execute('SELECT * FROM [ZZZSHOWBUG]')}
#=> #<WIN32OLE:0x00000004f39568>
res.getRows
# => [[nil], [nil], [nil], [nil], ["d"]]
```

It appears that ADO doesn't handle `varchar(max)` columns correctly, switching to `varchar(255)` makes things work correctly:

```ruby
DB.run <<END
CREATE TABLE zzzshowbug (
report_name varchar(255)
,client_name varchar(255)
,date_time datetime
,date_time_visible varchar(255)
,url varchar(255)
)
END
DB[:zzzshowbug].insert('a', 'b', Time.now, 'c', 'd')
DB[:zzzshowbug].all
# => [{:report_name=>"a", :client_name=>"b", :date_time=>2016-10-11 11:10:25 -0700, :date_time_visible=>"c", :url=>"d"}]
```

You should probably contact the WIN32OLE developers (ruby-core) if you want that fixed.  It's probably easier and better to just switch to the tinytds adapter instead, as the ado adapter has numerous other problems.

**Comment by evanmorton** [comment]
Good, thanks!

**Comment by vais** [comment]
>...better to just switch to the tinytds adapter instead, as the ado adapter has numerous other problems...

@jeremyevans, sorry to hijack this issue thread, but if I *really* need to use the ADO adapter (to support some legacy client code that wants XML-serialized ADO recordsets from the server, which I think I can hack the ADO adapter to output), is there a list of these "numerous other problems" that you are referring to somewhere?

It seems that every time the subject of the ADO adapter comes up, your response suggests it's a very bad idea to use it, but it's not clear exactly why. Is this mainly about performance? Or is it that it's unstable under load? E.g. performance I could deal with, but instability/crashiness/incorrect results under stress would be a show-stopper. Could you please point me to some existing resources on this subject or share your thoughts here?

**Comment by jeremyevans** [comment]
With the default provider, the ADO adapter can't even handle transactions, as it uses a separate underlying connection for every query.  The situation is better with other providers, but there are still other issues.  If you want to see the problems with the ADO adapter, try running Sequel's tests with it.

**Comment by vais** [comment]
Thanks @jeremyevans, the point regarding "try running Sequel's tests with it" makes a lot of sense, I've never tried that. Thanks again for getting back to me.
