### ISSUE TITLE
Columns of inet[] ain't handled correctly

### ISSUE THREAD

**Issue by fiscal-cliff** [jeremyevans/sequel#1258]
### Complete Description of Issue
Hello!
Thank you for great postgresql adapter for ruby
I've added column of `inet[]` type and noticed that the column contained string instead of array
Columns of types `text[]`, `int[]` work just fine.

### Simplest Possible Self-Contained Example Showing the Bug
Here are a few examples
`DB.select("ARRAY['127.0.0.1'::inet]::inet[]".lit).all`
```
=> [
    [0] {
        :array => "{127.0.0.1}"
    }
]
```
Meanwhile if I cast the same value as text[] the result will be array
`DB.select("ARRAY['127.0.0.1'::inet]::text[]".lit).all`
```
=> [
    [0] {
        :array => ["127.0.0.1/32"]
    }
]
```
And the same story with int[]
`DB.select("ARRAY[1]::int[]".lit).all`
```
=> [
    [0] {
        :array => [1]
    }
]
```

fixed by adding
DB.register_array_type('inet')

**Comment by jeremyevans** [comment]
You didn't post a self contained example, so I have to guess as to what is going on.  My guess is you are using the pg_array extension (as `text[]` columns are converted to arrays), but not the pg_inet extension.  You should use both, which will give you an array of IPAddr objects:

```
irb(main):001:0> DB.create_table(:a){column :a, 'inet[]'}
I, [2016-11-16T07:11:43.284516 #86907]  INFO -- : (0.008319s) CREATE TABLE "a" ("a" inet[])
=> nil
irb(main):002:0> DB[:a].insert("{127.0.0.1}")
I, [2016-11-16T07:12:04.261519 #86907]  INFO -- : (0.002691s) SELECT pg_attribute.attname AS pk FROM pg_class, pg_attribute, pg_index, pg_namespace WHERE pg_class.oid = pg_attribute.attrelid AND pg_class.relnamespace = pg_namespace.oid AND pg_class.oid = pg_index.indrelid AND pg_index.indkey[0] = pg_attribute.attnum AND pg_index.indisprimary = 't' AND pg_class.oid = CAST(CAST('"a"' AS regclass) AS oid)
I, [2016-11-16T07:12:04.262893 #86907]  INFO -- : (0.000802s) INSERT INTO "a" VALUES ('{127.0.0.1}') RETURNING NULL
=> nil
irb(main):003:0> DB[:a].all
I, [2016-11-16T07:12:09.164123 #86907]  INFO -- : (0.000453s) SELECT * FROM "a"
=> [{:a=>"{127.0.0.1}"}]
irb(main):004:0> DB.extension :pg_array, :pg_inet
=> #<Sequel::Postgres::Database: "postgres:///?user=sequel_test">
irb(main):005:0> DB[:a].all
I, [2016-11-16T07:12:20.252460 #86907]  INFO -- : (0.000355s) SELECT * FROM "a"
=> [{:a=>[#<IPAddr: IPv4:127.0.0.1/255.255.255.255>]}]
```

In any case, the pg_array extension doesn't add a convertor for `inet[]` (though it does for `text[]`).  This isn't a bug, it's expected behavior if you are using the pg_array extension by itself.  If you want to have `inet[]` returned as an array of strings, you need to register the inet array type:

```
irb(main):001:0> DB.extension :pg_array
=> #<Sequel::Postgres::Database: "postgres:///?user=sequel_test">
irb(main):002:0> DB.register_array_type(:inet)
I, [2016-11-16T07:18:26.209994 #40892]  INFO -- : (0.001743s) SELECT "typarray", "oid" FROM "pg_type" WHERE ("typname" = 'inet') LIMIT 1
=> nil
irb(main):003:0> DB[:a].all
I, [2016-11-16T07:18:32.848442 #40892]  INFO -- : (0.000667s) SELECT * FROM "a"
=> [{:a=>["127.0.0.1"]}]
```
