### ISSUE TITLE
nested_attributes: update association ids

### ISSUE THREAD

**Issue by blocknotes** [jeremyevans/sequel#1261]
I can't find a way to update the ids of an association.
Example:
```rb
class Book < Sequel::Model
  one_to_many :chapters
  nested_attributes :chapters
end
```
I need to change the associated chapters and they already exists.
For create / update it would be great something like: `book.update( :chapter_ids => [ 2, 3 ] )`
(the syntax used by ActiveRecord and Mongoid)
The same problem is with many_to_many association.

**Comment by jeremyevans** [comment]
That's not what nested_attributes is for.  You probably want to use the association_pks plugin, possible in conjunction with the nested_attributes plugin.

In the future, as mentioned in the contribution guidelines, please ask questions about how to use Sequel on the Google Group or IRC. You should only be adding a GitHub issue if you are sure the behavior is a bug.

**Comment by blocknotes** [comment]
I thought there was something wrong about allowed nested parameters.
Thank you for your answer Jeremy
