### ISSUE TITLE
.first returning hash instead of model instance...

### ISSUE THREAD

**Issue by maxiedaniels** [jeremyevans/sequel#1271]
I've been trying to add an association between an existing "track" and a "playlist", but I've been getting an error about "id is a restricted primary key". While trying to troubleshoot it, I realized when I get the existing "song" by using Song.first(:attribute_im_using = etc), it's returning a hash, rather than an instance of that Model class. This is not what the documentation shows... the documentation says I should be retreiving an instance of the Model class when using .first. Is this a bug?

*Edit*
Relevant code:

```
Model Setup:
@db.create_table? :playlists do
    primary_key :id
    String :name
    foreign_key :owner_id
    String :description
end

@db.create_table? :owners do
    primary_key :id
    String :name
end

@db.create_table? :tracks do
    primary_key :id
    String :name
    String :artist
end

@db.create_table? :playlists_tracks do
    primary_key :id
    foreign_key :playlist_id, :playlists
    foreign_key :track_id, :tracks
end

class Playlist < Sequel::Model
    many_to_one :owner
    many_to_many :tracks
end

class Track < Sequel::Model
    many_to_many :playlists
end

class Owner < Sequel::Model
    one_to_many :playlist
end
```

Picking

```
#getting existing track
nameToPick = "aName"
track = @db[:tracks].first(:name => nameToPick)
p track #this is returning a hash!
aPlaylist.add_track(track) #exception!! id is a restricted primary key (Sequel::MassAssignmentRestriction)
```

**Comment by jeremyevans** [comment]
Probably not a bug, but as you did not provide a code example or most of the other information requested in the issue template, it's hard to say for sure. There are ways to use the API that result in first returning a hash instead of a model instance.  However, without a self contained example, I couldn't do better than an uninformed guess.  I'll leave this open for a day, but unless more information is provided, I'll have to close it.

**Comment by maxiedaniels** [comment]
Original post updated..

**Comment by rennex** [comment]
Accessing the database table (`@db[:tracks]`) directly does give you a Hash. Try `Track.first(:name => nameToPick)`. That should also fix the `add_track` call, since then you'll be associating a Track object to it instead of creating a new record from a hash and associating that to the playlist.

**Comment by maxiedaniels** [comment]
Ahhh okay. Sorry for the confusion, and thank you for the help!
