### ISSUE TITLE
association_join doesn't include association's conditions when specified as a string or dataset block

### ISSUE THREAD

**Issue by zuk** [jeremyevans/sequel#1272]
When an association has a `:conditions` option given as a string, or as a dataset block, that condition constraint doesn't seem to be included when using `association_join`.

For example:

```
User.one_to_many :messages, conditions: {sent: true}
puts User.association_join(:messages).sql
# => SELECT * FROM "users" INNER JOIN "messages" AS "messages" ON (("messages"."user_id" = "users"."id") AND ("messages"."sent" IS TRUE))
```

Great! But...

```
User.one_to_many :messages, conditions: "sent IS TRUE"
puts User.association_join(:messages).sql
# => SELECT * FROM "users" INNER JOIN "messages" AS "messages" ON (("messages"."user_id" = "users"."id")

User.one_to_many :messages do |ds|
  ds.where(sent: true)
end
puts User.association_join(:messages).sql
# => SELECT * FROM "users" INNER JOIN "messages" AS "messages" ON (("messages"."user_id" = "users"."id")
```

:( the "sent IS TRUE" condition is not included for the other two.

If you point me to the right place in the code to fix this, I'm happy to take a stab at it. Of if this is intended behaviour, I would suggest printing a runtime warning to warn that the conditions will not be applied as might be expected. Silently omitting the constraint can be dangerous if, for example, your conditions are used for access authorization.

**Comment by jeremyevans** [comment]
This is expected.  association_join uses eager_graph, and eager_graph only supports :conditions that are a hash or array of pairs.  If you can't specify your condition as a hash or array of pairs, you need to specify :graph_block for the conditions to use when eager graphing.

The reasoning for this is that when :conditions is used normally, it applies to a dataset (WHERE).  When conditions are used when using eager_graph/association_join, they are used as join conditions (JOIN ON).  In cases where you provide a hash/array of pairs, Sequel knows how to construct the appropriate JOIN ON condition, but in other cases, it does not.

I don't have a problem adding a warning, but the placement would be important.  We don't want to warn on all cases where :conditions is set to a something that is not hash/array of pairs, we only want to warn in places where :conditions is set that way and ends up getting ignored during eager graphing.  Looks like Dataset#eager_graph_association would be the best place if we want to add a warning.

I'll also try to update the documentation to make it more clear that association join uses eager graphing.

**Comment by zuk** [comment]
Awesome, thanks. Super impressed with your responsiveness on this. One of the many reasons everyone loves Sequel so much, I'm sure :)

**Comment by jeremyevans** [comment]
Currently, I don't believe there is.  However, I'm not opposed to adding such an option.

**Comment by jeremyevans** [comment]
The auto_restrict_eager_graph plugin can be used to automatically restrict eager_graph usage when the association is passed a block.  So you should probably use that plugin for now.

I checked, and if you attempt to eager_graph/association_join with :conditions that is not a hash/array of pairs, and you haven't specified :graph_conditions, :graph_only_conditions, or :graph_block, Sequel raises an exception by default. Maybe we could expand the default behavior to warn for the case where the auto_restrict_eager_graph plugin would disallow eager_graph. Then we could make the auto_restrict_eager_graph behavior the default in Sequel 6.  Something like:

```diff
diff --git a/lib/sequel/model/associations.rb b/lib/sequel/model/associations.rb
index 3bee2b791..3be56e2fa 100644
--- a/lib/sequel/model/associations.rb
+++ b/lib/sequel/model/associations.rb
@@ -3387,8 +3387,15 @@ module Sequel
           local_opts = ds.opts[:eager_graph][:local]
           limit_strategy = r.eager_graph_limit_strategy(local_opts[:limit_strategy])

-          if r[:conditions] && !Sequel.condition_specifier?(r[:conditions]) && !r[:orig_opts].has_key?(:graph_conditions) && !r[:orig_opts].has_key?(:graph_only_conditions) && !r.has_key?(:graph_block)
-            raise Error, "Cannot eager_graph association when :conditions specified and not a hash or an array of pairs.  Specify :graph_conditions, :graph_only_conditions, or :graph_block for the association.  Model: #{r[:model]}, association: #{r[:name]}"
+          # SEQUEL6: remove and integrate the auto_restrict_eager_graph plugin
+          if !r[:orig_opts].has_key?(:graph_conditions) && !r[:orig_opts].has_key?(:graph_only_conditions) && !r.has_key?(:graph_block) && !r[:allow_eager_graph]
+            if r[:conditions] && !Sequel.condition_specifier?(r[:conditions])
+              raise Error, "Cannot eager_graph association when :conditions specified and not a hash or an array of pairs.  Specify :graph_conditions, :graph_only_conditions, or :graph_block for the association.  Model: #{r[:model]}, association: #{r[:name]}"
+            end
+
+            if r[:block] && !r[:graph_use_association_block]
+              warn "eager_graph used for association when association given a block without graph options.  The block is ignored in this case.  This will result in an exception starting in Sequel 6.  Model: #{r[:model]}, association: #{r[:name]}"
+            end
           end

           ds = loader.call(:self=>ds, :table_alias=>assoc_table_alias, :implicit_qualifier=>(ta == ds.opts[:eager_graph][:master]) ? first_source : qualifier_from_alias_symbol(ta, first_source), :callback=>callback, :join_type=>join_type || local_opts[:join_type], :join_only=>local_opts[:join_only], :limit_strategy=>limit_strategy, :from_self_alias=>ds.opts[:eager_graph][:master])
```

**Comment by jeremyevans** [comment]
I committed the warning at cd60828b591b50b456df562786e484ca5f6841bd
