### ISSUE TITLE
sqlite3 should preserve autoincrement on alter table using duplicate

### ISSUE THREAD

**Issue by thenrio** [jeremyevans/sequel#1277]
### Complete Description of Issue

Given table is like so

```ruby
  DB.create_table!(:testautoincrement) do
    primary_key :id, :type => Integer
    Integer :val, :null => false
  end
```

When I rename the `val` column like so

```ruby
DB.rename_column(:testautoincrement, :val, :value)
```

Then table `testautoincrement` should preserve its autoincrement behavior.

Actually, it does not.
I have:

```
sqlite> .schema testautoincrement
CREATE TABLE `testautoincrement`(`id` integer DEFAULT (NULL) NOT NULL PRIMARY KEY, `value` integer DEFAULT (NULL) NOT NULL);
```

Whereas I should have

```
sqlite> .schema testautoincrement
CREATE TABLE `testautoincrement` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `value` integer NOT NULL);
```

**Comment by jeremyevans** [comment]
`AUTOINCREMENT` in `CREATE TABLE` is a noise word in SQLite, it does not affect behavior.  Using your example, after the `rename_column`:

```ruby
DB[:testautoincrement].insert(:value=>10)
# => 1
DB[:testautoincrement].insert(:value=>20)
# => 2
DB[:testautoincrement].all
# => [{:id=>1, :value=>10}, {:id=>2, :value=>20}]
```

Related SQLite documentation: http://www.sqlite.org/lang_createtable.html#rowid

It's true that the schema SQL before and after the rename is different, but as the behavior is the same, that isn't considered a bug.

**Comment by jeremyevans** [comment]
Sorry, I was looking at the wrong SQLite documentation, the correct documentation is http://sqlite.org/autoinc.html, and I think you are correct that this is a bug.

**Comment by thenrio** [comment]
thanks @jeremyevans!

I made a PR for that https://github.com/jeremyevans/sequel/pull/1278

Cheers.

**Comment by thenrio** [comment]
The diff in behavior is : 

* will not reuse an id (autoincrement is much like a postgres sequence).
* we can see/change the sequence value with table `sqlite_sequence` (http://sqlite.org/fileformat2.html#seqtab).
