### ISSUE TITLE
Dataset#get always returns the first column instead of the requested column for SQL-based datasets

### ISSUE THREAD

**Issue by vais** [jeremyevans/sequel#1288]
### Complete Description of Issue

For SQL-based datasets, `Dataset#get` always returns the *first available* column value instead of the *requested* column value. I.e. regardless what column name is passed as the argument to `Dataset#get`, the value you will always get back is the value of the first column of the result row.

### Simplest Possible Self-Contained Example Showing the Bug
```
require "rubygems"
require "sequel"
require "logger"

# connect to an in-memory database
DB = Sequel.sqlite

# create an items table
DB.create_table :items do
  primary_key :id
  String :name
  Float :price
end

# create a dataset from the items table
items = DB[:items]

# populate the table
items.insert(:name => 'abc', :price => rand * 100)
items.insert(:name => 'def', :price => rand * 100)
items.insert(:name => 'ghi', :price => rand * 100)

DB.loggers << Logger.new($stdout)

puts "--- The Good ---"
puts
puts "Here `get` returns name: #{ DB[:items].get(:name) }"
puts
puts "And here `get` returns name: #{ DB[:items].select(:price).get(:name) }"
puts
puts "And here `get` returns name: #{ DB['SELECT name, price FROM items LIMIT 1'].get(:name) }"
puts
puts "--- The Bad ---"
puts
puts "But here `get` returns price instead: #{ DB['SELECT price, name FROM items LIMIT 1'].get(:name) }"
puts
puts "And here `get` returns id instead: #{ DB['SELECT * FROM items LIMIT 1'].get(:name) }"
```
### SQL Log (if any)
```
--- The Good ---

I, [2017-01-18T11:33:46.004227 #632]  INFO -- : (0.000000s) SELECT `name` FROM `items` LIMIT 1
Here `get` returns name: abc

I, [2017-01-18T11:33:46.004227 #632]  INFO -- : (0.000000s) SELECT `name` FROM `items` LIMIT 1
And here `get` returns name: abc

I, [2017-01-18T11:33:46.019827 #632]  INFO -- : (0.000000s) SELECT name, price FROM items LIMIT 1
And here `get` returns name: abc

--- The Bad ---

I, [2017-01-18T11:33:46.051027 #632]  INFO -- : (0.000000s) SELECT price, name FROM items LIMIT 1
But here `get` returns price instead: 7.355685407489354

I, [2017-01-18T11:33:46.051027 #632]  INFO -- : (0.000000s) SELECT * FROM items LIMIT 1
And here `get` returns id instead: 1
```

**Comment by jeremyevans** [comment]
This is expected behavior.  You shouldn't use Dataset#get with raw SQL, unless the raw SQL returns a single column.  Any argument you pass to Dataset#get is going to be ignored if you have raw SQL , as Dataset#select (which Dataset#get calls) will not affect a dataset with raw SQL (raw SQL always takes priority).

Note that if you are using a raw SQL dataset, pretty much all Dataset methods that modify the SQL will be ignored:

```ruby
ds = DB['SELECT 1']
ds.where(:a=>1).sql # SELECT 1
ds.select(:a).sql # SELECT 1
ds.order(:a).sql # SELECT 1
```

This is how Sequel has always worked.  If you want to be able to use Sequel methods to modify a dataset with raw SQL, you need to use from_self to wrap the dataset in a subquery:

```ruby
ds = DB['SELECT 1'].from_self
ds.where(:a=>1).sql # SELECT * FROM (SELECT 1) AS t1 WHERE (a = 1)
ds.select(:a).sql # SELECT a FROM (SELECT 1) AS t1
ds.order(:a).sql # SELECT * FROM (SELECT 1) AS t1 ORDER BY a
```

So for your example:

```ruby
DB['SELECT name, price FROM items LIMIT 1'].from_self.get(:name)
# SELECT name FROM (SELECT name, price FROM items LIMIT 1) AS t1 LIMIT 1
```

This is mentioned in the documentation (at least at http://sequel.jeremyevans.net/rdoc/files/doc/querying_rdoc.html#label-Custom+SQL), but I'm open to pull requests to document it elsewhere.

**Comment by vais** [comment]
@jeremyevans thanks for the pointer regarding`from_self`, that's actually pretty cool.

Regarding dataset methods quietly returning incorrect results, that seems very, very wrong to me. I understand the "that's how it has always worked" argument, but still... No amount of documentation can "fix" this - you'd literally have to add a comment to every affected dataset method that "this will likely do the wrong thing if called on a dataset created from raw SQL".

Do you think raising an error at runtime would be a better way to handle this discrepancy between datasets created from raw SQL vs from Sequel DSL? I mean, in my example, I would much rather get an error telling me that calling this method does not make sense on a raw SQL dataset than to quietly receive incorrect result.

Does this not rub you the wrong way?

**Comment by jeremyevans** [comment]
Personally, it doesn't seem very wrong to me. It's only a little wrong at most.  If you are using custom SQL, the expectation is you will not be attempting to modify the SQL.  This is unlikely to cause production issues, as it's a type of issue that will almost always be caught during development.

In terms of documentation, I don't think we need to document all dataset methods that modify raw SQL.  If you want to mention this in the method documentation, we only need to document it in the methods that set raw SQL stating that you should not call dataset methods that modify the SQL when using them, and there are only a couple of those methods (Database#fetch and Dataset#with_sql).

For backwards compatibility, we can't just change it to raise an error, and for performance reasons, I don't want to add checks to every dataset method that modifies SQL to check for raw SQL use.

If we do want to change Sequel to eventually raise in error in this case, we should probably add a deprecation warning to the methods that return the SQL (Dataset#static_sql), and then in Sequel 5 change it to raise an error if there are also options present related to SQL use.

However, the problem with that approach is it is likely to break things.  Calling Dataset#get on any dataset using raw SQL would break as Dataset#get sets the :select option.  There's probably a lot of code that relies on Dataset#get working on datasets using raw SQL. I know it would break some of my code.

To be safe, we could just introduce that check via a dataset extension, that way it is opt-in and will not break anyone's code unless they load it.  I think that is the best course of action in this case.

**Comment by vais** [comment]
Thank you for your thoughtful reply, Jeremy.

>If you are using custom SQL, the expectation is you will not be attempting to modify the SQL.

Hmm, so now I'm starting to think that perhaps this really *is* a documentation issue. You see, to *you* (from an insider's view), `get` is a kind of a dataset method that modifies SQL, because you know that *Dataset#get sets the :select option*, but to a newcomer to Sequel, this is just one of the "Methods that execute code on the database", as that's how it's documented (along with `all`, `first`, etc). In other words, the reason I reached for `get` is because 1) I had a dataset I created based on raw SQL using `fetch`, and 2) I needed to execute the query, and since I only wanted a single value from the result, I saw `get` and thought that it fits the bill quite perfectly. (Now, it's a different question why I have SQL that uses `select *` if all I want is a single column, but, whatever). Given that my other option would have been `.first[:column]`, `.get(:column)` looked more "right", or intention-revealing, but turned out to be the wrong choice.

Again, thank you for your patience and for taking the time to educate me, Jeremy.

**Comment by jeremyevans** [comment]
You are correct that Dataset#get is a little different than the other Dataset query methods that just modify SQL.  But the code examples for Dataset#get all show the SQL getting modified.

After giving this some more though, I don't think a warning or error as I described earlier is appropriate, as it is too likely to happen in cases where it isn't actually a problem.  I will try to update the appropriate method documentation.  I think one possible solution would be a dataset extension that changes the methods that modify SQL to implicitly call from_self first if the dataset uses raw SQL.  That way people that want to use raw SQL and then later Sequel's query methods to modify the query would be able to do so without calling from_self manually.
