### ISSUE TITLE
Documentation made very unreadable by dark code blocks

### ISSUE THREAD

**Issue by vais** [jeremyevans/sequel#1289]
Jeremy, this has bothered me for years literally, so I finally decided to file an issue.

The dark code blocks in the visual theme used for all Sequel online documentation make it extremely unreadable and unapproachable. The best I can describe the experience of reading these docs online is it's like getting stabbed in the face repeatedly, and getting completely lost as a consequence.

There is a ton of great content, great text, but the visual theme is actively distracting from it and makes it a pain to read and focus. Just visit http://sequel.jeremyevans.net/rdoc/files/doc/sql_rdoc.html for example, and try scrolling up and down the page (as one would, because that's how reading technical documents often works). You will notice two things: one, you very quickly loose context of where you were because of the stark contrast created by the code blocks, *which obscures the real document structure that is based on section headings*, and it's the section headings that should be given prominence, and two, if you were prone to epilepsy, you would start convulsing in seizures caused by the strobe effect produced by the quick alterations of white and black rectangles on the screen.

Ok, end of rant.

I believe if the code blocks were some sort of a more subtle off-white color (like GitHib renders them for example), that would solve the whole problem - I'm not advocating for some great re-design effort here, just to be clear.

**Comment by jeremyevans** [comment]
@vias, I appreciate that you may find it difficult to read the code blocks, but I don't agree that they make the documentation unreadable or unapproachable, for most users at least.  I quite like the current color scheme, but I can definitely admit it is a matter of personal taste.

However, I'm not tied to the current color scheme.  Sequel uses the default color scheme for hanna-nouveau, any issues you have with Sequel's documentation color scheme would be issues you would have with any project using hanna-nouveau (all of my projects use hanna-nouveau).  Just file a pull request in hanna-nouveau to change the color scheme to a light background/dark text scheme, and as long as it doesn't look bad (to me), it will probably be applied.
