### ISSUE TITLE
ArgumentError in paginate.rb

### ISSUE THREAD

**Issue by larsggu** [jeremyevans/sequel#1292]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

Trying to return a paginated dataset, as per the documentation, gives an ArgumentError - wrong number of arguments (given 1, expected 2..3) in paginate.rb line 40.

### Simplest Possible Self-Contained Example Showing the Bug

@result = DB[:test_table].paginate(:page_no=>params[:page], :page_size=>25)

### Full Backtrace of Exception (if any)

2017-01-25 11:50:11 - ArgumentError - wrong number of arguments (given 1, expected 2..3):
	/usr/local/lib/ruby/gems/2.4.0/gems/sequel-4.42.1/lib/sequel/extensions/pagination.rb:40:in `paginate'
	depoviewapp.rb:34:in `block in <main>'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'
	/usr/local/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

**Comment by robertlyall** [comment]
You're passing in a hash, rather than two separate arguments.

You'll need to do the following instead:

```ruby
@result = DB[:test_table].paginate(params[:page], 25)
```

You can take a look at [the method in question here](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pagination.rb#L40).

**Comment by jeremyevans** [comment]
I can't find any documentation that shows that paginate supports a single hash argument.  It has always required a minimum of 2 arguments, even when initially introduced: https://github.com/jeremyevans/sequel/commit/6001cc4fb306733f5193238fa8216a16e8b647d4

If there is some Sequel documentation showing a single hash argument, please let me know where so I can fix it.

**Comment by larsggu** [comment]
Ah, ok, my bad. I changed the line according to @robertlyall and I now get a NoMethodError in paginate.rb line 47.

Backtrace:

2017-01-26 09:13:11 - NoMethodError - undefined method `-' for nil:NilClass:
	/usr/local/lib/ruby/gems/2.4.0/gems/sequel-4.42.1/lib/sequel/extensions/pagination.rb:47:in `paginate'
	depoviewapp.rb:34:in `block in <main>'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/local/lib/ruby/gems/2.4.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'
	/usr/local/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

**Comment by jeremyevans** [comment]
Then `params[:page]` must be `nil` for you.  That was just an example, you need to use the appropriate integer value for the first argument.

**Comment by robertlyall** [comment]
I'd suggest using something like `param.fetch(params[:page], 1)` to provide a fallback value if `params[:page]` is `nil`.

**Comment by jeremyevans** [comment]
`params.fetch(:page, 1).to_i` is probably better, since paginate expects integer arguments.
