### ISSUE TITLE
#dataset.columns! always returning an empty array

### ISSUE THREAD

**Issue by mahlonsmith** [jeremyevans/sequel#1297]
### Complete Description of Issue

Sequel v4.42 `#dataset.columns!` is returning empty array.  v4.41 seems okay!  Breaks Sequel::Migration among other introspective things.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
db = Sequel.connect( 'postgres://...' )

# Note the '!', bypassing 4.42 cache
db[ :schema_migrations ].columns!    #=> []

# yet...
db[ :schema_migrations ].first #=> {:filename=>"20151102_initial.rb"}
```

First noticed this with Sequel::Migrator, due to:

    migration.rb:769:in `schema_dataset': Migrator table schema_migrations does not contain column filename (Sequel::Migrator::Error)`

It appears to be related to the column caching added in 4.42, but I'll need to do more digging to see specifically where the problem lies.

**Comment by jeremyevans** [comment]
Please do more digging and post a self contained example, as I am unable to reproduce:

```
$ ls testm
20151102_initial.rb
$ cat testm/20151102_initial.rb
Sequel.migration{}
$ bin/sequel -m testm postgres:///?user=sequel_test
$ bin/sequel postgres:///?user=sequel_test -c "p DB[ :schema_migrations ].columns!; p DB[ :schema_migrations ].first"
[:filename]
{:filename=>"20151102_initial.rb"}
```

**Comment by jeremyevans** [comment]
By any chance are you using an old version of sequel_pg (<1.6.17).  If so, that's what is causing the problem.  In general if you are updating Sequel, you should update sequel_pg at the same time.

**Comment by mahlonsmith** [comment]
Ah, yep.  I was on 1.6.13.

I was trying to make a self contained example using in-mem sqlite, and not having much success, which was a good clue it was localized to PG... but yeah.  I should have considered that before the bug report!

Since sequel_pg is optional, clearly there can't be specific gem dependencies -- but I wonder if there's an opportunity somewhere to have a sanity check for a min version in sequel that offers less surprising/funky behavior when compatibility is broken.   Maybe if the sequel_pg gem embedded it's own version, and the check could be in the postgres adapter after require?  Spit ballin':

```ruby
MIN_SEQUEL_PG = '1.6.17'

# ...

# Returns an easily comparable string from a version number.
def comparable_version( ver )
    return ver.split('.').collect {|char| char.to_i }.pack('N*')
end

# ...
if SEQUEL_POSTGRES_USES_PG && !ENV['NO_SEQUEL_PG']
  begin
    require 'sequel_pg'
    unless comparable_version( Sequel::Postgres::Streaming::VERSION ) >= comparable_version( MIN_SEQUEL_PG )
        raise "You need to upgrade your sequel_pg gem to at least #{MIN_SEQUEL_PG} for this version of sequel."
    end
  rescue LoadError
   # ...
```

If that sounds like something that's halfway appealing, I'm happy to make a more thoughtful patch submission.

In any event -- thank you, Jeremy!

**Comment by jeremyevans** [comment]
@mahlonsmith I agree a version check for sequel_pg like that would make sense.  If you could submit a PR for it, I would appreciate it.

**Comment by jeremyevans** [comment]
I've made changes to Sequel and sequel_pg to better handle situations like this in the future:

https://github.com/jeremyevans/sequel/commit/046291e24f683aa0094c1465ef42649450534580
https://github.com/jeremyevans/sequel_pg/commit/59c89dfab28d38cfc40472f4b6c4fc65dae136d5
