### ISSUE TITLE
Columns of type String are being cast into Float

### ISSUE THREAD

**Issue by thesmart** [jeremyevans/sequel#1308]
### Complete Description of Issue

I create a table with a column `xuid` that is type `String`.  When I create a record with value `"9999999999999999999"` I would expect to get back the same value as a String.  It is cast to a Float.

### Simplest Possible Self-Contained Example Showing the Bug

I have a code repro:
```ruby
require 'sequel'

DB = Sequel.sqlite(encoding: 'utf-8')
Sequel.extension :migration

m = Sequel.migration do
  up do
    create_table :users do
      primary_key :id
      column :name, :String, null: true
      column :xuid, :String, null: true, index: true
    end
  end
end

m.apply(DB, :up)

class User < Sequel::Model(DB[:users])

end

user = User.create({
  name: 'Foobar',
  xuid: '9999999999999999999'
})

puts "User#xuid: #{user.xuid}"
raise 'WTF, this isnt a string' unless user.xuid.is_a? String
```
Here is the output:
```
$ bundle exec ruby example.rb
User#xuid: 1.0e+19
example.rb:28:in `<main>': WTF, this isnt a string (RuntimeError)
```

**Comment by jeremyevans** [comment]
Welcome to SQLite, where this is expected behavior (see http://www.sqlite.org/datatype3.html).

```
sqlite> CREATE TABLE `users` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` String NULL, `xuid` String NULL);
sqlite> INSERT INTO `users` (`name`, `xuid`) VALUES ('Foobar', '9999999999999999999');
sqlite> SELECT * FROM `users` WHERE `id` = 1;
1|Foobar|1.0e+19
sqlite>
```

Instead of using `:String`, use `String`, then things should work as you expect:

```ruby
    create_table :users do
      primary_key :id
      column :name, String, null: true
      column :xuid, String, null: true, index: true
   end 
```

**Comment by thesmart** [comment]
shit. 🤦‍♂️

**Comment by thesmart** [comment]
For future reference to those that experience this, docs are quite clear, but I didn't catch it:

http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html
```ruby
create_table(:columns_types) do  # database type used
  column :a1, :string            # string
  column :a2, String             # varchar(255)
  column :a3, 'string'           # string
  column :a4, :datetime          # datetime
  column :a5, DateTime           # timestamp
  column :a6, 'timestamp(6)'     # timestamp(6)
end
```

> If you use a ruby class as the type, Sequel will try to guess the appropriate type name for the database you are using. If a symbol or string is used as the type, it is used verbatim as the type name in SQL, with the exception of :Bignum. Using the symbol :Bignum as a type will use the appropriate 64-bit integer type for the database you are using.

**Comment by thesmart** [comment]
@jeremyevans I'm interested to know how `:string` works differently than `String`.  Both result in TEXT storage class.  If they're both defined as TEXT, why does the column affinity change when loaded from SQLite?

**Comment by jeremyevans** [comment]
As mentioned in the schema modification guide, if you use a symbol (`:String`) or string (`'string'`), Sequel will use that verbatim as the type (with `:Bignum` being the sole exception).  If you use a ruby class (`String`), Sequel will try to determine an appropriate type for the database (e.g. `varchar(255)`).

See the column affinity section on http://www.sqlite.org/datatype3.html. `string` has `NUMERIC` affinity, `varchar(255)` has `TEXT` affinity.
