### ISSUE TITLE
Irretating error message when using non-existing Model plugin

### ISSUE THREAD

**Issue by fnordfish** [jeremyevans/sequel#1317]
This is running inside padrino 0.13.3.3 using sequel 4.44.0 and sequel_pg 1.6.17

Using a `database.rb` like this:

```ruby
Sequel::Model.plugin :schema
Sequel::Model.plugin :my_plugin
# ...
Sequel::Model.db = Sequel.connect(config)
```

where the `my_plugin` is not available (missing code), I get this error message:

```
bundle exec rake spec
  ERROR -  Sequel::Error - No database associated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db= ?:
 /home/vagrant/.gem/ruby/2.3.1/gems/sequel-4.44.0/lib/sequel/model/base.rb:361:in `db'
rake aborted!
Sequel::Error: No database associated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db= ?
/home/vagrant/.gem/ruby/2.3.1/gems/sequel-4.44.0/lib/sequel/model/base.rb:361:in `db'
/home/vagrant/.gem/ruby/2.3.1/gems/sequel-4.44.0/lib/sequel/model/base.rb:681:in `inherited'
/home/vagrant/project/models/post.rb:2:in `<top (required)>'
```

In the above example, the `post` model would the first to be loaded.

Once I've made the `my_plugin` code available, everything works like a charm.

I might be wrong, but I remember that there was a more telling error message along the lines of "Could not load plugin `my_plugin'" instead of "missing database connection"

**Comment by jeremyevans** [comment]
The root cause of the problem appears to be you are not setting the database connection before creating the model classes.  See http://sequel.jeremyevans.net/rdoc/files/doc/code_order_rdoc.html.  I'm not sure why things would work if the `my_plugin` plugin was available.

If you think there is a problem even when setting up the database connection before creating the model classes, please post a small self contained example including all code and a full backtrace and I will review it and reopen if there appears to be an issue.

**Comment by fnordfish** [comment]
Will do (I'm pretty sure my db setup runs before loading models). Any preferences? As small as possible, or smallest padrinorb sample (to be more close to my real project)?

**Comment by jeremyevans** [comment]
As small as possible to show the problem, with just using Sequel, without using padrinorb.  From the code you posted, I assumed you were loading the models in the `# ...` part, and the database connections was after that.

**Comment by fnordfish** [comment]
Short update/for the record: Sequel does throw a correct "LoadError" when the missing plugin cannot be loaded. However, Padrino loads the `database.rb` in it's "load dependencies"-run in which it catches LoadErrors (probably to cope with loading order issues) and just carries on.
That's why the connection is not set up when loading models.
I'll take this issue over to padrino/padrino-framework

Thanks @jeremyevans for your time and sorry for the noise.
