### ISSUE TITLE
Spurious "no transaction in progress" warnings due to deferrable constraints in Postgres

### ISSUE THREAD

**Issue by chanks** [jeremyevans/sequel#1318]
I started noticing "WARNING: there is no transaction in progress" showing up in my logs and investigated it. Here's a complete reproduction:

Sequel version: 4.44.0
Postgres version: "PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit"
```ruby
require 'sequel'
require 'logger'

DB = Sequel.connect "postgres:///scrap",
  after_connect: proc { |c|
    c.set_notice_processor { |warning|
      puts "Received warning!"
      puts warning
      puts caller
    }
  }

DB.loggers << Logger.new(STDOUT)

DB.create_table :widgets do
  primary_key :id
  integer :value
  unique :value, deferrable: true
end

DB.transaction do
  DB[:widgets].insert(value: 1)
  DB[:widgets].insert(value: 1)
end
```

What happens is that the "COMMIT" issued by the end of the transaction causes the constraint to be checked and the error to be raised, but unlike other SQL statements that raise errors, the COMMIT also apparently rolls back the transaction. The current transaction logic doesn't understand this, and tries to issue a "ROLLBACK", which triggers the warning.

I did notice that that transaction_status method on the connection object correctly reports the status of the connection as no longer being in a transaction - perhaps Sequel could use that to determine whether to issue the ROLLBACK?

**Comment by jeremyevans** [comment]
Anytime `COMMIT` fails, Sequel will attempt to issue `ROLLBACK` to be sure that the transaction is closed.  This is the default behavior for all databases (https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/transactions.rb#L225-L236).  

PostgreSQL issues a warning in this case, and it may be safe to omit the `ROLLBACK` in certain cases, but I'm guessing there are cases even in PostgreSQL where if the `ROLLBACK` wasn't sent, the connection would still be considered in the transaction.

As this is just a warning and not an exception, it can be safely ignored.  I will accept a patch for this, but it would have to involve overriding `rollback_transaction` on PostgreSQL to check the state of the connection with the database to ensure the connection was outside a transaction, and only then not issuing the `ROLLBACK`. 

Note that if you run Sequel's PostgreSQL adapter tests, those have the same warning.

**Comment by jeremyevans** [comment]
Adding more detail: skipping the `ROLLBACK` if `conn.transaction_status == 0` will probably work, but you can only do it in the postgres adapter (not in the shared postgres adapter), and then only when the pg driver is used (`Sequel::Postgres::USES_PG == true`).
