### ISSUE TITLE
Cannot inherit from Sequel::Model with auto-validations plugin and custom table name

### ISSUE THREAD

**Issue by bgentry** [jeremyevans/sequel#1320]
### Complete Description of Issue

I'm using the latest version of Sequel with Rails. I have a model that inherits from `Sequel::Model` where its underscored class name does not match its table name. When I load that class, I get an error as Sequel is trying to query the underscored class name.

It appears that it does this before the rest of the class is loaded, so there's no way for it to know whether or not my dataset/table name is different than the default.

### Simplest Possible Self-Contained Example Showing the Bug

I'm using several plugins globally, including `:auto_validations`:

```ruby
Sequel::Model.plugin :auto_validations
```

Then I have a model like this:

```ruby
class OAuthRefreshToken < Sequel::Model
  set_dataset :oauth_refresh_tokens
end
```

Note that the table is called `oauth_refresh_tokens`, not `o_auth_refresh_tokens`. When I try to use the `OAuthRefreshToken` class, I get the exception shown below. It appears that this plugin causes Sequel to try to query the table name based on its class name *before* it is able to read any settings such as `set_dataset`.

### Full Backtrace of Exception (if any)

```
Sequel::DatabaseError: PG::UndefinedTable: ERROR:  relation "o_auth_refresh_tokens" does not exist
LINE 1: ...indisvalid" IS TRUE) AND ("tab"."oid" = CAST(CAST('"o_auth_r...
                                                             ^

  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/postgres.rb:193:in `async_exec'
  [... snip ... ]
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/postgres.rb:683:in `fetch_rows'
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:149:in `each'
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel_pg-1.6.17/lib/sequel_pg/sequel_pg.rb:62:in `each'
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/shared/postgres.rb:408:in `indexes'
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/plugins/auto_validations.rb:163:in `setup_auto_validations'
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/model/plugins.rb:46:in `block in after_set_dataset'
  /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.44.0/lib/sequel/model/base.rb:682:in `inherited'
  /Users/bgentry/my-project/my-repo/app/models/o_auth_refresh_token.rb:1:in `<top (required)>'
```

### SQL Log (if any)

Thanks as always for making such a wonderful open source project 🙏

**Comment by jeremyevans** [comment]
This is expected behavior, please set the dataset when creating the class:

```ruby
class OAuthRefreshToken < Sequel::Model(:oauth_refresh_tokens)
end
```

There are other plugins that work the same way.  Sequel itself will raise an exception if you attempt to create a model class with an incorrect name, when using `Sequel::Model.require_valid_table = true`.  That will probably be the default behavior in Sequel 5.

It looks the documentation doesn't specifically state the problems that can occur if you set the dataset after creating the class.  I'll update it tomorrow to try to push people away from using `set_dataset` after class creation.

**Comment by bgentry** [comment]
@jeremyevans ahh sorry for the trouble. Thanks for explaining it!
