### ISSUE TITLE
Should Dataset#to_hash implicitly (and recursively) call JSON(B)Hash#to_hash?

### ISSUE THREAD

**Issue by jnardone** [jeremyevans/sequel#1323]
There are methods that I get a Dataset back, usually single rows, that I need to convert to a true Hash to perform other operations on.

However, I'm also using pg_json, so when my dataset includes columns of type json/jsonb, I would expect that calling Dataset#to_hash would also convert those JSON(B)Hashes back to Hash as well, but it doesn't.

Short of deep-traversing my Dataset and converting all columns of JSON(B)Hash back to Hash, is there a way to do this?  Is this a bug that this doesn't already happen?

**Comment by jeremyevans** [comment]
I'm not sure exactly what you are referring to here, and your question indicates confusion about how Sequel works.  Datasets represent queries, or collections of rows if want to consider the results.  If you have a dataset that returns a single row and want a hash, you would generally call `Dataset#first` on it.  `Dataset#to_hash` is used for an entirely different purpose, it transforms the entire dataset (considering all rows), and returns a hash using the keys and values that you specify.

In terms of the `pg_json` extension, it returns `json`/`jsonb` columns as `Sequel::Postgres::JSONHash`/`Sequel::Postgres::JSONBHash` instances (or similar delegate classes for JSON arrays).  However, Sequel only wraps the outer hash/array, not all included hashes:

```ruby
DB.extension :pg_json
DB.get(Sequel.pg_json({}))
# => {}
DB.get(Sequel.pg_json({})).class
# => Sequel::Postgres::JSONHash
DB.get(Sequel.pg_json({})).to_hash.class
# => Hash
DB.get(Sequel.pg_json('a'=>{}))
# => {"a"=>{}}
DB.get(Sequel.pg_json('a'=>{}))['a'].class
# => Hash
DB.select(Sequel.as(1, :k), Sequel.pg_json('a'=>{}).as(:v)).to_hash(:k, :v)
# => {1=>{"a"=>{}}}
DB.select(Sequel.as(1, :k), Sequel.pg_json('a'=>{}).as(:v)).to_hash(:k, :v).class
# => Hash
DB.select(Sequel.as(1, :k), Sequel.pg_json('a'=>{}).as(:v)).to_hash(:k, :v)[1].class
# => Sequel::Postgres::JSONHash
DB.select(Sequel.as(1, :k), Sequel.pg_json('a'=>{}).as(:v)).to_hash(:k, :v)[1].to_hash.class
# => Hash
DB.select(Sequel.as(1, :k), Sequel.pg_json('a'=>{}).as(:v)).to_hash(:k, :v)[1]['a'].class
# => Hash
```

If you still think this is a bug in Sequel, please post a minimal self contained example showing the problem.

**Comment by jnardone** [comment]
Sorry, I was referring to the row after Dataset.first, but otherwise correct.  You answered my question re: deep JSON(B)Hashes, thanks.
