### ISSUE TITLE
Invalid SSL certificate for https://sequel.jeremyevans.net/

### ISSUE THREAD

**Issue by kenaniah** [jeremyevans/sequel#1327]
Chrome is telling me that the current certificate appears to be that of www.github.com's.

**Comment by ayghor** [comment]
I TOLD U
+1
<3

**Comment by rennex** [comment]
I believe you could use a free CloudFlare account to fix this.

**Comment by jeremyevans** [comment]
The website is hosted on GitHub Pages.  It has never advertised HTTPS support, and I doubt the HTTPS certificate used would ever have been valid.  Whoever created the HTTPS link did so incorrectly (I've seen this in Google, if so it's a Google bug).

In any case, this is out of my control to fix, and adding a external dependency is undesirable.  If you are concerned about the security of the website, just generate it locally, there's nothing on the website that isn't generated from the rake tasks in the repository.
