### ISSUE TITLE
Add type conversion for DATETIMEOFFSET

### ISSUE THREAD

**Issue by iaddict** [jeremyevans/sequel#1332]
It would be great if the jdbc type for MS SQLServer DATETIMEOFFSET would be automatically converted to ruby Time.

I already created an attempt, but it didn't work properly.
Please see https://github.com/jeremyevans/sequel/pull/1331.

Currently the java class microsoft.sql.DateTimeOffset is returned.

**Comment by jeremyevans** [comment]
There are many database specific types that the generic jdbc type handling doesn't convert to ruby types.  It isn't a bug that the MSSQL-specific DATETIMEOFFSET is not converted to a ruby type.  That being said, I'd certainly consider a patch that supported it, assuming it came with appropriate specs.  If you would like it supported, please submit a working pull request with specs.  Closing this now as it isn't a bug.

**Comment by AndrewClarke** [comment]
Hi, I'm having a look at this, and it seems that Time is not the best option, since it only supports GMT or localtime. A Ruby DateTime would be more appropriate. I'm playing with your patch now, and I'll try to make it work with DateTime. Unless I'm wrong of course...
