### ISSUE TITLE
as400 jdbc adapter does not honor identifier_mangling: false

### ISSUE THREAD

**Issue by perlun** [jeremyevans/sequel#1335]
### Complete Description of Issue

I try to connect to Sequel using the `identifier_mangling: false` option with the now-deprecated jdbc/as400 adapter, and it doesn't work; the identifiers are still mangled.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
db = Sequel.connect(
  connection_string,
  identifier_mangling: false
)
 # The result here will have `FOOBAR` fields converted to `foobar` 
db[:table].where(foo: 'bar')symbols.
```

### Workaround

I did a horrible hack like this, monkeypatching the AS400 adapter after loading it:

```ruby
Sequel.require 'adapters/utils/unmodified_identifiers'

module Sequel
  module JDBC
    module AS400
      module DatabaseMethods
        include Sequel::UnmodifiedIdentifiers::DatabaseMethods
      end
    end
  end
end
```

This now _works_, but only if I _do not_ provide the `identifier_mangling` option when connecting (!). Even setting it to false _now makes the identifiers be mangled_. 😲 Say what?

Please suggest a proper way to fix this. I'll gladly submit a PR that makes the AS400 adapter behave like it should.

----

(We have used the AS400 adapter for years, but have historically always disabled the identifier mangling since we find it very obnoxious. The approach used have been this:

```ruby
        Sequel.connect(
          connection_string
        ).tap { |db|
          db.identifier_output_method = nil
          db.identifier_input_method = nil
        }
```

But this will now generate a warning saying that the identifier mangling support is deprecated. Yes, that's fine, we just want to get rid of it so please let me know how. 😆 

----

(If/when the as400 adapter is finally dropped from Sequel, I will likely have to help out in forking it out to a separate repo and gem. We rely on it **very heavily** in production, with a number of customers. But, for now I am very happy that it is still a part of Sequel core. 😄)

**Comment by jeremyevans** [comment]
Note that `:identifier_mangling => false` Database option does not mean no identifier mangling, it means don't load the identifier_mangling extension (technically, now the _deprecated_identifier_mangling extension).  The default in Sequel for databases that fold unquoted identifiers to uppercase is to upcase on input and downcase on output.  The default in Sequel for databases that fold unquoted identifiers to lowercase is to not modify identifiers.  The identifier_mangling extension allows you to modify the default mangling behavior.

If you want to not modify identifiers on as400, you should do the same thing as before, except load the identifier_mangling extension manually first:

```ruby
Sequel.connect(connection_string).tap do |db|
  db.extension(:identifier_mangling)
  db.identifier_output_method = nil
  db.identifier_input_method = nil
end
```

The jdbc/as400 adapter will be dropped in Sequel 5, which is probably 4-5 months away.  Extracting it to a separate repo and gem should be as simple as copying the existing file and adding a gemspec.  I should be able to help if you run into trouble with that.

**Comment by perlun** [comment]
> If you want to not modify identifiers on as400, you should do the same thing as before, except load the identifier_mangling extension manually first:

Thanks! I fixed it like that and the deprecation message is now gone.

Will the `identifer_mangling` extension be dropped in Sequel 5, what do you think? What will be the suggested approach there for disabling identifier mangling?

----

> The jdbc/as400 adapter will be dropped in Sequel 5, which is probably 4-5 months away. Extracting it to a separate repo and gem should be as simple as copying the existing file and adding a gemspec. I should be able to help if you run into trouble with that.

Thanks, I'll try to get that effort started in time. What do you suggest as the gem name for these adapter gems? `sequel-adapters-as400` or something? (making room for other, similar gems for the other adapters that are also going away)

**Comment by jeremyevans** [comment]
@perlun The identifier_mangling extension will remain in Sequel indefinitely, as there will be a continuing need for some users to modify the default mangling.  It's just that most users do not need to modify the default mangling, so the related code was moved out of core.

I would use `sequel-jdbc-as400` as the gem name.

**Comment by perlun** [comment]
> I would use sequel-jdbc-as400 as the gem name.

Alright, will go for that. Please let us know when there is a Sequel 5.0.0.beta-version or similar (where this support is dropped) so we can target the new gemspec accordingly and test that the new gem works as it should.

**Comment by jeremyevans** [comment]
@perlun You could always create the gem now and depend on sequel '>= 4.45.0'.  It wouldn't be picked up by Sequel unless the sequel-jdbc-as400 gem lib dir was earlier in the load path, until Sequel 5 was released.

**Comment by perlun** [comment]
> It wouldn't be picked up by Sequel unless the sequel-jdbc-as400 gem lib dir was earlier in the load path, until Sequel 5 was released.

OK, good point. I'll see what I can do.

**Comment by perlun** [comment]
Started here: https://github.com/ecraft/sequel-jdbc-as400

Still heavy WIP, but it _might_ even work in its current shape. 😄 Not published to Rubygems or anything yet though.
