### ISSUE TITLE
Sequel::SQLTime does not respect Sequel.default_timezone setting

### ISSUE THREAD

**Issue by iaddict** [jeremyevans/sequel#1336]
### Complete Description of Issue

Sequel always creates SQLTimes with #local instead of using #utc when Sequel.default_time_zone == :utc.
See: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/sql.rb#L62

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
Sequel.default_time_zone = :local
assert !Sequel::SQLTime.create(10, 0, 0).utc?

Sequel.default_time_zone = :utc
assert Sequel::SQLTime.create(10, 0, 0).utc?
```

**Comment by jeremyevans** [comment]
I'm not sure that is a bug, as SQLtime instances are never literalized with the timezone.  However, I guess I don't see the problem when using utc instead of local if that is the default time zone.  I'll make that change shortly.

**Comment by iaddict** [comment]
What a stellar response time.
Many many thanks!
