### ISSUE TITLE
Sequel.extension has no effect

### ISSUE THREAD

**Issue by baelter** [jeremyevans/sequel#1344]
Loading extension on the base class is not applied på Sequel sessions.

Try:
```
Sequel.extension :pg_hstore
@db = Sequel.connect 'postgres://localhost'
res = @db['SELECT hstore_col FROM my_table'].first
pust res[:hstore_col].class # => String
```

While
```
@db = Sequel.connect 'postgres://localhost'
@db.extension :pg_hstore
res = @db['SELECT hstore_col FROM my_table'].first
pust res[:hstore_col].class # => Sequel::Postgres::HStore
```

Applies to:
```
pg (0.20.0)
sequel (4.45.0)
sequel_pg (1.6.17)
```

**Comment by celsworth** [comment]
I think this is working as intended. If you want to load the extension for all future database objects,
as per the [docs](http://sequel.jeremyevans.net/rdoc/files/doc/extensions_rdoc.html) you probably want

```
Sequel::Database.extension(:pg_hstore)
```

You can see it's a database extension at the bottom of http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pg_hstore_rb.html

**Comment by baelter** [comment]
Oh, okey.

But FYI this has been working up until the latest version.

**Comment by celsworth** [comment]
Ah, see the [changelog](http://sequel.jeremyevans.net/rdoc/files/doc/release_notes/4_45_0_txt.html) which would explain it..

> The pg_hstore extension no longer modifies PG_NAMED_TYPES. This should not affect behavior if the pg_hstore extension is loaded into the Database instance.

**Comment by jeremyevans** [comment]
This is currently the expected behavior.  The fact that pg_hstore worked in previous instances if you didn't load the extension into the Database was a side effect of an implementation detail, not by design.
