### ISSUE TITLE
Sequel::Postgres::DatabaseMethods#views does not return materialized views

### ISSUE THREAD

**Issue by Blargel** [jeremyevans/sequel#1347]
### Complete Description of Issue
DB.views only returns regular views and not materialized views when connected to Postgres. I was unable to find an option in the documentation that would let me see them. I also tried passing the `:materialized => true` option just in case it was undocumented. The cause of this problem is that in the pg_class table, regular views have a relkind of v but materialized views have a relkind of m.

Sequel version: 4.46.0
Postgres version: 9.4.4

### Simplest Possible Self-Contained Example Showing the Bug
```Ruby
require 'sequel'
config = {
  :adapter  => "postgres",
  :host     => "localhost",
  :database => "test",
  :user     => "abnerqian",
}
DB = Sequel.connect(config)
DB.create_table(:foo)
DB.create_view(:bar, DB[:foo], :materialized => true)

DB.views
# => []
# expected to be [:bar]

DB.views(:materialized => true)
# => [] 
# :materialized option doesn't work or exist
```

### SQL Log (if any)
This is what's outputted in the above example if Logger is included
```
I, [2017-05-05T00:34:02.108492 #26105]  INFO -- : (0.018463s) CREATE TABLE "foo" ()
I, [2017-05-05T00:34:02.115355 #26105]  INFO -- : (0.004930s) CREATE MATERIALIZED VIEW "bar" AS SELECT * FROM "foo"
I, [2017-05-05T00:34:02.131851 #26105]  INFO -- : (0.014603s) SELECT "relname" FROM "pg_class" INNER JOIN "pg_namespace" ON ("pg_namespace"."oid" = "pg_class"."relnamespace") WHERE (("relkind" = 'v') AND ("pg_namespace"."nspname" = any(current_schemas(false))))
I, [2017-05-05T00:34:02.135872 #26105]  INFO -- : (0.000713s) SELECT "relname" FROM "pg_class" INNER JOIN "pg_namespace" ON ("pg_namespace"."oid" = "pg_class"."relnamespace") WHERE (("relkind" = 'v') AND ("pg_namespace"."nspname" = any(current_schemas(false))))
```

**Comment by jeremyevans** [comment]
PostgreSQL treats materialized views and regular views differently, because they are two different things in PostgreSQL.  The commands to create them are different and documented differently in PostgreSQL.

It's expected that `Database#views` does not return materialized views.  I'm OK with adding a `Database#materialized_views` method on PostgreSQL that returns materialized views.  If you would like to do that, please submit a pull request for it and include specs and documentation.

**Comment by jeremyevans** [comment]
After giving this some more thought, I think your idea of a `:materialized` option to `Database#views` is better than adding a new `materialized_views` method.  That would make `#views` consistent with `#create_view`
