### ISSUE TITLE
Picking up an specific read only slave

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1355]
In the multiple sharding models supported by Sequel, there doesn't seem to have a way to pick up one specific read only shard for an specific task, for instance:
```ruby
DB=Sequel.connect('postgres://master_server/database', \
  :servers=>{:api_customers=>config, :read_only=>read_only_proc})
```
Then if I pick `:api_customers`
```ruby
DB.with_server(:api_customers){ User.create }
Sequel::DatabaseError: PG::ReadOnlySqlTransaction: ERROR:  cannot execute INSERT in a read-only transaction
```
So it is considering `:api_customers` an master instance. I want it only as a read only slave, but an also be able to pick it up among others replicas in specific as certain load should go to one specific replica.

I can't see how to do that with a `read_only` proc.

**Comment by jeremyevans** [comment]
If you use `with_server`, you are telling Sequel that you want database activity inside the block to go to that server unless the dataset specifically overrides the server to use.  So if you don't want the `INSERT` to go to the `api_customers` shard, then you shouldn't use `with_server(:api_customers)`

Maybe you should better describe what you want.  However, as this is not a bug in Sequel, you should probably ask for support on the sequel-talk Google Group, as mentioned in the contribution guidelines.

**Comment by brauliobo** [comment]
When using without the `with_server` I don't need to worry about if it is an `INSERT` or an `SELECT`. So what I need is a way to specify a read replica and keep this smart behaviour.

**Comment by jeremyevans** [comment]
Unfortunately, that is not currently possible with the server_block extension.  You would have to modify the server_block extension or add a separate extension to support it.

**Comment by brauliobo** [comment]
Ok, that is also not possible with the `server` call, so I presume that problem isn't on the `server_block` extension

**Comment by jeremyevans** [comment]
You could always call `Dataset#server` to specify the server to use for each dataset (separately for the INSERT and SELECT).  However, in general Sequel uses the same server for the SELECT after the INSERT in a Model.create call.  Otherwse, there is often a race condition where the read replica won't have have received the row before Sequel tries to select from it.

**Comment by brauliobo** [comment]
@jeremyevans that is the big hassle: in large applications it is completely inviable to spread calls of `Dataset#server`, also considering that the server parameter would need to be passed to several contexts

**Comment by jeremyevans** [comment]
As the contribution guidelines mention, GitHub Issues is not a support forum.  This isn't a bug in Sequel.  If you'd like it to be considered as an additional feature (specify regular and read_only shards in with_server), please post on the sequel-talk Google Group and see if there is any community support for that.

**Comment by brauliobo** [comment]
Wouldn't it be simple to add a readonly flag to the server hash? So it would be easy for sequel to know if it is a master or not. Also would be interesting to have the read only replicas inside their respective *master*. As it is now, there is no way to know about which replica is for which master.

**Comment by brauliobo** [comment]
Sorry @jeremyevans, I seriously think this is a limitation, so this issue is a feature request IHMO

**Comment by jeremyevans** [comment]
GitHub Issues should not be used for feature requests, only for bugs, as specified in the contribution guidelines.  You can submit a pull request for features.

**Comment by brauliobo** [comment]
thanks @jeremyevans, I consider some time to improve this!
