### ISSUE TITLE
URI encode PG connection string before to URI.parse

### ISSUE THREAD

**Issue by jodosha** [jeremyevans/sequel#1361]
### Complete Description of Issue

Using non encoded chars in PG connection string cause an `URI::InvalidURIError`.

#### Create database and user

```shell
$ createdb bookshelf
$ createuser sequeltest --pwprompt
Enter password for new role:
Enter it again:
```

I picked `p@ssword` as password.

#### Verify the password

```shell
psql -d bookshelf -U sequeltest -W
Password for user sequeltest:
```

#### Ruby code

```ruby
require 'bundler/inline'

gemfile do
  gem 'pg'
  gem 'sequel'
end

DB = Sequel.connect('postgres://sequeltest:p@ssword@localhost/bookshelf')
```

### Full Backtrace of Exception (if any)

```shell
ruby test.rb
/Users/luca/.rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): postgres://sequeltest:p@ssword@localhost/bookshelf (URI::InvalidURIError)
	from /Users/luca/.rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
	from /Users/luca/.rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
	from /Users/luca/.gem/ruby/2.4.1/gems/sequel-4.46.0/lib/sequel/database/connecting.rb:57:in `connect'
	from /Users/luca/.gem/ruby/2.4.1/gems/sequel-4.46.0/lib/sequel/core.rb:116:in `connect'
	from test.rb:8:in `<main>'
```

---

Ref https://github.com/hanami/model/issues/402

**Comment by janko-m** [comment]
I'm not sure whether Ruby has a non-deprecated method for escaping strings, as `URI.encode`/`URI.escape` are deprecated (declared as "obsolete", but I didn't find any alternative in the [original discussion](http://ruby-core.ruby-lang.narkive.com/0XKxdn7l/ruby-core-29293-uri-un-escape-deprecated)). I was researching that in https://github.com/janko-m/shrine/issues/132, and I've come to the conclusion that the only correct way of encoding whole URLs is to use the [Addressable](https://github.com/sporkmonger/addressable) gem.

Unless I'm missing something and there is in fact a way to URI encode whole URLs that I don't know of, I think it would be simpler if Hanami were to URI encode the username and password parts, which can be done using `CGI.escape`.

```rb
require "cgi"
CGI.escape("p@assword").gsub('+', '%20') #=> "p%40assword"
```

**Comment by jeremyevans** [comment]
This is a bug in the connection string, not in Sequel.  The connection string must already be a valid URL.  Sequel unescapes URL encoded options, so the connection string should be: `postgres://sequeltest:p%40ssword@localhost/bookshelf`.

**Comment by jodosha** [comment]
@jeremyevans @janko-m Thanks for getting back. I agree with you folks, but just wanted to make sure that you were aware of the edge case.

I'm not gonna escape it in Hanami as well.

Once again, thank you very very much for Sequel. 💚

**Comment by SenseiCain** [comment]
They seem to have replaced them with `escape` and `unescape`
https://ruby-doc.org/stdlib-2.5.1/libdoc/uri/rdoc/URI/Escape.html#method-i-unescape
