### ISSUE TITLE
graph method does not return correct hash

### ISSUE THREAD

**Issue by arobecke** [jeremyevans/sequel#1363]
### Complete Description of Issue
I have a bookings table and cancellations table that has a booking_id column. I was trying to use the graph method to get a namespaced result hash. 

`DB[:cancellations].graph(:bookings, id: :booking_id)` returns the following dataset:

#<Sequel::Postgres::Dataset: "SELECT \"cancellations\".\"id\", \"cancellations\".\"booking_id\", \"cancellations\".\"body\", \"bookings\".\"id\" AS \"bookings_id\", \"bookings\".\"body\" AS \"bookings_body\" FROM \"cancellations\" LEFT OUTER JOIN \"bookings\" ON (\"bookings\".\"id\" = \"cancellations\".\"booking_id\")">

`DB[:cancellations].graph(:bookings, id: :booking_id).first.keys` returns `[:id, :booking_id, :body, :bookings_id, :bookings_body]`

I would have expected `:bookings` and `:cancellations` to be the keys that contain the hashes from the respective tables.

I'm using ruby `2.3.0` with sequel version `sequel-4.44.0`

**Comment by jeremyevans** [comment]
That behavior was moved to the graph_each extension in Sequel 4.
