### ISSUE TITLE
Looking for guidance on appending a literal field to each SELECT query

### ISSUE THREAD

**Issue by StevePotter** [jeremyevans/sequel#1365]
Hi, we are longtime users of your amazing gem.  We use pganalyze.com for database monitoring.  It does a good job showing us problematic queries, but it's very difficult to know exactly where a query is coming from.  We have a web app and bunch of other tasks and services that all use the DB.  I spoke with the pganalyze folks and there is no simple way to do this.  So I have an idea.  How about we append a column to the end of each SELECT query (forget inserts, deletes, and updates) that indicates where the query came from?  Then pganalyze will recognize what is essentially the same query as separate queries.  For example:
Today we have `select * from users`
But I want to have instead `select *, 'web' as _source from users` and `select *, 'background job 1' as _source from users`, where the `_source` value is set on our DB class.

I am unaware of the internals of the sequel gem and didn't find a suitable place in my brief look at the source code.  Is there a place I can hook into where I can append a field to every SELECT query?   I'd like to do it without string parsing, so something like `DB.select_handler {|query| query.fields.push(:_source,current_process_description }`  

I hope I'm clear in this description and appreciate any help you can offer, including a 'no you can't'.  Thanks!

**Comment by jeremyevans** [comment]
For this type of thing, I would recommend using the sql_comments extension that ships with Sequel.  But you could also override `select_columns_sql` for the dataset to append additional columns.

As mentioned in the contribution guidelines, GitHub Issues should only be used for bug reports.  In the future, please use the IRC channel or the sequel-talk Google Group to ask questions like this.

**Comment by StevePotter** [comment]
@jeremyevans sorry for posting to the wrong forum and thank you so much for your help!
