### ISSUE TITLE
SUM() returns float instead of bigint (int8)

### ISSUE THREAD

**Issue by gencer** [jeremyevans/sequel#1369]
I have this query:
` total_usage = Reserve.select{sum(:object_size).as(:object_size)}.where(...).first`

I inspect RAW SQL via `.sql` method. Sequel generates correct query.

Now, When I copy sequel query (by `.sql` method) and put to my DB client and manually execute I get this result:

`$= 43012405682` _(object_size)_

But Sequel gave me this:
`> #<Reserve @values={:object_size=>0.43012420299e11}>`

It is float. And start with zero. **0.43012420299e11**. I expect actual result **43012405682** to be return.

**PostgreSQL 9.6** with sequel_pg extension. `postgresql` adapter used (directly, not jdbc)

`object_size` field is `int8`

**Comment by jeremyevans** [comment]
Which adapter, driver, and database are you using (including versions)?  This could be expected behavior if the driver/database returns the aggregate function result using a non-integer type.  For example, MySQL returns sum/avg values as decimal (not integer) if the columns are integer (see https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html).

**Comment by gencer** [comment]
Oh. Sorry I was on phone I thought I added those details.

**PostgreSQL 9.6** with sequel_pg extension. `postgresql` adapter used (directly not jdbc)

**Comment by jeremyevans** [comment]
My guess is that object_size is bigint, and PostgreSQL returns sum(bigint_column) as numeric (see https://www.postgresql.org/docs/9.6/static/functions-aggregate.html).  That's not a float, that's a BigDecimal:

```ruby
DB.create_table!(:reserves){Bignum :object_size}
DB[:reserves].insert(:object_size=>1)
DB[:reserves].insert(:object_size=>43012405681)
class Reserve < Sequel::Model; end
Reserve.select{sum(:object_size).as(:object_size)}.first
# => #<Reserve @values={:object_size=>0.43012405682e11}>
Reserve.select{sum(:object_size).as(:object_size)}.first[:object_size].class
# => BigDecimal
```

If object_size isn't a bigint column or you think there is still an issue in Sequel, then please provide a minimal, self contained, reproducible example and I'll analyze it and possibly reopen.

**Comment by gencer** [comment]
@jeremyevans, Exactly. After I did CAST using Sequel, I get the correct output.

I did as `...select{Sequel.cast(sum(:object_size), :bigint).as(:object_size)}`

Is this correct way of handling SUM(bigint) on Sequel? If not, How can I do in proper?

**Comment by jeremyevans** [comment]
If you want the value returned as a bigint and you do not care about overflow, then it should fine if you CAST.  I believe the reason PostgreSQL doesn't do that is that the sum of two bigint values may not fit in bigint (integer overflow).  If you really want an integer in ruby, the best way to get one would be to call BigDecimal#to_i after the value is returned.
