### ISSUE TITLE
PG deprecation warnings

### ISSUE THREAD

**Issue by TiteiKo** [jeremyevans/sequel#1377]
### Complete Description of Issue

When using Sequel (4.47.0) with PG 0.21.0, deprecation warnings (about PG) are displayed.

No warning with PG 0.20.0, this was introduced by https://bitbucket.org/ged/ruby-pg/commits/3ce331d8c88ec928ad0349e47ffd717f34fa6104

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'sequel'
gem 'pg'
```

```ruby
# main.rb
require 'bundler/setup'
require 'sequel'

DB = Sequel.connect('postgres://postgres/pg_warnings')
```

```
$ ruby main.rb
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /bundle/gems/sequel-4.47.0/lib/sequel/database/connecting.rb:111:in `require'
```

**Comment by jeremyevans** [comment]
Closing as we'll be tracking completion of this on #1378.
