### ISSUE TITLE
Trouble with symbols with consecutive underscores in column name

### ISSUE THREAD

**Issue by fatcatt316** [jeremyevans/sequel#1379]
I have a SQLite DB that has a column with two consecutive underscores in its name ("1__two_underscores").

It looks like Sequel is interpreting that as a period somehow, so this happens:

If `column = :"1__space_after_underscore"`, then:

```
db[:data].where("? IS NOT NULL AND ? != ''", column, column).sql
"SELECT * FROM `data` WHERE (`1`.`space_after_underscore` IS NOT NULL AND `1`.`space_after_underscore` != '')"
```

If I convert it to a string, I get this, which is wrong in a different way:
```
db[:data].where("? IS NOT NULL AND ? != ''", column.to_s, column.to_s).sql
"SELECT * FROM `data` WHERE ('1__space_after_underscore' IS NOT NULL AND '1__space_after_underscore' != '')"
```

Is this a known issue? If so, do you know a good way around this problem?

Thanks for any info!

**Comment by fatcatt316** [comment]
This might solve it: https://github.com/jeremyevans/sequel/issues/327#issuecomment-1085816

**Comment by jeremyevans** [comment]
You currently need to set `Sequel.split_symbols = false` to stop splitting symbols.  This will be the default starting in Sequel 5.  If you want to keep the symbol splitting, you can do `column = Sequel.identifier(:"1__space_after_underscore")` to make sure that Sequel won't split it.
