### ISSUE TITLE
`pg` gem was updated to 0.21.0 with constants renaming

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/sequel#1380]
### Complete Description of Issue

Warnings from `pg` gem about its constants renaming in new (`0.21.0`) version.

### Simplest Possible Self-Contained Example Showing the Bug

Any connection to PostgreSQL DB, I guess.

### Full Backtrace of Exception (if any)

```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/alex/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.47.0/lib/sequel/database/connecting.rb:111:in `require'
```

**Comment by janko-m** [comment]
@AlexWayfer This looks like a duplicate of https://github.com/jeremyevans/sequel/issues/1380.

**Comment by AlexWayfer** [comment]
> @AlexWayfer This looks like a duplicate of #1380

Sorry, of what? #1380 is current issue.

Oh, I found #1378. Sorry.
