### ISSUE TITLE
Association pks not working for custom where statements

### ISSUE THREAD

**Issue by mbajur** [jeremyevans/sequel#1385]
### Complete Description of Issue
I have a `many_to_many` association defined for one of my models with custom `where` block.  It's defined like this:

```
class User < Sequel::Model
  plugin :association_pks
  many_to_many :user_attributes_hosting_preferences, class: :UserAttribute, join_table: :user_user_attributes, left_key: :user_id, right_key: :user_attribute_id do |usa|
    usa.where("user_attributes.category = ?", 'hosting_preferences')
  end
end
```
Which provides a valid results set and SQL query for getting a list of user_attributes:
```
> user.user_attributes_hosting_preferences
# => SELECT `user_attributes`.* FROM `user_attributes` INNER JOIN `user_user_attributes` ON (`user_user_attributes`.`user_attribute_id` = `user_attributes`.`id`) WHERE ((`user_sitter_attributes`.`user_id` = 1) AND (user_attributes.category = 'hosting_preferences'))
```

But when i'm trying to do the same but to get the `pks`, SQL query is wrong:

```
> user.user_attributes_hosting_preference_pks
# => SELECT `user_attribute_id` FROM `user_user_attributes` WHERE (`user_id` = 1)
```

As you can see - my custom `where` block is missing in here.

Am i doing something wrong or did it found a bug of association_pks? Thanks in advance for any help!

**Comment by jeremyevans** [comment]
By default, association_pks operates purely on the join table, and therefore does not respect association blocks or `:conditions` option.  However, with the most recent version, you can use the `:association_pks_use_associated_table` option to operate on the associated dataset.
