### ISSUE TITLE
type varchar in migrations

### ISSUE THREAD

**Issue by 7dr1v3** [jeremyevans/sequel#1386]
sequel (4.47.0) sequel-rails (0.9.16) pg (0.20.0)

In migration, if you try to make varchar column without fixed size then Sequel will set size 255. size: nil/false/0 is not working. But you can use 'varchar ' (with space at the end) or you can use 'character varying'. Although it is just alias Sequel don't add 255. I think it is very not obvious logic.))

**Comment by jeremyevans** [comment]
The fact that Sequel treats `'varchar'` specially is just for backwards compatibility, and not something that should be relied upon in new code.  However, the current behavior is expected.  In general if you want to create a string field with size 255, do `String :column_name, :size=>255`
