### ISSUE TITLE
Deprecation warning and broken behavior on dataset filtering method with a plain string

### ISSUE THREAD

**Issue by shelmire** [jeremyevans/sequel#1389]
### Complete Description of Issue

There is a deprecation warning about filtering datasets with string literals, saying this will be deprecated as of version 5. However, this change is already breaking as of 4.47.0. As a result, you will get the deprecation warning and more importantly, broken behavior.

### Simplest Possible Self-Contained Example Showing the Bug

dataset.select(:column_name).where('anything here')

### Full Backtrace of Exception (if any)

```
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with a plain string is deprecated and will be removed in Sequel 5.  Use Sequel.lit("site_id is not null") to create a literal string and pass that to the dataset filtering method, or use the auto_literal_strings extension.
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.47.0/lib/sequel/dataset/query.rb:1315:in `filter_expr'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.47.0/lib/sequel/dataset/query.rb:1249:in `add_filter'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-4.47.0/lib/sequel/dataset/query.rb:1034:in `where'
```

**Comment by jeremyevans** [comment]
The deprecation warning is expected.  Can you explain how the behavior is broken?  Here's what I get (ignoring the deprecation warning), which should be the same as in previous versions of Sequel:

```ruby
DB[:a].select(:column_name).where('anything here')
#  => "SELECT column_name FROM a WHERE (anything here)"
```

**Comment by shelmire** [comment]
I think perhaps I misread the deprecation trace as the cause script crashing. Closing this.
