### ISSUE TITLE
Item update not applying to actual DB?

### ISSUE THREAD

**Issue by maxiedaniels** [jeremyevans/sequel#1390]
I'm having a weird issue that I've never seen before, where an item isn't being updated.

Example:
```
available = $db[:users].where(:active=>0)
first_user = available.first
first_user.update(:active => 1)
```

Unless I'm mistaken, this should update the non-active user to be 'active', however it's not actually modifying the user.. if I print out $db[:users].all, it won't show that user as having :active changed to a 1.

**Comment by jeremyevans** [comment]
You are calling Hash#update, not Sequel::Model#update or Sequel::Dataset#update, so this is expected.  Hash#update only updates the hash itself.
