### ISSUE TITLE
Confusing string litteral deprecation

### ISSUE THREAD

**Issue by kenips** [jeremyevans/sequel#1392]
Hello, I'm confused as to whether `where("posted_at <= ?", @date)` is considered deprecated. I'm getting "Calling a dataset filtering method with multiple arguments or an array where the first argument/element is a string is deprecated and will be removed in Sequel 5." so it does sounds like it, but looking at the examples I can't tell that they are deprecated. Thanks!

**Comment by jeremyevans** [comment]
Yes, it is deprecated.The deprecation even gives an example of the replacement code.  Not all of the documentation has been updated yet, but that should happen before the release of Sequel 5.

**Comment by kenips** [comment]
Thanks @jeremyevans! Just wanted to confirm. The deprecation example isn't as useful in this case due to using `?` for substitution, and hence I thought it was only targeting complete string literals. Thanks for clarifying!
