### ISSUE TITLE
Add :stream => false option

### ISSUE THREAD

**Issue by Aryk** [jeremyevans/sequel#1394]
Discussed [here](https://groups.google.com/forum/#!topic/sequel-talk/lqYvmex9ojo).

I'm going to submit a PR to address this.

**Comment by jeremyevans** [comment]
Closing, tracking on #1395.  Note that an issue shouldn't be opened for this, as it is not a bug, but a request for a new feature.

**Comment by Aryk** [comment]
ok, i won't open issues for feature add-ons.
