### ISSUE TITLE
Timestamp formatting only works for some Oracle datatypes

### ISSUE THREAD

**Issue by IanWhitney** [jeremyevans/sequel#1400]
### Complete Description of Issue

Using the Oracle adapter, any Sequel query that is filtering by a Time or DateTime value will end up with something like this in the WHERE clause

```
TIMESTAMP '2017-07-14 16:56:44.000000 -05:00'
```

This format comes from the [Oracle `TIMESTAMP_FORMAT` constant](https://github.com/jeremyevans/sequel/blob/4.40.0/lib/sequel/adapters/shared/oracle.rb#L320). This format includes both fractional seconds and time zone info.

However, Oracle has [4 different DateTime datatypes](https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch4datetime.htm) and the above timestamp format only works for 2 of them. 

- `Date` does not support fractional seconds or time zones
- `Timestamp` supports fractional seconds, but not time zones
- `Timestamp with time zone` supports both
- `Timestamp with local time zone` supports both

If you try to filter a column with a timestamp containing elements that the datatype does not support, Oracle gives you incorrect results.

### Simplest Possible Self-Contained Example Showing the Bug

Given a table, `users`

| column name | data type |
| ---- | ---- |
| username | varchar |
| join_date | date |

And the `join_date` column contains values in the format `YYYY-MM-DD HH24:MI:SS`

Then a Sequel command like 

```ruby
yesterday = DateTime.now - 1
Users.where { join_date > yesterday }
```

Can return records where the `join_date` is before yesterday.

### Full Backtrace of Exception (if any)

N/A

### SQL Log (if any)

N/A

**Comment by jeremyevans** [comment]
What behavior would you like to see in this case?  I can't think of a behavior change that would make sense for all cases.  We can't just not use fractional times or timezones without breaking existing behavior.

I'm open to making it possible to change the timestamp format via a setting, if that's what you want, but if you are mixing different datetime types in the same query, there's not really a good way to handle that, unless you want to use wrapper objects.

**Comment by IanWhitney** [comment]
Well, I'm not sure there is a solution for this one. My understanding is that to properly handle all 4 datatypes Sequel would have to know the datatype of the column being referenced. So if the column is `DATE` then Sequel would use `TO_DATE`. But if the column is `TIMESTAMP WITH ZONE`, then Sequel would use `TIMESTAMP`. Etc. And I don't think Sequel does that kind of reflection. 

The best case here may be documenting the problem & possible workarounds. For my case I rewrote how we defined this dataset method. Instead of 

```ruby
yesterday = DateTime.now - 1
Users.where { join_date > yesterday }
```

We now use

```ruby
yesterday = DateTime.now - 1
where {
          "last_mod_date > TO_DATE('#{yesterday.strftime("%F %T")}', 'YYYY-MM-DD HH24:MI:SS')"
}
```

Which is much less elegant, but it works.

**Comment by jeremyevans** [comment]
Sequel can't know the type of the expression being used in filters, at least in non-trivial cases, so I don't think this is something that Sequel could handle automatically.  As I mentioned, I could add a way to override timestamp formats on a per-dataset basis, or add wrapper objects that would use different formatting.  Both of those would require the user to modify their code, though, and I'm not sure it would be better than the workaround you are using.

Since this isn't a bug, I'm going to close this now.
