### ISSUE TITLE
Sequel doesn't deduplicate fetching associations when using both `eager_graph` and `eager`

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [jeremyevans/sequel#1404]
### Complete Description of Issue

If you use both `eager_graph` and `eager` on a dataset, Sequel will still issue a second request to fetch the associations that it already fetched in the first request.

There could be some edge cases where this _is_ the desired behavior, but I can't think of any.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB.create_table(:first_examples) do
  primary_key :id
end

DB.create_table(:second_examples) do
  primary_key :id
  foreign_key :first_example_id, :first_examples
end

class FirstExample < Sequel::Model(:first_examples); end

class SecondExample < Sequel::Model(:second_examples)
  many_to_one :first_example, class: :FirstExample, key: :first_example_id
end

first_example = FirstExample.create
SecondExample.create(first_example: first_example)

DB.loggers << Logger.new($stdout)

SecondExample.eager_graph(:first_example).eager(:first_example).all
```

Outputs:

> SELECT "second_examples"."id", "second_examples"."first_example_id", "first_example"."id" AS "first_example_id_0" FROM "second_examples" LEFT OUTER JOIN "first_examples" AS "first_example" ON ("first_example"."id" = "second_examples"."first_example_id")
> SELECT * FROM "first_examples" WHERE ("first_examples"."id" IN (1))

**Comment by jeremyevans** [comment]
This is expected behavior.  Let's say you want to filter using the eager_graph, but then for the matching current records, get all associated records for them:

```ruby
Foo.eager_graph(:bar).where(Sequel[:bar][:baz]=>'quux').eager(:bar).all
```

Without the `eager(:bar)`, you only get the bars with column baz having value quux, instead of all bars for the foos that have any bar with a column baz having value quux.

If you don't want this behavior, then don't use eager and eager_graph with the same association.

**Comment by PaulJuliusMartinez** [comment]
Isn't that only the case for `one_to_many` associations? If it's a `many_to_one` association then there's only one value to filter by, so you wouldn't lose any associations.

(Though now it's just an optimization cause by a fairly unusual combination. I'm sure there are a lot of places where you could do things slightly more intelligently if the stars align, but then the onus should just be on the programmer.)


Thanks for your prompt response! I wasn't sure if this was the right place to file bugs because there weren't any open issues. Your diligence as a maintainer is impeccable!

**Comment by jeremyevans** [comment]
Well, it can be true for `many_to_one` in corner cases where the `many_to_one` doesn't reference an actual primary key and an order is used to get the first record, in which case the eager_graph result and the eager result can actually be different.  In any case, I don't think it would be a good idea to have different behavior in this area based on the association type(s).

This is the right place to file bugs, but as the contribution guide states, if you aren't sure if it is a bug, you should probably ask on the sequel-talk Google Group or IRC.
