### ISSUE TITLE
DB.extension and Sequel.extension

### ISSUE THREAD

**Issue by jnylen** [jeremyevans/sequel#1409]
Hi @jeremyevans,
Really love this gem.

I would want to recommend a way to notify users that plugins such as pg_json and pg_array should be in DB.extension rather than Sequel.extension as it took me a while to really understand why it didn't work.

Like raise an error about it or something on load through Sequel.extension.

**Comment by jeremyevans** [comment]
`DB.extension` calls `Sequel.extension`, so this is not possible.  The documentation informs users to use `DB.extension`.

**Comment by tindron** [comment]
The documentation could be more explicit.  The example shows `DB.extension` but the general extension docs imply `Sequel.extension` works for any extension.
