### ISSUE TITLE
Inaccurate error message when no migrations files exist

### ISSUE THREAD

**Issue by frank-west-iii** [jeremyevans/sequel#1417]
### Complete Description of Issue

When running migrations and [this line](https://github.com/jeremyevans/sequel/blob/21c557e0b50606bfd5d569324f5ffeac886fa897/lib/sequel/extensions/migration.rb#L529) is hit we will get an error message.

I think the intention is to have [this line](https://github.com/jeremyevans/sequel/blob/21c557e0b50606bfd5d569324f5ffeac886fa897/lib/sequel/extensions/migration.rb#L536) be hit before the comparison is made.

### Simplest Possible Self-Contained Example Showing the Bug

Running the sequel migratioin command with an empty migrations folder causes the issue.

`sequel -m db/migrations postgres://localhost/sequel_test`

### Full Backtrace of Exception (if any)

```
Error: NoMethodError: undefined method `>' for nil:NilClass
/Users/frank/.gem/ruby/2.4.1/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:529:in `initialize'
```

**Comment by frank-west-iii** [comment]
I just realized that when opening an issue from a context menu in the code view it does not use your issue template. I will adjust the issue contents when I am back at the desk.

**Comment by jeremyevans** [comment]
Thanks for reporting this.  We probably should just move the error check up.  I'll make that change shortly.
