### ISSUE TITLE
Default value of sslmode

### ISSUE THREAD

**Issue by limin8918** [jeremyevans/sequel#1426]
Hi, I got 2 questions of sslmode when connecting to db.
(1) I'm using sequel & pg in my Gemfile, what's the default value of sslmode ?  The code as below:
```
require 'sequel'
require 'pg'
DB = Sequel.postgres(
    'xxx',
    user: "user",
    password: "password",
    host: "my host",
    port: "9001"
    client_min_messages: false,
    force_standard_strings: false
)
```
So what's sslmode's default value ?

(2) I saw that sslmode can be set to 6 values in your Change log. 
```
:sslmode :: Set to 'disable', 'allow', 'prefer', 'require', 'verify-ca', or 'verify-full' to choose how to treat SSL (only respected if using the pg library)
```

But looks like pg only support 4 values: https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L246~L247

**Comment by jeremyevans** [comment]
Sequel doesn't set a default for :sslmode.  PostgreSQL/libpq will set a default value if one is not provided. I'm not sure what PostgreSQL's default is, but it is probably mentioned in the PostgreSQL documentation.

That's documentation, not code in ruby-pg, and apparently not up to date with recent PostgreSQL versions.  See the PostgreSQL documentation for the allowed values.

As mentioned in the contribution guidelines, questions about Sequel should be asked on the sequel-talk Google Group or IRC.  GitHub Issues should only be used to report a bug in the library.
