### ISSUE TITLE
Eager loading breaks in combination with def_column_alias

### ISSUE THREAD

**Issue by celsworth** [jeremyevans/sequel#1429]
I discovered that some of my associations were not returning the expected data, and believe it may be due to an interaction between eager loading and column aliases.

I put together a self contained example demonstrating this: https://gist.github.com/celsworth/e0cb97e3e1378cc135d308746e3fc9c1

The bug does not occur if eager loading isn't used, nor does it occur if there is no reciprocal association (try removing the `many_to_one` and making the necessary `Album.create` fix by adding the artist `.id`)

It also doesn't occur if the columns are named more sensibly, removing the need for the column aliasing, but unfortunately I'm stuck with that.

**Comment by jeremyevans** [comment]
This isn't a bug, you need to use the appropriate association options, see http://sequel.jeremyevans.net/rdoc/files/doc/association_basics_rdoc.html#label-Associations+Based+on+SQL+Expressions+Options

```ruby
Artist.one_to_many :albums, key: :artist, :key_method=>:artist_id
Album.many_to_one :artist, :key_column=>:artist
```

With those changes, here's the output for the final two queries:

```
I, [2017-10-03T07:56:57.991809 #44675]  INFO -- : (0.000119s) SELECT * FROM `artists` WHERE (`name` IN ('artist'))
I, [2017-10-03T07:56:57.992399 #44675]  INFO -- : (0.000106s) SELECT * FROM `albums` WHERE (`albums`.`artist` IN (1))
[#<Album @values={:id=>1, :name=>"album", :artist=>1}>]
I, [2017-10-03T07:56:57.993652 #44675]  INFO -- : (0.000099s) SELECT * FROM `artists` WHERE (`name` IN ('artist'))
I, [2017-10-03T07:56:57.994062 #44675]  INFO -- : (0.000102s) SELECT * FROM `albums` WHERE (`albums`.`artist` = 1)
[#<Album @values={:id=>1, :name=>"album", :artist=>1}>]
```
