### ISSUE TITLE
Sequel::DatabaseError SQLite3::BusyException: database is locked

### ISSUE THREAD

**Issue by chrisvel** [jeremyevans/sequel#1436]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
While trying to persist data to the database (sqlite3) with multiple processes, it fails with error: Sequel::DatabaseError SQLite3::BusyException: database is locked. I have found other (older) issues describing this but I didn't see a solution. I understand this can be a limitation of sqlite and If it does, please someone let me know so I can try using another kind of database.

**Comment by jeremyevans** [comment]
Yes, this is a limitation of SQLite, it's not optimized for use by multiple processes/threads at the same time.

In the future, as specified in the contribution guidelines, please ask questions like this on the sequel-talk Google Group or IRC.  GitHub Issues should only be used for reporting bugs in Sequel.
