### ISSUE TITLE
CLOB data on oracle adapter takes long time when reading it

### ISSUE THREAD

**Issue by MarioRuiz** [jeremyevans/sequel#1438]
### Complete Description of Issue
When reading data from Oracle if any of the columns contain CLOB data and calling the 'all' method to retrieve all data, takes a long time, 50 records... 9 seconds. 
In the exaxmple column1 is integer type and column2 is CLOB type but with nil content

### Simplest Possible Self-Contained Example Showing the Bug
start = Time.now
statement="SELECT column1, column2 FROM table where rownum < 50 "
res = @connection.fetch(statement)
puts res.all.inspect
puts (Time.now-start)

**Comment by jeremyevans** [comment]
Can you please post the adapter you are using (oracle or jdbc/oracle)?  As long as things work, this isn't considered a bug, but I'll see if it's possible to do any optimization.  Note that Sequel returns CLOB columns as strings, and it's possible that retrieving the CLOB values from Oracle is what is taking all of the time, since in general per-query overhead is high on Oracle.

**Comment by MarioRuiz** [comment]
I am using oracle adapter. The problem i guess is the time consumed to convert CLOB into strings

**Comment by jeremyevans** [comment]
I can't recreate the slowness you are seeing on my Oracle VM. Example code:

```ruby
require 'benchmark'

DB.create_table(:clob_test) do
  Integer :id
  clob :data
end

DB[:clob_test].import([:id], (0...50).map{|i| [i]})

puts Benchmark.measure{DB[:clob_test].all}

DB[:clob_test].update(:data=>'foo')

puts Benchmark.measure{DB[:clob_test].all}
```

Output:

```
  0.000000   0.000000   0.000000 (  0.028224)
  0.010000   0.000000   0.010000 (  0.032698)
```

Can you run the that code in your environment and let me know what the results are?

**Comment by MarioRuiz** [comment]
I don't have access to be able to do it

**Comment by jeremyevans** [comment]
Then I think this can be closed, since it doesn't appear to be a bug in Sequel.

**Comment by MarioRuiz** [comment]
Well exactly the same query run directly with oci8 takes less than 3 seconds

conn = OCI8.new('user/pwd@//111.333.333.333:1521/xe')
start = Time.now
res=[]
conn.exec("SELECT column1, column2 FROM table where rownum < 50") do |r|
  res.push r
end
puts res.inspect
puts (Time.now-start)

So I guess is something related to sequel

**Comment by jeremyevans** [comment]
I don't see there where you are reading the clob values.

**Comment by MarioRuiz** [comment]
Here sorry:
conn = OCI8.new('user/pwd@//111.333.333.333:1521/xe')
start = Time.now
res=[]
conn.exec("SELECT column1, column2 FROM table where rownum < 50") do |r|
res.push([r[0],r[1].read])
end
puts res.inspect
puts (Time.now-start)

**Comment by jeremyevans** [comment]
I'm not seeing a significant performance difference between doing this directly and through Sequel.  Example code:

```ruby
DB.create_table!(:clob_test) do
  Integer :id
  clob :data
end

DB[:clob_test].import([:id, :data], (0...50).map{|i| [i, 'foo']})
conn = DB.synchronize{|c| c}

puts(Benchmark.measure do
  100.times do
    res=[]
    conn.exec("SELECT id, data FROM clob_test") do |r|
      res.push([r[0],r[1].read])
    end
    res
  end
end)

puts Benchmark.measure{100.times{DB[:clob_test].all}}
```

Results (each benchmark run 3 times, lowest time shown):

```
  0.290000   0.190000   0.480000 (  1.161483) # direct
  0.350000   0.180000   0.530000 (  1.206919) # Sequel
```

**Comment by MarioRuiz** [comment]
Thanks anyway... if I found out the reason I'll let you know
