### ISSUE TITLE
copy_table raises Sequel::DatabaseDisconnectError with string argument

### ISSUE THREAD

**Issue by csuhta** [jeremyevans/sequel#1439]
### Complete Description of Issue

sequel_pg 1.8.0
sequel 5.1.0
Ruby 2.4.2
Postgres 10.0

Passing a string SQL literal for the first argument of `Database#copy_table` results in Postgres erring with `no COPY in progress`.

Passing a `:table_name` as a symbol or passing a `Dataset` works without any issues.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
class PricePoint < Sequel::Model
end
```

```ruby
DB.copy_table("SELECT * FROM price_points LIMIT 10", format: :csv, options: "HEADER true")
# Sequel::DatabaseDisconnectError: PG::Error: no COPY in progress
# from /Users/Me/.gem/ruby/2.4.2/gems/sequel-5.1.0/lib/sequel/adapters/postgres.rb:338:in `get_copy_data
```

```ruby
DB.copy_table(Sequel.lit("SELECT * FROM price_points LIMIT 10"), format: :csv, options: "HEADER true")
# Sequel::DatabaseDisconnectError: PG::Error: no COPY in progress
# from /Users/Me/.gem/ruby/2.4.2/gems/sequel-5.1.0/lib/sequel/adapters/postgres.rb:338:in `get_copy_data
```

```ruby
DB.copy_table(PricePoint.limit(10), format: :csv, options:"HEADER true")
#=> returns the correct CSV string
```

**Comment by jeremyevans** [comment]
If the first argument is a string, it should be a complete COPY statement, and you shouldn't try to use options that affect the SQL Sequel would generate (such as :format and :options):

```ruby
DB.copy_table("COPY (SELECT * FROM price_points LIMIT 10) TO STDOUT (FORMAT csv, HEADER true)")
```

It looks like the documentation doesn't make that explicit, I'll fix the documentation.

**Comment by csuhta** [comment]
Ah! I did indeed misunderstand what kind of SQL was needed. 🙂

Thanks for the very quick turnaround.
