### ISSUE TITLE
Collate information not dumped in schema

### ISSUE THREAD

**Issue by sdalu** [jeremyevans/sequel#1444]
Dumping schema doesn't dump collate information for database supporting it (I'm using mysql2)

~~~ruby
DB.dump_schema_migration(same_db: true)
~~~

For example with the following database
~~~sql
CREATE DATABASE  `toto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `categories_for_recipes` (
  `group` varchar(16) CHARACTER SET ascii DEFAULT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
~~~

Got
~~~ruby
    create_table(:categories_for_recipes) do
      column :group, "varchar(16)"
    end
~~~

Would like
~~~ruby
    create_table(:categories_for_recipes) do
      column :group, "varchar(16)", :collate=>"ascii_general_ci"
   end
~~~

**Comment by jeremyevans** [comment]
This isn't a bug.  Dumping schema doesn't dump lots of things, such as triggers, and database function defaults.  If you want a dump that includes everything, use the database dump tools.

That said, I'm not opposed to adding collation support to the schema dumper.  If you would like it added, you'll need to submit a pull request that adds support for it, including integration tests that work correctly on all databases that Sequel supports that support collations.
