### ISSUE TITLE
postgresql 10 breaks sequence handling

### ISSUE THREAD

**Issue by darix** [jeremyevans/sequel#1445]
While investigating my pg10 issues in [seed-fu](https://github.com/mbleigh/seed-fu/issues/122)

I noticed sequel has similar code in:

```
lib/sequel/adapters/shared/postgres.rb
512:        get{setval(seq, db[table].select{coalesce(max(pk)+seq_ds.select{:increment_by}, seq_ds.select(:min_value))}, false)}
```

This no longer works in postgresql 10. I think it is related to:

```
Move sequences' metadata fields into a new pg_sequence system catalog (Peter Eisentraut)

A sequence relation now stores only the fields that can be modified by nextval(), that is last_value, log_cnt, and is_called. Other sequence properties, such as the starting value and increment, are kept in a corresponding row of the pg_sequence catalog. ALTER SEQUENCE updates are now fully transactional, implying that the sequence is locked until commit. The nextval() and setval() functions remain nontransactional.

The main incompatibility introduced by this change is that selecting from a sequence relation now returns only the three fields named above. To obtain the sequence's other properties, applications must look into pg_sequence. The new system view pg_sequences can also be used for this purpose; it provides column names that are more compatible with existing code.

The output of psql's \d command for a sequence has been redesigned, too.
```

https://www.postgresql.org/docs/10/static/release-10.html

In worst a check on PG::Conn#server_version could be used.

**Comment by darix** [comment]
https://meta.discourse.org/t/discourse-appears-to-be-broken-with-postgres-10/71723

**Comment by radar** [comment]
I think I can reproduce an issue here, but only with Sequel 5.2.0, not the master version.

Here's some steps:

1. `createdb sequel_1445`

2. This Ruby script:

```ruby
require 'sequel'
db = Sequel.postgres "sequel_1445"
db.create_table!(:test) { primary_key(:id) }
db.reset_primary_key_sequence(:test)
```

**Comment by jeremyevans** [comment]
I fixed this issue yesterday (before this issue was posted) in 8370980b12f59d5439344d4de89d4552f05a3d13.  This was the only part of Sequel's tests that broke when run on PostgreSQL 10.

I usually test with PostgreSQL beta/rc versions so this type of thing is caught before the final release, but I was busy this year and didn't have time to do so.  Sorry about that.
