### ISSUE TITLE
SQLite3::BusyException: database is locked (Sequel::DatabaseError)

### ISSUE THREAD

**Issue by maxiedaniels** [jeremyevans/sequel#1446]
I've seen this bug mentioned in a 2011 bug report, but it was fixed then, so I'm wondering if this is something else..

I'm running a single ruby program that uses a thread pool (40 threads) which are adding data to a sqlite3 database. I'm getting this 'database is locked' error after ~10-15 seconds of running my program.

The thing is, there should only be one db connection, since my Sequel.sqlite(...) command is at the beginning of my program, far before any thread pool code starts.. so what would cause this?

**Comment by jeremyevans** [comment]
40 concurrent readers on an SQLite database is probably OK.  40 concurrent writers is not a use case SQLite was designed to handle.   See  https://sqlite.org/whentouse.html.

This isn't a Sequel issue, this is an SQLite issue, the error message comes from SQLite, not Sequel (a Sequel error would be a Sequel::PoolTimeout).

**Comment by maxiedaniels** [comment]
To clarify - I was under the impression Ruby isn't truly concurrent, so wouldn't writes using Sequel not be concurrent?

**Comment by jeremyevans** [comment]
CRuby is concurrent, though the doesn't execute separate threads in parallel (concurrency is not parallelism).

If you really think this is a Sequel issue, try running similar code without Sequel using the ruby-sqlite3 driver directly and see if you get a different result.
