### ISSUE TITLE
identifier/Fixnum order matters in `where {}` comparison operations

### ISSUE THREAD

**Issue by mreca89** [jeremyevans/sequel#1447]
### Complete Description of Issue
Order should not matter but it does here:
MyModel.where{id > 10} -> works
MyModel.where{10 < id} -> fails with following error

### Simplest Possible Self-Contained Example Showing the Bug
require 'sequel'
DB = Sequel.sqlite # memory database, requires sqlite3
DB.create_table :testing do
  primary_key :id
  Integer :myval
end
MyModel = DB[:testing]
MyModel.where{myval < 10} # works
MyModel.where{10 > myval} #fails

### Full Backtrace of Exception (if any)
ArgumentError: comparison of Fixnum with Sequel::SQL::Identifier failed
from (pry):10:in `<'

### SQL Log (if any)
N/A

**Comment by jeremyevans** [comment]
This is expected behavior.  You can do `MyModel.where{Sequel[10] > myval}` if for some reason you must have the number on the left hand side.

**Comment by janko-m** [comment]
@jeremyevans I'm curious, why does the following work?

```rb
10 < Sequel::SQL::Identifier.new(:id)
#<Sequel::SQL::BooleanExpression @op=>:<, @args=>[#<Sequel::SQL::NumericExpression @op=>:NOOP, @args=>[10]>, #<Sequel::SQL::Identifier @value=>:foo>]>
```

I know that it works because `Sequel::SQL::Identifier` has `#coerce` method defined, I'm just curious why isn't then `#coerce` also activated inside the virtual row block. Isn't it the same thing? 🤔

**Comment by jeremyevans** [comment]
Actually, I tested and the original code works correctly with the current version of Sequel:

```
irb(main):001:0> require 'sequel'
=> true
irb(main):002:0> DB = Sequel.sqlite # memory database, requires sqlite3
=> #<Sequel::SQLite::Database: {:adapter=>:sqlite}>
irb(main):003:0> DB.create_table :testing do
irb(main):004:1* primary_key :id
irb(main):005:1> Integer :myval
irb(main):006:1> end
=> nil
irb(main):007:0> MyModel = DB[:testing]
=> #<Sequel::SQLite::Dataset: "SELECT * FROM `testing`">
irb(main):008:0> MyModel.where{myval < 10} # works
=> #<Sequel::SQLite::Dataset: "SELECT * FROM `testing` WHERE (`myval` < 10)">
irb(main):009:0> MyModel.where{10 > myval} #fails
=> #<Sequel::SQLite::Dataset: "SELECT * FROM `testing` WHERE (10 > `myval`)">
```

I'm guessing @mreca89 is using an old version before I added support for `#coerce`, in which case wrapping with `Sequel[]` is the easiest fix.
