### ISSUE TITLE
Dataset#select_hash and #as_hash unexpectedly return nil on nullified datasets

### ISSUE THREAD

**Issue by chanks** [jeremyevans/sequel#1457]
I put a bit of effort into crafting a PR for this, but I couldn't reproduce it in the specs. I wonder if there's something I'm missing about the DB mocking, or if this is something Postgres-specific.

```ruby
require "sequel"

puts Sequel::VERSION #=> "5.3.0"

DB = Sequel.connect("postgres:///scrap")

DB.extension :null_dataset

DB.create_table :test_table do
  primary_key :id
  text :column
end

DB[:test_table].insert(column: "a")
DB[:test_table].insert(column: "b")

DB[:test_table].as_hash(:id, :column) #=> {1=>"a", 2=>"b"}, expected
DB[:test_table].nullify.as_hash(:id, :column) #=> nil, unexpected! Expected an empty hash!
```

Thanks!

**Comment by jeremyevans** [comment]
This is not an issue in Sequel, but in sequel_pg (set the NO_SEQUEL_PG=1 environment variable to check).  The fix in sequel_pg is fairly simple, I'll commit it soon.

**Comment by jeremyevans** [comment]
Fixed by https://github.com/jeremyevans/sequel_pg/commit/86f8c3947df36f7a433d6ba8895d3acad0db21b3
