### ISSUE TITLE
Database#indexes calls not cached / memoized

### ISSUE THREAD

**Issue by kenaniah** [jeremyevans/sequel#1460]
I feel this might be part bug & part feature, but the `:schema_caching` extension does not dump or load index metadata, which causes metadata queries for each model at startup when loading the `:auto_validations` plugin.

My understanding is that models memoize their schema in `@schemas` of the `Database` instance, but table index information is not memoized as each adapter will repeat the query if `Database#indexes` is called twice with the same args, and `:auto_validations` calls `Database#indexes` when plugged in.

What are your thoughts on memoizing the results of `Database#indexes` on an `@indexes` variable, and also adding that to the `:schema_caching` plugin?

**Comment by kenaniah** [comment]
Closing per project guidelines, but would still like to discuss.

**Comment by jeremyevans** [comment]
Discussions about development changes should generally happen on the sequel-talk Google Group.

I don't think I wan't this as default behavior for backwards compatibility reasons, but an index_caching extension that supports the caching of `Database#indexes` is acceptable.  You need to be  careful to modify the cache as appropriate when the the schema methods that could modify index information are called.  If options are given to the call `#indexes`, the cache should probably be ignored.  This extension could also support the dumping and loading of index caches from a file, similar to the `schema_caching` extension.
