### ISSUE TITLE
Possible to enable WAL on Sqlite3 databases?

### ISSUE THREAD

**Issue by maxiedaniels** [jeremyevans/sequel#1473]
I have two scripts running, one that connections to the database and frequently adds information to it, and then a separate script that reads from database periodically. However, the script that reads is only ever returning the data that was present when it first connected - it won't show new database information. It seems this is due to SQLite3 behavior of writes locking the database file. From StackOverflow:

> First, by default, multiple processes can have the same SQLite database open at the same time, and several read accesses can be satisfied in parallel.
> 
> In case of writing, a single write to the database locks the database for a short time, nothing, even reading, can access the database file at all.
> 
> Beginning with version 3.7.0, a new “Write Ahead Logging” (WAL) option is available, in which reading and writing can proceed concurrently.
> 
> By default, WAL is not enabled. To turn WAL on, refer to the SQLite documentation.

 I got around this by using a connection block on the second script and making sure to have delay before the block triggers again. However, I need my secondary script to maintain a connection, and therefore it seems I need to enable WAL. Is there any way to do so with the Sequel gem?

**Comment by jeremyevans** [comment]
You would first have to figure out how to enable it via ruby-sqlite3 directly, and then use an :after_connect block to apply those changes to each connection.

Note that as explained in the contribution guidelines:

```
1) Issues should only be created for things that are definitely bugs.
   If you are not sure that the behavior is a bug, ask about it on
   IRC or the sequel-talk Google Group.  GitHub Issues should not be
   used as a help forum.
```

The issue template says this right at the top:

```
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.
```

Please use the sequel-talk Google Group or IRC for support questions in the future.  Only file an issue on GitHub if you have found a bug in Sequel itself.

**Comment by maxiedaniels** [comment]
Sorry! Was just closing this now to repost on sequel-talk. Apologies.
