### ISSUE TITLE
db.indexes method not showing `full_text` indexes

### ISSUE THREAD

**Issue by okliv** [jeremyevans/sequel#1476]
### Complete Description of Issue

In my postgres db i have a table with a text type field - `description`. i altered this table with

    db.alter_table(name) do
      add_index [:description], type: :full_text
    end

It created an index with GIN type and fields like this

`to_tsvector('simple'::regconfig, COALESCE(description, ''::text))`

like i expected but now if i call `db.indexes(:my_table)` i can see all `btree` indexes (created with `add_index [:any_other_field_name]`) but not this one... 

(the sequel version is 4.49.0)

**Comment by jeremyevans** [comment]
This is expected, as full text indexes are indexes on expressions, not on simple columns, and `Database#indexes` only returns indexes on columns.

You'll notice that the hashes returned by  `Database#indexes` have a key for `:columns`, which wouldn't make sense for expression indexes.

**Comment by okliv** [comment]
any advice how can i list indexes like this? thanks

**Comment by jeremyevans** [comment]
You'll have to use database-specific code.  You should consult the documentation for the database you are using.

**Comment by okliv** [comment]
raw sql... what can be better )

i would suggest to rename 'indexes' method, maybe... it can be something like 'columns_indexes'. current method name gives... ammm... some kind of "unjustified hopes" 🤕

**Comment by jeremyevans** [comment]
Unfortunately, that would break backwards compatibility.  The documentation does state that `Database#indexes` doesn't include functional indexes (http://sequel.jeremyevans.net/rdoc/files/doc/reflection_rdoc.html#label-Indexes+on+a+table).
