### ISSUE TITLE
assigned but unused variable - ms

### ISSUE THREAD

**Issue by sandelius** [jeremyevans/sequel#1480]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
First I know Sequel don't "care" about ruby warnings like `unused variable` etc. But I think this might be something to look at.

In 5.6 I get a warning `assigned but unused variable - ms`. I looked it up and in that method sequel calls `ms = Migration.descendants` but the `ms` variable  isn't used at all in that method. Any reasons for this?

`sequel/extensions/migration.rb:739`

### Simplest Possible Self-Contained Example Showing the Bug
Run migrations

**Comment by jeremyevans** [comment]
Thanks for the heads up. That line can be deleted now.  It was needed before 5.6.0, but with the refactoring to the migrator in 5.6.0 to make it thread safe, it's no longer needed.  I'll commit a fix shortly.
