### ISSUE TITLE
Oracle PGA leak on temporary CLOBs

### ISSUE THREAD

**Issue by hlira** [jeremyevans/sequel#1482]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
When using jdbc with Oracle, if the query returns a temporary CLOB, eg, using XmlType.getClobVal(), the connection leak PGA Memory on Oracle instance.
According Oracle documentation the jdbc client must test if the CLOB returned is temporary and free it.
Oracle jdbc driver includes two functions for that: clob.isTemporary() and clob.freeTemporary()

http://download.oracle.com/otn_hosted_doc/jdeveloper/905/jdbc-javadoc/oracle/sql/CLOB.html#isTemporary()

**Comment by jeremyevans** [comment]
Thanks for the report.  I'll try to implement a fix for this soon.
