### ISSUE TITLE
Sequel.connect not respecting pool_timeout

### ISSUE THREAD

**Issue by abhimehta** [jeremyevans/sequel#1485]
I am connecting a PG10 db with

```DB = Sequel.connect("jdbc:#{adapter}://#{host}:#{port}/#{database}?user=#{user}&password=#{password}", :max_connections=>10, :pool_timeout=>60)```

System Info:
`jruby-9.1.14.0 [ x86_64 ]`
`sequel (5.5.0)`

In case of db connection failure, the timeout is not happening in the time specified at `pool_timeout`

Sample Code
```
start_time = Time.now
p "StartTime: #{start_time}"

begin
  DB = Sequel.connect("jdbc:#{adapter}://#{host}:#{port}/#{database}?currentSchema=assignments&user=#{user}&password=#{password}", :max_connections=>5, :pool_timeout=>60)

  DB.extension :pg_array, :pg_json, :pg_row
rescue => e
  end_time = Time.now
  p "EndTime: #{end_time}"
  p "Exception Class: #{e.class}"
  p "Exception Message: #{e.message}"
  p 'Error connecting to DB'
  p "Connection Failed after: #{end_time - start_time}"
end
```

Response:
```
StartTime: 2018-03-23 13:28:45 -0700
EndtTime: 2018-03-23 13:31:16 -0700
Exception Class: Sequel::DatabaseConnectionError
Exception Message:  Java::OrgPostgresqlUtil::PSQLException: Connection to data-store.abcd.us-east-3.rds.amazonaws.com:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Error connecting to DB
Connection Failed after: 151.158
```

Can you please help me understand if this is a valid scenario for using `pool_timeout`?
If yes, is this a bug?
If no, what is the right way to handle this?

Thank You

**Comment by jeremyevans** [comment]
:pool_timeout is not what you want.  That's the timeout to check out a connection from the connection pool, not the time to make a new connection.  You are using the jdbc adapter, so you probably want to use :login_timeout (see http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-jdbc+)
