### ISSUE TITLE
Irreversible `extension` method in migrations (`date_arithmetic`)

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/sequel#1488]
### Complete Description of Issue

I'm using [migrations from a Rake task](https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc#running-migrations-from-a-rake-task), and got `irreversible migration method used` with `extension :date_arithmetic`.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
# frozen_string_literal: true

Sequel.migration do
  change do
    extension :date_arithmetic

    create_table :keys do
      primary_key :id

      String :key, null: false

      timestamptz(
        :deadline,
        null: false,
        default: Sequel.date_add(Sequel::CURRENT_TIMESTAMP, days: 14)
      )
    end
  end
end
```

### Full Backtrace of Exception (if any)

```
I, [2018-03-30T18:59:40.022537 #31599]  INFO -- : (0.000277s) SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
I, [2018-03-30T18:59:40.022734 #31599]  INFO -- : (0.000104s) SELECT * FROM "schema_migrations" LIMIT 1
I, [2018-03-30T18:59:40.023238 #31599]  INFO -- : (0.000403s) SELECT "filename" FROM "schema_migrations" ORDER BY "filename"
I, [2018-03-30T18:59:40.024036 #31599]  INFO -- : Begin applying migration 201803301833_add_account_unsubscribe_keys.rb, direction: down
I, [2018-03-30T18:59:40.024137 #31599]  INFO -- : (0.000041s) BEGIN
I, [2018-03-30T18:59:40.024244 #31599]  INFO -- : (0.000039s) ROLLBACK
rake aborted!
Sequel::Error: irreversible migration method used, you may need to write your own down method
/path/to/Rakefile:274:in `block (3 levels) in <top (required)>'
```

### SQL Log (if any)

No.

**Comment by jeremyevans** [comment]
Just use up/down migrations instead of change migrations in cases where an irreversible migration method is used.

**Comment by AlexWayfer** [comment]
> Just use up/down migrations instead of change migrations in cases where an irreversible migration method is used.

Yes. I just thought that `extension` (at least with `:date_arithmetic` parameter) is not dangerous for reverse migration.

OK.

**Comment by jeremyevans** [comment]
Supporting `extension` would introduce additional complexity, since if it was executed in reverse order, there are cases where it wouldn't work correctly (not this particular case, since `date_add` is not called when migrating down).  Plus it opens up the slippery slope for adding other features to reversible migrations, and I don't want to do that.
