### ISSUE TITLE
bigserial primary keys broken

### ISSUE THREAD

**Issue by phyrog** [jeremyevans/sequel#1490]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

The 5.7 update in combination with Postgres 10 broke primary key columns with type `bigserial`, as it will try to generate an identity column with type `bigserial`.

We can't switch to `bigint` with identity because the server will still run Postgres 9.6, so we need a solution that works for both versions.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'
require 'logger'

DB = Sequel.connect(adapter: :postgres, user: 'postgres', password: 'postgres',
  database: 'sequel_test', logger: Logger.new(STDOUT))

DB.create_table :as do
  primary_key :id, type: :bigserial
end
```

### Full Backtrace of Exception (if any)

```
Traceback (most recent call last):
	18: from test.rb:7:in `<main>'
	17: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/database/schema_methods.rb:187:in `create_table'
	16: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/database/schema_methods.rb:674:in `create_table_from_generator'
	15: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/database/query.rb:43:in `execute_ddl'
	14: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/database/query.rb:50:in `execute_dui'
	13: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:274:in `execute'
	12: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/database/connecting.rb:269:in `synchronize'
	11: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	10: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:274:in `block in execute'
	 9: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:478:in `check_database_errors'
	 8: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:274:in `block (2 levels) in execute'
	 7: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:456:in `_execute'
	 6: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:134:in `execute'
	 5: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:110:in `check_disconnect_errors'
	 4: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:134:in `block in execute'
	 3: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:146:in `execute_query'
	 2: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
	 1: from /home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:146:in `block in execute_query'
/home/tom/.gem/ruby/2.5.0/gems/sequel-5.7.0/lib/sequel/adapters/postgres.rb:146:in `async_exec': PG::SyntaxError: ERROR:  both default and identity specified for column "id" of table "as" (Sequel::DatabaseError)
```

### SQL Log (if any)

```
ERROR:  both default and identity specified for column "id" of table "as": CREATE TABLE "as" ("id" bigserial GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)
```

The problem seems to be https://github.com/jeremyevans/sequel/blob/16266d7f93dc991676d03ab5c96b3997f9b150e7/lib/sequel/adapters/shared/postgres.rb#L601 where `identity` is set to `true` regardless of the column type.

**Comment by jeremyevans** [comment]
I agree this is a bug, and a regression.  The best work around is using `:type=>:Bignum`, as that's the standard way in Sequel to get an autoincrementing 64-bit primary key.

I'm not sure what the issue is with supporting both PostgreSQL 10 and 9.6.  If you use  `:type=>:Bignum` run a migration on 9.6, you'll get a bigserial column, and if you run it on 10 you'll get a bigint identity column, but the behavior should be more or less the same.  Can you explain what the problem is there?

As this is a regression from the previous release, it meets the criteria to release a new gem with the fix. Please let me know if you would like me to do that after fixing this.

**Comment by phyrog** [comment]
I'm getting a null-constraint violation when using `bigint`, though in hindsight that might be caused by something different. A new release would be much appreciated, otherwise we would downgrade to 5.6 for the time being.

Thanks for the quick response and fix!

**Comment by jeremyevans** [comment]
Sequel 5.7.1 has been released with this fix.
