### ISSUE TITLE
Add logger in rake task

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1504]
I think see SQL which executed when run migration is import for debug.

but, in [verbose-migrations](https://github.com/jeremyevans/sequel/blob/master/doc/migration.rdoc#verbose-migrations) doc, no see relative content.

so, i think here should be a example for clarify, Add following into rake task:

```rb
# ...

db = Sequel.connect(@db_str)

# Add this line into rake task
db.loggers << Logger.new($stdout)

# ...
```

**Comment by jeremyevans** [comment]
This sounds OK to me, though I'll probably just use the Database :logger option.  I'll update the documentation today or tomorrow.
