### ISSUE TITLE
Sequel::SQL::Expression `==`, `eq?` not worked as expect?

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1505]
From my aspect, I think following three form is equal.

```rb
FeedMedia.where(feed_id: 300)

FeedMedia.where(Sequel[:feed_id] == '300')

FeedMedia.where(Sequel[:feed_id].eq? '300')
```

But, later two form return SQL not as expect

```rb
(pry):0> FeedMedia.where(Sequel[:feed_id] == '300').explain
I, [2018-04-30T22:32:24.446051 #12350]  INFO -- : (0.118600s) EXPLAIN SELECT * FROM `feed_medias` WHERE 0
```

**Comment by jeremyevans** [comment]
This is expected.  #== and #eq? are not overridden, as it would make usage of the objects in general more difficult (think normal Ruby comparison).  You can use #=~ if you don't want to use a hash.

**Comment by zw963** [comment]
OK, thanks, though, this missing some consistency.

And,  AFAIK (from the ruby programming language book), #== and #eq? could be override, and should be override for special purpose, but, never override equal?

**Comment by jeremyevans** [comment]
It is possible to override #== and #eq?, that doesn't make it a good idea.  What if you want to check whether to Sequel::SQL::Identifier objects represent the same identifier in ruby?  #equal? is not appropriate in that case, as it checks identity, not equality.

**Comment by zw963** [comment]
I think i understood, thank very much.
