### ISSUE TITLE
Sequel mySQL db schema dump Integer to Bignum

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1506]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

I have one table, named `activities`, have a id column, which is  primary key.
i could see this column type is:  `int(10) unsigned`, it should  be a `Integer` column.

### Simplest Possible Self-Contained Example Showing the Bug

```sh

mysql> describe activities;
+-----------------+------------------+------+-----+-------------------+-----------------------------+
| Field           | Type             | Null | Key | Default           | Extra                       |
+-----------------+------------------+------+-----+-------------------+-----------------------------+
| id              | int(10) unsigned | NO   | PRI | NULL              | auto_increment              |
```

After i dump database schema into a file, e.g.  db/schema.rb

```rb
task :dump => :create_db_conn do |task, args|
      sh "bundle exec sequel -d #{@db_str}"
 end
```

we got error schema:
```rb
   create_table(:activities, :ignore_index_errors=>true) do
      primary_key :id, :type=>:Bignum    # <== we expect this type is Integer.
      # ...
   end
```

if use raw format:

```rb
desc 'Dump current database tables for mysql only'
    task :dump_mysql => :create_db_conn do |task, args|
      sh "bundle exec sequel -D #{@db_str}"
    end
```

We got the correct result

```rb
create_table(:activities) do
      primary_key :id, :type=>"int(10) unsigned"
     # ....
end
```

MySQL version:
```sh
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
```

**Comment by zw963** [comment]
sequel 5.2.0

**Comment by utilum** [comment]
This is expected behaviour. What is the use case you have in mind, negative ids ?

**Comment by zw963** [comment]
@utilum , 

Maybe i misunderstood somethings ...

why `int(10) unsigned` is `Bignum` ??

If this is `Bignum`,  after this migration is rerun in my local mysql database, 
i got following `bigint(20)` type:


```sh
+-----------------+--------------+------+-----+-------------------+----------------+
| Field           | Type         | Null | Key | Default           | Extra          |
+-----------------+--------------+------+-----+-------------------+----------------+
| id              | bigint(20)   | NO   | PRI | NULL              | auto_increment |

```

**Comment by jeremyevans** [comment]
As @utilum stated, this is expected behavior. If you are restoring to MySQL, use the `-D` flag instead of the `-d` flag to use the actual database type.  For other databases, they may not support an unsigned 32-bit integer type, so a 64-bit integer type is used to make sure it can hold the full range of values.
