### ISSUE TITLE
Effect of sorting of keys in create_join_table on name and index

### ISSUE THREAD

**Issue by yb66** [jeremyevans/sequel#1516]
Hi Jeremy,

### Complete Description of Issue

I noticed that `create_join_table` names the table alphabetically, e.g.

     create_join_table(  user_id: :users, team_id: :teams )

will create a table called `teams_users` when I expected `users_teams`.

[This line](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/schema_methods.rb#L113) sorts the keys.

```
def create_join_table(hash, options=OPTS)
      keys = hash.keys.sort
```

I'm wondering if either the docs should be updated to mention this, as the example given is already sorted (cats and dogs) so it's not obvious, or, to change the method so the keys aren't sorted.

I lean towards not sorting the keys for 2 reasons:

1. Mainly because if I write it one way the accompanying `down` statement in a migration is likely to be written to mirror the order, e.g. `drop_table :users_teams`.
2. A [composite primary key is created](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/schema_methods.rb#L123) and order may matter (this may be old info that's still in my head so let me know if I'm wrong). There may some other reason for the sort that I'm unaware of. Looking at the code I notice there's [an index of the reverse name order created](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/schema_methods.rb#L124) so perhaps this isn't an issue.

I can add the `name` option but that was fiddly to get right and starts getting ugly quickly, even without extra options:

    create_join_table({ 
        user_id: :users,
        team_id: :teams,
      },
       name: :users_teams
    )

Either way, I'm happy to add the note/remove the sort, I wanted to get your thoughts first.

Regards,
iain

### Simplest Possible Self-Contained Example Showing the Bug

    create_join_table(  cat_id: :cats, dog_id: :dogs )

produces the same table as

    create_join_table(  dog_id: :dogs, cat_id: :cats )

**Comment by jeremyevans** [comment]
This is expected, because the sorted table name is the default table name that Sequel::Model will use for join tables for many_to_many associations.  Not to mention changing it would break backwards compatibility.

**Comment by yb66** [comment]
Hi,

That's fine, I'm just wondering if a note in the method docs would be nice?

Regards,
iain

**Comment by jeremyevans** [comment]
You are correct, the current documentation does not mention this.  I'll fix that shortly.
