### ISSUE TITLE
When multiple associations share a key column, setting one can erroneously clear the other from the cache

### ISSUE THREAD

**Issue by chanks** [jeremyevans/sequel#1521]
I have a parent model, a child model that references it, and a second child model that references both the parent and the first child. The second child model's two associations both use the parent's foreign key, and it seems that this means that setting one association clears the other (I suspect Sequel is being proactive in clearing the association cache when an involved foreign key is touched, but doesn't realize that this is unnecessary because the foreign key isn't being changed).

Complete reproduction:
```ruby
require 'sequel'

DB = Sequel.sqlite

DB.create_table :parents do
  integer :parent_id, primary_key: true
end

DB.create_table :first_children do
  integer :parent_id
  integer :first_child_id

  primary_key [:parent_id, :first_child_id]
  foreign_key [:parent_id], :parents
end

DB.create_table :second_children do
  integer :parent_id
  integer :second_child_id
  integer :first_child_id

  primary_key [:parent_id, :second_child_id]
  foreign_key [:parent_id], :parents
  foreign_key [:parent_id, :first_child_id], :first_children
end

class Parent < Sequel::Model
  unrestrict_primary_key
  one_to_many :first_children
end

class FirstChild < Sequel::Model
  unrestrict_primary_key
  set_primary_key [:parent_id, :first_child_id]
  many_to_one :parent
end

class SecondChild < Sequel::Model
  unrestrict_primary_key
  set_primary_key [:parent_id, :second_child_id]
  many_to_one :parent
  many_to_one :first_child, primary_key: [:parent_id, :first_child_id], key: [:parent_id, :first_child_id]
end

p = Parent.create(parent_id: 1)
#=> #<Parent @values={:parent_id=>1}>
fc = FirstChild.create(parent: p, first_child_id: 1)
#=> #<FirstChild @values={:parent_id=>1, :first_child_id=>1}>
sc = SecondChild.new(parent: p, second_child_id: 1)
#=> #<SecondChild @values={:parent_id=>1, :second_child_id=>1}> 

sc.associations
#=> {:parent=>#<Parent @values={:parent_id=>1}>}
# (correct)

sc.first_child = fc
sc.associations
#=> {:first_child=>#<FirstChild @values={:parent_id=>1, :first_child_id=>1}>}
# (the parent association has been erroneously/unnecessarily cleared)

sc.parent = p
sc.associations
#=> {:parent=>#<Parent @values={:parent_id=>1}>} 
# (now it's happened to the first_child association)
```

Thank you!

**Comment by jeremyevans** [comment]
The reason you are seeing this behavior is you have `SecondChild.new` instead of `SecondChild.create`.  Sequel's behavior for changed column values is to always consider column values changed if the instance has not yet been persisted.  And Sequel's behavior for many_to_one associations is to clear cached associations whenever the related key values are changed.

It is possible to modify the associations code to check whether the instance has not been persisted and double check whether the value is actually different:

```
diff --git a/lib/sequel/model/associations.rb b/lib/sequel/model/associations.rb
index 3a4c5835b..65f370818 100644
--- a/lib/sequel/model/associations.rb
+++ b/lib/sequel/model/associations.rb
@@ -2400,7 +2400,12 @@ module Sequel
         # If a foreign key column value changes, clear the related
         # cached associations.
         def change_column_value(column, value)
-          if assocs = model.autoreloading_associations[column]
+          if new?
+            vals = @values
+            skip = true unless !vals.include?(column) || value != (c = vals[column]) || value.class != c.class
+          end
+
+          if !skip && (assocs = model.autoreloading_associations[column])
             assocs.each{|a| associations.delete(a)}
           end
           super
```

Kind of ugly though.  Doesn't break any tests, so it should be safe.  Do you think we should do that?

**Comment by chanks** [comment]
Ah! Interesting. :thinking: 

I agree that it's a little ugly - it seems to me that changing the behavior of `change_column_value` would be preferable. Considering the case:

```ruby
u = User.new
u.name = "Jeremy"
u.name = "Jeremy"
```

The behavior I'd expect here would be that `change_column_value` would be called the first time but not the second. That's a more significant change and may break backwards compatibility, though.

**Comment by chanks** [comment]
Also, just as an aside, I don't see the point of the explicit class check (`value.class != c.class`) if the values are already known to be unequal? Have you found that necessary in the past?

**Comment by jeremyevans** [comment]
I think the reason we don't check against existing values if the object hasn't yet been persisted is that it generally doesn't matter and causes unnecessary work.

And the `value.class != c.class` is checked when the values are equal, not when they are unequal.  Basically, if the values are equal but the class differs, still consider the column changed.  That's just copied from the general change column logic, I'm not sure how important it is for this particular case.

Performance wise, it's probably best to only do the checking if we would be clearing an association:

```
diff --git a/lib/sequel/model/associations.rb b/lib/sequel/model/associations.rb
index 3a4c5835b..874f93293 100644
--- a/lib/sequel/model/associations.rb
+++ b/lib/sequel/model/associations.rb
@@ -2401,6 +2401,11 @@ module Sequel
         # cached associations.
         def change_column_value(column, value)
           if assocs = model.autoreloading_associations[column]
+            if new?
+              vals = @values
+              return super unless !vals.include?(column) || value != (c = vals[column]) || value.class != c.class
+            end
+
             assocs.each{|a| associations.delete(a)}
           end
           super
```

**Comment by chanks** [comment]
Alright, that makes sense, and I’m certainly happy with that change to the
associations logic if you are.

**Comment by chanks** [comment]
Thank you!
