### ISSUE TITLE
PG uuid primary key column migration broken since 5.7.0

### ISSUE THREAD

**Issue by carlhoerberg** [jeremyevans/sequel#1522]
### Complete Description of Issue

Since Sequel 5.7.0 our migrations with UUID primary keys doesn't work anymore. 

### Simplest Possible Self-Contained Example Showing the Bug

```
$ createdb db1
$ mkdir -p mig
$ cat > mig/01_primary.rb <<EOF
Sequel.migration do
  change do
    create_table :t1 do
      primary_key :id, type: 'uuid'
    end
  end
end
EOF
$ sequel -m mig/ -E postgres://localhost/db1
```

### Full Backtrace of Exception (if any)

```
E, [2018-06-07T11:38:30.987028 #84823] ERROR -- : PG::InvalidParameterValue: ERROR:  identity column type must be smallint, integer, or bigint: CREATE TABLE "t1" ("id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)
I, [2018-06-07T11:38:30.987420 #84823]  INFO -- : (0.000143s) ROLLBACK
Error: Sequel::DatabaseError: PG::InvalidParameterValue: ERROR:  identity column type must be smallint, integer, or bigint

/Users/carl/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.9.0/lib/sequel/adapters/postgres.rb:146:in `async_exec'
```

### Other

With Sequel 5.5.0 the resulting SQL from of the migration is: 

```
CREATE TABLE "t1" ("id" uuid PRIMARY KEY)
```

**Comment by jeremyevans** [comment]
Despite the change in behavior, this is not a bug (well, it's a bug in your code, not in Sequel).  From the `primary_key` method documentation:

```
Adds an autoincrementing primary key column...If you want
to create a primary key column that is not autoincrementing,
you should not use this method. Instead, you should use the
regular column method with a primary_key: true option.
```
As uuids are not autoincrementing, you basically got lucky it worked earlier, that code would fail on many databases that Sequel supports.

You should switch to: `uuid :id, primary_key: true`

**Comment by EricWVGG** [comment]
I feel like this error message should be better written. Identity columns must not necessarily be smallint, integer, or bigint…
