### ISSUE TITLE
tree plugin functions break with renamed children association

### ISSUE THREAD

**Issue by celsworth** [jeremyevans/sequel#1525]
### Complete Description of Issue

When using the `tree` plugin and renaming the `children` association via the plugin options, I don't appear to be able to use the `#ancestors` or `#siblings` methods it adds.

I think the problem is the association name is not stored and used when those methods are called, it just assumes it is called `children`.

I can have a go at fixing this if you can advise that the best fix would be to store the names of the associations in a class-instance variable (?) and then use them in the relevant instance functions?

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'

DB = Sequel.sqlite('test.db')

DB.create_table?(:discs) do
  primary_key :id
  foreign_key :parent_id, :discs
end

class Disc < Sequel::Model
  plugin :tree, children: { name: :backups }
end

d = Disc.create
Disc.create parent: d
Disc.create parent: d

d.backups.first.siblings
```

### Full Backtrace of Exception (if any)

```
$ ruby tree_siblings_bug.rb
/Users/chris/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.9.0/lib/sequel/plugins/tree.rb:124:in `self_and_siblings': undefined method `children' for #<Disc @values={:id=>1, :parent_id=>nil}> (NoMethodError)
	from /Users/chris/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.9.0/lib/sequel/plugins/tree.rb:131:in `siblings'
	from tree_siblings_bug.rb:18:in `<main>'
```

**Comment by jeremyevans** [comment]
Thanks for the report. This is definitely a bug.  I have a fix locally, just working on tests for it now.  Should be pushed up to GitHub later today.
