### ISSUE TITLE
Serialization plugin return symbol key when create a sequel object

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1527]
http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/Serialization.html Strange behavior.

Following is some pry debug info:

```sh
From: /home/zw963/Kid17/kid17-graph/app/models/feed.rb @ line 56 Feed.create_child_feed:

    52: def self.create_child_feed(params, image_ids, audio_ids)
    53:   DB.transaction do
    54:     result = true


  # here is models/feed.rb, a class method, invoke create to create a new feed object,
  # this feed have a metadata column with:  following declare:

  # plugin :serialization, :json, :metadata

    55:     feed = create(params)
 => 56:     binding.pry
    57: 
    58:     if image_ids.count.positive?
    59:       Array(image_ids).each do |id|
    60:         result &&= FeedImage.insert(feed_id: feed[:id], image_id: id)
    61:       end
    62:     end
    63: 
    64:     Array(audio_ids).each do |id|
    65:       result &&= FeedAudio.insert(feed_id: feed[:id], audio_id: id)
    66:     end
    67:     raise Sequel::Rollback unless result && feed
    68:     feed
    69:   end
    70: end
```

```sh
# get feed metadata, result is a hash, key is a symbol, this is not expected
(pry):Feed(0)> feed.metadata
{
      :title => "测试标题",
    :content => "测试内容"
}
```

```sh
# reload it, get expected result:  key is a string.
(pry):Feed(0)> feed.reload.metadata
{
      "title" => "测试标题",
    "content" => "测试内容"
}
```

## What we expected

always return uniform key type, i think string is better.

**Comment by zw963** [comment]
I have try it in `development` and `test` env, all behavior is invalid.

**Comment by jeremyevans** [comment]
JSON doesn't support symbols, automatically converting them to strings as it does for other unsupported types.  This is a well known issue with JSON.  Use marshal, yaml, or a custom serialization format that supports symbols if you want to use symbol keys.  

Conversely, if you don't want to use symbols, then convert them to strings before using them as keys in the metadata hash.  You don't show how the metadata hash is populated, and your example is not self contained (please follow the issue template next time), so I'm not sure why symbols are being used.  I can only assume that is a bug in your code.  Sequel doesn't automatically convert keys or values in serialized hashes, as a standard ruby hash is used for storage.

**Comment by zw963** [comment]
thanks, help me a lot, when i save metadata, i populated it with a symbol keys hash, e.g.

```rb
metadata = {
  key1: 'value1', 
  key2: 'value2'
}
```
i think this is the reason cause this issue, i will change it to string key.
