### ISSUE TITLE
BC dates are not handled correctly in PostgreSQL

### ISSUE THREAD

**Issue by rosenfeld** [jeremyevans/sequel#1532]
### Complete Description of Issue

Trying to insert a BC date into a table would raise PG::InvalidTimeZoneDisplacementValue error.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB[:table].insert date: Date.new(-1000, 1, 1)
# this works:
DB[:table].insert date: Sequel.lit("'1000-1-1 BC'")
# but fetching the date will parse it incorrectly:
DB[:table].first[:date].to_s # 1000-01-01
```

**Comment by jeremyevans** [comment]
You need to use the pg_extended_date_support extension to support BC dates:

``` ruby
DB.extension :pg_extended_date_support
DB.get(Sequel.cast(Date.new(-1000, 1, 1), Date))
# SELECT CAST('1001-01-01 BC' AS date) AS "v" LIMIT 1
# => #<Date: -1000-01-01 ((1355808j,0s,0n),+0s,2299161j)>
```

**Comment by rosenfeld** [comment]
Oh, thanks, I wasn't aware of that!

**Comment by rosenfeld** [comment]
There's a corner case I don't understand though. Using 1/1/-4012 seems to work but 1/1/-4013 would raise "ERROR: date out of range: "4714-01-01 BC"".

Why is Sequel converting it to 4714-01-01 BC instead of 4713-01-01?

**Comment by jeremyevans** [comment]
Year -4013 should work fine:

``` ruby
DB.get(Sequel.cast(Date.new(-4013, 1, 1), Date))
# SELECT CAST('4014-01-01 BC' AS date) AS "v" LIMIT 1
# => #<Date: -4013-01-01 ((255310j,0s,0n),+0s,2299161j)>
```

Years before -4712 will not work, as that is outside of the range for PostgreSQL date types: https://www.postgresql.org/docs/current/static/datatype-datetime.html

``` ruby
DB.get(Sequel.cast(Date.new(-4712, 1, 1), Date))
# SELECT CAST('4713-01-01 BC' AS date) AS "v" LIMIT 1
# => #<Date: -4712-01-01 ((0j,0s,0n),+0s,2299161j)>

DB.get(Sequel.cast(Date.new(-4713, 1, 1), Date))
# SELECT CAST('4714-01-01 BC' AS date) AS "v" LIMIT 1
# Sequel::DatabaseError (PG::DatetimeFieldOverflow: ERROR:  date out of range: "4714-01-01 BC")
```

**Comment by rosenfeld** [comment]
Yes, I understand about the limits but I tried to insert a value Date.new(-4013, 1, 1) and it failed:

```ruby
DB[:dates].insert date: Date.new(-4713, 1, 1)
# raises PG::DatetimeFieldOverflow: ERROR:  date out of range: "4714-01-01 BC"
```

As far as I understand from the documentation 4713 BC should be allowed, right? Maybe a pg bug? Or a bug in the documentation?

**Comment by rosenfeld** [comment]
maybe the documentation is not correct, as I found this:

https://www.postgresql.org/docs/8.1/static/functions-formatting.html


`J | Julian Day (days since January 1, 4712 BC)`

**Comment by jeremyevans** [comment]
Your code does not match the description you are giving (-4013 vs -4713).  Year -4713 is 4714 BC which is outside of the range.  In any case, if you have an issue with the PostgreSQL documentation, you should ask the PostgreSQL developers.

**Comment by rosenfeld** [comment]
Sorry, the code was correct, fixed the description.

**Comment by rosenfeld** [comment]
I wasn't aware that -4713 was 4714 BC, that explains a lot, thanks.

**Comment by rosenfeld** [comment]
Oh, I just noticed you were referring to the older comment, yes, sorry, I kept repeating 4013 when I meant 4713.
