### ISSUE TITLE
test_connection returning true despite the database being deleted 

### ISSUE THREAD

**Issue by LeninGangwal** [jeremyevans/sequel#1537]
Once a Sequel db object is created, then even if I go and delete that particular mysql database, the test_connection still returns true. 
On using some table-related query only do I get a connection error.

**Comment by jeremyevans** [comment]
test_connection has always only tested that you can checkout a connection from the connection pool.  It is usually used to test that you can create a connection after initially creating the Sequel::Database object (in Sequel 5 it is called by default when creating a Sequel::Database object).

If you want to validate that existing connections are still good, you should probably use the connection_validator extension.
