### ISSUE TITLE
Postgresql String Literal Escaping is Expensive

### ISSUE THREAD

**Issue by benmmurphy** [jeremyevans/sequel#1541]
When sequel escapes strings it ends up calling literal_string_append: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/postgres.rb#L775 

```
      def literal_string_append(sql, v)
        sql << "'" << db.synchronize(@opts[:server]){|c| c.escape_string(v)} << "'"
      end
```
This causes a connection to be checked out from the connection pool and then put back in the connection pool. Now, imagine if you were escaping thousands of strings. This problem is most noticeable if you are using connection_validator with a timeout of -1 which causes the connection to be validated each time it is checked out. However, even if you have a 'reasonable' timeout it causes Time.now to be repeatedly sampled which can be quite expensive.

I'm guessing if you were using a proper multi-threaded ruby then this would be a problem with all the contention it causes on the pool. But I'm guessing no-one uses the pg gem with a proper multi-threaded ruby.

The following sample code illustrates the problem. You can see it repeatedly calling SELECT NULL:

```
require 'sequel'
require 'logger'

db = Sequel.connect("postgres://postgres:test@localhost")
db.extension(:connection_validator)
db.pool.connection_validation_timeout = -1
db.loggers << Logger.new($stdout)

values = 1000.times.map { 'x' }
puts db.select(*values).to_a

```

**Comment by jeremyevans** [comment]
This is expected behavior and not a bug.  Not checking out a connection from the pool to do the escaping can cause improper escaping and lead to security issues.

In your particular example, you are validating the connection on every checkout, which is going to be slow.  You can either not do that, or you can checkout a connection around the query.  The documentation for the connection_validator extension explicitly states: "Note that if you set the timeout to validate connections on every checkout, you should probably manually control connection checkouts on a coarse basis, using Database#synchronize."  In your example, that would be:

```ruby
puts db.synchronize{db.select(*values).to_a}
```

You are free to override `literal_string_append` to use a faster but less secure escaping method if you value performance more than security in your application.

**Comment by benmmurphy** [comment]
thanks the synchronize method is perfect for me. do you think maybe it makes sense for the methods in dataset that generate an sql string and then execute that string to be wrapped into a synchronize block so this would not bite other people because this behaviour is not obvious. i notice you have a postgresql jdbc driver that does the same thing and running multi-threaded java when you are checking out a connection from a shared resource every time you escape a string could cause performance degradation [tho, its not clear cut because if there are not many connections and the query building is expensive then checking out each time could be good]. 

also, if people do weird stuff with connections in the pool then the way you escape strings is insecure as well because you are using the escape_string method on one connection and then feeding in the result to another connection which i guess is an argument for forcing the use of synchronize in the dataset methods.

**Comment by jeremyevans** [comment]
I don't think we want to run `synchronize` around query generation by default.  The majority of queries probably do not literalize strings, and it only really bites you if you are using the connection_validator extension with a timeout of -1 (and the documentation tells to use coarse checkouts in that case).  It's fairly simple to do it manually if you want to:

```ruby
DB.extend_datasets do
  def select_sql
    db.synchronize{super}
  end

  # likewise for other SQL generation methods if you want to affect those
end
```

If anyone is doing weird stuff with connections (e.g. modifying `standard_conforming_strings` on a connection and checking the connection back into the pool), they are basically on their own in terms of security.  You are correct that could be a potential issue, I hope nobody is foolish enough to do that.  Note that that problem will probably still occur with coarse connection checkouts, it would just be delayed until a later use (unless you have every checkout resetting the state to the desired state).

If you think the documentation should be improved for the connection_validator extension to go more into detail on this issue, please submit a pull request.
