### ISSUE TITLE
Postgres cidr mapped to IpAdd, netmask is lost when serializing to json

### ISSUE THREAD

**Issue by pdifranc** [jeremyevans/sequel#1544]
### 

The pg_inet extensions maps both postgres `inet` and `cidr` datatypes to IpAddr. While this works fine for `inet`, there might be issues with `cidr` when it comes to serialize, since IpAddr.new('10.0.0.1/8') loses the netmask information when serializing the object to json.

To overcome the problem I created a new `pg_cidr` extension but thatmust be load after the `pg_inet` otherwise it gets overwritten. Changing the `pg_inet` would also be work, probably it would even be better.

Please find below the extension we included in our codebase. It works also for arrays of cidr 
```ruby
module Sequel
  module Postgres
    # Methods enabling Database object integration with the cidr types.
    module CidrDatabaseMethods
      # Reset the conversion procs when extending the Database object, so
      # it will pick up the cidr converter.
      def self.extended(db)
        db.instance_exec do
          extend_datasets(CidrDatasetMethods)
          add_conversion_proc(650, NetAddr::CIDR.method(:create))
          if respond_to?(:register_array_type)
            register_array_type('cidr', :oid=>651, :scalar_oid=>650)
          end
          @schema_type_classes[:cidr] = NetAddr::CIDR
        end
      end

      # Convert an NetAddr::CIDR arg to a string.  Probably not necessary, but done
      # for safety.
      def bound_variable_arg(arg, conn)
        case arg
        when NetAddr::CIDR
          arg.to_s
        else
          super
        end
      end

      private

      # Handle cidr[] types in bound variables.
      def bound_variable_array(a)
        case a
        when NetAddr::CIDR
          "\"#{a.to_s}\""
        else
          super
        end
      end

      # Make the column type detection recognize the cidr type.
      def schema_column_type(db_type)
        case db_type
        when 'cidr'
          :cidr
        else
          super
        end
      end

      # Typecast the given value to a NetAddr::CIDR object.
      def typecast_value_cidr(value)
        case value
        when NetAddr::CIDR
          value
        when String
          NetAddr::CIDR.create(value)
        else
          raise Sequel::InvalidValue, "invalid value for cidr: #{value.inspect}"
        end
      end
    end

    module CidrDatasetMethods
      private

      # Convert IPAddr value to a string and append a literal version
      # of the string to the sql.
      def literal_other_append(sql, value)
        if value.is_a?(NetAddr::CIDR)
          literal_string_append(sql, value.to_s)
        else
          super
        end
      end
    end
  end

  Database.register_extension(:pg_cidr, Postgres::CidrDatabaseMethods)
end

```

**Comment by jeremyevans** [comment]
I think it would be a good idea for you to ship your `pg_cidr` as an external extension so that other Sequel users with similar issues have the option of using it.

I don't think this is a bug in the pg_inet extension, merely the result if it using `IPAddr` from the stdlib as the class for both inet and cidr values. `IPAddr` does support netmasks, but doesn't have built in json support.  If you just need the netmask in the json output:

```ruby
class IPAddr
  def to_json
    "#{self}/#{prefix}"
  end
end
```

I'm open to patches to the `pg_inet` extension to document this issue, as well as adding a link to the external `pg_cidr` extension to the website.

**Comment by pdifranc** [comment]
Thanks for the tip.

Sorry, this might sound a bit dumb, but how would I proceed with the creation of a "`pg_cidr` external extension" to `sequel` to make this available to everyone?

**Comment by jeremyevans** [comment]
Use `sequel-pg_cidr `as the gem name.  The gem just needs to include the content you posted in `lib/sequel/extensions/pg_cidr.rb`, then users will be able to do `DB.extension :pg_cidr` to load it.
