### ISSUE TITLE
update_fields does not always return self

### ISSUE THREAD

**Issue by larryfox** [jeremyevans/sequel#1548]
### Complete Description of Issue
The docs for `update_fields` state that it "Returns self." which is only true if there were saved changes.

This behavior seems fine but the docs should reflect the behavior of calling `save_changes` and/or include the blurb "If the object has not been modified, returns nil."

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
class Thing < Sequel::Model
end
thing = Thing.create
thing.update_fields({}, []) # => nil
```

**Comment by jeremyevans** [comment]
Thanks for the report. I agree, this is a documentation bug, I'll fix it shortly.
