### ISSUE TITLE
When use timestamps plugins, optional skip update timestamp when save.

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1562]
I read may document, but could not found this feature.

Thanks

**Comment by jeremyevans** [comment]
This is not a bug.  Please follow the contribution guidelines and only use GitHub Issues to report bugs.  Questions about how to use the library should be posted on the Google Group or IRC.

FWIW, you can get the behavior you want:

```ruby
ModelClass.plugin :timestamps, :allow_manual_update=>true
model_obj = ModelClass.first
model_obj.modified!(:updated_at)
model_obj.save
```

**Comment by zw963** [comment]
Oh, thanks, this worked, 

i think i misunderstood allow_manual_update.

i tried with following code yesterday, but it not work:

```rb
odelClass.plugin :timestamps, :allow_manual_update=>true
model_obj = ModelClass.first
model_obj.updated_at = model_obj.updated_at
model_obj.save            # <= this save not worked
```
