### ISSUE TITLE
timestamps plugins not work when run update in dataset

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1567]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

Following is some code to explain:

```rb
Backlog.where(origin_id: [1, 2]).update(is_finished: true)
```
`is_finished` is updated successful for two result, but, updated_at is keep no changed.

### Simplest Possible Self-Contained Example Showing the Bug

```rb
Backlog.where(origin_id: [1, 2]).update(is_finished: true)
```

### Full Backtrace of Exception (if any)

No

### SQL Log (if any)
```sql
 UPDATE `backlogs` SET `is_finished` = 1 WHERE ((`backlogs`.`deleted_at` IS NULL) AND (`origin_id` IN (1, 2)))
```

**Comment by janko-m** [comment]
@zw963 `timestamps` is a _model_ plugin, and will only work on model-level updates, where you're updating each record individually. This code would update the timestamp:

```rb
Backlog.where(origin_id: [1, 2]).each do |backlog|
   backlog # Sequel::Model instance
   backlog.update(is_finished: true)
end
```

If you want to update the timestamp on the dataset level, you have to pass it in manually.

**Comment by AlexWayfer** [comment]
Related discussions:

* https://groups.google.com/d/msg/sequel-talk/OCAiZdEjI4Q/91XtbQpNBgAJ
* https://groups.google.com/d/msg/sequel-talk/TqqbMLvsO08/DcxYtossrU4J
* https://groups.google.com/d/msg/sequel-talk/r2H5RY8-roM/IW0USybcBAAJ

> `.each do |backlog|`

From [documentation](https://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-each):

> Note that this method is not safe to use on many adapters if you are running additional queries inside the provided block. If you are running queries inside the block, you should use all instead of each for the outer queries, or use a separate thread or shard inside each.

**Comment by tycooon** [comment]
Why can't it wrap model dataset's `update` method as well?

**Comment by jeremyevans** [comment]
This is expected behavior.  Calling modification methods on a model's dataset does not instantiate model instances or call model instance hooks (with the exception of `destroy`, which only exists for backwards compatibility).  You can do:

```ruby
Backlog.where(origin_id: [1, 2]).all{|b| b.update(is_finished: true)}
# or:
Backlog.where(origin_id: [1, 2]).update(is_finished: true, :updated_at=>Sequel::CURRENT_TIMESTAMP)
```
