### ISSUE TITLE
Difference model, all with unique index added, raise different exception when record duplicate.

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1569]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

Here we have two models, which use unique index:

```rb
class FeedCollection < Sequel::Model(:feed_collections)
end

class Backlog < Sequel::Model(:backlogs)
end
```
We have one config for use `auto_validate` plugin.

```rb
# config/initializer/sequel.rb

Sequel::Model.plugin :auto_validations
```

here is our tables, we have one unique index, individually. (we use Active Record migrate)

```rb
create_table "feed_collections", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", comment: "动态采集表", force: :cascade do |t|
    t.bigint "collector_id", null: false, comment: "采集者人ID"
    t.integer "collector_type", null: false, comment: "采集者类型: 1:教师 2:家长"
    t.bigint "feed_id", null: false, comment: "动态ID"
    t.bigint "image_id", null: false, comment: "图片ID"
    t.bigint "student_id", null: false, comment: "学生ID"
    t.bigint "child_id", comment: "这个可能为空, 可能小孩还没有建立, 教师就给学生采集."
    t.datetime "created_at", default: -> { "CURRENT_TIMESTAMP" }, null: false
    t.datetime "updated_at", default: -> { "CURRENT_TIMESTAMP" }, null: false
    t.datetime "deleted_at", default: "1970-01-01 00:00:00", comment: "必须提供默认值以使得包含 deleted_at 字段的 unique 联合索引生效"
    t.index ["child_id"], name: "index_feed_collections_on_child_id"
    t.index ["collector_id"], name: "index_feed_collections_on_collector_id"
    t.index ["deleted_at"], name: "index_feed_collections_on_deleted_at"
    t.index ["feed_id", "image_id", "student_id", "deleted_at"], name: "unique_index_1_for_feed_collections", unique: true
    t.index ["feed_id"], name: "index_feed_collections_on_feed_id"
    t.index ["image_id"], name: "index_feed_collections_on_image_id"
    t.index ["student_id"], name: "index_feed_collections_on_student_id"
  end

create_table "backlogs", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.integer "origin_id", null: false, comment: "原ID"
    t.integer "origin_type", null: false, comment: "1-在园活动，2-亲子任务，3-通知分享"
    t.integer "sub_id", comment: "子id, 如家长完成的亲子任务ID"
    t.boolean "is_finished", default: false, null: false, comment: "是否完成"
    t.integer "sort", default: 0, null: false, comment: "排序"
    t.integer "clazz_id", null: false, comment: "班级ID"
    t.integer "user_id", null: false, comment: "用户ID"
    t.integer "child_id", null: false, comment: "孩子ID"
    t.datetime "created_at", default: -> { "CURRENT_TIMESTAMP" }, null: false
    t.datetime "updated_at", default: -> { "CURRENT_TIMESTAMP" }, null: false
    t.datetime "deleted_at"
    t.index ["origin_id", "origin_type"], name: "backlogs_origin_columns_index"
    t.index ["user_id", "clazz_id", "child_id", "is_finished", "origin_type"], name: "backlogs_filter_index"
    t.index ["user_id", "clazz_id", "child_id", "origin_id", "origin_type"], name: "backlogs_unique_filter_index", unique: true
  end
```

### Simplest Possible Self-Contained Example Showing the Bug

Follow code create a duplicate `backlogs` record, which exist in backlogs table, it raise a `Sequel::ValidationFailed` exception.

```rb
Backlog.create(user_id: 132467, clazz_id: 4394, child_id: 102421, origin_id: 9249, origin_type: 1)
# Exception: Sequel::ValidationFailed: user_id and clazz_id and child_id and origin_id and origin_type is already taken
```

Follow code create a duplicate `feed_collections` record, it raise `Exception: Sequel::UniqueConstraintViolation` error

```rb
FeedCollection.create(feed_id: 4201961, image_id: 6220773, student_id: 65802, collector_id: 2234, collector_type: 1)
#  Sequel::UniqueConstraintViolation: Mysql2::Error: Duplicate entry '4201961-6220773-65802-1970-01-01 00:00:00' for key 'unique_index_1_for_feed_collections'
```

What we expected is: all raise `Sequel::ValidationFailed`, not underground  `Mysql2:Error` and `Sequel::UniqueConstraintViolation`.

### Full Backtrace of Exception (if any)

No

### SQL Log (if any)

No

**Comment by jeremyevans** [comment]
This is because you didn't provide a deleted_at column value when creating the FeedCollection instance.  So deleted_at doesn't have a value until you attempt the insert.  At the time that Sequel would do the uniqueness check during validation, it skips the check because one of the uniqueness column values is nil (deleted_at in this case).

You can probably fix this by adding a before_validation hook that did something like `self.deleted_at = '1970-01-01 00:00:00' if new? && !values.has_key?(:deleted_at)`.

I don't consider the current behavior a bug.  While it is possible in this case to infer which value will be used by looking at the column default, there will be many cases where that is not possible (expression defaults, triggers/rules/model hooks that change column values).  It is something that could potentially be supported as an additional feature in validation_helpers/auto_validations enabled by another option, but I'm not sure the extra complexity is worth it given the rare need.
