### ISSUE TITLE
Postgres adapter is not able of taking database connectiong string

### ISSUE THREAD

**Issue by graywolf** [jeremyevans/sequel#1570]
### Complete Description of Issue

Postgres adapter does not accept conection string same way as pg gem does.

### Simplest Possible Self-Contained Example Showing the Bug

```
Sequel.postgres('host=localhost')
```

### Full Backtrace of Exception (if any)

```
Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: No such file or directory
```

### Patch fixing it

Sorry I have troubles cloning the sequel repo (something about zeroPaddedFilemode) so I'm providing patch here:

```
diff --git a/lib/sequel/adapters/postgres.rb b/lib/sequel/adapters/postgres.rb
index 0551905..0ddd2d4 100644
--- a/lib/sequel/adapters/postgres.rb
+++ b/lib/sequel/adapters/postgres.rb
@@ -203,7 +203,12 @@ module Sequel
             :sslrootcert => opts[:sslrootcert]
           }.delete_if { |key, value| blank_object?(value) }
           connection_params.merge!(opts[:driver_options]) if opts[:driver_options]
-          conn = Adapter.connect(connection_params)
+          begin
+            # Try connection string (host=x port=y)
+            conn = Adapter.connect(opts[:database])
+          rescue PG::ConnectionBad
+            conn = Adapter.connect(connection_params)
+          end
 
           conn.instance_variable_set(:@prepared_statements, {})
```

It's probably not final version but seems to work fine for me.

Thanks for considering this feature

**Comment by jeremyevans** [comment]
I'm OK with supporting connection strings, but it would have to be as a separate option (e.g. :conn_string), not via the :database option.  If this is something you would like Sequel to support, please submit a pull request.
