### ISSUE TITLE
call_mssql_sproc does not return all values due to ds.first call at end of method

### ISSUE THREAD

**Issue by JohnAtFenestra** [jeremyevans/sequel#1575]
### Complete Description of Issue
I encountered this issue while developing against an existing complex stored procedure in a Sql Server database.

When the stored proc is complex and returns multiple values, the call to `call_mssql_sproc` returns incomplete information. This is solvable by returning the entire ds result `ds.all` instead of only `ds.first`.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
          Sequel.tinytds(testing_config) do |client|
              client.run("create table foo (id int, mytext varchar(10))")
              dataset = client[:foo]
              dataset.insert(id: 1, mytext: 'hello')
              dataset.insert(id: 2, mytext: 'world')
              client.run <<-eof
CREATE PROCEDURE FooProc (@ID  integer, @RCNT integer = 0 out) AS
BEGIN
  select distinct mytext from foo
  select foo.*, id_in = @ID from foo
  set @RCNT = @@rowcount
  return 42
END
              eof
              sql =<<-eof
DECLARE	@return_value int,
		@RCNT int

EXEC	@return_value = FooProc
		@ID = 1,
		@RCNT = @RCNT OUTPUT

SELECT	@RCNT as N'@RCNT'

SELECT	'Return Value' = @return_value
              eof
              result = {
                raw_sql: client.fetch(sql).to_a,
                call_mssql_sproc_array: client.call_mssql_sproc('FooProc', {args: [1, :output]}),
                call_mssql_sproc_named_args: client.call_mssql_sproc('FooProc', {args: {id: 1, rcnt: [:output, 'int', 'RCNT']} } ),
                proposed_1: begin
                  dataset = client['select *']
                  ds = dataset.with_sql("DECLARE @RC int, @RCNT int; EXECUTE @RC = FooProc @id=1, @rcnt=@RCNT OUTPUT; SELECT @RC AS RESULT, @@ROWCOUNT AS NUMROWS, @RCNT AS [RCNT]")
                  r = ds.all
                  {
                    result: r.last,
                    data: r.slice(0..-2)
                  }
                end,
                proposed_2: begin
                  dataset = client['select *']
                  ds = dataset.with_sql("DECLARE @RC int, @RCNT int; EXECUTE @RC = FooProc @id=1, @rcnt=@RCNT OUTPUT; SELECT @RC AS RESULT, @@ROWCOUNT AS NUMROWS, @RCNT AS [RCNT]")
                  r = ds.all.last
                end
              }
              client.run "drop table foo"
              client.run "drop procedure FooProc"
              result
          end
```

Output (through awesome_print):

```ruby
{
                        raw_sql: [
        {
            mytext: "hello"
        },
        {
            mytext: "world"
        },
        {
                "id" => 1,
            "mytext" => "hello",
             "id_in" => 1
        },
        {
                "id" => 2,
            "mytext" => "world",
             "id_in" => 1
        },
        {
            "@RCNT" => 2
        },
        {
            "Return Value" => 42
        }
    ],
         call_mssql_sproc_array: {
        mytext: "hello"
    },
    call_mssql_sproc_named_args: {
        mytext: "hello"
    },
                     proposed_1: {
        result: {
             "RESULT" => 42,
            "NUMROWS" => 1,
               "RCNT" => 2
        },
          data: [
            {
                mytext: "hello"
            },
            {
                mytext: "world"
            },
            {
                    "id" => 1,
                "mytext" => "hello",
                 "id_in" => 1
            },
            {
                    "id" => 2,
                "mytext" => "world",
                 "id_in" => 1
            }
        ]
    },
                     proposed_2: {
         "RESULT" => 42,
        "NUMROWS" => 1,
           "RCNT" => 2
    }
}
```

### Problematic code:

```ruby
      def call_mssql_sproc(name, opts=OPTS)
...
        sql = "DECLARE #{declarations.join(', ')}; EXECUTE @RC = #{name} #{values.join(', ')}; SELECT #{names.join(', ')}"

        ds = dataset.with_sql(sql)
        ds = ds.server(opts[:server]) if opts[:server]
        ds.first
      end
```

### Proposed change:
There are two issues. First, the resultset does not contain all of the data which would be expected to be returned. Second, if the resultset has a select involved, the intended hash is replaced by the first returned row of the first select instead of the result information.

Rather than breaking the existing interface, I would propose the following steps:

1. Rename `call_mssql_sproc` to `call_mssql_sproc_raw` and return the full ds result
1. Create two new methods 
   1. `call_mssql_sproc` which calls `call_mssql_sproc_raw(name, opts).all.last`. Returning `last` instead of `first` ensures that the intended hash result is returned instead of the first row of a select.
   1. `call_mssql_sproc_all` which calls `call_mssql_sproc_raw(name, opts).all`.

```ruby
      def call_mssql_sproc_raw(name, opts=OPTS)
...
        sql = "DECLARE #{declarations.join(', ')}; EXECUTE @RC = #{name} #{values.join(', ')}; SELECT #{names.join(', ')}"

        ds = dataset.with_sql(sql)
        ds = ds.server(opts[:server]) if opts[:server]
        ds
      end

      def call_mssql_sproc(name, opts=OPTS)
        call_mssql_sproc_raw(name, opts).all.last
      end

      def call_mssql_sproc_all(name, opts=OPTS)
        result = call_mssql_sproc_raw(name, opts).all
        {
          result: result.last,
          data: result.slice(0..-2)
        }
      end
```

**Comment by jeremyevans** [comment]
Thanks for posting an issue regarding this.

I'm not sure if this is something that can be fixed.  Sequel datasets do not support having multiple `SELECT`s in a single query.   That's not to say it always fails, but the behavior is undefined and adapter dependent.  In most cases, it is not going to work correctly if separate columns are used, and because `call_mssql_sproc` does a `SELECT` to return the result code and number of rows affected, that's always going to be the case if the procedure does a `SELECT` internally.

I checked and we can't split the query into two separate queries, as doing so results in a database error because the `@RC` variable cannot be accessed if a separate query is used.  Here's a diff for that:

```diff
diff --git a/lib/sequel/adapters/shared/mssql.rb b/lib/sequel/adapters/shared/mssql.rb
index d590c194e..0ecc8e213 100644
--- a/lib/sequel/adapters/shared/mssql.rb
+++ b/lib/sequel/adapters/shared/mssql.rb
@@ -98,9 +98,21 @@ module Sequel

         sql = "DECLARE #{declarations.join(', ')}; EXECUTE @RC = #{name} #{values.join(', ')}; SELECT #{names.join(', ')}"

-        ds = dataset.with_sql(sql)
+        ds = dataset
         ds = ds.server(opts[:server]) if opts[:server]
-        ds.first
+        rows = nil
+        hash = nil
+
+        synchronize(opts[:server]) do
+          rows = ds.with_sql("DECLARE #{declarations.join(', ')}; EXECUTE @RC = #{name} #{values.join(', ')}").all
+          hash = ds.with_sql("SELECT #{names.join(', ')}").single_record!
+        end
+
+        unless rows.empty?
+          hash[hash.has_key?(:rows) ? "rows" : :rows] = rows
+        end
+
+        hash
       end

       def database_type
```

I think our only option is to just document that `call_mssql_sproc` does not handle stored procedures that return rows, and to drop down to the driver/connection level if you need to call such procedures.

**Comment by JohnAtFenestra** [comment]
Thanks for the quick response. I will tell you that the solution I proposed does work with this particular scenario; I have tested it. I'd run the specs but I'm running into an issue:

```
  cannot load such file -- minitest/shared_description
# ./spec/extensions/spec_helper.rb:12:in `<top (required)>'
# ./spec/extensions/insert_returning_select_spec.rb:1:in `require_relative'
# ./spec/extensions/insert_returning_select_spec.rb:1:in `<top (required)>'
```

I've installed the minitest gem and minitest-hooks gem. If you have any ideas, I'd be happy to run the specs and see if anything current breaks with my change.

**Comment by jeremyevans** [comment]
As the development dependencies in the gemspec indicate, `minitest-shared_description` is also required.

I'm certainly open to supporting stored procedures that return rows if it is possible to do so in a backwards compatible manner without changing adapter code and it works correctly on all adapters supporting MSSQL (ado/mssql, tinytds, odbc/mssql, jdbc/jtds, jdbc/sqlserver).

**Comment by jeremyevans** [comment]
From looking at your example output, there are some fairly obvious problems, such as only the first result set correctly using symbol keys.  I'm guessing on different adapters, the problems may be worse than that.

**Comment by JohnAtFenestra** [comment]
I missed the inconsistent field name types.

I may have to simply add this in as my own extension; personally I believe stored procedures are a "bad idea" for a lot of reasons (violates DRY like crazy, scatters business logic throughout hundreds [not kidding] of SPs, makes business logic testing impossible, even the best stored procs are undocumentable), however, I have to deal with this as a starting point for a complete redesign - which is what I'm working on. When I finish the redesign, I'll probably recommend killing all the stored procs anyhow.

Thanks for considering my proposal.
