### ISSUE TITLE
Problem with stored procedures

### ISSUE THREAD

**Issue by ciaoben** [jeremyevans/sequel#1577]
It continues to throw me a  `Mysql2::Error: Commands out of sync; you can't run this command now`
after running a stored procedure, can't find anything about multi statements query on the docs:

```
MyModel.db['CALL get_info("arg")').first
# => {col: val, col2: val}
MyModel.db['CALL get_info("arg")').first
# => Sequel::DatabaseDisconnectError: Mysql2::Error: Commands out of sync; you can't run this command now
from /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
```

I am on `sequel (5.15.0)`

**Comment by jeremyevans** [comment]
The mysql2 adapter (and most Sequel adapters) do not handle multi statement queries.  You could try using the mysql adapter, which has a `Dataset#split_multiple_result_sets` method.  That may work, but I'm not sure.  If not, you'll have to drop down to the connection level via `Database#synchronize` to get an underlying connection, and use the driver's API to run the stored procedure.

**Comment by ciaoben** [comment]
> The mysql2 adapter (and most Sequel adapters) do not handle multi statement queries. You could try using the mysql adapter, which has a `Dataset#split_multiple_result_sets` method. That may work, but I'm not sure. If not, you'll have to drop down to the connection level via `Database#synchronize` to get an underlying connection, and use the driver's API to run the stored procedure.

Thanks for the details answer, I didn't understand one thing when you say "use the driver's API" what exactly do you mean, what is the driver in this case?

**Comment by jeremyevans** [comment]
The driver in your case would be Mysql2. You can use the driver's API by getting access to the connection object:

```
  DB.synchronize do |connection|
    # connection is Mysql2::Client object
  end
```

You can see https://github.com/brianmario/mysql2#usage for details on the Mysql2 API.  https://github.com/brianmario/mysql2#multiple-result-sets may also be useful to review.

**Comment by ciaoben** [comment]
> The driver in your case would be Mysql2. You can use the driver's API by getting access to the connection object:
> 
> ```
>   DB.synchronize do |connection|
>     # connection is Mysql2::Client object
>   end
> ```
> 
> You can see https://github.com/brianmario/mysql2#usage for details on the Mysql2 API. https://github.com/brianmario/mysql2#multiple-result-sets may also be useful to review.

Really appreciate the help. thank you very much!
