### ISSUE TITLE
Table inheritance seems to break setters methods

### ISSUE THREAD

**Issue by ciaoben** [jeremyevans/sequel#1578]
I have upgraded an old codebase from (4.39.0) to (5.15.0). Following the changelog, I made the adjustments necessary but one behavior is different and can't understand why, maybe it is a bug.

I have two class with class_table_inheritance a class
```
class User < Sequel::Model
   plugin :class_table_inheritance, key: :type, ignore_subclass_columns: [:created_at, :updated_at] 

  # this field exists on the the table users in the db
  def field_getter
    p 'this is called'
    super
  end

  def field_setter= val
    p 'this is NOT called'
    super(val)
  end

end

class SpecialUser < User
end
```

Then I test it in the console:

```
rails c
pry > s = SpecialUser.new
pry > s.field_getter
"this is called"
pry > s.field_setter('test')
pry > s.field_getter
"this is called"
=> "test"
```

This code worked on version `4.39.0` but now it does not. Can't find any reference in the Changelog. Any hint on what could be?

**Comment by jeremyevans** [comment]
Thanks for the report!  I've confirmed that this is a bug introduced in Sequel 5, and it is not limited to class_table_inheritance, but potentially affects all Sequel::Model classes (more likely to affect subclasses of other Sequel::Model classes).  I have a fixed prepared, I just need to add tests for it, then it should be merged shortly.
