### ISSUE TITLE
Postgres sslrootcert as string rather than path

### ISSUE THREAD

**Issue by jtara** [jeremyevans/sequel#1586]
FEATURE REQUEST:

It would be really nifty if when connecting to Postgres:

:sslrootcert | Specify the path to the root SSL certificate to use.

... were able to accept a string, in addition to a path to a file. Maybe a new key? e.g. *sslrootcertstring*. Maybe an option.

Specific use case is when working with IBM Cloud Databases for PostgreSql. One can download a credential structure in JSON format (manually from IBM Cloud console, cli, or api/sdk), and one of the things it includes is the root certificate in base64 format.

My current workaround is to write the root certificate to a file.

I dunno how common it would be to have this as base64, that might be a nice additional option. But easy enough to decode the base64 ones self.

e.g. this is from a Rake helper

``` ruby
# dig the postgres connect string out of developer credential
# Has the side effect of writing the root certificate to config/postgres_root.crt
# To connect with SSL verification, the root certificate has to be able to be found
# in a file. (Can't just be passed in a string!) This is a Sequel limitation
def load_postgres_credential
  credential = developer_credential('postgres')
  composed = credential[:connection][:postgres][:composed][0]
  root_cert_b64 = credential[:connection][:postgres][:certificate][:certificate_base64]
  root_cert = Base64.strict_decode64(root_cert_b64)
  @postgres_root_cert_path = 'config/postgres_root.crt'
  # TODO: It would be better to use a memmap Gem and never write this to actual disk/flash
  File.open(@postgres_root_cert_path, 'wb') { |f| f.write(root_cert) }
  @postgres_connect_string = composed
end
```
``` ruby
  db = Sequel.connect(@postgres_connect_string, {
    database:     @environment[:database],
    search_path:  [@environment[:schema]],
    sslrootcert:  @postgres_root_cert_path
    },
  )
```

**Comment by jeremyevans** [comment]
Thank you for the suggestion.  However, I don't think this is appropriate for Sequel.  It probably needs upstream support in libpq (so you would have to submit a patch to PostgreSQL itself), then ruby-pg would need to add support for it, then you could use the `:driver_options` option in the Sequel postgres adapter to use the ruby-pg support.
