### ISSUE TITLE
Inconsistent primary key compatibility using serial: true on postgresql

### ISSUE THREAD

**Issue by hugomelo** [jeremyevans/sequel#1591]
I saw Sequel has a change in the default primary key value for postgresql. Now, the default value is `generated by default as identity` instead of something like this `nextval('users_id_seq'::regclass)`
The text explaining the new usage is here:
https://github.com/jeremyevans/sequel/blob/67cc4245227a6c01ecb20d0138aaf37b05a5aebc/doc/release_notes/5.8.0.txt#L110
As I want to keep compatibility with old postgresql versions, I want to keep using serial primary keys and when I tried it using:
`primary_key :id,   serial: true, type: :serial`
It really created the `nextval` entry but the sequence was slightly different, which still breaks compatibility.

Note the *AS integer* new line which is not present on the older sequences created using sequel.
```
 CREATE SEQUENCE public.connection_suggestions_id_seq
+    AS integer
     START WITH 1
     INCREMENT BY 1
     NO MINVALUE
```
I've tested removing the *AS integer* line and it worked as before.
So, I understand this is breaking compatibility with PG older versions. If there's a way to avoid this issue, please, let me know. But I still think only a `serial: true` should do all the trick.

Thanks!

**Comment by jeremyevans** [comment]
Sequel doesn't set the sequence data type explicitly.  If you use `primary_key :id, serial: true`, Sequel uses `"id" serial PRIMARY KEY`, just like it did in previous versions.  Before PostgreSQL 10, all sequences used a 64-bit data type.  Starting with PostgreSQL, you can have 2-byte, 4-byte, and 8-byte sequence data types, and PostgreSQL will choose the appropriate size sequence based on data type for either identity or serial columns.  See PostgreSQL's documentation for 9.6 and 10 and notice how 9.6 does not support types for sequences:

9.6: https://www.postgresql.org/docs/9.6/sql-createsequence.html
10: https://www.postgresql.org/docs/10/sql-createsequence.html

I don't think it is possible to get the PostgreSQL <10 behavior (integer column type but bigint sequence type) when creating serial/identity columns on PostgreSQL 10+, but that is a difference in PostgreSQL, not in Sequel.  If you want to have the historical PostgreSQL <10 behavior, use PostgreSQL <10.
