### ISSUE TITLE
Oracle JDBC connection idle timeout issues: How to validate a connection (ex: sequel_opts in Oracle?)

### ISSUE THREAD

**Issue by stanuku** [jeremyevans/sequel#1593]
I'm indexing data from Oracle DB to Elasticsearch using logstash.

The Logstash process always terminates (after about ~ 20 mins), with the below error:
`Sequel::DatabaseError: Java::JavaSql::SQLException: ORA-02396: exceeded maximum idle time`

Is there a way I could have the jdbc connection validation from Sequel to work for Oracle? 
How do we use sequel_opts in the Logstash input config?

`jdbc_validate_connection` setting in logstash config doesn't seem to help.`

- Version: Sequel-5.14.0, logstash-input-jdbc (4.3.13), Logstash 6.5.4,
- OS: Windows Server 2012 R2
- Input Oracle DB, Output: Elasticsearch
- Config:

```
input {
	jdbc {
		clean_run => false
		jdbc_driver_library => "E:\logstash\ojdbc8.jar"
		jdbc_driver_class => "Java::oracle.jdbc.OracleDriver"
		jdbc_connection_string => "jdbc:oracle:thin:@xxxxx:1234/xyz"
		...
		#-> Connection pool configuration. Validate connection before use.
		**jdbc_validate_connection => true**
		#->How often to validate a connection (in seconds)
		jdbc_validation_timeout => 120
		#->**??** jdbc_validation_query => "SELECT 1 FROM DUAL" **??**
		#->Maximum number of times to try connecting to database
		connection_retry_attempts => 5
		#-> Number of seconds to sleep between connection attempts
		connection_retry_attempts_wait_time => 2		
				
                #https://github.com/jeremyevans/sequel/blob/master/doc/opening_databases.rdoc)#
		sequel_opts =>
		{
			login_timeout => "60"
			prefetch_rows => "1000"
			jdbc_properties => #=> **Are these valid for Oracle JDBC ??** -#
			{
				"defaultRowPrefetch" => "1000"
				"loginTimeout" => "60"
				"inactiveConnectionTimeout" => "120"
				"timeoutCheckInterval" => "120"
				"tcpKeepAlive" => "true"
				"oracle.net.READ_TIMEOUT" => "5000"
				"validationQuery" => "SELECT 1 FROM DUAL"
			}
		}
	...
	}
output {
	elasticsearch {
		hosts => ["http://localhost:9200"]
		index => "projects"
		document_id => "%{project_id}"
		document_type => "_doc"
		doc_as_upsert => true
		http_compression => true
	}
	stdout {
		codec => rubydebug
	}
}
```

**Comment by jeremyevans** [comment]
You should probably try the connection_validator extension, which can validate connections before Sequel attempts to use them.  You could also modify your Oracle configuration to not drop idle connections.

If neither of those works, you may want to ask the logstash-input-jdbc developers, as the config file you are providing seems related to logstash or logstash-input-jdbc, not Sequel.  I have not used logstash and have no knowledge about how logstash or logstash-input-jdbc uses Sequel.

This is a question about using Logstash/Sequel, and not a report of a bug in Sequel. Per the contribution guidelines and the issue template, you should ask questions about using Sequel on the IRC channel or the Google Group (after you have replicated the underlying issue without using Logstash).  Only use GitHub Issues to report bugs in Sequel itself.
