### ISSUE TITLE
Sequel::SQLTime does not work with Postgres time with time zone

### ISSUE THREAD

**Issue by davidarnold** [jeremyevans/sequel#1595]
### Complete Description of Issue

Attempting to store or retrieve a Postgres `time with time zone` value results in `Sequel::SQLTime` stripping the offset.

It seems that `Sequel::SQLTime` is generally unaware of zone offsets as evidenced by the method signature `create(hour, minute, second, usec = 0)`.  Although it is capable of storing an offset provided through an alternative constructor like base `Time#parse`, that internal offset does not make it in or out of `time with time zone` fields.

I've been able to store offsets by monkey patching `Sequel::Dataset#literal_sqltime` to include a `%:z` in the `strftime` format string, but this is obviously a hack.  It also does nothing to retrieve the stored values correctly.  They are still retrieved as `Sequel::SQLTime` in the local time zone.

### Simplest Possible Self-Contained Example Showing the Bug

```
Sequel::Dataset.new(nil).send(:literal_sqltime, Sequel::SQLTime.parse('09:00:00+05:30')) #=> "'09:00:00.000000'"
```

### SQL Log (if any)

From the Puma log with query debugging turned on, when attempting to store `09:00:00+05:30`:

```
I, [2019-01-28T12:59:20.933037 #22507]  INFO -- : (0.000136s) EXECUTE smpsp_18 (UPDATE "calendar_event_actions" SET "time" = $1, "updated_event_id" = $2 WHERE ("id" = $3)); ["'09:00:00.000000'", 612355, "a0e0e33b-d3ab-499b-a0d6-3079ddd2a8d7"]
```

which results in a local (for me) `time with time zone` value of `09:00:00-05` being stored.

And with the monkey patch:

```
I, [2019-01-28T13:11:49.375189 #22507]  INFO -- : (0.000145s) EXECUTE smpsp_18 (UPDATE "calendar_event_actions" SET "time" = $1, "updated_event_id" = $2 WHERE ("id" = $3)); ["'09:00:00.000000+05:30'", 612357, "a0e0e33b-d3ab-499b-a0d6-3079ddd2a8d7"]
```

which results in `09:00:00+05:30` being stored.

**Comment by jeremyevans** [comment]
Correct, `time with time zone` is not handled fully by `Sequel::SQLTime`.  That was not an oversight, it was a design choice, but I probably should document that.

The PostgreSQL documentation states:

```
The type time with time zone is defined by the SQL standard, but the
definition exhibits properties which lead to questionable usefulness.
```

I think most people can agree with that, and that is why you almost never see the type used in production applications.  This is the first request received for supporting the type.

I'm not opposed to adding support for it, but considering almost nobody uses it, it should be added via a Database extension.  The `Sequel::SQLTime` class can be subclassed, and the subclass can support the timezone, and a conversion proc can be added for the oid for the `time with time zone`  that uses the `Sequel::SQLTime` subclass.  The subclass would basically be the same except it would accept a timezone in initialize, and would override `literal_sqltime` for the dataset to include the timezone if a subclass object is given.  Possibly some other changes would be necessary for better integration with model typecasting, if that is desired.

If that is something you are interested in working on, please submit a pull request for such an extension.  You may want to review the other pg_* extensions for examples.

**Comment by davidarnold** [comment]
Thanks for the quick response.  Totally fair to punt this back to me for a PR, but I won't be able to work on it anytime soon.

For the record, I don't really agree with Postgres's "questionable usefulness" jab.  The use of `with time zone` versions of temporal data isn't really so much about wanting to record a time zone (which is a misnomer anyway, since offsets are not zones), but rather being explicit that the underlying value is in fact recorded in UTC.

The non-zoned versions of the data are ambiguous wall time.  Most sane people write UTC, but there is nothing in the data to make that clear when reading, so it is an assumption that retrieved data is in UTC.  Similar to the zone erasure behavior in this issue, alternate zones do end up accidentally being stored in a field that is believed to be UTC by the developers, leading to errors.

It's odd to me that the prevailing best practice is to use `timestamptz` everywhere, but `timetz` would be seen as junk.  If there's anything "questionable" about `timetz`, it would be wanting to record a free-floating time at all, which is just as strange regardless of whether it is `time` or `timetz`.

My particular application needs it for a cron-like system where the `date`s are generated from calendar rules, then paired with a `timetz` stored in the database to produce a set of `timestamptz` values for the run times.  Without `timetz` support, I am essentially just generating a `timestamp` values instead.

**Comment by jeremyevans** [comment]
If all timetz values you are storing are in UTC, if you set `Sequel.application_timezone = :utc`, the Sequel::SQLTime instances will use a UTC offset instead of a local offset.  That does not handle the general case, but it may handle your specific use case easier.  If that won't work, here is a manual work around to convert the local time into a UTC time:

```ruby
  t = Sequel::SQLTime.now
  (t + t.utc_offset).utc
```

One alternative approach for you use case that will work even with non-UTC offsets is to do the time calculation in the database instead of in ruby, since both the date and timetz are stored in the database.  Then you can return timestamptz to the application, which is already handled.  That's probably also faster than doing the calculations in ruby, though it may take some refactoring to use such an approach.

**Comment by davidarnold** [comment]
Thank you for the suggestions!  I appreciate your feedback on practical solutions and workarounds.

In my particular case, the users are currently submitting their jobs with calendar rules like "monthly starting Jan 1, 2019" along with a run time with offset specified as [RFC 3339 `full-time`](https://tools.ietf.org/html/rfc3339#section-5.6) format (e.g. `03:00:00-05:00`).

Trying to normalize the incoming time with offset into a UTC value for storage in the supported `time without time zone` type leaves the problem of a remainder day, either borrowed or carried.  For example, `20:00:00-05:00` turns into `01:00:00Z` *plus a day* and `'02:00:00+05:30'` turns into `20:30:00Z` *less a day*.  That means I would have to store an additional integer column to hold this remainder, which I would factor in later when calculating the run times, and then somehow roundtrip all this back to the user when viewing the rule.

Given the difficulties here, I might as well take a totally different approach and refactor to accept a wall time without offset (stored in a `time without time zone` column) and IANA time zone name.  Then either the [TZInfo library](https://github.com/tzinfo/tzinfo) or Postgres [`timezone` function](https://www.postgresql.org/docs/9.6/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT) could be used to convert the theoretical requested "wall run time" (`timestamp`) into a system UTC run time (`timestamptz`).

This does have the major downside that you have to handle and adjust for `TZInfo::PeriodNotFound` and `TZInfo::AmbiguousTime` exceptions caused by DST boundaries, which was why I originally avoided this approach.  But it appears to be doable after some experimentation, and it seems from everything we've discussed that there would be some potentially major hacking to pull off the originally simple idea of a RFC 3339 passthrough to a `timetz` field.
