### ISSUE TITLE
Upstream breaking changes in TZInfo Gem break named_timezones extension

### ISSUE THREAD

**Issue by yaauie** [jeremyevans/sequel#1596]
### Complete Description of Issue

When using the named_timezones extension and the tzinfo dependency resolves to 2.x, breaking changes in that dependency cause `NoMethodErrors` to be raised. 

From their [changelog](https://github.com/tzinfo/tzinfo/releases/tag/v2.0.0):
> The TZInfo::TimezonePeriod#utc_total_offset_rational method has been removed. Equivalent information can be obtained using the TZInfo::TimezonePeriod#observed_utc_offset method.

### Full Backtrace of Exception (if any)

~~~
  2032     NoMethodError: undefined method `utc_total_offset_rational' for #<TZInfo::OffsetTimezonePeriod:0x55b909f8>
Did you mean?  utc_total_offset
  2032       /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/sequel-5.16.0/lib/sequel/extensions/named_timezones.rb:71:in `convert_input_datetime_other'
  2032       /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/sequel-5.16.0/lib/sequel/timezones.rb:119:in `convert_input_datetime_no_offset'
  2032       /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/sequel-5.16.0/lib/sequel/timezones.rb:156:in `convert_input_timestamp'
  2032       /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/sequel-5.16.0/lib/sequel/timezones.rb:77:in `convert_timestamp'
  2032       /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/sequel-5.16.0/lib/sequel/database/misc.rb:298:in `to_application_timestamp'
  2032       /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/sequel-5.16.0/lib/sequel/adapters/jdbc.rb:686:in `timestamp_convert'
  2032     <--snip-->
~~~

**Comment by jeremyevans** [comment]
Thanks for the report.  Looks like this wasn't caught by Travis because the Travis config is indirectly limiting the tzinfo dependency due to the activemodel dependency.  I'll work on a fix shortly.

**Comment by yaauie** [comment]
Thanks for the quick turnaround on getting a fix into master!
