### ISSUE TITLE
after_save don't work when included through a module in pro

### ISSUE THREAD

**Issue by youjiuzidangge** [jeremyevans/sequel#1598]
### Complete Description of Issue
this is a feed model, and every time i update a feed, it supposes to do some hook work.
in my local dev and pro env, it just work fine.
but in our server production env, it doesn't work, and i found there are no any logs.

other infomation may help:
1. we use graphql-ruby
2. because of a lot of models use same logic, so i put code in a module:

``` ruby
module DataReportsCallbackable
  extend ActiveSupport::Concern

  def after_save
    Rails.logger.info('*' * 30 + 'just logger' + '*' * 30)

    Rails.logger.info(changed_happened_at = send(:column_changed?, :happened_at))
    request_id = get_request_param(self)[0]
    Rails.logger.info('*' * 30 + 'this is request_id' + '*' * 30)
    Rails.logger.info(request_id)
    super
    return unless changed_happened_at

    db.after_commit do
      Rails.logger.info('*' * 30 + 'just logger' + '*' * 30)
      http_put_request(id: request_id)
    end
  end
end
```
and in model 

``` ruby
class Feed < Sequel::Model(:feeds)
  include DataReportsCallbackable
end
```

### Simplest Possible Self-Contained Example Showing the Bug

in my local dev and pro env just work fine, and there is log as follows:
![image](https://user-images.githubusercontent.com/23353593/52700479-f0ac0400-2fb2-11e9-9759-5be51aada490.png)

but in server pro, there is nothing in log:
![image](https://user-images.githubusercontent.com/23353593/52700544-22bd6600-2fb3-11e9-903f-1ae241f0c44c.png)

actually，there is an after_create in the module, but it works fine, so i don't give it out.

i think there are some mistake when i am using the hook,but i just don't know why, please help, thanks!

**Comment by jeremyevans** [comment]
I would guess in the server production environment you have another after_save method in a different module that is not calling super.  But that's just a guess.

This doesn't appear to be a bug in Sequel, so I'm going to close this. If you think this is a bug in Sequel as opposed to your code, please submit a minimal, self contained example showing the bug (not screen shots from your application), and this could be reopened.

If you need help using Sequel (as opposed to reporting a bug in Sequel), please use the sequel-talk Google Group or the IRC channel, but even there you are going to want to post a minimal, self contained example for help.
