### ISSUE TITLE
Sharding documentation not right / bug in jdbc adapter

### ISSUE THREAD

**Issue by TheWudu** [jeremyevans/sequel#1605]
Good Morning!

Yesterday I invested in why we have connections using our read-only user to the master database, although we configured them to be used with the slave database.

After some hours of code-reading and trying stuff i found the reason in the configuration of the read_only database and the jdbc adapter. I did not check other adapters, but they may be affected as well. 

The issue is, that we define an URI as connect string for the master, and the read_only servers using host / user / pass. This leads to the read_only server is initialized by the (master) URI and the user / pass of the read_only server config.

```
{
  servers: {
    read_only: {
      host:     host,
      user:     user,
      password: password
    }
  }
}
```

does not work, whereas

```
{
  servers: {
    read_only: {
      uri:     uri_for_slave,
    }
  }
}
```

does.

The reason is this: 
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/connecting.rb#L26-L32

If the connect string is a String, and starts with `:jdbc`, it takes the connect string and merges the read_only options in. This leads to this hash:

```
{
  servers: {
    read_only: {
      uri:        connect_string,  # for master!
      host:     host,
      user:     user,
      password: password
    }
  }
}
```

The jdbc-adapter then takes this URI and the user/password options and opens the connection. The host is ignored completely. 

So either the documentation is wrong (or dependent on the adapter), or the implementation.

**Comment by jeremyevans** [comment]
Thanks for the report.

The behavior is expected, as Sequel does no processing of JDBC connection strings.  This isn't related just to sharding, as you can't use the `:host`, `:user`, or `:password` options when connecting with JDBC, either, it only works with JDBC connection URIs.

This is kind of mentioned in the documentation for the JDBC adapter (http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-jdbc+), but that's probably not sufficient to explain the behavior.  I agree it is probably a good idea to mention how to handle JDBC in the sharding documentation. I'll work on expanding the documentation in both areas today.

**Comment by TheWudu** [comment]
Hello!

It is true that it does not process the connection URIs, but at least it is altering it a bit, as it "replaces" the user/password:

https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/jdbc.rb#L204-L205

From reading the code i guess it will result in 

`<original_connection_string>&user=#{user}&password=#{password}` 

so maybe:
`jdbc:mysql://#{orig-host}:#{orig-port}/#{orig-database}?user=#{orig-user}&password=#{orig-password}&user=#{user}&password=#{password}`

And the last user/password parameters are "winning" the game.

I also think at least a hint in the documentation at sharding would be great! Thanks in advance.

**Comment by jeremyevans** [comment]
@TheWudu `:user` and `:password` in jdbc do not modify the connection URL, they are passed as separate arguments to `DriverManager.getConnection`.  They may take precedence, they may not.  Unless JDBC defines how they should work, I assume it is up to the JDBC driver.  I would recommend not relying on them, and just using a separate URI for the replica servers.

As indicated above, this issue was closed with a commit that added documentation to the sharding guide discussing usage with JDBC.

**Comment by TheWudu** [comment]
Perfect!
