### ISSUE TITLE
Wrong date with Sequel TinyTDS Adapter connecting to SQL Anywhere Server

### ISSUE THREAD

**Issue by acsSystemhaus** [jeremyevans/sequel#1606]
We are in the process of switching to Sequel Models and came up with this problem:

Connecting to SQL Anywhere 16 (16.0.0.2043) and retrieving a dataset that contains any kind of date or datetime will give strange results.

As using TinyTDS without Sequel previously returned the dates and datetimes correctly, I suspect that the TinyTDS connection in Sequel is only able to communicate with MicrosoftSQL servers.

This can be reproduced with the development version from Sybase.
[https://www.sap.com/cmp/syb/crm-xu15-int-asewindm/index.html?url_id=text-us-sapcom-ase-trial-software](url)

### Simplest Possible Self-Contained Example Showing the Bug

``` ruby
require 'sequel'

DB = Sequel.tinytds dataserver: '192.168.1.43:5003\sequel_test',
                    username: 'dba',
                    password: 'dba',
                    encoding: 'iso-8859-1',
                    database: 'sequel_test',
                    tds_version: '100',
                    server_version: 10001600 # needs to be set to get the connection in the first place
# error without server_version:
# Sequel::DatabaseError: TinyTds::Error: SQL Anywhere-Fehler -265: Prozedur 'SERVERPROPERTY' nicht gefunden

class SQLTest < Sequel::Model(:test)
end

puts SQLTest.first.inspect
```

All the other columns which aren't a date or datetime return normal values.

**Comment by jeremyevans** [comment]
The tinytds adapter is only supported with Microsoft SQL Server, please use the sqlanywhere adapter for connecting to Sybase SQLAnywhere.  The sqlanywhere adapter is tested on a regular basis and should work correctly.
