### ISSUE TITLE
Undefined method `tables' for Sequel::SchemaDumper:Module

### ISSUE THREAD

**Issue by zzidante** [jeremyevans/sequel#1613]
### Complete Description of Issue
Attempting to use `Sequel::Database.dump_schema_migration(indexes: true, foreign_keys: true)` results in a `NoMethodError: undefined method 'tables' for Sequel::Database:Class` error.

It seems to originate from ` ts = sort_dumped_tables(tables(options), options)` where `tables` is used as a method but it doesn't seem to exist anywhere inside the file (or inside of 
`Sequel.extension :eval_inspect` in the case it was expected to get a patched one).

### Simplest Possible Self-Contained Example Showing the Bug

```
  require 'sequel'
  
  Sequel.extension(:schema_dumper)

  DB_CONNECTION = Sequel.connect({
    adapter: ENV["db_adapter"].to_sym, 
    user: ENV["db_user"], 
    password: ENV["db_password"], 
    host: ENV["host"], 
    port: ENV["db_port"],
    database: ENV["db_database"], 
    max_connections: ENV["db_pool"],
  })

  include Sequel::SchemaDumper
  Sequel::Database.dump_schema_migration(indexes: true, foreign_keys: true)

```

### Full Backtrace of Exception (if any)
```
NoMethodError: undefined method `tables' for Sequel::Database:Class
from .gem/ruby/2.4.6/gems/sequel-5.19.0/lib/sequel/extensions/schema_dumper.rb:130:in `dump_schema_migration'
```

### SQL Log (if any)
n/a

**Comment by jeremyevans** [comment]
This is not a bug, you are not using the API correctly.  Including the `Sequel::SchemaDumper` class in Object is not going to work.  You probably want this:

```ruby
  require 'sequel'
 
  DB = Sequel.connect({
    adapter: ENV["db_adapter"].to_sym, 
    user: ENV["db_user"], 
    password: ENV["db_password"], 
    host: ENV["host"], 
    port: ENV["db_port"],
    database: ENV["db_database"], 
    max_connections: ENV["db_pool"],
  })

  DB.extension(:schema_dumper)
  DB.dump_schema_migration(indexes: true, foreign_keys: true)
```
