### ISSUE TITLE
Sequel.connect("sqlite://test.db?timeout=1000") raises TypeError

### ISSUE THREAD

**Issue by jmettraux** [jeremyevans/sequel#1620]
Hello,

thanks again for Sequel and Ruby on OpenBSD.

### Complete Description of Issue

I am trying to open a connection to a Sqlite3 database with a `timeout` URI query parameter and it fails.

* Ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
* Sequel 5.20.0

I like to use a simple connection string, it's more "portable" than a connection string plus a hash of options or a hash of options.

The documentation at https://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-Using+the+Sequel.connect+method says:

> You can use URI query parameters to specify options:
> (...)
> You can also pass an additional option hash with the connection string:
> (...)
> You can also just use an options hash without a connection string. If you do this, you must provide the adapter to use:
> (...)
> All of the above statements are equivalent.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'                                                                                 
                                                                                                 
Sequel.connect('sqlite://test.db')                 # OK                                          
                                                                                                 
Sequel.connect('sqlite://test.db', timeout: 1000)  # OK                                          
Sequel.connect('sqlite://test.db?timeout=1000')    # raises 
```

### Full Backtrace of Exception (if any)

```
Traceback (most recent call last):
	10: from t.rb:8:in `<main>'
	 9: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/core.rb:121:in `connect'
	 8: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/database/connecting.rb:58:in `connect'
	 7: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/database/connecting.rb:279:in `test_connection'
	 6: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	 5: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	 4: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
	 3: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
	 2: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/connection_pool.rb:122:in `make_new'
	 1: from /Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/adapters/sqlite.rb:115:in `connect'
/Users/jmettraux/.gem/ruby/2.5.1/gems/sequel-5.20.0/lib/sequel/adapters/sqlite.rb:115:in `busy_timeout=': TypeError: no implicit conversion of String into Integer (Sequel::DatabaseConnectionError)
```

### SQL Log (if any)

None.

**Comment by jeremyevans** [comment]
Thanks for the report.

The documentation in the guide isn't wrong.  `All of the above statements are equivalent.` is true for the example, as the values of `user` and `password` options are strings.  Sequel makes no guarantees about converting Database options to the appropriate type.

That being said, it's not difficult in this case to convert the value to an integer, so I'll take care of it.

**Comment by jmettraux** [comment]
Thanks a lot!
