### ISSUE TITLE
DB.create_table! should (maybe?) drop with CASCADE

### ISSUE THREAD

**Issue by doriantaylor** [jeremyevans/sequel#1621]
I'm currently writing a backend-agnostic tool and found that either `create_table!` behaviour might need additional semantics to include cascading, and/or the SQLite driver should interpret `:cascade` passed into `drop_table` as a no-op. Without the following workaround, I get a crash in Postgres without the explicit drop with cascade, and a crash in SQLite due to a SQL syntax error without testing the adapter scheme first. This is Sequel 5.20.0

Here is an example of my workaround:

```ruby
    def create_tables force: false
      # (note db here is an instance accessor)

      # sneaky
      method = 'create_table' + (force ? ?! : ??)

      # arrrgh you can't cascade for create_table!

      # double arggh sqlite has no drop table cascade
      cascade = force && db.adapter_scheme != :sqlite

      db.drop_table :user, cascade: true if cascade
      db.send method, :user do
        # need to do this if you want to auto increment
        primary_key :id, type: Integer, primary_key_constraint_name: :pk_user
        String   :principal, null: false, unique: true
        String   :email,     null: false, default: ''
        DateTime :added,     null: false, default: S::CURRENT_TIMESTAMP
        DateTime :disabled,  null: true
      end

      # more table definitions follow
    end
```

Thoughts?

**Comment by jeremyevans** [comment]
`create_table!` using `CASCADE` automatically is too risky, even ignoring the backwards compatibility issues.  However, maybe `create_table!` could take a `:drop_options` option and pass the options to `drop_table?`.  If that is something you are interested in, please send a pull request with specs and integration tests.

**Comment by doriantaylor** [comment]
Agreed `create_table!` shouldn't cascade without some kind of flag. It will probably take me a little while to circle back to this.

As for the SQLite issue (`CASCADE` being passed in when its `DROP TABLE` doesn't support it), do you want that in a separate PR?

**Comment by jeremyevans** [comment]
If you pass `:cascade` as an option to `drop_table?`, then `CASCADE` should be used, even if the underlying database does not support the syntax.  It is better for the database to raise an exception for an unsupported option than to explicitly and silently ignore the option when generating the SQL.  You'll find there are many places in Sequel where you can get an exception on specific databases when using features that the database doesn't support.

If you want to `:cascade` to work on SQLite, you'll have to get SQLite to support `DROP TABLE CASCADE`.
