### ISSUE TITLE
Dataset shadows Enumerable#select method

### ISSUE THREAD

**Issue by Sod-Almighty** [jeremyevans/sequel#1623]
The documentation says:

> Datasets are Enumerable objects, so they can be manipulated using any of the Enumerable methods

This is not correct.

The Dataset class defines its own `select` method, shadowing `Enumerable#select`. This is a problem.

**Comment by jeremyevans** [comment]
I agree, it should probably note that there are some methods that Dataset defines that override Enumerable methods.  As for `Dataset#select` becoming the same as `Enumerable#select`, that will never happen due to backwards compatibility issues.

**Comment by Sod-Almighty** [comment]
Then rather than just closing the ticket and leaving the problem unresolved, wouldn't it make more sense to implement some kind of `as_enumerable` method to return an object that *will* respect the expectation of Enumerable?

**Comment by jeremyevans** [comment]
I don't see it as an unresolved problem. There was a minor documentation issue, which I resolved by updating the documentation.  You should not assume that all `Enumerable` instance methods perform exactly the same way in every class that includes `Enumerable`.  Even some Ruby core classes that include `Enumerable` override some `Enumerable` methods.

This is Ruby, you are free to use `remove_method` to remove the `Dataset` methods that are different from `Enumerable` methods, or add an `as_enumerable` method, but neither is something I want to support.

**Comment by janko** [comment]
@jeremyevans What do you think about having `Dataset#each` return an Enumerator object when the block is *not* passed in?

```rb
def each
  return to_enum(:each) unless block_given?
  # ...
end
```

This is a general convention for any Enumerable object, and it seems like it shouldn't cause any backwards compatibility issues, because from what I can see `Dataset#each` currently requires a block.

**Comment by janko** [comment]
@Sod-Almighty By the way, this is how you can get an Enumerable object from a dataset today without any changes to Sequel (which respects `Enumerable#select`):

```rb
enumerable = dataset.enum_for(:each)
enumerable.select { ... } # this should work
```

**Comment by jeremyevans** [comment]
@janko That would slow down retrieval of records for all dataset objects, which is why I haven't done it.  You should use the explicit `enum_for(:each)` if you really need that behavior.

**Comment by Sod-Almighty** [comment]
@janko Thank you, that is helpful.

@jeremyevans Why would this have a significant performance impact?

**Comment by jeremyevans** [comment]
Every dataset method that retrieves data from the database goes through `Dataset#each`.  This would add an extra conditional and method call for everything that returns rows.  Individually, that's much a large cost, but a bunch of small calls do add up.  I don't think even a small performance decrease is worth the added functionality.
