### ISSUE TITLE
CTI: deleting dataset cause an error

### ISSUE THREAD

**Issue by okliv** [jeremyevans/sequel#1635]
I have two CTI models:

```ruby
class Transaction
  plugin :class_table_inheritance, key: :kind
end

class Payment < Transaction

end
```

now, if i simply try to delete something like this

    Payment.where(year: '2018').delete

i get this error:

```
Sequel::DatabaseError: PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 1: DELETE FROM (SELECT "transactions"."id", "transactions"."per...
```

and i have not found any other alternative to bulk delete filtered CTI dataset instead of ugly `each(&:delete)`

**Comment by jeremyevans** [comment]
This is expected.  You can't delete or update datasets that select from subqueries (as CTI model datasets do).  You can try:

```ruby
pks = Payment.where(year: '2018').select_order_map(Payment.primary_key)
Payment.cti_tables.reverse_each do |table|
  Payment.db.from(table).where(Payment.primary_key=>pks).delete
end
```

**Comment by okliv** [comment]
uh. thanks to provide a solution.

maybe this "hook" can be implemented as an overrider for `delete` method for every CTI datasets?

**Comment by jeremyevans** [comment]
I don't think it is a good idea to override the `delete` and `update` methods for CTI datasets.  I'm not sure the above code works in all possible cases.  However, I would accept a pull request to add documentation to the CTI plugin.

**Comment by okliv** [comment]
i would definitely make a pull req but feel shy because of quality of my english 🤓

by the way... it is not expected (for me at first view) that `Payment.delete_all` works... but it works

**Comment by jeremyevans** [comment]
`Model.delete_all` is not a method defined by Sequel, so I'm not sure where that comes from.

I can work on a documentation change later today.

**Comment by okliv** [comment]
whoops, my fault. `delete_all` method were implemented by my colleague. feel shy again.. have no reason to worry you anymore. thank a lot for your time.
