### ISSUE TITLE
Support for AWS RDS Data API

### ISSUE THREAD

**Issue by jonstokes** [jeremyevans/sequel#1636]
Amazon Aurora has a brand new connectionless Data API:

https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/

It would be awesome if Sequel supported this. Any plans?

**Comment by jeremyevans** [comment]
There are no plans for support for this shipping with Sequel.  However, someone could definitely work on an external adapter if they are interested in supporting it.

**Comment by joelvh** [comment]
@jeremyevans is there a guide to create a custom adapter? Could you point me to a starting point so I can evaluate what's involved if I were to take a stab at this? Thanks!

**Comment by jeremyevans** [comment]
I don't think there is currently a guide.  There are plenty of examples in the adapters that ship with Sequel, and you can use Sequel's integration tests as a test suite.

**Comment by joelvh** [comment]
OK, thanks @jeremyevans - I figured that might be all there is to go by.

**Comment by chadmyers** [comment]
👍 on adding support for this.

If anyone has built an adapter for the Data API, please post a link here as I think some folks might find it useful. Thanks!
