### ISSUE TITLE
Console like AR

### ISSUE THREAD

**Issue by dcalixto** [jeremyevans/sequel#1637]
Hello! @jeremyevans  thank you for the work! 
Just one doubt!
how to run a console with sequel like for exemple with AR

```
require 'sinatra/activerecord/rake'

task :console do
  Pry.start
end

```

**Comment by v-kolesnikov** [comment]
@dcalixto https://github.com/jeremyevans/sequel#the-sequel-console

**Comment by jeremyevans** [comment]
As @v-kolesnikov linked to, Sequel ships with a `sequel` command line tool that should do what you want.

As the contribution guidelines state, GitHub Issues should only be used to report bugs in Sequel.  Please use IRC or the Google Group if you have questions about Sequel.
