### ISSUE TITLE
CreateTableGenerator#exclude has no place to use a different opclass

### ISSUE THREAD

**Issue by fdr** [jeremyevans/sequel#1639]
### Complete Description of Issue

In, https://www.rubydoc.info/gems/sequel/4.38.0/Sequel/Postgres/CreateTableGenerator#exclude-instance_method, there is no place to put in a non-default opclass.

### Simplest Possible Self-Contained Example Showing the Bug

Try to write any migration that uses "&&" with a cidr type.

This concretely manifests when trying to use exclusion constraints with cidr data types, which for probably-legacy reasons need a non-default opclass specification, generating SQL rather like this, noting the syntactic element "inet_ops":

```sql
ALTER TABLE networks ADD CONSTRAINT cidr_disjoint
  EXCLUDE USING GIST (net_id with =, cidr inet_ops with &&);
```

...or its `CREATE TABLE` equivalent.

Migration showing intent:

```ruby
Sequel.migration do
  change do
    create_table(:networks) do
      primary_key  :id
      text         :name, null: false
      cidr         :cidr, null: false
      exclude([[:name, '='], [:cidr, '&&']])
    end
  end
end
```

Crashes with:

```
ERROR -- : PG::WrongObjectType: ERROR:  operator &&(inet,inet) is not a member of operator family "gist_cidr_ops"
DETAIL:  The exclusion operator must be related to the index operator class for the constraint.: CREATE TABLE "networks" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" text NOT NULL, "cidr" cidr NOT NULL, EXCLUDE USING gist ("name" WITH =, "cidr" WITH &&))
```

**Comment by jeremyevans** [comment]
You need to use `Sequel.lit` for this:

```ruby
DB.alter_table(:networks) do
  add_exclusion_constraint({:net_id=>'=', Sequel.lit('cidr inet_ops')=>'&&'}, :name=>:cidr_disjoint)
end
```

Direct support for this could not be reasonably handled via an option to `exclude`/`add_exclusion_constraint`, since the op class can differ per element.

I'll update the documentation to explain this.
