### ISSUE TITLE
Loading `:core_extensions` causes an error when comparing dates with symbols

### ISSUE THREAD

**Issue by pabloh** [jeremyevans/sequel#1645]
### Complete Description of Issue

When loading `:core_extensions` it becomes impossible to compare a `Date`/`DateTime` with a `Symbol` if the `Date`/`DateTime` is on the left side of the comparison.
The error does not occur if you put the `Symbol` on the left.

```ruby
Date.today == :today # NoMethodError: super: no superclass method `coerce' for :today:Symbol 
DateTime.now == :now # NoMethodError: super: no superclass method \`coerce' for :now:Symbol
```
### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'

:today == Date.today # false
:now == DateTime.now # false
Date.today == :today # false
DateTime.now == :now # false

Sequel.extension(:core_extensions)

:today == Date.today # false
:now == DateTime.now # false
Date.today == :today # NoMethodError: super: no superclass method `coerce' for :today:Symbol
DateTime.now == :now # NoMethodError: super: no superclass method `coerce' for :now:Symbol
```

### Full Backtrace of Exception (if any)
```
ruby -r sequel -e "Sequel.extension(:core_extensions)
begin Date.today == :today; rescue => e; puts e.backtrace; end"

/home/pablo/.rvm/gems/ruby-2.5.5/gems/sequel-5.24.0/lib/sequel/sql.rb:792:in `coerce'
-e:1:in `<=>'
-e:1:in `=='
-e:1:in `<main>'
```

**Comment by jeremyevans** [comment]
This appears to be a bug in Date/DateTime, it should not be trying to call `coerce` on an object that doesn't respond to it.  I'll see if I can fix that upstream.

**Comment by jeremyevans** [comment]
Actually, this is a bug in Sequel.  `coerce` is defined, but it is calling `super` without checking whether `super` is defined.  Should be simple to fix.

**Comment by pabloh** [comment]
Thanks!
