### ISSUE TITLE
Sequel::Plugins::JsonSerializer problem with :include

### ISSUE THREAD

**Issue by Jesterovskiy** [jeremyevans/sequel#1646]
Hi @jeremyevans. I found something strange in behaviour of JsonSerializer plugin:

```
test_data = TestData.first
test_data.to_json(include: :other_data)

... \"other_data\":[{\"id\":10 ...

test_data.to_json(include: {other_data: {only: :id}})

... \"other_data\":[{\"json\":\"{\\\"id\\\":10 ...
```
Why I get `json` and how I can drop it?

**Comment by jeremyevans** [comment]
You can only pass through options with a nested hash if `other_data` is an association.  Is that true in this case?  I can't tell based on the context. You should probably include a minimal self-contained example that reproduces the problem.

**Comment by Jesterovskiy** [comment]
Yes, it has association `one_to_many : other_data`. Ok, I'll try to prepare test data

**Comment by Jesterovskiy** [comment]
Sequel::Model.plugin :json_serializer

class TestData < Sequel::Model
  one_to_many : other_data
end

class OtherData < Sequel::Model
  many_to_one :test_data
end

**Comment by jeremyevans** [comment]
You are probably loading active support's JSON support, which breaks things.  This is explicitly warned against in the json_serializer documentation.

Minimal self contained example:

```ruby
Sequel::Model.plugin :json_serializer

DB.create_table(:test_data){primary_key :id; String :name}
DB.create_table(:other_data){primary_key :id; String :name; Integer :test_data_id}

class TestData < Sequel::Model(:test_data)
  one_to_many :other_data, class: :OtherData
end

class OtherData < Sequel::Model(:other_data)
  many_to_one :test_data, class: :TestData
end

td = TestData.create(name: 'a')
td.add_other_datum(name: 'b')
p td.to_json(include: :other_data)
p td.to_json(include: {other_data: {only: :id}})
```

Running:

```
$ bin/sequel sqlite:/ t.rb
"{\"id\":1,\"name\":\"a\",\"other_data\":[{\"id\":1,\"name\":\"b\",\"test_data_id\":1}]}"
"{\"id\":1,\"name\":\"a\",\"other_data\":[{\"id\":1}]}"
$ bin/sequel -ractive_support/all sqlite:/ t.rb
"{\"id\":1,\"name\":\"a\",\"other_data\":[{\"id\":1,\"name\":\"b\",\"test_data_id\":1}]}"
"{\"id\":1,\"name\":\"a\",\"other_data\":[{\"json\":\"{\\\"id\\\":1}\"}]}"

```

**Comment by Jesterovskiy** [comment]
@jeremyevans Thank you! I found in doc, that you suggest fix `to_json`, but I can't understand, how to properly apply this. Maybe you can help?

**Comment by jeremyevans** [comment]
The proper fix is to stop using active_support/json.  If you can't do that, you can use the example code in the doc, but that will probably break code relying on active_support/json's modified API.
