### ISSUE TITLE
Dirty plugin not working with blobs

### ISSUE THREAD

**Issue by assembler** [jeremyevans/sequel#1647]
### Complete Description of Issue

The dirty plugin is not working properly on columns of binary type. The problem is that the value is converted to `Blob` object upon assignment so the comparison to initial value which is retrieved from database (and is a `String`) always fails, thus the object is always dirty.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
> media = Media.first
> media.digest
=> "v\x83\x1E\x82L:]\xAA\x17\xFE\xC9\xC4\f2\xD1+\xB75\x12\xC7Q\f\x85Q\x9F\xC1x\xB7\xF8\xFE\x17F"

> media.digest = media.digest
> media.digest
=> #<Sequel::SQL::Blob:0x3ff5d48d0a2c bytes=32 start="v\x83\x1E\x82L:]\xAA\x17\xFE" end="\x85Q\x9F\xC1x\xB7\xF8\xFE\x17F">

> media.column_changed?(:digest)
=> true

> media.digest.to_s ==  media.initial_value(:digest).to_s
=> true

```

**Comment by jeremyevans** [comment]
What adapter are you using?  The correct way to handle this is for the adapter to do the type conversion for you.  Unfortunately, not all adapters do that.  If the adapter does not do that, you can try the typecast_on_load plugin.  I'm not sure if the typecast_on_load plugin currently works with the dirty plugin, but if it doesn't that can probably be added.

**Comment by jeremyevans** [comment]
The dirty plugin wasn't working with the typecast_on_load plugin, but after the changes in 272fd37543c168481e91e8c146340e3ae5ce78c6, it is now.  I think that will solve your issue.  If not, please reopen and provide details why it does not.

**Comment by assembler** [comment]
Hey @jeremyevans, thanks for looking into this. Your commit along with the use of `typecast_on_load` did the trick! It works now. Can you bump the gem version? Thanks!

**Comment by assembler** [comment]
Actually, `272fd37` introduces some new problems. When new record is created, it is no longer marking any column as changed. Here is an example:

```ruby
class Media < Sequel::Model(Hub.db[:medias])
  plugin :dirty
  plugin :typecast_on_load, :digest

  def after_save
    puts "Saved. Digest changed: #{column_changed?(:digest)}"
  end
end

media = Media.new
media.digest = 'digest'
media.save
```

Before  we had the following script output: `Saved. Digest changed: true`. This makes sense because the digest has changed from `nil` to `something`.

However, with the `272fd37`, the output changes to `Saved. Digest changed: false`.

Perhaps i'm misunderstanding how the dirty should work with hooks. I want to have logic like `do_something if column_changed?(:digest)` in `after_save` which covers both the case when new record is created and existing one is being updated.

**Comment by AlexWayfer** [comment]
> Can you bump the gem version? Thanks!

@assembler, please read https://github.com/jeremyevans/sequel#sequel-release-policy

**Comment by jeremyevans** [comment]
I see what the problem is.  `typecast_on_load` needs to move the `_clear_changed_columns` call to callers of `load_typecast` so they can correctly set the reason.  I'll make that change today.
