### ISSUE TITLE
Surprising behaviour when comparing PGRanges

### ISSUE THREAD

**Issue by steveh** [jeremyevans/sequel#1648]
### Complete Description of Issue

Ruby uses a different code path to compare arrays of  `SMALL_ARRAY_LEN` (16) elements or fewer. I haven't dug into [the source](https://ruby-doc.org/core-2.6.5/Array.html#method-i-2D), but I suspect that implementing `PGRange#hash` will fix this.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
builder = -> { 17.times.collect { |i| Sequel::Postgres::PGRange.new(i, i*2) } }

group1 = builder.call
group2 = builder.call

puts (group1[0..15] - group2[0..15]).size
# => 0

puts (group1[0..16] - group2[0..16]).size
# => 17 (expected 0)
```

**Comment by jeremyevans** [comment]
It certainly makes sense that if 2 `PGRange`s are equal, they should have the same hash.  I'll fix this tomorrow.
