### ISSUE TITLE
Using DateTime in filter ignores timezone (MySQL)

### ISSUE THREAD

**Issue by hkmaly** [jeremyevans/sequel#1652]
### Complete Description of Issue
Datetime with different timezone has timezone ignored when used in filter.
MySQL (with mysql2 0.5.2 gem OR mysql 2.9.1 gem), Sequel 5.25.0
column \`start_time\` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
timezone on server is GMT
### Simplest Possible Self-Contained Example Showing the Bug
require 'time'
require 'sequel'
x = DateTime.parse('2019-10-19T14:00:00-04:00')
DB = Sequel.connect("mysql2://....:3306/main?encoding=utf8")
puts DB[:calendar_events].filter(:start_time => x).select_sql
puts DB[:calendar_events].filter(:start_time => x.to_time).select_sql
### outputs
SELECT * FROM \`calendar_events\` WHERE (\`start_time\` = '2019-10-19 14:00:00')
SELECT * FROM \`calendar_events\` WHERE (\`start_time\` = '2019-10-19 18:00:00')
### expected output
SELECT * FROM \`calendar_events\` WHERE (\`start_time\` = '2019-10-19 18:00:00')
SELECT * FROM \`calendar_events\` WHERE (\`start_time\` = '2019-10-19 18:00:00')

**Comment by jeremyevans** [comment]
It looks like your Database timezone may not be set to `:utc`.  If you fix that, things should work:

```ruby
x = DateTime.parse('2019-10-19T14:00:00-04:00')
DB = Sequel.connect('mock://mysql')
puts DB[:calendar_events].filter(:start_time => x).select_sql
# SELECT * FROM `calendar_events` WHERE (`start_time` = '2019-10-19 14:00:00')
DB.timezone = :utc
puts DB[:calendar_events].filter(:start_time => x).select_sql
# SELECT * FROM `calendar_events` WHERE (`start_time` = '2019-10-19 18:00:00')
```

**Comment by hkmaly** [comment]
Of course it's not set. There is no warning anywhere that you need to set databaze timezone to make Sequel work. It works with Time.

**Comment by jeremyevans** [comment]
`DateTime` has the same behavior as `Time`:

```ruby
DB = Sequel.connect('mock://mysql')

x = DateTime.parse('2019-10-19T14:00:00-04:00')
# => #<DateTime: 2019-10-19T14:00:00-04:00 ((2458776j,64800s,0n),-14400s,2299161j)>

t = x.to_time
# => 2019-10-19 14:00:00 -0400

DB[:calendar_events].filter(:start_time => x).select_sql
# => "SELECT * FROM `calendar_events` WHERE (`start_time` = '2019-10-19 14:00:00')"

DB[:calendar_events].filter(:start_time => t).select_sql
# => "SELECT * FROM `calendar_events` WHERE (`start_time` = '2019-10-19 14:00:00')"

DB.timezone = :utc

DB[:calendar_events].filter(:start_time => x).select_sql
# => "SELECT * FROM `calendar_events` WHERE (`start_time` = '2019-10-19 18:00:00')"

DB[:calendar_events].filter(:start_time => t).select_sql
# => "SELECT * FROM `calendar_events` WHERE (`start_time` = '2019-10-19 18:00:00')"
```

One possible explanation for the behavior you are seeing could be you are using an old version of Ruby (Ruby <2.4) where `DateTime#to_time` will convert the timezone in the returned `Time` to the process's current timezone.  This is assuming your process timezone is GMT/UTC.

**Comment by hkmaly** [comment]
... so, it will be even WORSE with newer Ruby? Thanks for warning.

Also, yes, my process timezone is GMT/UTC, the timezone of the MySQL server process is GMT/UTC and I would expect that between those two, Sequel will be able to guess I want it to use GMT/UTC as well (considering I didn't explicitly SET the timezone to anything), talk with database in way which would PRESERVE the timezone or, failing that, raise an exception. Not silently turn the data to garbage.

Hint:
```
SELECT @@global.time_zone, @@session.time_zone, @@system_time_zone;
SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);
```
and also see https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_convert-tz
```
SELECT convert_tz(now(),@@session.time_zone,'+00:00')
```
... also, if you are given Time, you can use FROM_UNIXTIME and UNIX_TIMESTAMP, not only it would be more reliable, it would also be FASTER than parsing date strings (obviously, if you are given DateTime, it would reduce range).

**Comment by hkmaly** [comment]
(I'm actually changing my programs to set Sequel.default_timezone ...)

Usually, MySQL would do the correct thing if the generated query would be
```
SELECT * FROM `calendar_events` WHERE (`start_time` = convert_tz('2019-10-19 14:00:00', '-04:00', @@session.time_zone));
```
... unfortunately I'm not sure what it would do with possible differences in daylight savings time or if it would be possible to specify the timezone in way Ruby and MySQL would agree on the meaning ... I guess it would be same dangerous assumption as the "local time" one.

I'll try the Google Group if I find it ...
