### ISSUE TITLE
Shard / Server specific Caching

### ISSUE THREAD

**Issue by jrgns** [jeremyevans/sequel#1653]
### Complete Description of Issue

The caching plugin assumes that the record with id 1 from table `records` on shard A is the same as the record with id 1 from table `records` on shard B.

Although this is true for the general case (a shared DB schema with data distributed across various DB shards), it breaks caching when sharding is used to run multiple shards with a common DB schemas, but data unique to each shard.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
servers = { client1: { database: 'client1' }, client2: { database: 'client2' }}
DB = Sequel.connect('postgres://hash_host/hashes', servers: servers)
CACHE = Memcached.new(ENV['MEMCACHED_URL'])
Sequel::Model.plugin :caching, CACHE, ignore_exceptions: true

DB.with_server(:client1) { Record[1] } # This will hit the DB as the cache is empty
DB.with_server(:client2) { Record[1] } # This will use the cached entry from the line above
```

**Comment by jeremyevans** [comment]
Thanks for the report. Agreed, this is not a case where the caching plugin should be used.  We should probably update the documentation to warn against using the caching plugin when `Model.[]` can return different results.  If you want to submit a pull request for that, please do so.  Otherwise, I will take care of it before the next release.

**Comment by jrgns** [comment]
@jeremyevans I want to see if I can update the caching plugin to include the shard in the cache key. Something like:

```ruby
        # Return a key string for the given primary key.
        def cache_key(pk)
          raise(Error, 'no primary key for this record') unless pk.is_a?(Array) ? pk.all? : pk
          "#{shard_name}:#{cache_key_prefix}:#{Array(pk).join(',')}"
        end
```

or even

```ruby
        # Returns the prefix used to namespace this class in the cache.
        def cache_key_prefix
          return to_s unless sharded?

          "#{shard_name}:#{to_s}"
        end
```

The `sharded?` and `shard_name` methods will need to be implemented too.

Is that something you'll consider including?

To make it even more general, it might be possible to add a `cache_key_prefix` option which can be used in the `cache_key_prefix` method, and be set to the shard name (or anything else the user might require).

**Comment by jrgns** [comment]
If anyone needs this, I extended the Caching plugin to create a ShardedCaching plugin:

```ruby
module Sequel
  module Plugins
    module ShardedCaching
      def self.apply(model, store, opts = OPTS)
        model.instance_eval do
          plugin :caching, store, opts
        end
      end

      module ClassMethods
        # Returns the prefix used to namespace this class in the cache.
        def cache_key_prefix
          current_shard.to_s + '::' + to_s
        end

        def current_shard
          db.pool.instance_variable_get(:@default_servers).first[-1][0][-1]
        end
      end
    end
  end
end
```

It basically just modifies the caching prefix to include the name current shard.

@jeremyevans Getting the current shard seems to be quite convoluted. Is there a better way to do it?

**Comment by jeremyevans** [comment]
I think you could do `db.pool.send(:pick_server, :default)`.

**Comment by jrgns** [comment]
@jeremyevans works great, thanx.
