### ISSUE TITLE
A README.md to highlight ruby syntax

### ISSUE THREAD

**Issue by CharlyJazz** [jeremyevans/sequel#1654]
If each example of the Readme file could be highlighted, it would increase the developer experience.

Why is the current Readme rdoc?

This is a example of a readme ruby highlighed code

# A Short Example

``` ruby
require 'sequel'

DB = Sequel.sqlite # memory database, requires sqlite3

DB.create_table :items do
  primary_key :id
  String :name
  Float :price
end

items = DB[:items] # Create a dataset

# Populate the table
items.insert(:name => 'abc', :price => rand * 100)
items.insert(:name => 'def', :price => rand * 100)
items.insert(:name => 'ghi', :price => rand * 100)

# Print out the number of records
puts "Item count: #{items.count}"

# Print out the average price
puts "The average price is: #{items.avg(:price)}"
```

:cupid:

**Comment by adam12** [comment]
All documentation for Sequel is in RDoc. Makes sense that the README is as well, for consistency.

You'll find more context in the duplicate issue #1500, #1249, and maybe others.

**Comment by jeremyevans** [comment]
The README is syntax highlighted: http://sequel.jeremyevans.net/rdoc/files/README_rdoc.html

Now, that may not be true on GitHub, but that is a GitHub bug.

I don't want to use a different format for the README than I used for all of Sequel's other documentation, and I don't want to reformat all documentation from rdoc to markdown.

**Comment by CharlyJazz** [comment]
Fine i am agree now :lollipop:
