### ISSUE TITLE
table alias with insert

### ISSUE THREAD

**Issue by 7dr1v3** [jeremyevans/sequel#1656]
### Complete Description of Issue
Sequel 5.25
Postgres 10
I try to set alias for a table in insert expression. I need it for "insert on conflict" and Postgres can do it after 9.5 version. 

### Simplest Possible Self-Contained Example Showing the Bug
`DB[Sequel[:users].as(:test)]` 
=> `SELECT * FROM "users" AS "test"` - everything is OK
`DB[Sequel[:users].as(:test)].insert(a: 1)` 
=> `INSERT INTO "users" ("a") VALUES (1) RETURNING NULL` - alias was lost

**Comment by jeremyevans** [comment]
I suppose we could allow aliases in `INSERT` if the database supports it.  I don't think it is required for insert on conflict support to work (where you could use the unaliased name for qualified columns), but it shouldn't cause problems and should make things easier.

**Comment by 7dr1v3** [comment]
@jeremyevans I need it just because I use insert on conflict in a circle with different tables, so thank you.
