### ISSUE TITLE
alter_column refresh_at, Time, only_time: false

### ISSUE THREAD

**Issue by AustinBlues** [jeremyevans/sequel#1658]
Using Sequel 5.25.0 and Padrino 0.14.4, I expect after running the migration below that the date and time is stored in the database.  Instead only the time is stored.  The MariaDB type of the altered column is 'time'.  I expected 'timestamp'.  Before the migration the MariaDB column type was 'datetime'.

If the table is created, this works as documented.  If the table is altered, it doesn't.

Sequel.migration do
  up do
    alter_table :feeds do
      set_column_type :refresh_at, :Time, only_time: false
    end
  end

  down do
    alter_table :feeds do
      set_column_type :refresh_to, :Datetime
    end
  end
end

**Comment by jeremyevans** [comment]
You are using `:Time`, not `Time`.  When you provide a symbol and not a class as the type, Sequel uses the symbol verbatim as the type.  See http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-Column+types, where it says: `If a symbol or string is used as the type, it is used verbatim as the type name in SQL`.  If you change to `Time`, things will work correctly.
