### ISSUE TITLE
Using update with expression is badly documented

### ISSUE THREAD

**Issue by hkmaly** [jeremyevans/sequel#1663]
"Best" documentation about using update I found is https://sequel.jeremyevans.net/rdoc/files/doc/cheat_sheet_rdoc.html#label-SQL+Functions+-2F+Literals which shows how to use functions but doesn't specify what to do when you want to use expression.

Virtual row blocks doesn't seem to work with update.

I suppose that simplest way (without using core_extension or other module) to, for example, increment value by one is
```
update(:value => Sequel.identifier(:value) + 1)
```

Can this be added into documentation, maybe with few other examples if there is something else which might be surprising?

**Comment by AlexWayfer** [comment]
You can find documentation for similar functionality at https://sequel.jeremyevans.net/rdoc/files/doc/sql_rdoc.html#label-Standard+Mathematical+Operators+-28-2B+-+-2A+-2F-29

Please, remember, that `Sequel[:value]` (or `Sequel[:table][:value]`) is simpler form of `Sequel.identifier(:value)`.

**Comment by hkmaly** [comment]
Thanks for answer. Could this link be added to the place of cheat sheet I mentioned?

**Comment by jeremyevans** [comment]
I'll add an example to the cheat sheet.  Probably after the release on Sunday.

**Comment by janko** [comment]
@hkmaly Note that the place you linked to isn't actually documentation for the `#update` method, it's for "SQL Functions / Literals", as the section title says.

When I want documentation for a specific method, I usually look at the RDocs, and the [`#update`](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-update) docs there *do* have an example of building expressions.

**Comment by AlexWayfer** [comment]
> When I want documentation for a specific method, I usually look at the RDocs, and the #update documentation there does have an example of building expressions.

This is good point. "Cheat sheet" can't contain all methods and variations of usage.
