### ISSUE TITLE
`NameError` for BigDecimal in v4.* in Ruby 2.7.0

### ISSUE THREAD

**Issue by voikya** [jeremyevans/sequel#1666]
I'm not sure if you're planning on any sort of ongoing support for the v4.* series, but it looks like it's no longer compatible with Ruby 2.7.0, at least when using the postgres adapter. Attempting to open a connection with a postgres database results in a `NameError` exception due to it attempting to call `BigDecimal.new`.

```
NameError: undefined method `new' for class `#<Class:BigDecimal>'
Did you mean?  next
gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:89:in `method'
gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:89:in `<module:Postgres>'
gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:19:in `<module:Sequel>'
gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:5:in `<top (required)>'
gems/sequel-4.49.0/lib/sequel/core.rb:228:in `block in require'
gems/sequel-4.49.0/lib/sequel/core.rb:228:in `each'
gems/sequel-4.49.0/lib/sequel/core.rb:228:in `require'
gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:3:in `<top (required)>'
gems/sequel-4.49.0/lib/sequel/database/connecting.rb:111:in `load_adapter'
gems/sequel-4.49.0/lib/sequel/database/connecting.rb:39:in `adapter_class'
gems/sequel-4.49.0/lib/sequel/database/connecting.rb:68:in `connect'
gems/sequel-4.49.0/lib/sequel/core.rb:116:in `connect'
```

This appears to have been fixed preemptively in v5.9.0: https://github.com/jeremyevans/sequel/commit/dfa587e0981736f6e7677de2c634dbda75045491

If you don't plan on backporting this, I would recommend just putting in a notice in the README somewhere that Sequel ≥5 is needed for starting with Ruby 2.7.0.

**Comment by jeremyevans** [comment]
I'm sorry, I do not plan to update the README to reference a version of Sequel that went out of support over 2 years ago.  Just to make clear the policy: 

1. Only the master branch and the most recent gem version are supported.
2. All development occurs on the master branch.
3. Bugfixes are only backported from the master branch to the most recent gem version to fix regressions that first occurred in the most recent gem version, or for security issues.

FWIW, I think in 2.7.0 you can install and activate an older version of the `bigdecimal` gem before requiring Sequel, and then things should continue to work in Sequel 4.
