### ISSUE TITLE
Inaccurate/confusing description for column :primary_key

### ISSUE THREAD

**Issue by dteoh** [jeremyevans/sequel#1670]
In the docs for `Sequel::Schema::CreateTableGenerator#column` `:primary_key` option:

"This should not be used if you have a single, **nonautoincrementing** primary key column (use the primary_key method in that case)."

This is the opposite, you should not use it if you have an autoincrement PK column.

I think maybe rewriting this to when you can use the option would be easier to read?

"This should be used if you do not want to use an auto-incrementing PK column."

**Comment by jeremyevans** [comment]
Thanks for catching that.  I'll fix the documentation shortly.
