### ISSUE TITLE
Reading Float values

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [jeremyevans/sequel#1673]
### Complete Description of Issue
When inserting floating-point (`Float`) values into the database and reading them back. The values slightly change. The values are correctly stored in the database.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
> connection[:zones].insert(zone1_min: 1.1, zone1_max: 1.2, zone2_min: 1.3, zone2_max: 1.4, zone3_min: 1.5, zone3_max: 1.6, zone4_min: 1.7, zone4_max: 1.8, zone5_min: 1.9, zone5_max: 2.0)
=> 509588439

> connection[:zones].where(id: 509588439).first
=> {
  :id=>509588439,
  :zone1_min=>1.100000023841858,
  :zone1_max=>1.2000000476837158,
  :zone2_min=>1.2999999523162842,
  :zone2_max=>1.399999976158142,
  :zone3_min=>1.5,
  :zone3_max=>1.600000023841858,
  :zone4_min=>1.7000000476837158,
  :zone4_max=>1.7999999523162842,
  :zone5_min=>1.899999976158142,
  :zone5_max=>2.0
}
```

### SQL Log
```
# INSERT
I, [2020-01-16T18:15:21.661594 #41851]  INFO -- : (0.013549s) INSERT INTO `zones` (`zone1_min`, `zone1_max`, `zone2_min`, `zone2_max`, `zone3_min`, `zone3_max`, `zone4_min`, `zone4_max`, `zone5_min`, `zone5_max`) VALUES (1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0)

# READ
I, [2020-01-16T18:16:17.381671 #41851]  INFO -- : (0.001336s) SELECT * FROM `zones` WHERE (`id` = 509588439) LIMIT 1
```

### Version Details
Sequel: `5.28.0`
Ruby:    `JRuby-9.2.9.0`
MySQL: `5.7.28`

**Comment by jeremyevans** [comment]
Can you please create a self contained example showing the error?  I tried with Sequel 5.28.0, JRuby 9.2.9.0, and MariaDB 10.0.38 and couldn't recreate:

```ruby
DB.create_table(:a){Float :a}
# CREATE TABLE `a` (`a` double precision)
# => nil
irb(main):006:0> DB[:a].insert(1.1)
# INSERT INTO `a` VALUES (1.1)
# => 0
DB[:a].all
# SELECT * FROM `a`
# => [{:a=>1.1}]
```

Same results with MySQL 8.0.11.

**Comment by ThomasKoppensteiner** [comment]
I think the main difference here is, that your example uses `'a' double precision` where as our existing table was created with `float DEFAULT NULL`.

```
CREATE TABLE `zones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `zone1_min` float DEFAULT NULL,
  `zone1_max` float DEFAULT NULL,
  `zone2_min` float DEFAULT NULL,
  `zone2_max` float DEFAULT NULL,
  `zone3_min` float DEFAULT NULL,
  `zone3_max` float DEFAULT NULL,
  `zone4_min` float DEFAULT NULL,
  `zone4_max` float DEFAULT NULL,
  `zone5_min` float DEFAULT NULL,
  `zone5_max` float DEFAULT NULL,
  PRIMARY KEY (`id`)
) 

```

**Comment by ThomasKoppensteiner** [comment]
Your example works also on MySQL `5.7.28` and creates a table with `double`.

```
CREATE TABLE `a` (
  `a` double DEFAULT NULL
)
```

**Comment by jeremyevans** [comment]
It seems the MySQL `float` type uses single precision instead of double precision.  When JRuby converts the MySQL data into a Ruby object using JDBC getFloat, it gives you the closest double precision value (Ruby Float uses double precision) to the single precision value provided by MySQL.  That apparently doesn't match the initial double precision input value.  This isn't a bug in Sequel, merely a consequence of Ruby's behavior.  You can work around the issue by rounding the floats:

```
DB.create_table(:a){float :a}
DB[:a].insert(1.1)
DB[:a].insert(1.100000023841858)
DB[:a].select_map{a.cast(String).as(:v)}
# => ["1.1", "1.1"]
DB[:a].select_map{a}
# => [1.100000023841858, 1.100000023841858]
DB[:a].select_map{a}.map{|x| x.round(7)}
=> [1.1, 1.1]
```

**Comment by ThomasKoppensteiner** [comment]
Thank you for our investigation.
