### ISSUE TITLE
Assigning many_to_one association on existing record with generated_always_as column fails

### ISSUE THREAD

**Issue by joeosburn** [jeremyevans/sequel#1681]
### Complete Description of Issue

I have an `Account` which has many (`one_to_many`) `Donations`. These are both Sequel models, with their respective database tables in Postgres. As referenced in issue #1680, I added a `generated_always_as` column to the `donations` table. The `generated_always_as` column in question in this case is called `search`.

If I create a new `Donation` record and then assign the account to it via `account.add_donation(donation)` or by directly setting the `account` attribute and then saving, it fails because the generated `UPDATE` SQL statement attempts to manually assign the `search` column.

### Simplest Possible Self-Contained Example Showing the Bug

```
donation = Donation.create(name: 'Joe', description: 'a donation')
account = Account.create
account.add_donation(donation)
```

### Full Backtrace of Exception (if any)

```
[2020-03-06T15:52:54.510-06:00] INFO: (0.000108s) BEGIN
[2020-03-06T15:52:54.511-06:00] ERROR: PG::SyntaxError: ERROR:  column "search" can only be updated to DEFAULT
DETAIL:  Column "search" is a generated column.: UPDATE "donations" SET "account_id" = 4, "description" = 'a donation', "created_at" = '2020-03-06 21:52:50.156433+0000', "updated_at" = '2020-03-06 21:52:54.510688+0000', "name" = 'Joe', "search" = 'Joea donation' WHERE ("id" = 120)
[2020-03-06T15:52:54.511-06:00] INFO: (0.000099s) ROLLBACK
Sequel::DatabaseError: PG::SyntaxError: ERROR:  column "search" can only be updated to DEFAULT
DETAIL:  Column "search" is a generated column.
from /Users/joe/.rvm/gems/ruby-2.6.5/bundler/gems/sequel-77b6db742f45/lib/sequel/adapters/postgres.rb:156:in `exec'
Caused by PG::SyntaxError: ERROR:  column "search" can only be updated to DEFAULT
DETAIL:  Column "search" is a generated column.

from /Users/joe/.rvm/gems/ruby-2.6.5/bundler/gems/sequel-77b6db742f45/lib/sequel/adapters/postgres.rb:156:in `exec'
```

**Comment by jeremyevans** [comment]
The default behavior with Sequel::Model is that all values of the instance are saved to the database, regardless of whether the keys in the values are columns in the underlying table or you have access to update them.  You get the same behavior if you use database permissions to revoke the update permission to a non-generated column, for instance.  So I don't think that this is necessarily a bug, though we could offer a way to make this easier for the user of generated columns.

I think it makes sense to add a plugin that recognizes which columns are generated and does not attempt to save them.  That should be possible now that the schema entries flag generated columns.  Should be fairly simple to implement by overriding `Model#_save_update_all_columns_hash` and calling super, then deleting more entries from the hash before returning it.  Is that something you think you could work on?

**Comment by joeosburn** [comment]
Makes sense. Yeah, I can work on that. I'll aim for something in the next day or two.

**Comment by joeosburn** [comment]
Just to give you an update, I have a plugin written with a simple spec. I need to work on the comments and tighten up a few things, but I'll work on getting it submitted as a PR tomorrow.
