### ISSUE TITLE
RSpec warning

### ISSUE THREAD

**Issue by MicMicMon** [jeremyevans/sequel#1686]
### Complete Description of Issue

When running RSpec specs on my projet, I get this warning when warnings are enabled:
```sh
/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.31.0/lib/sequel/dataset/query.rb:84: warning: statement not reached
```

Using Ruby 2.7.1.

**Comment by jeremyevans** [comment]
This is a verbose-mode warning, and expected due to an optimization that Sequel uses. If you want to ignore it:

```ruby
require 'warning' # warning gem
Warning.ignore(:not_reached)
```

**Comment by MicMicMon** [comment]
Got it, thanks!

**Comment by qortex** [comment]
Following up, this gem is amazing (as usual!). Thanks a lot.
Used:
```
Warning.ignore(:not_reached, /.*query\.rb/)
```
And useful to silence warnings from a bunch of other gems too. Very nice.
