### ISSUE TITLE
MSSQL connection cannot be used by Ruby 2.6 because of tiny_tds issue 

### ISSUE THREAD

**Issue by centuryfall** [jeremyevans/sequel#1688]
### Complete Description of Issue
On Windows 10, if I want to use Ruby 2.6, I will not be able to leverage a **tiny_tds** connection if I want to connect to a MSSQL database.

_However,_ There is currently a new **tiny_tds** version being tested for 2.6: [version 2.1.3-pre](https://github.com/rails-sqlserver/tiny_tds/issues/434#issuecomment-611174907).

I just want to make awareness around how Sequel will handle this for Ruby 2.6 if this new tiny_tds gem version will work for 2.6?

Thanks.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
# Validate the Ruby version is at least 2.6
raise RuntimeError unless RUBY_ENGINE_VERSION >= '2.6'

require 'sequel'
require 'tiny_tds' # Test should produce error here

# It should never reach here
Sequel.connect({adapter: 'tinytds',
                          host: 'HOST',
                          port: 'PORT',
                          database: 'DATABASE',
                          user: 'USERNAME',
                          password: 'PASSWORD'})
```

### Full Backtrace of Exception (if any)
```
ERROR: Error installing tiny_tds:
The last version of tiny_tds (>= 0) to support your Ruby & RubyGems was 2.1.2. Try installing it with gem install tiny_tds -v 2.1.2
tiny_tds requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.1.33.
```

**Comment by jeremyevans** [comment]
This is obviously not a bug in Sequel, it's just that tiny_tds doesn't ship a Windows binary gem for Ruby 2.6.  Sequel works fine with tiny_tds on Ruby 2.6 and higher versions if tiny_tds works (it's tested on a regular basis on other operating systems).  tiny_tds will work fine on Windows and Ruby 2.6, you just have to build the gem itself from the source gem, instead of using the binary gem.

**Comment by centuryfall** [comment]
Ok -- just wanted to get some personal clarity. This is understandable. Thanks!
