### ISSUE TITLE
Fallback possibility from DriverManager to Driver.connect not working

### ISSUE THREAD

**Issue by 111andre111** [jeremyevans/sequel#1694]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
At the moment I have a JDBC consisting of several JAR files doesn't correctly fall back to the connect if DriverManager is not loading the class appropriately.

### Simplest Possible Self-Contained Example Showing the Bug
1. load the JAR files
```
require 'JDBC.jar'
require 'avro-1.9.0.jar'
```
2. Load the classes
```
require "java"
require "sequel"
require "sequel/adapters/jdbc"
Sequel::JDBC.load_driver('com.....Driver')
```
3. load the url and opts including the driver class
```
opts = { :user => "", :password => "", :pool_timeout => 5, :keep_reference => false, :driver => "com.....Driver" }
url = 'jdbc:....;'
``` 
4. Load the Database
```
DB = Sequel.connect(url, opts=opts)
```
and run into the error, because the driver class is not autoloaded
```
Traceback (most recent call last):
       15: from C:/jruby/bin/jirb:13:in `<main>'
       14: from org/jruby/RubyKernel.java:1193:in `catch'
       13: from org/jruby/RubyKernel.java:1193:in `catch'
       12: from org/jruby/RubyKernel.java:1425:in `loop'
       11: from org/jruby/RubyKernel.java:1061:in `eval'
       10: from (irb):69:in `evaluate'
        9: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/core.rb:125:in `connect'
        8: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/database/connecting.rb:58:in `connect'
        7: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/database/connecting.rb:279:in `test_connection'
        6: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/database/connecting.rb:270:in `synchronize'
        5: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        4: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
        3: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
        2: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/connection_pool.rb:122:in `make_new'
        1: from C:/jruby/lib/ruby/gems/shared/gems/sequel-5.32.0/lib/sequel/adapters/jdbc.rb:227:in `connect'
Sequel::DatabaseConnectionError (NoMethodError: undefined method `new' for "com.simba.googlebigquery.jdbc42.Driver":String)
```

Use JRuby 9.2.7.0
Sequel version 5.29.0 and 5.32.0 tested

### Possible workaround
For me after some digging I found out that the :driver parameter that I used which is mentioned here:
https://github.com/jeremyevans/sequel/blob/master/doc/opening_databases.rdoc#jdbc--
doesn't seem to be set appropriately and it interprets
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/jdbc.rb#L227
driver variable as the string of my class, but it should be the loaded class.
So as a workaround I was able to fix it by adding here in line 225:
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/jdbc.rb#L225
following snippet:
```
            if opts && opts[:driver]
              driver=Sequel::JDBC.load_driver(opts[:driver])
            end
```
in order to load the class appropriately.

Because I was not sure if am on the right track of using the driver appropriately and if this is a bug, could you help please where to fix it appropriately, then I can open a PR.

**Comment by jeremyevans** [comment]
The `:driver` option should be the driver itself, not a string containing the driver name (e.g. `:driver => com.....Driver`). Can you try that and see if it works?

**Comment by 111andre111** [comment]
Ok, I changed it to
```
DBClass=Sequel::JDBC.load_driver('com.....Driver')
opts = { :user => "", :password => "", :pool_timeout => 5, :keep_reference => false, :driver => DBClass }
```
With that it works. Cool, thank you.
