### ISSUE TITLE
Can't update a row

### ISSUE THREAD

**Issue by AtomicLemon** [jeremyevans/sequel#1697]
No matter how hard I try, I cannot seem to update a row in my table.

Here is the code I have:
```ruby
users = db[:users]
users.where(Sequel[:id] == '1').update(:email => 'emailhere')
```

The table looks like this:
```mysql
+----+----------------+
| id | email          |
+----+----------------+
|  1 | me@example.com |
+----+----------------+
```

I created the table like this:
```ruby
db.create_table :users do
  primary_key :id
  String :email
end
```

The code runs perfectly without any changes to the row at all. Does anyone have any ideas on why this could be happening? It's probably just me overlooking something stupid

**Comment by janko** [comment]
You need to use the `=~` operator (the `==` operator isn't overridable in Ruby):

```rb
users.where(Sequel[:id] =~ '1').update(:email => 'emailhere')
```

**Comment by AlexWayfer** [comment]
> You need to use the `=~` operator (the `==` operator isn't overridable in Ruby)

It's overridable: https://repl.it/join/xnuftsug-alexwayfer

As well as `eql?`, `equal?` and everything, as I remember.

But I guess it's used internally, like for comparison between Sequel objects inside Sequel.

And yes, Hash or `=~` are correct for this target in Sequel.

**Comment by AtomicLemon** [comment]
Worked perfectly, thanks so much

I knew it would of been something simple :facepalm:

**Comment by AtomicLemon** [comment]
Another question

What can I use for null in a mysql table?
I want to try this
```ruby
users.where(Sequel[:id] != '')
```
I basically just want to fetch everyone in `users` who's `:id` is not null.
This peice of code returns them anyway. What should I use to check if something is nil?

**Comment by adam12** [comment]
The `!=` operator has the same issue in this case as the `==` operator you used above. You actually want `!~`.  `''` (empty string) isn't the same as `NULL`, so if you want `NULL` pass `nil`. This is documented in the [Dataset Filtering](https://sequel.jeremyevans.net/rdoc/files/doc/dataset_filtering_rdoc.html) docs.

You can use a different method to filter on this if it looks better: `exclude(id: nil)`.

In the future, you'll want to ask your questions on either the Google Group or IRC, as the bug tracker is for bugs only. You have great chances of receiving an answer on both (but IRC you need to stay online for a response). Both are linked from the [Development ](http://sequel.jeremyevans.net/development.html)page.

**Comment by AtomicLemon** [comment]
> In the future, you'll want to ask your questions on either the Google Group or IRC, as the bug tracker is for bugs only.

Sorry about that, I will use them from now on.

Also your fix worked like a charm :+1:
