### ISSUE TITLE
Question: Bigquery backend

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1701]
Hi, is there a Google Bigquery backend? It mostly uses Standard SQL so maybe another backend could be reused as a basis?

**Comment by jeremyevans** [comment]
Sequel doesn't ship with a bigquery adapter.  I'm not sure whether there is an external adapter.

Note that if you have questions about Sequel, please ask on the Google Group or IRC per the contribution guidelines.  GitHub Issues should only be used for reporting bugs in Sequel.
