### ISSUE TITLE
Unique index disappears on SQLite

### ISSUE THREAD

**Issue by arthurmmoreira** [jeremyevans/sequel#1704]
### Complete Description of Issue

My unique index disappears when I run a migration with `set_column_default` using SQLite.

### Simplest Possible Self-Contained Example Showing the Bug

Suposing I have the following migration:

```
Sequel.migration do
  up do
    create_table(:test) do
      Bignum :id, null: false, unique: true
      Bignum :another_id, null: false
      String :name, size: 50, null: false
      String :test

      unique [:another_id, :name]
    end
  end

  down do
    drop_table(:test)
  end
end
```

When I print the SQLite schema, it shows me the following:

```
sqlite> .schema test
CREATE TABLE `test` (`id` bigint NOT NULL UNIQUE, `another_id` bigint NOT NULL, `name` varchar(50) NOT NULL, `test` varchar(255), UNIQUE (`another_id`, `name`));
```

If I create another migration using `set_column_default`.

```
Sequel.migration do
  up do
    alter_table(:test) do
      set_column_default :test, 'test'
    end
  end

  down do
    alter_table(:test) do
      set_column_default :test, nil
    end
  end
end
```

The SQLite schema will disappears with my unique index:

```
sqlite> .schema test
CREATE TABLE `test`(`id` bigint DEFAULT (NULL) NOT NULL UNIQUE, `another_id` bigint DEFAULT (NULL) NOT NULL, `name` varchar(50) DEFAULT (NULL) NOT NULL, `test` varchar(255) DEFAULT ('test') NULL);
```

```
$ ruby --version
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 25.252-b09 on 1.8.0_252-b09 +jit [linux-x86_64]
$ sequel --version
sequel 5.34.0
```

And `jdbc-sqlite3 (3.28.0)` to connect to SQLite.

### SQL Log (if any)

Thanks.

**Comment by jeremyevans** [comment]
SQLite does not support changing a column's default value.  Sequel attempts to emulate support in this case, and such emulation is best-effort, there will always be cases that cannot be handled correctly.  I'll see if there is a way to improve the emulation to handle this case, but I cannot make any promises in this regard.

**Comment by jeremyevans** [comment]
I looked into this, and the issue is your example doesn't use a unique index, it uses a composite unique constraint (internally, SQLite implements this via an autoindex, but they are not the same thing).  Switch this a unique index and it will work with the current release:

```ruby
  up do
    create_table(:test) do
      Bignum :id, null: false, unique: true
      Bignum :another_id, null: false
      String :name, size: 50, null: false
      String :test

      index [:another_id, :name], :name=>:test_another_id_name_uidx, :unique=>true
    end
  end
```

I should be able to expand the emulation to handle composite unique constraints.

**Comment by arthurmmoreira** [comment]
Awesome, thank you.
