### ISSUE TITLE
Consider supporting the db-postgres and db-mariadb drivers.

### ISSUE THREAD

**Issue by ioquatix** [jeremyevans/sequel#1708]
This issue is just to kick start a discussion around using `db-postgres` and `db-mariadb` as low level drivers.

I may try to do some of the heavy lifting as time permits, but in the first instance I just wanted to bring awareness of their existence.

The `mysql2` gem does not expose enough hooks to be event driven.

The `pg` gem isn't far away from being event driven (see https://github.com/ged/ruby-pg/issues/342) but I didn't want to wait.

- https://github.com/socketry/db
- https://github.com/socketry/db-mariadb
- https://github.com/socketry/db-postgres

I think we could probably create a gem `db-sequel` which exposes the right driver interfaces, rather than over-extending the implementation here (already has a ton of drivers). Another option might be to create `sequel-driver-db` or something like that.

Let me know what you think.

**Comment by jeremyevans** [comment]
As the contribution guide states, please start discussions like this on the sequel-talk Google Group.  GitHub Issues should only be used for bug reports.

My gut feeling is it's probably best to first implement the adapter in a gem, and then depending on demand and ease of maintenance I could consider shipping the adapters with Sequel.
