### ISSUE TITLE
Checking if view exists doesn't work with multiple schemas in a oracle DB

### ISSUE THREAD

**Issue by jume-dev** [jeremyevans/sequel#1710]
Hi there,
First of all, as it's my first issue here, I'd like to thank you for your work with sequel. This is so awesome and it mainly works out of the box for any use cases we had. Sadly, I found one that seems a bit buggy.

### Complete Description of Issue
So, you see, we have an oracle DB with multiple schemas for test and development (and more, but that's not the issue here).
While playing around we noticed that the method [`view_exists?`](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/oracle.rb#L106) from the oracle adapter doesn't check for multiple schemas and therefore returns true even if the view exists in another schema and not in the current active one.

### Simplest Possible Self-Contained Example Showing the Bug
* Have an oracle database with two schemas
* Create a simple view in one of them
* Startup an IRB and initiate a connection to the other schema
* call DB.view_exists?
* **Expectation:** false, **Actual value:** true

### Solution Idea
When I tried to check with ActiveRecord, if they do that, they use the following SQL to check for the view: `SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')`
Maybe this helps with fixing this issue?

**Comment by jeremyevans** [comment]
Looking in all schemas except for the system schemas is actually a deliberate choice, and changing the default behavior could break things for other users.  We could add a `:owner` option to specify a schema, or a `:current_schema` option to restrict results to the current schema.  Which would you prefer?

**Comment by jume-dev** [comment]
Alright, I see and I can see your reasoning.
I'd prefer the current_schema option for it's simplicity in the usage.

**Comment by jeremyevans** [comment]
OK, I'll work on implementing that shortly.

**Comment by jume-dev** [comment]
Dude, you're awesome, holy shit. Thanks a lot!
