### ISSUE TITLE
mysql: conditions for the same key and operation not being replaced

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/sequel#1712]
### Complete Description of Issue

I'm experiencing a behaviour with `mysql` that I'm not experiencing with `postgres` nor `sqlite`. Specifically, if I add conditions to the same key, it won't replace the existing conditions, but it will add on it.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
Sequel::VERSION
#=> "5.35.0"
ds = db[:some_table]
ds.where(id: 1)
#<Sequel::Mysql2::Dataset: "SELECT * FROM `some_table` WHERE ((`id` = 1))`
ds.where(id: 1).where(id: 2)
#<Sequel::Mysql2::Dataset: "SELECT * FROM `some_table` WHERE ((`id` = 1) AND (`id` = 2))`
```

This only happens with the `mysql` variant, as the others pick up only the second condition.

**Comment by jeremyevans** [comment]
The Dataset#where behavior of adding to the conditions happens for all Sequel adapters, and it isn't a bug, it is the expected behavior:

```ruby
# postgres
ds = DB[:some_table]
ds.where(id: 1)
# => #<Sequel::Postgres::Dataset: "SELECT * FROM \"some_table\" WHERE (\"id\" = 1)">
ds.where(id: 1).where(id: 2)
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"some_table\" WHERE ((\"id\" = 1) AND (\"id\" = 2))">

# sqlite
ds = DB[:some_table]
ds.where(id: 1)
# => #<Sequel::SQLite::Dataset: "SELECT * FROM `some_table` WHERE (`id` = 1)">
ds.where(id: 1).where(id: 2)
# => #<Sequel::SQLite::Dataset: "SELECT * FROM `some_table` WHERE ((`id` = 1) AND (`id` = 2))">
```

**Comment by HoneyryderChuck** [comment]
you're right, got confused by a misuse of the `Sequel::Dataset#update# method. sorry about that.
