### ISSUE TITLE
Migrator does not error if target cannot be satisfied

### ISSUE THREAD

**Issue by collinsauve** [jeremyevans/sequel#1716]
### Complete Description of Issue

When using `Sequel::Migrator.run(database, directory, options)` with `options.target` is specified but that target version cannot be reached with existing migrations, the migrator does not error.  

### Simplest Possible Self-Contained Example Showing the Bug

1. Create migration files with integer ids `1` and `2`
2. Migrate as normal, `schema_info.version` is set to `2`
3. Delete the `2` migration file
4. Migrate using options `{ target: 1 }`

`schema_info.version` is still `2` so at least it does not leave the DB in a bad state, but I would expect some feedback (ie raise an error) that it was not able to satisfy the requested target.

### Full Backtrace of Exception (if any)
No exception

**Comment by jeremyevans** [comment]
The described behavior does seem like a bug. I agree an exception should be raised in this case.  I'll look into it.

**Comment by collinsauve** [comment]
Thanks for the fast turn-around @jeremyevans ! :fire:
