### ISSUE TITLE
nulldb adapter support?

### ISSUE THREAD

**Issue by username-is-already-taken2** [jeremyevans/sequel#1722]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

![image](https://user-images.githubusercontent.com/13700297/95061963-38d1ea00-06f4-11eb-9974-c9be10b43887.png)

Hi there

We use mysql2 driver for our rails app, but I use the [nulldb](https://rubygems.org/gems/activerecord-nulldb-adapter/versions/0.4.0) at build time to help with precompiling the assets without a database connection.

Unfortunately my precompile task errors say that no file exists, I wondered if you could consider adding support for this adapter?

Best Regards

Gary

**Comment by janko** [comment]
Sequel has the equivalent of ActiveRecord's nulldb adapter – the `mock` adapter:

```rb
DB = Sequel.mock
# or
DB = Sequel.connect("mock:///")
```

**Comment by jeremyevans** [comment]
As @janko mentioned, you should use the mock adapter for this.
