### ISSUE TITLE
Sequel::Postgres::Database#server_version swallows database disconnect exception

### ISSUE THREAD

**Issue by janko** [jeremyevans/sequel#1724]
### Complete Description of Issue

I'm currently integrating Sequel into a Rails app, which is using Spring. In tests, I've encountered a very curious issue where `#insert_conflict` didn't seem to be applied anymore after Spring has been loaded when used with `#multi_insert`.

I've managed to isolate this scenario into the following script:

```rb
require "sequel"
require "logger"

# imitate tables already created when the app is started
Sequel.postgres("mydb") do |db|
  db.create_table!(:records) do
    primary_key :id
    String :column
  end
end

# establish connection in initializer
DB = Sequel.postgres("mydb")
DB.logger = Logger.new($stdout)

# each test run is executed inside a subprocess
Process.waitpid fork { DB[:records].insert_conflict.multi_insert([{column: "foo"}]) }
Process.waitpid fork { DB[:records].insert_conflict.multi_insert([{column: "bar"}]) }
```

This code will successfully execute both INSERT statements, but the second one will not have the `ON CONFLICT` clause:

```
INSERT INTO "records" ("column") VALUES ('foo') ON CONFLICT DO NOTHING
INSERT INTO "records" ("column") VALUES ('bar')
```

Now, I know that Sequel requires you to disconnect before forking (and I admit I had forgotten that Spring forks), but there is another issue here. The following happens in this scenario:

1. (process A) Sequel checks `#server_version` to check whether PG version supports `ON CONFLICT`
1. (process A) query which retrieves PG version is correctly executed, and `ON CONFLICT` is added
1. process A exits, process B enters without closing the previous connection
1. (process B) Sequel checks `#server_version` to check whether PG version supports `ON CONFLICT`
1. (process B) query which retrieves PG version errors with `PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly` (expected), which is then swallowed via a catch-all `rescue`, and server version is set to `0`: https://github.com/jeremyevans/sequel/blob/d14ccc602b925098b713c8faa30f297d15087168/lib/sequel/adapters/shared/postgres.rb#L784
1. (process B) in the meanwhile, connection pool detects the disconnect error and removes the faulty connection
1. (process B) Sequel proceeds with the INSERT statement, but given that server version is `0`, it doesn't add the `ON CONFLICT` clause

Now, I know that the root cause of this issue was not disconnecting before each fork. However, I would be able to identify that sooner had the disconnect exception not been swallowed (for some reason I've not seen the exception in the logs). I think `#server_version` method shouldn't rescue exceptions, or at least let disconnect exceptions bubble up.

### Simplest Possible Self-Contained Example Showing the Bug

```rb
require "sequel"

DB = Sequel.postgres("mydb")

Process.waitpid fork { p DB.server_version }

p DB.server_version
```
```
120001
0
```

In this case, I would like the second `DB.server_version` call to propagate the PG error that happened.

**Comment by jeremyevans** [comment]
I think the reason for the check is for other databases that speak the PostgreSQL protocol but don't actually support the `CAST(current_setting('server_version_num') AS integer)`.  So removing the rescue may break things.  I suppose we could remove the rescue and support an option for setting the server version explicitly, for those users not using a real PostgreSQL database.  It would be more backwards compatible to continue to rescue non-disconnect errors, though. What are your thoughts?

**Comment by janko** [comment]
I think rescuing only non-disconnect errors would already be a big improvement, because most people *are* using a real PostgreSQL database, and for them it's desired that disconnect errors are always communicated (and it's probably the most common type of transient errors).

**Comment by jeremyevans** [comment]
OK.  I'm currently testing a change that only rescues Sequel::DatabaseErrors that aren't Sequel::DatabaseDisconnectError.  That should hopefully work better for other cases where exceptions should be raised that shouldn't be swallowed.  It may not work well if the driver raises an exception that isn't recognized as a database error (which may affect postgres-pr).

**Comment by janko** [comment]
Thank you for the quick fix!
