### ISSUE TITLE
Can I get the sql that was used to create a view

### ISSUE THREAD

**Issue by mdavis1960** [jeremyevans/sequel#1726]
Question: how can I get the SQL that used to create a view?

**Comment by jeremyevans** [comment]
If Sequel is creating the view, add a Database logger (see the README) before the code that calls `create_view`.  If this is an existing view in the database, Sequel does not have code that gets the SQL for views, please consult the documentation for your database to see how to do that.

As specified in the contribution guidelines, please ask questions on how to use Sequel on IRC or in the Google Group.  Only use GitHub Issues if you are sure you have found a bug in the library.
