### ISSUE TITLE
DB.tables method does not return partitioned tables for PostgreSQL

### ISSUE THREAD

**Issue by epoberezhny** [jeremyevans/sequel#1729]
### Complete Description of Issue

`DB.tables` method does not return partitioned tables for PostgreSQL. Looks like it selects only ordinary tables https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/postgres.rb#L849. But it would be nice to get partitioned tables as well i.e. this method should also select classes with `relkind = 'p'` https://www.postgresql.org/docs/13/catalog-pg-class.html

**Comment by jeremyevans** [comment]
I agree.  If you want to submit a pull request for this, please do so.  Otherwise, I'll work on it next week.

**Comment by jeremyevans** [comment]
Fixed at e96344472b9499ba941a0479ca9646c3a425fed6.
