### ISSUE TITLE
Tree plugin missing a Qualify

### ISSUE THREAD

**Issue by qortex** [jeremyevans/sequel#1731]
When using the `tree` plugin, I found myself needing to compute the `roots_dataset` myself because of a complicated query where I got an error `Sequel::DatabaseError (PG::AmbiguousColumn: ERROR:  column reference "parent_id" is ambiguous)`.

Using a simple `where(Sequel[:table_name][:parent_id] => nil)` instead gave me the correct dataset.

I think the plugin should always return the correct dataset no matter in which query the dataset is pulled.

My understanding is that adding a `qualify` in the following method would be a correct fix. Am I right?

https://github.com/jeremyevans/sequel/blob/df173ffbf9f35d4a12c13d08d2bb7a519013f32b/lib/sequel/plugins/tree.rb#L153-L157

If this is not enough context to understand the issue, I'll try to put together a small repro.

### SQL Log (if any)

```
irb(main):003:0> r.parts_roots_dataset
\"report_id\", \"sqan_diag_parts\".\"parent_id\", \"sqan_diag_parts\".\"library_parent_id\", \"sqan_diag_parts\".\"title\", \"sqan_diag_parts\".\"description\", \"sqan_diag_parts\".\"hidden\", \"sqan_diag_parts\".\"created_at\", \"sqan_diag_parts\".\"updated_at\", \"sqan_diag_parts\".\"maturity\", \"library_parent\".\"id\" AS \"library_parent_id_0\", \"library_parent\".\"parent_id\" AS \"library_parent_parent_id\", \"library_parent\".\"unique_id\", \"library_parent\".\"title\" AS \"library_parent_title\", \"library_parent\".\"description\" AS \"library_parent_description\", \"library_parent\".\"ordering\", \"library_parent\".\"framework\", \"library_parent\".\"created_at\" AS \"library_parent_created_at\", \"library_parent\".\"updated_at\" AS \"library_parent_updated_at\" FROM \"sqan_diag_parts\" LEFT OUTER JOIN \"sqan_library_framework_parts\" AS \"library_parent\" ON (\"library_parent\".\"id\" = \"sqan_diag_parts\".\"library_parent_id\") WHERE ((\"sqan_diag_parts\".\"report_id\" = 'bb7d88eb-005a-44de-bf44-68414e422358') AND (\"parent_id\" IS NULL)) ORDER BY \"library_parent\".\"ordering\" ASC">
```

**Comment by jeremyevans** [comment]
Are you are calling `roots_dataset` in the same query where you are joining to another table?  I agree that should probably work, and qualifying the column should fix it.  I can fix that tomorrow.

**Comment by qortex** [comment]
Yes exactly. Thanks!

**Comment by qortex** [comment]
Awesome, thanks a lot!
