### ISSUE TITLE
typecast_timezone attribute in generated docs not a link

### ISSUE THREAD

**Issue by jlmuir** [jeremyevans/sequel#1739]
### Complete Description of Issue

The `typecast_timezone` attribute referenced in the first paragraph of the [Sequel::SequelMethods documentation](https://sequel.jeremyevans.net/rdoc/classes/Sequel/SequelMethods.html) should be a link just like `application_timezone` and `database_timezone`, but it is not.

### Simplest Possible Self-Contained Example Showing the Bug

[Sequel::SequelMethods documentation](https://sequel.jeremyevans.net/rdoc/classes/Sequel/SequelMethods.html):

<img width="838" alt="timezone-doc-attr-no-link" src="https://user-images.githubusercontent.com/959381/100636986-f4c82380-32f7-11eb-827a-d438504598a0.png">

### Full Backtrace of Exception (if any)

n/a

### SQL Log (if any)

n/a

**Comment by jeremyevans** [comment]
This is definitely more of an rdoc bug than a Sequel bug (probably due to the trailing `.`), but I think I can work around it.
