### ISSUE TITLE
Add foreign key on table with UUID as primary key

### ISSUE THREAD

**Issue by khataev** [jeremyevans/sequel#1743]
I have a table 
```
    create_table(:artists) do
      column :id, :uuid, default: Sequel.function(:gen_random_uuid), primary_key: true
    end

   create_table(:albums) do
      column :id, :uuid, default: Sequel.function(:gen_random_uuid), primary_key: true
    end
```

and I try to create join table

```
create_join_table(artist_id: :artists, album_id: :albums)
```

And I've got an error

```
E, [2020-12-08T13:26:29.166437 #57468] ERROR -- : PG::DatatypeMismatch: ERROR:  foreign key constraint "albums_artists_album_id_fkey" cannot be implemented
DETAIL:  Key columns "bundle_id" and "id" are of incompatible types: integer and uuid.: CREATE TABLE "albums_artists" ("album_id" integer NOT NULL REFERENCES "albums", "artist_id" integer NOT NULL REFERENCES "artists", PRIMARY KEY ("album_id", "artist_id"))
I, [2020-12-08T13:26:29.166888 #57468]  INFO -- : (0.000193s) ROLLBACK
rake aborted!
Sequel::DatabaseError: PG::DatatypeMismatch: ERROR:  foreign key constraint "albums_artists_album_id_fkey" cannot be implemented
DETAIL:  Key columns "artist_id" and "id" are of incompatible types: integer and uuid.
```

This is also relate to separate foreign constraint declaration, because I need join table with addtional fields

```
create_table(:albums_artists) do
  column ...
  foreign_key :album_id, :albums
end
``` 

How could I specify, that join table should have columns of uuid type?

**Comment by adam12** [comment]
> `create_join_table(artist_id: :artists, album_id: :albums)`

```ruby
create_join_table(artist_id: {table: :artists, type: :uuid}, album_id: {table: :albums, type: :uuid})
```

>   foreign_key :album_id, :albums

```ruby
foreign_key :album_id, :albums, type: :uuid
```

In the future, you should post questions like these to the Google group or IRC, per the contributing guidelines. Issue tracker is reserved for confirmed bugs only.

**Comment by khataev** [comment]
@adam12 Ok, sorry. But IRC chat does not seem to work. There is no such channel
<img width="1458" alt="Screen Shot 2020-12-09 at 10 34 34 AM" src="https://user-images.githubusercontent.com/5956518/101599090-3a78a080-3a0a-11eb-96f0-d4ad94201444.png">

Also, I think, that [documentation](https://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-foreign_key) lacks description of type option, doesn't it?

Thanks

**Comment by bananarne** [comment]
> @adam12 Ok, sorry. But IRC chat does not seem to work. There is no such channel
> <img alt="Screen Shot 2020-12-09 at 10 34 34 AM" width="1458" src="https://user-images.githubusercontent.com/5956518/101599090-3a78a080-3a0a-11eb-96f0-d4ad94201444.png">
> 
> Thanks

The channel does exist, as in fact i read the notification of your post in it.
