### ISSUE TITLE
Schema caching when using multiple databases

### ISSUE THREAD

**Issue by mscrivo** [jeremyevans/sequel#1744]
### Complete Description of Issue
We have 3 databases. One is primary and considered essential, so when connecting we connect with `test:true` and assume it's always available. However, we'd like the app to continue working, and even startup if the other 2 are not available. My thought was to connect the other two DB's with `test: false` and use the schema_caching extension to load the models from the cache so that app can at least startup if they are down.  However, the model caching does not seem to work with models that use the second or third DB. When starting the app, it fails to connect to the model on the second or third DB's, even though they should be loaded from the cache.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB_ESSENTIAL = Sequel.connect(test: true)
DB_ESSENTIAL.extension :schema_caching
DB_ESSENTIAL.load_schema_cache?('/tmp/essential_schema.dump')

DB_NON_ESSENTIAL = Sequel.connect(test: false)
DB_NON_ESSENTIAL.extension :schema_caching
DB_NON_ESSENTIAL.load_schema_cache?('/tmp/non)essential_schema.dump')

# load model files from both DB's

DB_ESSENTIAL.dump_schema_cache?('/tmp/essential_schema.dump')
DB_NON_ESSENTIAL.dump_schema_cache?('/tmp/non_essential_schema.dump')

# Sample model for non_essential DB:
class Table < Sequel::Model(DB_NON_ESSENTIAL[:table]) # it fails connecting to DB_NON_ESSENTIAL here
   ...
end
```

### Full Backtrace of Exception (if any)
```
! Unable to load application: Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
bundler: failed to load command: puma (/Users/mscrivo/project/vendor/bundle/ruby/2.7.0/bin/puma)
Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?

  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/adapters/postgres.rb:210:in `initialize'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/adapters/postgres.rb:210:in `new'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/adapters/postgres.rb:210:in `connect'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/connection_pool.rb:122:in `make_new'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/database/connecting.rb:269:in `synchronize'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/database/transactions.rb:195:in `transaction'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/model/base.rb:684:in `check_non_connection_error'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/model/base.rb:772:in `get_db_schema'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/model/base.rb:604:in `set_dataset'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/model/base.rb:192:in `Model'
  /Users/mscrivo/project/vendor/bundle/ruby/2.7.0/gems/sequel-5.38.0/lib/sequel/model/base.rb:140:in `block in def_Model'
```

is thrown from the first line in the model above

**Comment by jeremyevans** [comment]
When loading the schema for a table, Sequel runs the schema checking in a savepoint if currently in a transaction.  In order to do this, it needs to checkout a connection from the database.  If the database is not currently available, then you get the expected connection error.

What you are doing (trying to use models without being able to connect to the database) is not currently supported.  One approach would be to try connecting to the actual database, but if that fails, use a mock database instead.  You can load the schema cache into the mock database and it should still allow the model to load.

If for some reason that won't work, you could try suppressing errors completely from the related code:

```ruby
def (Sequel::Model).check_non_connection_error(_=nil)
  yield
rescue
end
```

**Comment by mscrivo** [comment]
Thanks @jeremyevans! Overriding that method for the non-essential DBs' models worked nicely. I was able to test the scenario of:

* Stop DB
* Load app
* Verify accessing model for stopped DB throws connection error
* Restart DB while app still running
* Verify accessing & deleting record with same model works

I didn't even need to cache the models to disk.
