### ISSUE TITLE
Capitalized schemas are incorrectly escaped when used in a Dataset

### ISSUE THREAD

**Issue by raggi** [jeremyevans/sequel#1745]
### Complete Description of Issue

SQL construction for tables in uppercase schemas is no longer correct for postgresql since 5.

Correct:

```
>> Sequel[:'"FOO".bar']
=> #<Sequel::SQL::Identifier @value=>"\"FOO\".bar">
```

Incorrect:

```
>> db[Sequel[:'"FOO".bar']]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"\"\"FOO\"\".bar\"">
```

It works correctly for functions still:

```
>> db[Sequel.function(:'"FOO".bar')]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"FOO\".bar()">
```

Using instead the input `:'FOO.bar'` seems to attempt an alternative strategy, but this strategy does not work with postgresql:

```
>> db[Sequel[:'FOO.bar']]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"FOO.bar\"">
```

This will not query the table `"FOO".bar`.

Another construction could be, as documented:

```
>> Sequel[:FOO][:bar]
=> #<Sequel::SQL::QualifiedIdentifier @table=>"FOO", @column=>:bar>
>> Sequel[:FOO][:bar][:baz]
=> #<Sequel::SQL::QualifiedIdentifier @table=>#<Sequel::SQL::QualifiedIdentifier @table=>"FOO", @column=>:bar>, @column=>:baz>
```

However this does not select for schemas.

### Simplest Possible Self-Contained Example Showing the Bug

```
>> db[Sequel[:'"FOO".bar']]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"\"\"FOO\"\".bar\"">
```

should instead be:

```
>> db[Sequel[:'"FOO".bar']]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"FOO\".bar">
```

**Comment by jeremyevans** [comment]
Trying to put a qualified identifier inside a `Sequel::SQL::Identifier` is unsupported.  Use the `Sequel[:FOO][:bar]` syntax to create a `Sequel::SQL::QualifiedIdentifier`, that is the supported way.  Alternatively, you can use `Sequel.lit("FOO".bar)` to create a literal SQL expression, but it's always best to avoid dropping down to literal SQL unless you need to.

The fact that it works for functions is because function names are not quoted by default.  However, it's still wrong to put a qualified identifier inside a `Sequel::SQL::Identifier`.

You mentioned that `this does not select for schemas`.  I'm not sure what you mean by that, could you explain?

**Comment by raggi** [comment]
Thanks for the prompt response.

Here's an example schema:

```sql
create schema "EXAMPLE";
create table "EXAMPLE".foo ( id int primary key );
insert into "EXAMPLE".foo VALUES ( 1 );
select * from "EXAMPLE".foo;
# id
# ----
# 1
# (1 row)
select * from "EXAMPLE.foo";
# ERROR:  relation "EXAMPLE.foo" does not exist
# LINE 1: select * from "EXAMPLE.foo";
```

I see what you mean:

```
>> db[Sequel[:EXAMPLE][:foo]]
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"EXAMPLE\".\"foo\"">
```

I think I got mislead when I just did: 

```
>> Sequel[:EXAMPLE][:foo]
=> #<Sequel::SQL::QualifiedIdentifier @table=>"EXAMPLE", @column=>:foo>
```

As this looks to be generating a less general identifier, but really it's just a quoted identifier sequence, and `db[Sequel[:EXAMPLE][:foo]]` solves for my requirement.

Is it then more correct construction for a schema'd function to do:

`db[Sequel[:EXAMPLE][Sequel.function(:bar)]]` ?

Many thanks, and happy new year!

**Comment by jeremyevans** [comment]
For a schema qualified function, you can use `Sequel[:EXAMPLE][:bar].function`.

Briefly, regarding the `[]` methods:

* `Sequel.[]`: short for `Sequel.expr`, returns an `Sequel::SQL::Identifier` when called with a symbol
* `Sequel::SQL::Identifier#[]`: returns an `Sequel::SQL::QualifiedIdentifier`
* `Sequel::Database#[]`: returns a `Sequel::Dataset` based on the argument

**Comment by raggi** [comment]
Thank you Jeremy!
