### ISSUE TITLE
Question: How to add NOT VALID to add_constraint?

### ISSUE THREAD

**Issue by xenyal** [jeremyevans/sequel#1753]
I looked around in the documentation as well as the method source for `add_constraint`, but couldn't find something like a `validate: false` argument that translates to `NOT VALID` for the statement generated. How might I add that within an `alter_table` block where I'm adding a constraint like so?

```
add_constraint :new_constraint_name, column_name: column_check_constraints
```

**Comment by jeremyevans** [comment]
This should work:

```ruby
add_constraint({:name=>:new_constraint_name, :not_valid=>true}, column_name: column_check_constraints)
```

I guess this isn't specifically mentioned in the documentation, so I'll add it.

**Comment by xenyal** [comment]
Thanks @jeremyevans!
