### ISSUE TITLE
Sequel::DatabaseError (ODBC::Error: H (-1) M)

### ISSUE THREAD

**Issue by ravindra9278** [jeremyevans/sequel#1754]
Getting this issue when trying to pull run queries.

```
2.6.6 :028 > db.fetch("show WAREHOUSES;").entries
conn=#<ODBC::Database:0x00007fdcecd1ff30>, sql="show WAREHOUSES;"
Traceback (most recent call last):
        3: from (irb):28
        2: from (irb):28:in `rescue in irb_binding'
        1: from (irb):28:in `entries'
Sequel::DatabaseError (ODBC::Error: H (-1) M)
2.6.6 :029 >
```

**Comment by jeremyevans** [comment]
This is an error raised by the ODBC driver, not a bug in Sequel.  If you are looking to get help with Sequel, per the contribution guidelines, you should ask for help on the sequel-talk Google Group.  GitHub Issues should only be used for reporting bugs in Sequel.

If you to decide to post on the sequel-talk Google Group, you'll need to provide a lot more information, including steps to reproduce what you are experiencing.  With what you posted here, nobody will be able to help you.

**Comment by ravindra9278** [comment]
@jeremyevans sure I will post more information on sequel-talk Google Group.
