### ISSUE TITLE
Drop constraint does not appear to work for Sqlite

### ISSUE THREAD

**Issue by bethesque** [jeremyevans/sequel#1755]
### Complete Description of Issue

`drop_constraint` as documented [here](https://sequel.jeremyevans.net/rdoc/classes/Sequel/Schema/AlterTableGenerator.html#method-i-drop_constraint) does not appear to work for Sqlite when the constraint has been created as part of the column definition. The same code works with postgres.

### Simplest Possible Self-Contained Example Showing the Bug

Zip file contains all the code to run, using Ruby 2.7

```
bundle install
bundle exec ruby run.rb
```

[sqlite-drop-unique-constraint-issue.zip](https://github.com/jeremyevans/sequel/files/6226254/sqlite-drop-unique-constraint-issue.zip)

Relevant code:

```ruby
require 'sequel'
require 'logger'

FileUtils.rm_rf "test.sqlite3"
DATABASE_CREDENTIALS = { adapter: "sqlite", database: "test.sqlite3", logger: Logger.new($stdout)}

connection = Sequel.connect(DATABASE_CREDENTIALS)

connection.create_table(:my_table) do
  primary_key :id
  String :name, null: false, unique: true, unique_constraint_name: 'unique_name_constraint' # unique_name_constraint is not actually used, because Sqlite?
end

name_constraint = connection.indexes(:my_table).find{ |name, properties| properties[:unique] == true && properties[:columns] == [:name] }
puts "Need to drop #{name_constraint.first}"

connection.alter_table(:my_table) do
  drop_constraint(name_constraint.first, type: :unique)
end

name_constraint = connection.indexes(:my_table).find{ |name, properties| properties[:unique] == true && properties[:columns] == [:name] }
puts "This constraint should not still exist:"
puts name_constraint
```

### SQL Log (if any)

The "`name` varchar(255) DEFAULT (NULL) NOT NULL UNIQUE" should be "`name` varchar(255) DEFAULT (NULL) NOT NULL"

```
I, [2021-03-30T15:53:28.197180 #53756]  INFO -- : (0.000604s) ALTER TABLE `my_table` RENAME TO `my_table_backup0`
I, [2021-03-30T15:53:28.197327 #53756]  INFO -- : (0.000109s) CREATE TABLE `my_table`(`id` integer DEFAULT (NULL) NOT NULL PRIMARY KEY AUTOINCREMENT, `name` varchar(255) DEFAULT (NULL) NOT NULL UNIQUE)
```

I believe it is something to do with the fact that there is only one unique column in the constraint and the `no_unique` only gets evaluated if there are two columns

https://github.com/jeremyevans/sequel/blob/bc5925e3f6789de70343158b086d2266d91b6acb/lib/sequel/adapters/shared/sqlite.rb#L425-L434

**Comment by jeremyevans** [comment]
Thanks for the report! It looks like expanding the scope of `:no_unique` will work:

```diff
diff --git a/lib/sequel/adapters/shared/sqlite.rb b/lib/sequel/adapters/shared/sqlite.rb
index 31b58d351..43a70b13e 100644
--- a/lib/sequel/adapters/shared/sqlite.rb
+++ b/lib/sequel/adapters/shared/sqlite.rb
@@ -424,10 +424,10 @@ module Sequel
         skip_indexes = []
         indexes(table, :only_autocreated=>true).each do |name, h|
           skip_indexes << name
-          if h[:unique]
+          if h[:unique] && !opts[:no_unique]
             if h[:columns].length == 1
               unique_columns.concat(h[:columns])
-            elsif h[:columns].map(&:to_s) != pks && !opts[:no_unique]
+            elsif h[:columns].map(&:to_s) != pks
               constraints << {:type=>:unique, :columns=>h[:columns]}
             end
           end
```

The historical reason for the behavior was to fix the copying of composite unique constraints, and it chose a conservative approach.  This expands it to also handle non-composite unique constraints.  I can't rule out the possibility of regressions from this change, though it doesn't break any existing tests.  

The prerelease testing for 5.43.0 has already started, so I'll probably wait until after release to commit this.

**Comment by bethesque** [comment]
Thanks for the quick fix Jeremy. Appreciate your work on this amazing gem.
