### ISSUE TITLE
Mysql NO_CACHE_SQL option

### ISSUE THREAD

**Issue by drqCode** [jeremyevans/sequel#1758]
I'm not sure if this is really not possible or is a missing feature, but how can I set NO_CACHE_SQL option to all datasets or at least for a dataset: https://dev.mysql.com/doc/refman/5.6/en/query-cache-in-select.html? Is there any config option? Or a not so bad trick? I need this cause it is not currently possible to deactivate query caching in our mysql server...

**Comment by jeremyevans** [comment]
Sequel doesn't currently have support for this.  You could kind of emulate support via:

```ruby
DB[:table].select(Sequel.lit("NO_CACHE_SQL *"))
```

Replacing `*` with whatever columns you want to select.

It's not difficult to add support for this, but you are the first person to ask for it, so I'm not sure if the benefit is worth the cost.  The cost being making SQL generation for all MySQL SELECT statements slightly slower.  If you would like this added, please open a thread on the sequel-talk Google Group and see if there is community support for this.
