### ISSUE TITLE
Get a dataset error for oracle  where I query a table data from another schema

### ISSUE THREAD

**Issue by bluesaiz** [jeremyevans/sequel#1764]
I use jruby and jdbc to connect oracle use user1 like this 
**DB = Sequel.connect('jdbc:oracle:thin:user1/pass@//localhost:1521/orcl')**
then I create a dataset use a table from another shema(user2 has a table "t2")
**ds = DB[:"user2.t2"] #<Sequel::JDBC::Oracle::Dataset: "SELECT * FROM \"USER2.T2\"">** 
then I call
**ds.count**
get an error
**Java::JavaSql::SQLSyntaxErrorException: ORA-00942: table or view does not exist** 
I use other tools to connect to oracle and check the SQL statements, the right sql should be
**SELECT * FROM USER2."T2"**

**Comment by jeremyevans** [comment]
You need to use `DB.from{user2[:t2]}` or another format that uses a qualified identifier.  See http://sequel.jeremyevans.net/rdoc/files/doc/sql_rdoc.html#label-Identifiers

**Comment by bluesaiz** [comment]
I got it, thanks a lot
