### ISSUE TITLE
ODBC Adapter returns False for NULL booleans 

### ISSUE THREAD

**Issue by markusos** [jeremyevans/sequel#1765]
### Description:

The ODBC Adapter is not correctly handling `NULL` values in BOOLEAN columns, and instead returning `False`.

### How to reproduce:

- Setup a table with at least one BOOLEAN field
```
CREATE TABLE public.boolean_test (
	test_field BOOLEAN
);
```

- Insert some data with True, False and NULL values into the table

```
INSERT INTO public.boolean_test (test_field) VALUES (true);
INSERT INTO public.boolean_test (test_field) VALUES (false);
INSERT INTO public.boolean_test (test_field) VALUES (null);
```

- Connect to the DB with sequel and select the data:

```
require 'sequel'
Sequel.odbc(drvconnect: connection)
client.fetch('SELECT test_field FROM public.boolean_test;').to_a
```

Expected results:

```
[{:test_field=>true}, {:test_field=>false}, {:test_field=>nil}]
```

Actual result:
```
[{:test_field=>true}, {:test_field=>false}, {:test_field=>false}]
```

### Bug

It seems the behavior stems from the `convert_odbc_value` function:

https://github.com/jeremyevans/sequel/blob/1fd7694e342eca69fc52bb8f6079f746a286500f/lib/sequel/adapters/odbc.rb#L106-L127

Specifically:

https://github.com/jeremyevans/sequel/blob/1fd7694e342eca69fc52bb8f6079f746a286500f/lib/sequel/adapters/odbc.rb#L121-L122

will cause `convert_odbc_value(nil, -7)` to return `false` instead of `nil` as expected.

**Comment by jeremyevans** [comment]
Thank you very much for the detailed analysis and bug report.  I will be committing a fix for this shortly.
