### ISSUE TITLE
create_table :as to create a new table, can not add new record when used with sqlite3.

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1766]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

Following is my old stocks table:

```rb
Sequel.migration do
  change do
    create_table(:stocks) do
      primary_key :id
      String :name, null: false, unique: true
      foreign_key :exchange_id, :exchanges
    end
  end
end
```

I want to create a new_stocks table from there, so i add a new migrate.

```rb
Sequel.migration do
  change do
    create_table(:new_stocks, as: DB[:stocks])
  end
end
```

Now, i have a new new_stocks table, but when i create a new record, id is nil.

I try fix this with:

```rb
Sequel.migration do
  change do
    alter_table(:new_stocks) do
      set_column_not_null :id
      add_primary_key [:id]
    end
  end
end
```

But, it can not add new record anymore.

equel::NotNullConstraintViolation: SQLite3::ConstraintException: NOT NULL constraint failed: new_stocks.id

Caused by SQLite3::ConstraintException: NOT NULL constraint failed: new_stocks.id

### What i expected.

Create a autoincrementing id, as old stocks

```rb
create_table(:new_stocks, :ignore_index_errors=>true) do
  primary_key :id
end
```

### But current 

We got like this.

```rb
create_table(:new_stocks) do
  Integer :id, :null=>false
  primary_key [:id]
  # ...
end
```

Thank you.

**Comment by jeremyevans** [comment]
The current behavior is expected and matches SQLite's behavior:

```
battleground$ sqlite3 
SQLite version 3.35.5 2021-04-19 18:32:05
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .headers on 
sqlite> CREATE TABLE `stocks` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` varchar(255) NOT NULL UNIQUE, `exchange_id` integer REFERENCES `exchanges`);
sqlite> CREATE TABLE `new_stocks` AS SELECT * FROM `stocks`;
sqlite> INSERT INTO `new_stocks` DEFAULT VALUES;
sqlite> SELECT * FROM `new_stocks`;
id|name|exchange_id
||
```

This behavior is not specific to SQLite, I believe other databases work the same way (PostgreSQL does at least). `CREATE TABLE AS` does not copy constraints, default values, triggers, etc. from the source table, it only copies data.  If you need to copy any of the above, you should not use `CREATE TABLE AS`.

**Comment by zw963** [comment]
> This behavior is not specific to SQLite, I believe other databases work the same way (PostgreSQL does at least). `CREATE TABLE AS` does not copy constraints, default values, triggers, etc. from the source table, it only copies data. If you need to copy any of the above, you should not use `CREATE TABLE AS`.

Yes,  I absolutely agree with you, it should not copy constraints, triggers etc.

but, the current issue is, we need a way to recreate the autoincrementing id column for `new_stocks`, but current, we are not.

thank you.

**Comment by jeremyevans** [comment]
Create the `new_stocks` table using the same definition as the `stocks` table, then use a regular insert:

```ruby
    create_table(:new_stocks) do
      primary_key :id
      String :name, null: false, unique: true
      foreign_key :exchange_id, :exchanges
    end
    from(:new_stocks).insert(from(:stocks))
```

**Comment by zw963** [comment]
> Create the `new_stocks` table using the same definition as the `stocks` table, then use a regular insert:
> 
> ```ruby
>     create_table(:new_stocks) do
>       primary_key :id
>       String :name, null: false, unique: true
>       foreign_key :exchange_id, :exchanges
>     end
>     from(:new_stocks).insert(from(:stocks))
> ```

Oh, i use wrong way! it works, thank you!

**Comment by zw963** [comment]
Sorry,  , leave message here just for forget mention to you before,  i create a new gem several days ago, [only_blank](https://github.com/zw963/only_blank), it use some code in sequel [here](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/blank.rb), thank you for offer this awesome library.
