### ISSUE TITLE
Security Guide

### ISSUE THREAD

**Issue by athix** [jeremyevans/sequel#1767]
The [Security section of the README](https://github.com/jeremyevans/sequel#label-Security) mentions a security guide that you can reference for more information, but there is no link to the guide, nor is there one in the resources section of the README, nor a SECURITY.md file in the root of the repo.

As an end user looking into sequel, I don't know where to go to find it. Adding a direct link would be very beneficial.

Thanks!

**Comment by jeremyevans** [comment]
Probably helps if you view the README on the generated RDoc, such as the Sequel website, as that links to the security guide: http://sequel.jeremyevans.net/rdoc/files/README_rdoc.html#label-Security  . GitHub doesn't handle this correctly, but that's a bug in GitHub's rdoc parser, not a bug in Sequel.

The Security Guide it takes you to is also the second link on Sequel's documentation page, directly after the README: http://sequel.jeremyevans.net/documentation.html

**Comment by athix** [comment]
@jeremyevans nothing indicated to me that the Github README was not a desirable place to read the information. Perhaps referencing that the canonical URL for the documentation is the RDoc url near the top would be an ideal solution while Github's processing is bugged.

**Comment by jeremyevans** [comment]
Other than not showing all links, GitHub's rdoc parser does a fine job.  Adding something to the README warning about a minor link issue in GitHub's RDoc parsing doesn't make sense to me, as it would be pointless for all the cases where people are viewing the README not on GitHub.  This isn't an issue about a canonical URL, any user that installs the sequel gem and generates rdoc documentation for it can view the README in it and have a working link to the security guide (and other links).

This isn't a new issue, GitHub has been like this for a long time and I doubt has any plans to fix the issue.

In any case, even without any link or indication, I don't think it is unreasonable to expect that a user would look in the `doc` directory for the guide (it's located at `doc/security.rdoc`).

**Comment by athix** [comment]
If you feel that this isn't an issue, then that's your decision as the project lead. I wanted to convey my confusion as an end user, which has been accomplished.

Have a good day!

**Comment by jeremyevans** [comment]
I appreciate your comments. I wish GitHub handled rdoc links correctly.  However, I feel the costs of such a documentation change outweigh the benefits.
