### ISSUE TITLE
PostgreSQL: Unlogged tables not respected by SchemaDumper

### ISSUE THREAD

**Issue by jordannb** [jeremyevans/sequel#1778]
### Complete Description of Issue
`Sequel::SchemaDumper` does not have support for PostgreSQL `:unlogged` that was introduced to Sequel by [this PR](https://github.com/jeremyevans/sequel/pull/575). As a result, every time migrations are run that include the `unlogged: true` option, the associated schema dump does not include `, unlogged: true` in the `create_table` table declaration. This means that when db is created from a dumped schema, the schema will not match what it would had it been created via migrations.

Our current workaround is to edit the schema dump (`schema.rb` in our Rails app) and undo or ignore this change to the file before committing to source control. This is not ideal, as it may not be intuitive to developers that the file change should be ignored.

I looked into how to fix this a bit, starting with [this](https://github.com/jeremyevans/sequel/blob/f44925e5c4074a7c3f2dba0d853e125d76988b90/lib/sequel/extensions/schema_dumper.rb#L153), where the table dump happens, but it only seems to support schema details for *columns*. I'd be happy to help with a PR to fix this issue, but I'm not sure if we should change the return model of [this method](https://github.com/jeremyevans/sequel/blob/d4bd4df36ad65ad7e41fe0cd703ff41cdb468db4/lib/sequel/database/query.rb#L80-L183) to return more than just columns, or if there's a less disruptive way to make the change.

### Simplest Possible Self-Contained Example Showing the Bug
Context: I am experiencing this issue in a pre-existing Rails application, and I'm not yet familiar enough with the Ruby ecosystem to know what filenames and commands would apply fairly universally vs. only in a fairly "conventional" Rails app, so I've tried to keep this description fairly generic.

Add a new migration:
```
Sequel.migration do
  change do
    create_table(:some_table, unlogged: true) do
      column :id, "uuid", :null=>false

      primary_key [:id]
    end
  end
end
```

Then run the migration, dumping schema, and note that the newly dumped schema includes only:

```
Sequel.migration do
  change do
    create_table(:some_table) do
      column :id, "uuid", :null=>false

      primary_key [:id]
    end
  end
end
```

### Full Backtrace of Exception (if any)
N/A

### SQL Log (if any)
N/A

**Comment by jeremyevans** [comment]
This is expected and not considered a bug.  There are many things the schema dumper doesn't handle that are way more popular than unlogged tables, such as CHECK constraints, functions, and partial indexes.  The schema dumper is primarily designed for taking the schema from one database type and applying it to a different database type, and I don't know of other databases that support unlogged tables.

I guess the documentation does not stress the limitations of the schema dumper as strongly as it should.  I'll fix that.
