### ISSUE TITLE
No way to i18n error message when adding error message to an array of columns 

### ISSUE THREAD

**Issue by JemarJones** [jeremyevans/sequel#1779]
### Complete Description of Issue
When adding a validation error that involves multiple columns (ie as the `validates_unique` validation helper does), the resulting error message starts off with the list of affected columns [joined by the english word " and "](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/model/errors.rb#L41). This portion of the message is not customizable and therefore cant be internationalized.

### Simplest Possible Self-Contained Example Showing the Bug
Say you have some model with columns called name, country, and postal_code, and you have some validation involving all of these fields which you add an error message for:
```
class Contact < Sequel::Model
  def validate
    errors.add(
      [:name, :country, :postal_code],
      I18n.t('errors.has_some_problem')
    )
  end
end
```

If your custom error message is translated to french for example you might wind up with an error message like `name and country and postal_code a des problèmes` which includes the english word `and`.

**Comment by jeremyevans** [comment]
The current behavior is expected. You have to override `Sequel::Model::Errors#full_messages` to handle this.  This is documented in the `validation_helpers` plugin documentation.

I'm open to making the behavior easier to override to better support i18n.  Would you prefer a method such as?:

```ruby
def full_message(att, error)
  "#{Array(att).join(' and ')} #{e}"
end
```

If not, do you have another suggestion?

**Comment by JemarJones** [comment]
Ahh i seem to have missed this note in the documentation about overriding `full_messages`, thanks for pointing that out!

I do like your proposal of a `full_message` method to override 👍. My alternative thought would be to define an even more granular `attribute_conjunction` method which could be overridden. Depending on how granular you're willing to get with this

**Comment by jeremyevans** [comment]
I think the issue with `attribute_conjunction` is that potentially different i18n needs may require something other than a simple join of the attributes with the conjunction.  Also, different i18n needs may want the error message before the attributes.  I think `full_message` handles both of those needs.

I'll add support for `full_message` later today.

**Comment by JemarJones** [comment]
Those are good points, i think that sounds reasonable then 👍
