### ISSUE TITLE
Omitting database name defaults to username (with postgres)

### ISSUE THREAD

**Issue by theorician** [jeremyevans/sequel#1781]
### Complete Description of Issue

I'm not sure if this is a bug or intended as-is. I'm not great at sleuthing docs but I tried and came up empty. Quite simply: doing a Sequel.connect (using the URI or the hash formats) and omitting the database name causes it to attempt to connect to a database equal to the username. (At least that's the case for the postgres adapter.) If that DB does not exist, the error given comes directly from the postgres adapter, and reads "FATAL: database <name> does not exist." 

Maybe I'm naive - but my expectation would have been that Sequel connects to postgresql without connecting to a DB. (This way you could e.g. create users or check the postgres version using users that have no access rights to specific data.) 

### Simplest Possible Self-Contained Example Showing the Bug

Assuming the `valid_*` names below are actually valid,
```
Sequel.connect("postgres://valid_user:valid_pass@valid_host")
```

### Full Backtrace of Exception (if any)

```
irb(main):003:0> Sequel.connect('postgres://valid_user:valid_password@valid_host:5432')
Traceback (most recent call last):
       15: from (irb):2
       14: from (irb):3:in `rescue in irb_binding'
       13: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/core.rb:124:in `connect'
       12: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/database/connecting.rb:57:in `connect'
       11: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/database/connecting.rb:57:in `new'
       10: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/database/misc.rb:169:in `initialize'
        9: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/database/connecting.rb:278:in `test_connection'
        8: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        7: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        6: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
        5: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
        4: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/connection_pool.rb:122:in `make_new'
        3: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/adapters/postgres.rb:210:in `connect'
        2: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/adapters/postgres.rb:210:in `new'
        1: from /usr/share/gems/gems/sequel-5.46.0/lib/sequel/adapters/postgres.rb:210:in `initialize'
Sequel::DatabaseConnectionError (PG::ConnectionBad: FATAL:  database "valid_user" does not exist)
```

### SQL Log (if any)

N/A

Thanks in advance for the help and for the quality software, Jeremy!

**Comment by jeremyevans** [comment]
This isn't a bug, this is PostgreSQL's default behavior. Both the PostgreSQL client command line tool (`psql`) and the PostgreSQL  C interface (`libpq`) operate this way.  I don't believe PostgreSQL has a concept of connecting without connecting to a database.  So if you would like this changed, you should ask the PostgreSQL developers.

**Comment by theorician** [comment]
@jeremyevans Thanks for the response. I was convinced that psql let me connect without a DB - but I defer to your knowledge. Sorry for the interruption and thanks again!
