### ISSUE TITLE
auto validations on mysql tables with blob type field

### ISSUE THREAD

**Issue by msz-kp** [jeremyevans/sequel#1782]
### Complete Description of Issue

i'm not sure it is a bug or i am missing something..

tables with blob type fields and auto validations enabled results in an error while saving
it's somehow related with mysql.. i do not have this problem with postgres
shouldn't Test.new(blob: "xxx").save.blob.class return Sequel::SQL::Blob in example below ? (it returns String)

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require "mysql2" # 0.5.3
require "sequel" # same behavior on 5.43.0 and 5.48.0

DB = Sequel.connect("mysql2://test:test@localhost/test") # mariadb 10.5.10

DB.drop_table?(:tests)
DB.create_table :tests do
  primary_key :id
  String :str
  File :blob
end

class Test < Sequel::Model
  plugin :auto_validations
end

rec = Test.new   #<Test @values={}>
rec.blob = 'xxx' #<Test @values={:blob=>#<Sequel::SQL::Blob:0xd34 bytes=3 content="xxx">}>
rec.save_changes #<Test @values={:id=>1, :str=>nil, :blob=>"xxx"}>
rec.str = 'yyy'  #<Test @values={:id=>1, :str=>"yyy", :blob=>"xxx"}>
# error
rec.save_changes # Sequel::ValidationFailed: blob is not a valid sequel::sql::blob

rec = Test.first #<Test @values={:id=>1, :str=>nil, :blob=>"xxx"}>
rec.str = 'yyy'  #<Test @values={:id=>1, :str=>"yyy", :blob=>"xxx"}>
# error
rec.save_changes #Sequel::ValidationFailed: blob is not a valid sequel::sql::blob

rec = Test.first #<Test @values={:id=>1, :str=>nil, :blob=>"xxx"}>
rec.blob = 'xxx' #<Test @values={:id=>1, :str=>nil, :blob=>#<Sequel::SQL::Blob:0xd48 bytes=3 content="xxx">}>
rec.str = 'yyy'  #<Test @values={:id=>1, :str=>"yyy", :blob=>#<Sequel::SQL::Blob:0xd48 bytes=3 content="xxx">}>
# ok
rec.save_changes #<Test @values={:id=>1, :str=>"yyy", :blob=>#<Sequel::SQL::Blob:0xd48 bytes=3 content="xxx">}>
```

### Full Backtrace of Exception (if any)

Traceback (most recent call last):
	2: from tst.rb:31:in `<main>'
	1: from /tmp/test/vendor/bundle/ruby/2.7.0/gems/sequel-5.48.0/lib/sequel/model/base.rb:1501:in `save_changes'
/tmp/test/vendor/bundle/ruby/2.7.0/gems/sequel-5.48.0/lib/sequel/model/base.rb:1485:in `save': blob is not a valid sequel::sql::blob (Sequel::ValidationFailed)

**Comment by jeremyevans** [comment]
This isn't a bug in auto_validations, it's due to the mysql2 adapter not typecasting the blob columns.  The mysql2 adapter uses the mysql2 driver to handle all typecasting, and it doesn't handle this.  The workaround in this case is to use the `typecast_on_load` plugin: `Test.plugin :typecast_on_load, :blob`

**Comment by msz-kp** [comment]
Thanks ! problem solved
