### ISSUE TITLE
variables naming in Sequel[:public][:users]

### ISSUE THREAD

**Issue by 7dr1v3** [jeremyevans/sequel#1783]
Hi Jeremy. We use PostgreSQL with schemas at our work and naming in Sequel::SQL::QualifiedIdentifier are confused our newbies in Sequel

```
> Sequel[:public][:users]
=> #<Sequel::SQL::QualifiedIdentifier @table=>"public", @column=>:users>
```
`public` is not a table. So, I am understand that we can't detect `public` as schema in Sequel, it can be a table. But may be you can change this to array for example.

When we do 
```
> Sequel[:public][:users][:id]
=> #<Sequel::SQL::QualifiedIdentifier @table=>#<Sequel::SQL::QualifiedIdentifier @table=>"public", @column=>:users>, @column=>:id>
```

It can be 
```
#<Sequel::SQL::QualifiedIdentifier @path=> [:public, :users, :id]>
```

It will be more comfortable for newbies

**Comment by jeremyevans** [comment]
I understand the issue, but I don't think the benefits of making such a change are worth the cost. Such a change may make it easier for your newbies, but the vast majority of other newbies that don't work with schemas are probably better served by the current table/column naming.
