### ISSUE TITLE
pg 14  (production on centos 8) and pg 13  (development on archlinux) generate different db/schema.rb

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel#1790]
I generate db/schema.rb use a command like following in a rake task.

```
bundle exec sequel -d postgres://postgres:postgres@localhost:5432/marketbet_crawler_development > db/schema.rb
```

In fact, i don't sure if pg version different or whatever cause this issue, but, the result is, it generate two version db/schema.rb, following is a diff example

```diff
@@ -1,16 +1,16 @@
 Sequel.migration do
   change do
     create_table(:exchanges, :ignore_index_errors=>true) do
-      primary_key :id
-      String :name, :text=>true, :null=>false
+      primary_key :id, :type=>:Bignum
+      String :name, :size=>255, :null=>false
       
-      index [:name], :name=>:exchanges_name_key, :unique=>true
+      index [:name], :name=>:sqlite_autoindex_exchanges_1, :unique=>true
     end
```

Following is changes:

- `Integer` change to `Bignum` on production
- primary_key add `type: Bignum` on production
- `text: true` on String type change to `size: 255`

Because i need to export production data to development use `pg_dump -Fc ...`, `pg_restore`, that cause a strange issue:

when i run `rake db:migrate` on development, it update db/schema.rb use production imported data, then, when i run rake test, 
it use data populate with factories,  two migration generate different version schema like above example, it annoying ...

So, if this is a issue? if this is expected, how to workaround this when do import/output ?

Thank you.

**Comment by jeremyevans** [comment]
It actually looks like one of the databases used is SQLite, since I  doubt PostgreSQL is going to generate an index named `sqlite_autoindex_exchanges_1`.

In any case, this is expected behavior.  The databases you are generating the migration from have different schema, and the generated migration reflects that.

In terms of working around it, the simplest solution is to avoid the issue by using the same database version in development that you use in production.

**Comment by zw963** [comment]
> It actually looks like one of the databases used is SQLite, since I doubt PostgreSQL is going to generate an index named `sqlite_autoindex_exchanges_1`.

Yes,  I almost forget it, i development and deployment use sqlite 3 when start my project, but, switch to postgres after a while.
i migrate my data use `sequel -C` like this on production.

```
bundle exec sequel -C sqlite://db/files/marketbet_crawler_production.db postgres://postgres:postgres@localhost:5432/marketbet_crawler_production
```

So, there exists some evidence use sqlite3.

just for double confirm, for my cause, this issue maybe caused by: 

data on production is data import from sqlite3,  because this, run migration on there generate schema like:  `:type=>:Bignum`, `:size=>255`, right?
