### ISSUE TITLE
H2 Database 2.0 stops working with Sequel due to "identity" data type restrictions in changelog

### ISSUE THREAD

**Issue by sharkos** [jeremyevans/sequel#1817]
### Complete Description of Issue
According to H2's PR #3067: **Restrict identity data types and result limitation clauses to compatibility modes**. In your adapter for H2 under JDBC, it is noted to use the identity data type. 
See :  https://www.h2database.com/html/changelog.html

Using JRuby 9.3.2.0, Sequel 5.52.0, H2 loaded as Jar file. (2.0.206) 

### Simplest Possible Self-Contained Example Showing the Bug

```
# -> Try to load H2 Database from JAR.
# (instead of using the GEM for jdbc-h2 which tends to be outdated)
begin
  require 'h2-2.0.206.jar'  # This loads the entire DB engine from jar
  Java::org.h2.Driver             # This loads the native JDBC driver
rescue LoadError
  raise "ERROR: unable to load embedded database engine."
end

# H2 Database ARRAY Datatype
class Java::OrgH2Jdbc::JdbcArray
  # Returns the JDBC array to a Ruby Array
  def to_r
    return self.getArray.to_a
  end

  def count
    return self.getArray.to_a.length
  end

end

Sequel.connect("jdbc:h2:./db/testdb", :user => "sa", :password=> "changeme")

Sequel.migration do
  change do
  create_table(:users) do
    primary_key  :id
    boolean      :islocked
    String      :login,          size: 16, unique: true
    TimeStamp   :login_last
    TimeStamp   :created
    TimeStamp   :modified
  end
end // change
end //migration

class User < Sequel::Model(:users)
end

    User.create  :login => 'someuser',
      :islocked => false
```

### Full Backtrace of Exception (if any)
DB Preloading data..........................................[STRT]
 inserting: Admin User......................................rake aborted!
Sequel::DatabaseError: Java::OrgH2Jdbc::JdbcSQLSyntaxErrorException: Function "IDENTITY" not found; SQL statement:
SELECT IDENTITY(); [90022-206]

**Comment by jeremyevans** [comment]
Currently, the Sequel jdbc/h2 adapter only supports H2 1.4 (that's the latest release of the jdbc-h2 gem).  If you would like this fixed, can you get the Sequel jdbc/h2 adapter updated to support H2 2.0, then I can start testing with it?

**Comment by jeremyevans** [comment]
> Currently, the Sequel jdbc/h2 adapter only supports H2 1.4 (that's the latest release of the jdbc-h2 gem). If you would like this fixed, can you get the Sequel jdbc/h2 adapter updated to support H2 2.0, then I can start testing with it?

Sorry, I meant to say, can you get the jdbc-h2 gem updated to support H2 2.0, so I can start testing the jdbc/h2 adapter with it, and make the appropriate changes so it works with both H2 1.4 and 2.0.

**Comment by sharkos** [comment]
No one has touched those repos in 8 years :(

**Comment by jeremyevans** [comment]
jdbc-h2 gem seems last updated in 2018: https://rubygems.org/gems/jdbc-h2

**Comment by sharkos** [comment]
I'll ask enebo and see if he can update it
https://github.com/sharkos/activerecord-jdbc-adapter/tree/master/jdbc-h2

Thanks!

**Comment by enebo** [comment]
@jeremyevans @sharkos I put out a new version with 2.0.204 bundled.  We had dropped support for a bunch of dbs in arjdbc when we added Rails 5 support and this was one of those.  I am happy to keep this and any others you support up to date for sequel.  I mostly just need to know which ones should be updated.

**Comment by jeremyevans** [comment]
@enebo Thank you very much.  I'll try to work on this today, but I might not have time until next week.
