### ISSUE TITLE
`Infinity` float values are silently converted to `0.0`

### ISSUE THREAD

**Issue by sir4ur0n** [jeremyevans/sequel#1825]
### Complete Description of Issue
Have a value of `Infinity` in database for a float column (I use Redshift, using the `postgres` adapter).
Query it with Sequel, e.g. `DB[Sequel[:my_schema][:my_table]].all`.
The returned value contains `0.0`.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
DB = Sequel.connect('postgres://my_user:my_password@my_redshift_host:5439/my_database', client_min_messages: '', force_standard_strings: false)
DB[Sequel[:my_schema][:my_table]].all
```

### Full Backtrace of Exception (if any)
N/A

### SQL Log (if any)
N/A

I am a Ruby newbie so I am not opinionated on what Sequel should do in that case, but I am strongly in favor of **not** silently converting to `0.0`.

I find this bug even weirder as https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/postgres.rb makes me think `Infinity` should be correctly handled by Sequel. There are chances there is something wrong in the way I use Sequel, but I've read through the documentation a few times and can't figure it out :disappointed:

**Comment by jeremyevans** [comment]
This doesn't seem like a problem when using PostgreSQL:

```ruby
DB.get(Sequel.cast("Infinity", Float))
# SELECT CAST('Infinity' AS double precision) AS "v" LIMIT 1
# => Infinity
```

Maybe it is a Redshift-specific issue.  Sequel doesn't advertise Redshift support, and any Redshift-specific issues are not bugs in Sequel.  If you can reproduce this issue on PostgreSQL, please post how to do that and I can reopen this.

**Comment by sir4ur0n** [comment]
Indeed I just tested on a Postgres server and the value is correctly returned as `Infinity`, so I guess the problem only occurs when using Sequel (Postgres adapter) for Redshift :disappointed: 

I am pretty sad and disappointed but it's none of Sequel's fault :smile: Thank you for the prompt answer and have a nice week-end!

**Comment by sir4ur0n** [comment]
Hello @jeremyevans 

I have been digging further with various libraries, and I keep thinking Sequel is probably the best in Ruby ecosystem.
Would you be willing to add support for Redshift by any chance? (I know it's a long shot, but one never knows :sweat_smile: )
As far as I can see, for now all of Postgres adapter works, except apparently Redshift uses `'inf'` rather than `'Infinity'` to encode infinity...

Alternatively, would there be a - if possible simple - way to override, extend or add an adapter to Sequel in my own application code please?

**Comment by jeremyevans** [comment]
I have no plans to add support for Redshift.  I will not be adding support for additional adapters that I cannot host/test locally.

If the issue is limited to parsing infinite floats, it seems you could do:

```ruby
    DB.conversion_procs[700] = DB.conversion_procs[701] = proc do |value|
      case value
      when 'NaN'
        0.0/0.0
      when 'inf'
        1.0/0.0
      when '-inf'
        -1.0/0.0
      else 
        value.to_f 
      end  
    end
```

However, you are probably better off maintaining a sequel-redshift adapter.  There is one already, but it appears to have not been maintained in a while: https://github.com/knaveofdiamonds/sequel-redshift

**Comment by sir4ur0n** [comment]
Wow, again I appreciate the fast and quality answers, thank you so much @jeremyevans !

For the record (in case anyone lands here in the future) Redshift apparently also encodes `Float::NAN` as `'nan'` rather than `'NaN'`, so the full code looks like this (tested on all values):
```ruby
    DB.conversion_procs[700] = DB.conversion_procs[701] = proc do |value|
      case value
      when 'nan'
        0.0/0.0
      when 'inf'
        1.0/0.0
      when '-inf'
        -1.0/0.0
      else 
        value.to_f 
      end  
    end
```

Purely for my curiosity (I am fairly new in Ruby if that was not obvious enough :grin: ) is there a reason why you use e.g. `1.0/0.0` rather than `Float::INFINITY` in Sequel code?

**Comment by jeremyevans** [comment]
> Purely for my curiosity (I am fairly new in Ruby if that was not obvious enough grin ) is there a reason why you use e.g. `1.0/0.0` rather than `Float::INFINITY` in Sequel code?

Likely a holdover from when we supported Ruby 1.8, as `Float::INFINITY` wasn't added until Ruby 1.9.
