### ISSUE TITLE
be able to test the connection before execute the SQL?

### ISSUE THREAD

**Issue by TDtianzhenjiu** [jeremyevans/sequel#1862]
### Complete Description of Issue

Currently in our prd env raise exception  `Sequel::DatabaseDisconnectError/PGError  `frequently.

In order to fix the issue, my idea is to check the connection before execute the SQL statement, if connection is not valid needs re-connect. it similar to the `testOnBorrow` in the jdbc connection pool

for instance :  execute SQL "select 1" before execute real  SQL statement.

Be able to implement it?
Or do you have any better suggestions to avoid that exception？
Thanks

**Comment by jeremyevans** [comment]
You probably want to use the `connection_validator` extension, which automatically handles this.

In the future, as mentioned in the contribution guidelines, please post questions like this as a discussion.  Only open an issue to report a bug in Sequel itself.

**Comment by TDtianzhenjiu** [comment]
OK, thanks

but is there a way to change the `valid_connection_sql`?
It seems always return `select null`
