### ISSUE TITLE
CLI error: value too long for type character varying(50)

### ISSUE THREAD

**Issue by ejstembler** [jeremyevans/sequel#1887]
### Complete Description of Issue

When using the CLI to import sqlite3 to Postgres, the following error is raised:

```
Error: Sequel::DatabaseError: PG::StringDataRightTruncation: ERROR:  value too long for type character varying(50)
```

**Note**: Not sure if this matters, this is a Google Cloud SQL Postgres instance which uses [cloud_sql_proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy) to connect via localhost.

### Simplest Possible Self-Contained Example Showing the Bug

```console
sequel -C sqlite://data.db postgresql://user:password@127.0.0.1:5432/database
```

Output:

```
Databases connections successful
Migrations dumped successfully
Tables created
Begin copying data
Begin copying records for table: table1
Status: 181 records copied
Status: 389 records copied
Status: 583 records copied
Status: 781 records copied
Finished copying 834 records for table: table1
Begin copying records for table: table2
Status: 201 records copied
Status: 413 records copied
Status: 612 records copied
Status: 804 records copied
Status: 985 records copied
Status: 1177 records copied
Status: 1377 records copied
Status: 1566 records copied
Status: 1755 records copied
Status: 1959 records copied
Status: 2153 records copied
Status: 2357 records copied
Error: Sequel::DatabaseError: PG::StringDataRightTruncation: ERROR:  value too long for type character varying(50)

/Users/estemble/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:154:in `exec'
```

### Full Backtrace of Exception (if any)

Not available

### SQL Log (if any)

Not available

**Comment by ejstembler** [comment]
@jeremyevans Thanks for the detailed response.  I had suspected as much.

Does the sequel CLI try to guess the size if the source is sqlite, or is it hard-coded?  This may be able to be solved doing a length check on all `TEXT` columns.  Something like:

```sql
SELECT MAX(LENGTH(column_name) FROM table_name;
```

That value would be the size for the column in the target database `varchar(value)`

**Comment by jeremyevans** [comment]
Sequel doesn't try to guess the size, Sequel uses the type of the column in the source table to determine the type of the column in the destination table.

As someone who likes understatement, trying to calculate maximum column size in the source table, and using that to set the type of the column in the destination table, seems unwise even though it may allow the copying to work.
