### ISSUE TITLE
NoMethodError: undefined method `blank?'

### ISSUE THREAD

**Issue by bethesque** [jeremyevans/sequel#1919]
### Complete Description of Issue

My sincere apologies that this is such a poor bug report, but I hope if someone else has the same issue, they may be able to help me identify the cause.

This change appears to have caused a problem in my projects https://github.com/jeremyevans/sequel/commit/0e0e9db9e97dc902e818843ab9e9ff863cf05d88

I am not sure how a method can cause defined? to return true, but to raise a NoMethodError when invoked, but it is happening.

### Simplest Possible Self-Contained Example Showing the Bug

Sorry, I'm still working on reproducing the issue in isolation from the full project. I can't reproduce it on a vanilla ruby 2.7 docker image. I suspect there may be some other gem that is causing problems.

```
# In Ruby 2.7.5
git clone git@github.com:pact-foundation/pact_broker.git
cd pact_broker
bundle install
bundle exec rake spec
```

See the failing builds here, which only started when Sequel 5.60.0 was relased  https://github.com/pact-foundation/pact_broker/runs/8146948768?check_suite_focus=true

### Full Backtrace of Exception (if any)

```
NoMethodError: undefined method `blank?' for "tmp/pact_broker_database_test.sqlite3":String
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/database/misc.rb:353:in `blank_object?'
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/adapters/sqlite.rb:236:in `connection_pool_default_options'
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/database/misc.rb:128:in `initialize'
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/adapters/sqlite.rb:102:in `initialize'
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/database/connecting.rb:57:in `new'
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/database/connecting.rb:57:in `connect'
/usr/local/bundle/gems/sequel-5.60.0/lib/sequel/core.rb:124:in `connect'
/home/pact_broker/spec/support/test_database/connection.rb:57:in `connect'
```

```
D, [2022-09-02T11:46:23.838175 #27017] DEBUG -- : (0.000058s) SELECT sqlite_version()
D, [2022-09-02T11:46:23.838333 #27017] DEBUG -- : (0.000046s) SELECT NULL AS 'nil' FROM `schema_migrations` LIMIT 1
D, [2022-09-02T11:46:23.838387 #27017] DEBUG -- : (0.000023s) SELECT * FROM `schema_migrations` LIMIT 0
D, [2022-09-02T11:46:23.838852 #27017] DEBUG -- : (0.000408s) SELECT `filename` FROM `schema_migrations` ORDER BY `filename`
E, [2022-09-02T11:46:23.863424 #27017] ERROR -- : NoMethodError: undefined method `blank?' for "NULL":String: PRAGMA table_xinfo('webhook_executions')
Traceback (most recent call last):
```

**Comment by jeremyevans** [comment]
Thanks for the report.  One of the things I checked before switching to `defined?` was that it handled `respond_to_missing?` correctly:

```ruby
class A
end
a = A.new
[defined?(a.foo), a.respond_to?(:foo)]
# => [nil, false]

class A
  def respond_to_missing?(meth, *); super || meth == :foo end
end

[defined?(a.foo), a.respond_to?(:foo)]
# => ["method", true]
```

Please let me know if you are able to isolate the problem.  The only thing I can think of is a situation where `blank?` is defined on the object, but calling `blank?` raises `NoMethodError`.  Maybe `respond_to?` is explicitly defined to `false` for the object, even though the object will respond to it?

```ruby
class A
  def foo; raise NoMethodError end
  def respond_to?(meth, *); return false if meth == :foo; super end
end

a = A.new
[defined?(a.foo), a.respond_to?(:foo)]
# => ["method", false]

a.foo
# NoMethodError
```

If that is the cause of the problem, I'm not sure Sequel should support that.  If an object reports it does not respond to a method, it shouldn't respond to it.

From additional testing, I was able to find able to find a case where the behavior differed.  This is for protected methods, where `respond_to?` would return false, but `defined?` would not return nil if called in a context that would allow the protected method call.  However, this seems more like a bug fix than a bug, and doesn't appear to be related to your issue.

**Comment by bethesque** [comment]
Thanks for having a look at it Jeremy. I'll do some more digging and see if I can get to the bottom of it.

**Comment by bethesque** [comment]
Looks like it's a ruby 2.7 issue, and is present when there is a refinement on the String (and other) classes.

Script to reproduce:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "sequel", "5.60.0"
  gem "sqlite3", "1.4.4"
end

require "logger"

module StringRefinements
  refine String do
    def blank?
      self.strip.size == 0
    end
  end
end

Sequel.connect("sqlite:////tmp/db.sqlite3", logger: Logger.new($stdout))
```

This fails with:

```
/Users/beth/.gem/ruby/2.7.6/gems/sequel-5.60.0/lib/sequel/database/misc.rb:353:in `blank_object?': undefined method `blank?' for "//tmp/db.sqlite3":String (NoMethodError)
```

For me, this fails on ruby-2.7.5, ruby-2.7.6 and passes on ruby-3.1.2, running on Mac Monterey.

**Comment by jeremyevans** [comment]
Ah, so an unused refinement is picked up by `defined?`.  Your example fails in all versions of Ruby 2, but passes in Ruby 3.  Definitely a bug in Ruby, which is why it was fixed. Unfortunately, I think the only solution is to revert the change to `defined?`, since I don't want to drop support for Ruby < 3.  I'll push out a 5.60.1 gem with the change, hopefully today if I have time.  Thanks again for reporting this.

**Comment by bethesque** [comment]
Thank you for the quick response Jeremy. Your work on this gem is much appreciated.

**Comment by kuraga** [comment]
Possibly, Ruby bug issue is https://bugs.ruby-lang.org/issues/16932
