### ISSUE TITLE
Hstore gotcha

### ISSUE THREAD

**Issue by baelter** [jeremyevans/sequel#1931]
This is a bit of a gotcha: 
`DB[:table].where(id:).update(col: Sequel.hstore_op(:col).concat(key: "value"))` 
gives `col = nil` if it was `nil` beforehand.

Maybe Sequel should add `coalesce` to the query in that case?

**Comment by tycooon** [comment]
But this is how postgres works. If you want `coalesce`, you can use it like this: `Sequel.function(:coalesce, ...)`.

**Comment by baelter** [comment]
Yeah, I know. But code is getting pretty ugly for updating a hstore, so would by nice with some sugar.
`DB[:table].where(id:).update(col: Sequel.hstore_op(Sequel.function(:coalesce, :col, Sequel.hstore({})).concat(col: "value")))`

**Comment by baelter** [comment]
Sure, don't change behavior of concat, but a new method?
