### ISSUE TITLE
`connect_sqls` aren't executed if inside `:servers`

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1935]
### Complete Description of Issue
`connect_sqls` are executed only if they are on the main config. They don't work if done on a server-specific basis.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
require 'sequel'
require 'logger'
require 'dotenv'

Dotenv.load ".env.development"
Dotenv.load ".env"

config = {
  adapter:         ENV['DB_ADAPTER'],
  encoding:        ENV['DB_ENCODING'],
  database:        ENV['DATABASE'] || ENV['DB_NAME'],
  host:            ENV['DB_HOST'],
  user:            ENV['DB_USER'],
  password:        ENV['DB_PASSWORD'],
  port:            ENV["DB_PORT"] || '5432',
  max_connections: ENV['DB_POOL'].to_i,
  pool_timeout:    ENV['DB_POOL_TIMEOUT'].to_i,
  # it works here
  #connect_sqls: ['SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY'],
  test:            true,
}
servers           = config[:servers] = {}
servers[:offload] = config.merge(
  # but not here
  connect_sqls: ['SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY']
)

DB = Sequel.connect config, servers: servers
DB.sql_log_level = :debug
DB.loggers << Logger.new($stdout)

DB.fetch('delete from users where id = -123').all
```

**Comment by jeremyevans** [comment]
I'm not sure this is a bug, as sharding options are supposed to only affect connection information, and this would be post-connection setup. However, I agree that this would be a useful feature to have. It might require backwards incompatible changes to the adapter API. I'll look into what can be done to support this.

**Comment by jeremyevans** [comment]
Actually, looks like this is handled by the connection pool, so thankfully it doesn't require changes to the the adapter API.  Here's a patch:

```diff
diff --git a/lib/sequel/connection_pool.rb b/lib/sequel/connection_pool.rb
index d4d4407b7..e3a96aa94 100644
--- a/lib/sequel/connection_pool.rb
+++ b/lib/sequel/connection_pool.rb
@@ -129,7 +129,7 @@ class Sequel::ConnectionPool
         end
       end

-      if cs = @connect_sqls
+      if cs = @db.send(:server_opts, server)[:connect_sqls]
         cs.each do |sql|
           db.send(:log_connection_execute, conn, sql)
         end
```

I'll probably add a Database method for this, as the patch above isn't very clean.

**Comment by jeremyevans** [comment]
Unfortunately, that approach breaks backwards compatibility, since Sequel supports `DB.pool.connect_sqls = ...`.  I'll have to make this more complex to keep backwards compatibility.
