### ISSUE TITLE
Performance of large select statements

### ISSUE THREAD

**Issue by davidhin** [jeremyevans/sequel#1938]
### Complete Description of Issue
Sequel is much slower than pyodbc when executing select statements. Not sure if this is because I'm using the wrong API or if Sequel is not made for large select queries?

### Simplest Possible Self-Contained Example Showing the Bug
I've created a small repo to show this:
https://github.com/davidhin/sequel-pyodbc-test

The relevant Sequel code I ran is in main.rb:

```ruby
require "sequel"
require "benchmark"

conn = Sequel.connect(
  adapter: "odbc",
  driver: "ODBC Driver 18 for SQL Server",
  server: "0.0.0.0",
  port: "1433",
  uid: "sa",
  pwd: "Password123",
  Encrypt: "yes",
  TrustServerCertificate: "yes",
  ConnectionTimeout: "5",
  Authentication: "SqlPassword",
  database: "TESTDB",
)

benchmark_result = Benchmark.measure do
  conn[:testtable].all
end

puts "Time taken (Sequel): #{benchmark_result.real}"
```

**Comment by jeremyevans** [comment]
Your Sequel code actually retrieves all results (keeps them all in memory).  Looks like your Python code is `cursor.execute("select * from TESTTABLE")`, which just runs the query without retrieving any results.  If you want to benchmark the same behavior in both, iterating over all rows of a large table without keeping all rows in memory:

Ruby:
```ruby
conn[:testtable].each{}
```

pyodbc (guessing):

```python
cursor.execute("select * from TESTTABLE")
row = cursor.fetchone() 
while row: 
    row = cursor.fetchone()
```

**Comment by davidhin** [comment]
Hi Jeremy, thanks for the response. However, I am quite sure that my python code is retrieving the results. After all, I can save them out into a file and literally look at them.

**Comment by jeremyevans** [comment]
Can you post the python code you are using to save the results into a file?

**Comment by davidhin** [comment]
Hi Jeremy, apologies for that message - I thought I deleted it on mobile. But basically, I've updated the code and the results are still faster (see repo)

**Comment by jeremyevans** [comment]
Can you show the result of `cursor.fetchone()` in the python code?

**Comment by davidhin** [comment]
It's still the same as fetchall - updated to use:

```python
import time

import pyodbc

conn = pyodbc.connect(
    "Driver=ODBC Driver 18 for SQL Server;"
    "Server=0.0.0.0;"
    "Port=1433;"
    "uid=sa;"
    "pwd=Password123;"
    "Encrypt=yes;"
    "TrustServerCertificate=yes;"
    "ConnectionTimeout=5;"
    "Authentication=SqlPassword;"
    "Database=TESTDB;"
)

start = time.time()
with conn.cursor() as cursor:
    cursor.execute("select * from TESTTABLE")
    row = cursor.fetchone()
    while row:
        row = cursor.fetchone()
end = time.time()

print(f"Time taken (Pyodbc): {end - start}")
```

**Comment by jeremyevans** [comment]
Sorry if my request was confusing.  I meant can you literally show the results of a single call to `cursor.fetchone()` so I can see what it returns.

**Comment by davidhin** [comment]
Oh right, sorry about that. Here:

('5f0f2cca-4982-4da4-854a-ed2232264a73', datetime.datetime(2022, 10, 8, 7, 28, 57, 105114))

**Comment by jeremyevans** [comment]
Thanks. The Sequel odbc adapter is very slow for timestamp conversions, because it has to convert the Ruby odbc driver `ODBC::Timestamp` type to the core/stdlib Ruby `Time`/`DateTime` type, including handling possible database->application timezone conversions.  Since you are connecting to MSSQL, I would highly recommend using the tinytds adapter instead if performance is desired.

**Comment by davidhin** [comment]
Thanks, I will look into it. But is there a database agnostic option? Although I am using mssql in my example here, the operational code will be connecting with different types of databases as well.

**Comment by jeremyevans** [comment]
Sequel supports a wide variety of databases, and in general you will get the best performance using a database-specific driver/adapter with Sequel.   Sequel itself is the database agnostic option (the Sequel API is pretty much the same regardless of the backend database).

**Comment by davidhin** [comment]
I see, I think I know what to do now. Still, I wonder why on the python side it does not require manually picking the best database drivers?
