### ISSUE TITLE
Connection leak when using prepared statement and Oracle JDBC driver

### ISSUE THREAD

**Issue by andsel** [jeremyevans/sequel#1956]
### Complete Description of Issue
When reusing same prepared statement across multiple DB session it creates a connection leakage with or JDBC Oracle driver.

The flow of control I use to access the DB could be summarized like:
```ruby
statement = "SELECT * FROM table"
name = "MY.PS"

db = open_connection
prepared = db[statement].prepare(:select, name)
query = db.call(name, {})
query.each {|row| queue << row}
db.disconnect

# Execute second query
db = open_connection
db.set_prepared_statement(name, prepared)
query = db.call(name, {})
query.each {|row| queue << row}
db.disconnect
```

The prepared statement is created with the first connection and reused in the second.
What happens, is that every time I iterate over the snipped above I got a new connection (checked with `lsof`) that's never closed, so it's a connection leak.
This seems to happen only with Oracle driver, tried with Postgress and doesn't happen.

First question: is this way of reuse prepared statement across DB session a legit use of `set_prepared_statement` ?

### Simplest Possible Self-Contained Example Showing the Bug
- run a dockerized version Oracle
- run this
<details>
<summary>execute the following script</summary>

```ruby
# encoding: utf-8

# Script to test Sequel connection leakage

require 'jruby'
require "java"
require "sequel"
require "sequel/adapters/jdbc"

config = {
	"jdbc_driver_library" => "/path/to/oracle/ojdbc11-full/ojdbc11_g.jar",
  "jdbc_driver_class" => "Java::oracle.jdbc.driver.OracleDriver",
  "jdbc_connection_string" => "jdbc:oracle:thin:@//10.93.0.227:1521/ORCLCDB",
  "jdbc_user" => "user",
  "jdbc_password" => "pwd",
  "statement" => "SELECT * from SYSTEM_PRIVILEGE_MAP",
  "prepared_statement_name" => "MY.PS",
}

def load_jdbc_driver_class(jdbc_driver_class)
  # sub a potential: 'Java::org::my.Driver' to 'org.my.Driver'
  klass = jdbc_driver_class.gsub('::', '.').sub(/^Java\./, '')
  # NOTE: JRuby's Java::JavaClass.for_name which considers the custom class-loader(s)
  # in 9.3 the API changed and thus to avoid surprises we go down to the Java API :
  klass = JRuby.runtime.getJavaSupport.loadJavaClass(klass) # throws ClassNotFoundException
  # unfortunately we can not simply return the wrapped java.lang.Class instance as
  # Sequel assumes to be able to do a `driver_class.new` which only works on the proxy,
  org.jruby.javasupport.Java.getProxyClass(JRuby.runtime, klass)
end

def jdbc_connect( config)
  sequel_opts = {:pool_timeout => 5, :keep_reference => false}
  sequel_opts[:user] = config["jdbc_user"]
  sequel_opts[:password] = config["jdbc_password"]
  sequel_opts[:driver] = load_jdbc_driver_class(config["jdbc_driver_class"]) 
  return Sequel.connect(config["jdbc_connection_string"], sequel_opts)
end  


def load_driver(config)
  require "java"
  require "sequel"

  require config["jdbc_driver_library"]
  load_jdbc_driver_class(config["jdbc_driver_class"])
end

puts "Loading JDBC driver"
load_driver(config)
puts "driver loaded\n\n"

(1..5).each do |i|
  puts("loop #{i}")

  queue = []

  statement = config["statement"]
  name = config["prepared_statement_name"].to_sym 

  # Execute first query
  db = jdbc_connect(config)
  puts "Executing first query"
  prepared = db[statement].prepare(:select, name)
  query = db.call(name, {})
  query.each {|row| queue << row}
  db.disconnect

  # Execute second query
  puts "Executing second query"
  db = jdbc_connect(config)
  db.set_prepared_statement(name, prepared)
  query = db.call(name, {})
  query.each {|row| queue << row}
  db.disconnect
  
  sleep_secs = 5
  puts("Run for a #{sleep_secs} seconds then exit\n\n")
  sleep sleep_secs
end
```
</details>

- after every loop monitor the connection count with
```
sudo lsof -p 12345 -i | grep 1521
```

### Full Backtrace of Exception (if any)
```
$ sudo lsof -p 44259 -i | grep 1521
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse file system /run/user/1000/doc
      Output information may be incomplete.
docker-pr 116653            root    4u  IPv4 521303      0t0  TCP *:1521 (LISTEN)
docker-pr 116660            root    4u  IPv6 521308      0t0  TCP *:1521 (LISTEN)
java      131164          andrea   14u  IPv6 594142      0t0  TCP kalimera.lan:59994->kalimera.lan:1521 (ESTABLISHED)
java      131164          andrea   15u  IPv6 594151      0t0  TCP kalimera.lan:39432->kalimera.lan:1521 (ESTABLISHED)
java      131164          andrea   16u  IPv6 594176      0t0  TCP kalimera.lan:39476->kalimera.lan:1521 (ESTABLISHED)
java      131164          andrea   17u  IPv6 594188      0t0  TCP kalimera.lan:60590->kalimera.lan:1521 (ESTABLISHED)
java      131164          andrea   18u  IPv6 594210      0t0  TCP kalimera.lan:53380->kalimera.lan:1521 (ESTABLISHED)
```

**Comment by jeremyevans** [comment]
I think your problem is your call to `db.set_prepared_statement(name, prepared)`.  You are taking a prepared statement for first Database object in the loop, and setting it as the prepared statement for the second Database object in the loop.  That prepared statement is used after the disconnect for the first Database object, causing a new connection for the first Database object.  You are not calling disconnect on the first Database object after that point, so the connection never gets disconnected. The connections don't get garbage collected, because by default, a reference to each Database object is kept in Sequel::DATABASES (you can use `keep_reference: false` Database option to prevent that).

Your code seems to be under the impression that you need to create a separate Database object for each underlying database connection, apparently not realizing that a Database object represents a pool of connections, not a single connection.  Unless you need to connect to arbitrary databases at runtime, in general you should only have a single Database object per SQL database you are connecting to.  The Database object is generally created during application initialization, and remains active until the application is stopped.

I'm not sure why this code doesn't have the same problems on PostgreSQL.  Maybe internally the PostgreSQL JDBC driver keeps a separate pool of connections, that are reused?

**Comment by andsel** [comment]
Thanks @jeremyevans for commenting and explaining :-)

> I'm not sure why this code doesn't have the same problems on PostgreSQL. Maybe internally the PostgreSQL JDBC driver keeps a separate pool of connections, that are reused?

Yes I think the same, maybe the other drivers has slightly different ways to handle the connection and so can close the underlying socket in cases like this.

**Comment by jeremyevans** [comment]
The problem will still manifest even with `:keep_reference => false` (at least until the related Sequel::Database is garbage collected) because you are doing `db.set_prepared_statement(name, prepared)`.
