### ISSUE TITLE
`:default` keeping many idle connections when only `:read_only` are being used

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1974]
In a microservice daemon, the server configuration was using the master PostgreSQL as the `:default` server in the connection hash. It also has 5 read replicas rotated in a `:read_only` block. This daemon runs approximately 50 threads per worker, although `:max_connections` is set to less than half with a decent `pool_timeout`.

When checking the master instance it had more than 400 open connections for the specific application user, all of them idle with `SET DateStyle = 'ISO'` as the last query run as seen using the `pg_stat_activity` table.
This is explained as the application only uses read-only queries.

I've replaced the default with the read-only replica address, and this alone freed more than 3gb of memory in the master instance!
Although this replacement helps the master, it now generates many unneeded idle connections in the replica.

Is there any reason to keep those idle connections?

Sequel used is 5.49.0.

**Comment by jeremyevans** [comment]
My guess is you have some parts of your code that are implicitly using the default server when asking for a connection, even if they aren't sending a query on the connection.  Once a connection is added to the pool, it stays in the pool until it is disconnected, there isn't an idle timeout where connections are disconnected.

By default, there will be at least 1 connection per database object as Sequel will test the `:default` shard when creating the Database object (you can disable this with the `test: false` Database option).  If you are using the `:preconnect` Database option, Sequel will create however many max_connections are allowed to the `:default` server when the Database is setting up.

One possible way to see where the `:default` connections are coming from, assuming they are created after the Database object is initialized:

```ruby
DB = Sequel.connect('...', test: false)
def DB.new_connection(server)
  raise "connection to default server" if server == :default # or puts caller if server == :default
  super
end
```

You could then take appropriate action to make sure that a different shard is used for those cases.  The `server_block` Database extension can be helpful in such cases.  If you come across a case where the `server_block` extension will not allow you to handle things appropriately, please post here.

**Comment by brauliobo** [comment]
thanks @jeremyevans. I'll investigate further what is causing it with the patch provided. I antecipate that `test` is true and `preconnect` isn't being used.

**Comment by jeremyevans** [comment]
Since this doesn't appear to be a bug in Sequel, I'm going to close this.  If you find out what is going on and need assistance, please open a Discussion, not an Issue (Issues should only be created for bugs).
