### ISSUE TITLE
Model.db.select(1).where(xyz) gives invalid query for mysql 5.7

### ISSUE THREAD

**Issue by will-gant** [jeremyevans/sequel#1977]
### Complete Description of Issue

A chain of Sequel methods contrived to `SELECT 1` from no table in particular produces queries that are valid for mysql 8.0, and postgres 10 and 14, but invalid for mysql 5.7.

We're running 5.62.0 of the sequel gem and 0.5.4 of mysql2.

### Simplest Possible Self-Contained Example Showing the Bug

This is a slimmed-down example from my code. I'm sort of needlessly calling this on `User` as this is the only way I've found that allows me to generate a `SELECT 1 WHERE...` query:

```ruby
User.db.select(1).
  where do
    Sequel.or(
      [
        [SomeRole.where(user_id: id).exists, true],
        [SomeOtherRole.where(user_id: id).exists, true],
      ]
    )
  end.any?
```

As is, this produces this error when using mysql 5.7:
```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (((EXISTS (SELECT * FROM `some_roles` WHERE (`user_id` = 1))) IS TR' at line 1
```

The query generated for mysql 5.7 is as follows:
```mysql
SELECT 
  1 
WHERE 
  (
    (
      (
        EXISTS (
          SELECT 
            1 
          FROM 
            `some_roles` 
          WHERE 
            (`user_id` = 1) 
          LIMIT 
            1
        )
      ) IS TRUE
    ) 
    OR (
      (
        EXISTS (
          SELECT 
            1 
          FROM 
            `some_other_roles` 
          WHERE 
            (`user_id` = 1) 
          LIMIT 
            1
        )
      ) IS TRUE
    )
  )
```

If you change `SELECT 1` to `SELECT 1 FROM <some-table>` (literally _any_ table) this works as expected.

From what I can tell, in mysql 5.7 a `FROM` is mandatory in the example below, and optional in 8.0:

```mysql
Server version: 5.7.40 Homebrew
mysql> SELECT 1 WHERE 1 = 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1 = 1' at line 1

mysql> CREATE TABLE useless (
    ->   foobar INT
    -> );
Query OK, 0 rows affected (0.04 sec)

mysql> SELECT 1 FROM useless WHERE 1 = 1;
Empty set (0.00 sec)
```

```mysql
Server version: 8.0.31 Homebrew
mysql> SELECT 1 WHERE 1 = 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

**Comment by jeremyevans** [comment]
I don't think this is a bug in Sequel.  `FROM` is not required for all `SELECT` queries in MySQL 5.7 according to the documentation (https://dev.mysql.com/doc/refman/5.7/en/select.html).  The MySQL documentation explicit states that queries without `FROM` are valid, so this seems like a bug in MySQL. You can try this to work around the MySQL bug:

```ruby
DB.extend_datasets do
  def empty_from_sql
    ' FROM DUAL'
  end
end
```

**Comment by will-gant** [comment]
Thanks for the rapid reply and helpful advice! And apologies for raising something that apparently belonged elsewhere.
