### ISSUE TITLE
add_#{table_name} method added when using many_to_many method skips validations

### ISSUE THREAD

**Issue by Benaaaaa** [jeremyevans/sequel#1986]
### Complete Description of Issue
When adding many_to_many to your Sequel::Model, you are given 3 new methods, one of them is `add_#{table_name}` e.g `add_comments`. It does not call validations on join table model when being used.
Premise:
Let's say we have `posts`, `comments` and `comments_posts` tables, alongside `Post`, `Comment` and `CommentsPosts` Sequel::Models.
Let's say we add `many_to_many :comments` to Post model, that gives us three new methods, `add_comments`, `remove_comment` and `remove_all_comments`.
When calling `post.add_comment(comment)` we will create an entry in the `comments_posts` table, but the validation on `CommentsPosts` sequel model won't be called. In a situation where we have added any constraints to the `comments_posts` table, if the constraint prerequisites are fulfilled the validation won't block it, rather we will get an error on the database, and then the table `comments_posts` gets locked

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
# create_posts migration
Sequel.migration do
  change do
    create_table(:posts) do
      primary_key :id

      String :name
    end
  end
end

# create_comments migration
Sequel.migration do
  change do
    create_table(:comments) do
      primary_key :id

      String :name
    end
  end
end

# create_comments_posts_migration
Sequel.migration do
  change do
    create_table(:groups) do
      primary_key :id
      foreign_key :post_id, :posts
      foreign_key :comment_id, :comments
      index [:post_id, :comment_id], unique: true
    end
  end
end

# models/post.rb
class Post < Sequel::Model
  many_to_many :comments
end

# models/comment.rb
class Comment < Sequel::Model
  many_to_many :posts
end

# models/comments_posts.rb
class CommentsPosts < Sequel::Model
  plugin :validation_helpers
  
  def validate
    super
    validates_unique [:post_id, :comment_id]
  end
end

```
```bash
# now open console or in spec and do these calls:

post = Post.create
=> #<Post @values={:id=>1}>

comment = Comment.create
=> #<Comment @values={:id=>1}>

post.add_comment(comment)
=> #<Comment @values={:id=>1}>

CommentsPosts.all
=> [#<CommentsPosts @values={:id=>1, :post_id=>1, :comment_id=>1}>]

CommentsPosts.create(post_id: 1, comment_id: 1)
Sequel::ValidationFailed: post_id and comment_id is already taken
from /Users/bena/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.62.0/lib/sequel/model/base.rb:1494:in `save`

post.add_comment(comment)
Sequel::UniqueConstraintViolation: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "comments_posts_post_id_comment_id_index"
DETAIL:  Key (post_id, comment_id)=(1, 1) already exists.

from /Users/bena/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.62.0/lib/sequel/adapters/postgres.rb:171:in `exec`
Caused by PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "comments_posts_post_id_comment_id_index"
DETAIL:  Key (post_id, comment_id)=(1, 1) already exists.

from /Users/bena/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.62.0/lib/sequel/adapters/postgres.rb:171:in `exec`

CommentsPosts.all
Sequel::DatabaseError: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

from /Users/bena/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.62.0/lib/sequel/adapters/postgres.rb:171:in `exec`
Caused by PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

from /Users/bena/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.62.0/lib/sequel/adapters/postgres.rb:171:in `exec`
```

From the error above, we can see that the validation was not called when trying to add a new post to comment.
Expected behavior of `add_comment` method is  that it will call `CommentsPosts.create(post_id: 1, comment_id: 1)` and then raise a validation error, rather than trying to immediately access the database.

Is this the intended way for this to work, because you usually don't need the model on the join table to use the `many_to_many` method.
Is it possible to add a clause where we check that the join table model exists, and if it does we call validate on it?

**Comment by jeremyevans** [comment]
The current behavior is expected, because `many_to_many` does not use a join model, it does a direct insert to the join table.  If you want validations using a join model, use a `one_to_many` association to the join model.  In your example, I'm guessing that would be:

```ruby
Post.one_to_many :comments_posts

# instead of post.add_comment(comment)
post.add_comments_post(comment: comment)
```

You could even keep your current API if you wanted:

```ruby
class Post
  def add_comment(comment)
    add_comments_post(comment: comment)
  end
end
```

**Comment by Benaaaaa** [comment]
Hey, thanks for such a fast answer and a clarification.
Does sequel by any chance provide some method with which I could access all of the comments that belong to a post? Sort of like `has_many :comments, through: comments_posts`? Or does that have to be implemented manually then?

**Comment by jeremyevans** [comment]
That is what `post.comments` gives you if you use `Post.many_to_many :comments`?  You can have both `Post.one_to_many :comments_posts` and `Post.many_to_many :comments`, they aren't mutually exclusive.

**Comment by Benaaaaa** [comment]
Thanks 😄 
I've got one last question, I promise 😅 
The only problem I am having with using `many_to_many` is that it then adds the `add_comments` method, which is potentially harmful, as I've described above. In case a new developer comes to the project and is not aware of the possible problems `add_comments` might introduce he might try to integrate it into the project. Is there any way to disable the inclusion of these helper methods when adding `many_to_many` ?

**Comment by jeremyevans** [comment]
> Thanks 😄 I've got one last question, I promise 😅 The only problem I am having with using `many_to_many` is that it then adds the `add_comments` method, which is potentially harmful, as I've described above. In case a new developer comes to the project and is not aware of the possible problems `add_comments` might introduce he might try to integrate it into the project. Is there any way to disable the inclusion of these helper methods when adding `many_to_many` ?

Yes, it's covered in the documentation: http://sequel.jeremyevans.net/rdoc/files/doc/association_basics_rdoc.html#label-3Aadder+-28_add_association+method-29

**Comment by Benaaaaa** [comment]
Awesome, this was exactly what I was looking for, but was overlooking it somehow. 
Thank you so much for the answers and the clarifications, especially for being so responsive! 😄 
It's pretty impressive to see 0 issues 🎉
