### ISSUE TITLE
#union use along #with queries without duplicating query

### ISSUE THREAD

**Issue by brauliobo** [jeremyevans/sequel#1987]
See the example below:
```ruby
> ds = DB.dataset.with(:a, DB.select('1'.as(:x))).with(:b, DB.select('2'.as(:x))); ds = ds.select_all(:a).from(:a).union(ds.select_all(:b).from(:b)); ds.all
D, [2023-01-31T16:51:34.814149 #571290] DEBUG -- : (0.000453s) SELECT * FROM (WITH "a" AS (SELECT '1' AS "x"), "b" AS (SELECT '2' AS "x") SELECT "a".* FROM "a" UNION (WITH "a" AS (SELECT '1' AS "x"), "b" AS (SELECT '2' AS "x") SELECT "b".* FROM "b")) AS "t1"
=> [{:x=>"1"}, {:x=>"2"}]
```
The #union duplicates the sources although they both use only #with queries.

This is similar to an application query with multiple `WITH` queries, but there that # with queries are being joined together resulting at the end in a big query.

By using UNION, this big query is then duplicated resulting in a final query of almost 100 lines.

Is it currently impossible to use #union using internal queries of #with and without duplicating the same dataset?

**Comment by jeremyevans** [comment]
I'm not sure what behavior you expect here.  Both datasets you are including in the UNION have WITH clauses, which Sequel rightly uses.  Do you expect Sequel to try to determine if the WITH clauses are the same, and hoist them above the UNION?  Sequel doesn't do that for multiple reasons (one would be the difficulty of doing so, two would be a deviation from what you are telling Sequel to do).

If you want a WITH above the UNION, add the WITH after the UNION:

```ruby
ds = DB[:a].select_all(:a).
  union(DB[:b].select_all(:b)).
  with(:a, DB.select('1'.as(:x))).
  with(:b, DB.select('2'.as(:x)))
# WITH "a" AS (SELECT '1' AS "x"), "b" AS (SELECT '2' AS "x")
# SELECT * FROM (
#   SELECT "a".* FROM "a"
#   UNION
#    (SELECT "b".* FROM "b")
# ) AS "t1"
```

In the future, per the contribution guidelines, please ask questions like this in GitHub Discussions.  Only file a GitHub Issue if you are sure what you are describing is a bug in Sequel.
