### ISSUE TITLE
MS SQL foreign key dumping does not work for schemas other than the default

### ISSUE THREAD

**Issue by betelgeuse** [jeremyevans/sequel#2006]
### Complete Description of Issue

Sequel does not dump foreign key definitions for SQL server foreign keys in schemas different from the default

### Simplest Possible Self-Contained Example Showing the Bug

```
irb(main):060:0> DW.create_table(:dw__first) do primary_key :id end
=> nil
irb(main):061:0> DW.create_table(:dw__second) do column :first_id, 'int'; foreign_key :first_id, Sequel::SQL::QualifiedIdentifier.new(:dw, :first), name: 'fk', key: :id end
=> nil
irb(main):064:0> puts DW.dump_foreign_key_migration(schema: :dw)
Sequel.migration do
  change do
    
  end
end
```

Commit used was a3e8a3f802c2f67225fdc0ccbf33f62e8419f917

**Comment by jeremyevans** [comment]
Thanks for the report.  I'll see if I can fix this before the next release.

**Comment by jeremyevans** [comment]
@betelgeuse Can you try the master branch and test that the fixes work in your environment?

**Comment by betelgeuse** [comment]
> @betelgeuse Can you try the master branch and test that the fixes work in your environment?

Looks like it 👍. The same dump I get looks good.
