### ISSUE TITLE
Model.create({ ... }) is slow due to creating a singleton class per call

### ISSUE THREAD

**Issue by eregon** [jeremyevans/sequel#2007]
See https://github.com/Shopify/yjit-bench/pull/207.

It would be great if `Model.create({ ... })` wouldn't create a singleton class, and perform more similarly to `DB[:posts].insert()`.
Creating many singleton classes has nasty side effects like making call sites going megamorphic and uncached, which makes the whole program slower + the cost of creating a singleton class is not trivial.

**Comment by eregon** [comment]
Regarding https://github.com/jeremyevans/sequel/commit/56e63e96914f6d66d55fac99c31300bec73557eb
> you cannot create a singleton class for a object that doesn't have a singleton class if the object is frozen.

Actually one can, yes it's surprising but I think the idea is the singleton class is conceptually always there and just created lazily and transparently when needed. OTOH one cannot add methods to such a singleton class once the object is frozen (even if the object is frozen after the singleton class is created).
```
$ irb
irb(main):001:0> obj=Object.new
=> #<Object:0x00007f37ce927310>
irb(main):002:0> obj.freeze
=> #<Object:0x00007f37ce927310>
irb(main):003:0> obj.singleton_class
=> #<Class:#<Object:0x00007f37ce927310>>
irb(main):004:0> def obj.foo; end
(irb):4:in `<main>': can't modify frozen object: #<Object:0x00007f37ce927310> (FrozenError)
        from /home/eregon/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /home/eregon/.rubies/ruby-3.1.3/bin/irb:25:in `load'
        from /home/eregon/.rubies/ruby-3.1.3/bin/irb:25:in `<main>'
$ ruby -ve 'obj=Object.new; obj.freeze; p obj.singleton_class'
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
#<Class:#<Object:0x00007fc7be5f7548>>
```

Is it really a problem if a user creates a singleton class though?

**Comment by jeremyevans** [comment]
It's not a problem if a user creates the singleton class if the singleton class cannot do anything useful.  However, if you can change the behavior (add singleton methods or include modules in the singleton class), then using `with_extend` would not work correctly because the subclass created would lose those methods/modules.

**Comment by eregon** [comment]
Right, then it should be fine, given a singleton class is frozen if the object is frozen (no matter which of the two happens first).
