### ISSUE TITLE
MS SQL dump_table_schema does not dump size parameter

### ISSUE THREAD

**Issue by betelgeuse** [jeremyevans/sequel#2013]
### Complete Description of Issue

Sequel does not dump the :size parameter on MS SQL. The default is 1 so the create_table rarely would create anything useful.

"When n isn't specified in a data definition or variable declaration statement, the default length is 1"

https://learn.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver16

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DW.create_table(:test_size_dump) do String :name, size: 10 end
DW.dump_table_schema(:test_size_dump, same_db: true)
```

output

```ruby
create_table(:test_size_dump) do
  column :name, "varchar"
end
```

### Sequel Version

b4e56aa8ce66aee2afd8c48106d53250ad0e34db

**Comment by jeremyevans** [comment]
Thanks for the report.  This is because the schema for the table returns:

```
[[:name, {:db_type=>"varchar", :max_chars=>10, :default=>nil, :allow_null=>true, :column_size=>nil, :scale=>nil, :primary_key=>false, :type=>:string, :max_length=>10, :ruby_default=>nil}]]
```

The `schema_dumper`  probably doesn't handle the separate `max_length`/`max_chars` currently.  I'll see if I can fix that.
