### ISSUE TITLE
connection_validator plugin: "undefined method `sync'" bug on single threaded connection

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/sequel#2042]
### Complete Description of Issue

When loading it on a database object marked as single threaded, a `NoMethodError` is raised.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB = Sequel.connect(ENV["DATABASE_URL"], single_threaded: true)
DB.extension(:connection_validator) #=> undefined method `sync' for #<Sequel::SingleConnectionPool:0x00007fedc6959d98 @db
# the second call works, possibly because the original object has been marked as disconnected?
DB.extension(:connection_validator) #=> #<Sequel::Postgres::Database: "...
```

### Full Backtrace of Exception (if any)

/usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/extensions/connection_validator.rb:65:in `block in extended': undefined method `sync' for #<Sequel::SingleConnectionPool:0x00007fedc6959d98 @db=#<Sequel::Postgres::Database: "postgresql://postgres:password@database/postgres" {:single_threaded=>true}>, @use_old_connect_api=false, @after_connect=nil, @connect_sqls=nil, @error_classes=[PG::Error], @conn=[#<Sequel::Postgres::Adapter:0x00007fedc6942f30 host=database port=5432 user=postgres type_map_for_queries=#<PG::TypeMapByClass:0x00007fedc6cd2a10>>]> (NoMethodError)

        sync do
        ^^^^
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/extensions/connection_validator.rb:64:in `instance_exec'
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/extensions/connection_validator.rb:64:in `extended'
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/extensions/connection_validator.rb:121:in `extend'
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/extensions/connection_validator.rb:121:in `block in <module:Sequel>'
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/database/misc.rb:236:in `block in extension'
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/database/misc.rb:233:in `each'
        from /usr/local/bundle/ruby/3.2.0/gems/sequel-5.68.0/lib/sequel/database/misc.rb:233:in `extension'
        from (irb):6:in `<main>'
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'
        from /usr/local/bin/irb:25:in `<top (required)>'
        from /usr/local/bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
        from /usr/local/bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

### Ruby Version

3.2

### Sequel Version

"5.68.0"

**Comment by jeremyevans** [comment]
It's expected and documented that connection_validator does not work with the single threaded pools: http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html .

If you want similar behavior, use the default threaded pool with `max_connections: 1`.

**Comment by HoneyryderChuck** [comment]
thx for the heads-up! I guess [this discussion's answer](https://github.com/jeremyevans/sequel/discussions/2041) will have to be updated to `dedicated = Sequel.connect(DB.opts.merge(max_connections: 1))`, right?

**Comment by jeremyevans** [comment]
> thx for the heads-up! I guess [this discussion's answer](https://github.com/jeremyevans/sequel/discussions/2041) will have to be updated to `dedicated = Sequel.connect(DB.opts.merge(max_connections: 1))`, right?

Nowhere in that discussion is connection_validator mentioned, so I don't think it should be updated.

**Comment by HoneyryderChuck** [comment]
I'll still add it there, in case someone using it stumbles into it.

**Comment by conn** [comment]
I'm sorry that I haven't been providing adequate validation. I promise I'll do better.
