### ISSUE TITLE
Ruby 3+ prevents passing parameters to `.clone()` 

### ISSUE THREAD

**Issue by gotoAndBliss** [jeremyevans/sequel#2056]
### Complete Description of Issue

In this [line](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/dataset.rb#L34) we are setting `TRUE_FREEZE` to true, if Ruby is `3.1.4`.

However, this will then cause us to pass an arg to Ruby's `clone` which no longer allows arguments [here](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/dataset/query.rb#L93)

My temporary work around is to explicitly override the gem to set this to `false`. 

### Simplest Possible Self-Contained Example Showing the Bug

Using Ruby 3.1.4 and Sequel..

Attempt to call the method `clone(freeze: false)` within query.rb

### Full Backtrace of Exception (if any)

The official ruby return would be 

```
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

### Ruby Version

3.1.4

### Sequel Version

4.48.0

**Comment by jeremyevans** [comment]
4.48.0 is almost 7 years old and predates Ruby 3.  Maybe that is the cause of this issue?  Try updating to 5.69.0.  If it is still a problem then, please post a minimal self-contained example showing the issue and I can review and reopen if appropriate.
