### ISSUE TITLE
`search_path` on PogstgreSQL 15 is empty when using raw statements

### ISSUE THREAD

**Issue by DrTom** [jeremyevans/sequel#2057]
### Complete Description of Issue

We are using sequel in the context of testing with RSpec and some other ruby libraries.

When accessing the data via a defined model we get for example the following query

```
User.where(id: @user.id)
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"users\" WHERE (\"id\" = '1f1ad4fe-6797-463a-a9fe-4b1fbae13980')">
``` 
which when evaluated returns the expected result (the dataset of the specified row). 

However, when using raw statements we will get the same query statement  but evaluation query itself fails: 
```
database[:users].where(id: @user.id)
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"users\" WHERE (\"id\" = '1f1ad4fe-6797-463a-a9fe-4b1fbae13980')">
...
Caused by PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 1: SELECT * FROM "users" WHERE ("id" = '1f1ad4fe-6797-463a-a9fe...
```

As far as I can see the reason seems to be that the raw statement have an empty `search_path` which can be validated e.g. with: 
```
database["SELECT setting, source, boot_val, reset_val, sourcefile, sourceline FROM pg_settings WHERE name = 'search_path'"].all
=> [{:setting=>"", :source=>"session", :boot_val=>"\"$user\", public", :reset_val=>"public", :sourcefile=>nil, :sourceline=>nil}]
```

Setting should be something like `"\"$user\", public"` but it is just the empty string `""`. Hence, the `users` table is not found because the query is not "fully qualified". For example 
```
database["SELECT * FROM public.users"].all
```
would work. 

We were using PostgreSQL 10 and this problem occurred after upgrading to PostgreSQL 15. However I am not sure if this is the root cause or if there is some side effect due to other upgrades. 

Gemfile.lock states the following possibly relevant versions: 
```
pg (1.5.3)
...
rspec (3.12.0)
sequel (5.69.0)
```

### Ruby Version
3.1.3

### Sequel Version
5.69.0

**Comment by jeremyevans** [comment]
Considering that the issue occurred after upgrading to PostgreSQL 15, this seems unlikely to be related to Sequel, and more likely to be issues in your local setup.

It could be that `User.db` and `database` in your examples are different Database objects.  However,  that's not an educated guess, since you didn't provide the self-contained example required by the issue report.  

I'm going to close this now.  If you think this is a bug in Sequel, please post a self contained example as requested in the bug report form and I can investigate and reopen if appropriate.

**Comment by DrTom** [comment]
> It could be that User.db and database in your examples are different Database objects.

Then `public.users` should not work either. Also there is the empty `search_path` path which is consistent with the result and not how it is configured. 

I can not exclude some other library being responsible, I will try to come up with an example.

**Comment by DrTom** [comment]
So the problem was not caused by sequel. The cause of the problem was an execution with `database.run` of some larger sql code which contained a reset of the `search_path`. After that one particular connection was tainted. It is mysterious to me why always the raw commands ended up using the tainted connection and never the ones using defined models. Anyways, it lead me to suspect that the raw connections are broken. Maybe this is of some use for similar problems. Thank you.
