### ISSUE TITLE
adapter/jdbc does not reconnect when DB2 "SqlNonTransientConnectionException" is raised

### ISSUE THREAD

**Issue by edmocosta** [jeremyevans/sequel#2083]
### Complete Description of Issue

Sequel is not reconnecting when a JDBC DB2`SqlNonTransientConnectionException` is raised. Instead, it maintains the stale connection in the pool, trying to reuse it indeterminately.

The problem seems to be on the [adapters/jdbc#disconnect_error?](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/jdbc.rb#L418) method. This specific exception is not being wrapped into another exception, letting the `:cause` nil. 

Changing it to the following solved the problem, as the actual disconnection error is thrown and is available on the `exception` variable. 

```diff
-cause = exception.respond_to?(:cause) ? exception.cause : exception
+cause = exception.respond_to?(:cause) && exception.cause ? exception.cause : exception
```

I didn't test it using other JDBC drivers, but I think it might be affecting others as well, depending on how those exceptions are being raised.

The `:connection_validator` extension can be used as a workaround, but I believe those disconnections should be handled by default.

Steps to reproduce
1 - Run the example code
2- While running, kill the DB connection

Thank you!

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'java'
require 'logger'
require 'sequel'
require 'sequel/adapters/jdbc'
require 'jcc-11.5.7.0.jar'

logger = Logger.new(STDOUT)
logger.level = 'DEBUG'

options_hash = {
  :user => '<user>',
  :password => '<password>',
  :pool_timeout => 10,
  :keep_reference => false,
  :driver => ::Sequel::JDBC.load_driver('com.ibm.db2.jcc.DB2Driver'),
  :logger => logger
}

db = ::Sequel.connect("jdbc:db2://localhost:50000/testdb", options_hash)

loop do
  begin
    db['SELECT id FROM TEST.MY_TABLE'].each { |row| puts row }
    sleep 1
  rescue => e
    logger.error e.message
  end
end
```

### Sequel Version

5.71.0

**Comment by jeremyevans** [comment]
Thanks for the report.  I'll look into this right away.

**Comment by edmocosta** [comment]
Hi @jeremyevans!

Thank you very much for your quick response and fix!
I've tested it locally using the master branch and the problem was solved. Sequel successfully detected the database disconnection and discarded the stale connection from the pool :)
