### ISSUE TITLE
Model.update_or_create raises Sequel::UniqueConstraintViolation

### ISSUE THREAD

**Issue by MatzFan** [jeremyevans/sequel#2086]
### Complete Description of Issue

A call to `update_or_create` on my model raises a primary key duplicate violation error. The following backtrace resulted from this call:
```ruby
Appeal.update_or_create({ appeal_ref: 'MD-ENV-2023-651' }) # rest of hash omitted as N/R
```

This unexpected behavior is caused my model modifying the unrestricted pk in a `before_validation` hook to pad the last part of the pk string (`:appeal_ref`), if necessary, to 4 digits. My model looks like this:

```ruby
class Appeal < Sequel::Model
  unrestrict_primary_key
  many_to_one :appeal_kind, key: :appeal_type
  many_to_many :applications, left_key: :appealref, right_key: :appref

  def before_validation
    self.appeal_ref = fix_short_appeal_refs
  end

  def before_save
    AppealKind.find_or_create(type: appeal_type) if appeal_type
    super
  end

  def after_save
    add_applications
  end

  def add_applications
    applications_list.each do |app_ref|
      attributes = { appealref: appeal_ref, appref: app_ref }
      num_records = DB[:appeals_applications].where(attributes).count
      DB[:appeals_applications].insert(attributes) if num_records.zero?
    end
  end

  def fix_short_appeal_refs
    arr = appeal_ref.split('-') # 4 elements
    arr[0..-2].push(pad_zeros(arr.last)).join('-')
  end

  def pad_zeros(str)
    str.length > 3 ? str : pad_zeros("0#{str}") # recurse
  end

  def applications_list
    appeal_apps ? appeal_apps.split(', ').sort : []
  end
end
```

The error occurs because my DB already has an `Appeal` record with `:appeal_ref` 'MD-ENV-2023-0651'.

The behavior is unexpected as the [docs](https://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/UpdateOrCreate.html) say "The first method is update_or_create, which updates an object if it exists in the database, or creates the object if it does not". The unexpected part is that the method checks the DB for an *unvalidated* object. In fact, the check has nothing to do with an object as it simply checks for a record with the provided hash keys - as the module [docs](https://github.com/jeremyevans/sequel/blob/01613aa94bb610bf7e9282794f4f0e78d72276f9/lib/sequel/plugins/update_or_create.rb#L40) correctly say.

The behavior I expected was the `before_validation` hook to be called before the check for existing records.

If this is in fact the expected behavior I'd suggest the docs make it clear that no object validation is done before the DB check.

I'll also suggest to the folks over at Rubocop that modifying an unrestricted pk in a `before_validation` hook is picked up as an offense.

My workaround is to pad the pk string before the call to `update_or_create`

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
create_table :foos do
  String :bar, primary_key: true
end

class Foo < Sequel::Model
  unrestrict_primary_key

  def before_validation
    self.bar = "#{bar}0"
  end
end

Foo.create(bar: 'bar')
Foo.update_or_create(bar: 'bar') # does not check DB for 'bar0' so tries to create new record
```

### Full Backtrace of Exception (if any)

```
Sequel::UniqueConstraintViolation: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "appeals_pkey"
DETAIL:  Key (appeal_ref)=(MD-ENV-2023-0651) already exists.
/home/me/gitlab/jps/tasks/appeals/update.rake:21:in `block (5 levels) in <top (required)>'
/home/me/gitlab/jps/tasks/appeals/update.rake:20:in `each'
/home/me/gitlab/jps/tasks/appeals/update.rake:20:in `block (4 levels) in <top (required)>'
/home/me/gitlab/jps/tasks/appeals/update.rake:19:in `block (3 levels) in <top (required)>'
/home/me/gitlab/jps/tasks/appeals/update.rake:14:in `each'
/home/me/gitlab/jps/tasks/appeals/update.rake:14:in `block (2 levels) in <top (required)>'
/home/me/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/home/me/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "appeals_pkey"
DETAIL:  Key (appeal_ref)=(MD-ENV-2023-0651) already exists.
/home/me/gitlab/jps/tasks/appeals/update.rake:21:in `block (5 levels) in <top (required)>'
/home/me/gitlab/jps/tasks/appeals/update.rake:20:in `each'
/home/me/gitlab/jps/tasks/appeals/update.rake:20:in `block (4 levels) in <top (required)>'
/home/me/gitlab/jps/tasks/appeals/update.rake:19:in `block (3 levels) in <top (required)>'
/home/me/gitlab/jps/tasks/appeals/update.rake:14:in `each'
/home/me/gitlab/jps/tasks/appeals/update.rake:14:in `block (2 levels) in <top (required)>'
/home/me/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/home/me/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
Tasks: TOP => appeals:update
(See full trace by running task with --trace)
```

### Ruby Version

3.2.2

### Sequel Version

5.73.0

**Comment by jeremyevans** [comment]
This doesn't work correctly because the first argument to `update_or_create` must work both as a filter condition and as values to set.  In your case, the `bar: 'bar'` is invalid as a filter condition.  The filter condition must be `bar: 'bar0'`. `update_or_create` takes a second argument that is only used to set the values.  It also can yields the object to the block if the block is given.

Here's a fixed example that shows correct usage:

```ruby
DB.create_table :foos do
  String :bar, primary_key: true
end

class Foo < Sequel::Model
  unrestrict_primary_key
  plugin :update_or_create

  def before_validation
    self.bar = "#{bar}0"
  end
end

Foo.create(bar: 'bar')

# This is invalid:
# Foo.update_or_create(bar: 'bar')

# Fixed:
Foo.update_or_create({bar: 'bar0'}, bar: 'bar')
```

The `update_or_create` plugin documentation does not explicitly address your issue with modifying values in `before_validation`, but I don't think such a niche case is worth explaining.  While the `update_or_create` method technically supports calling calls with a single hash and no block, such usage doesn't make much sense.  It's allowed only because there is no defensive argument checking, and it's not worth breaking backwards compatibility to add such checks.  The plugin documentation examples do not show such a call.

**Comment by MatzFan** [comment]
Understood Jeremy and I admit it is a niche case, it was just surprising to me that a method called `update_or_create` which purports to check the DB for a existing model does not in fact do a dummy run 'create' complete with validation checks first. It is probably an anti-pattern to modify a pk inside a model anyhow, so happy you close this. Thanks for your time - and for `Sequel`!
