### ISSUE TITLE
Mysql2::Error: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/x86_64-linux-gnu/mariadb18/plugin/caching_sha2_password.so

### ISSUE THREAD

**Issue by vardaanmittal09** [jeremyevans/sequel#2101]
### Complete Description of Issue

Not able to connect to Mysql 8.0.

### Simplest Possible Self-Contained Example Showing the Bug

Trying to connect like this, ther same used to work with mysql: 5.7 but not with mysql: 8.0.
Gem versions: sequel-5.74.0
Mysql2 :  mysql2-0.5.5
Payments.db = Sequel.mysql2({
  encoding: 'utf8',
  host: mysql.host,
  port: mysql.port,
  database: mysql.db,
  username: mysql.user,
  password: mysql.password
})

/usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:97:in `connect': Mysql2::Error: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/x86_64-linux-gnu/mariadb18/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory (Sequel::DatabaseConnectionError)
	from /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:97:in `initialize'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/adapters/mysql2.rb:43:in `new'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/adapters/mysql2.rb:43:in `connect'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/database/connecting.rb:248:in `new_connection'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/connection_pool.rb:161:in `make_new'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/database/connecting.rb:276:in `synchronize'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/database/connecting.rb:302:in `test_connection'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/database/misc.rb:188:in `initialize'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/database/connecting.rb:57:in `new'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/database/connecting.rb:57:in `connect'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/core.rb:124:in `connect'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/core.rb:412:in `adapter_method'
	from /usr/local/bundle/gems/sequel-5.74.0/lib/sequel/core.rb:419:in `block (2 levels) in def_adapter_method'
	from /usr/src/app/config/development.rb:16:in `<top (required)>'
	from /usr/local/bundle/gems/elastic-apm-3.5.0/lib/elastic_apm/spies.rb:73:in `require'
	from /usr/local/bundle/gems/elastic-apm-3.5.0/lib/elastic_apm/spies.rb:73:in `require'
	from /usr/src/app/app.rb:204:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/src/app/bin/util:7:in `<main>'

### Ruby Version

2.3

### Sequel Version

sequel-5.74.0

**Comment by jeremyevans** [comment]
This is an issue in mysql2, not in Sequel, please try asking the mysql2 developers: https://github.com/brianmario/mysql2/issues

Please realize that Ruby 2.3 is very old at this point, so I'm not sure how supported it is by mysql2.
