### ISSUE TITLE
Error during evaluation of Ruby in uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/sequel-5.74.0/lib/sequel/database/misc.rb at line 462: (DatabaseError) Java::JavaSql::SQLException: A string constant starting with ''' is too long.

### ISSUE THREAD

**Issue by jackshang** [jeremyevans/sequel#2110]
### Complete Description of Issue

I want to copy data from postgres to derby database, but throw a error between postgres "text" field and derby "clob" field. How to solve this issue? Thx.

JRuby snippet:
pdb = Sequel.connect("jdbc:postgresql://...." ) 
ddb = Sequel.connect("jdbc:derby:...." ) 
map = pdb[:config].where(:id=>1).first
ddb[:config].insert(map)

Error log:
Error during evaluation of Ruby in uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/sequel-5.74.0/lib/sequel/database/misc.rb at line 462: (DatabaseError) Java::JavaSql::SQLException: A string constant starting with ''' is too long.
----------------
Postgres table:
CREATE TABLE config
(
    id bigint NOT NULL,
    name character varying(64)  NOT NULL,
    doc text  NOT NULL,
    CONSTRAINT config_pkey PRIMARY KEY (id),
);

Derby table:
CREATE TABLE config
(
    id bigint NOT NULL,
    name varchar(64)  NOT NULL,
    doc clob(1M) NOT NULL,
    CONSTRAINT config_pkey PRIMARY KEY (id),
);

### Simplest Possible Self-Contained Example Showing the Bug

Error during evaluation of Ruby in uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/gems/sequel-5.74.0/lib/sequel/database/misc.rb at line 462: (DatabaseError) Java::JavaSql::SQLException: A string constant starting with ''class AutoCodeUtil #(param, clazz, object&' is too long.

### Sequel Version

sequel-5.74.0

**Comment by jeremyevans** [comment]
This error is raised by the database, not by Sequel itself.  This appears to be a Derby limitation on string constants: https://db.apache.org/derby/docs/10.8/ref/rrefstringlimits.html

You could probably work around this using a prepared statement or bound variable: https://sequel.jeremyevans.net/rdoc/files/doc/prepared_statements_rdoc.html
