### ISSUE TITLE
adapter/jdbc does not reconnect when Sybase raises "connection is already closed"

### ISSUE THREAD

**Issue by kaisecheng** [jeremyevans/sequel#2159]
### Complete Description of Issue

Similar issue to https://github.com/jeremyevans/sequel/issues/2083 but this time happens in Sybase.

Sequel is not reconnecting when Sybase disconnect the connection. Instead, it maintains the stale connection in the pool, trying to reuse it indeterminately.

The problem is on [adapters/jdbc#disconnect_error?](https://github.com/jeremyevans/sequel/blob/5.80.0/lib/sequel/adapters/jdbc.rb#L423), where [_database_exception_sqlstate](https://github.com/jeremyevans/sequel/blob/5.80.0/lib/sequel/adapters/jdbc.rb#L405) returns "JZ0C0" instead of "08XXX" in `exception.getSQLState`

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
# (1) run sybase docker
# docker run --platform linux/amd64 -p 2638:2638 jaschweder/sybase dbsrv16 -ti 1 -tl 30 "/opt/sqlanywhere16/demo.db"
#	-ti <minutes>  client idle time before disconnect (default is 240 minutes)
#	-tl <seconds>  client liveness timeout in seconds (default is 120 seconds)

# (2) run the following script
# after one minute, error log shows "Java::JavaSql::SQLException: JZ0C0: Connection is already closed."
require 'java'
require 'logger'
require 'sequel'
require 'sequel/adapters/jdbc'
require './jconn4.jar'

logger = Logger.new(STDOUT)
logger.level = 'DEBUG'

options_hash = {
  :user => 'DBA',
  :password => 'sql',
  :pool_timeout => 10,
  :keep_reference => false,
  :driver => ::Sequel::JDBC.load_driver('Java::com.sybase.jdbc4.jdbc.SybDriver'),
  :logger => logger
}

db = ::Sequel.connect("jdbc:sybase:Tds:localhost:2638", options_hash)

loop do
  begin
    db["SELECT TABLE_NAME FROM SYS.SYSTABLE WHERE TABLE_TYPE = 'BASE'"].each { |row| print "." }
    sleep 61
    puts ""
  rescue => e
    logger.error e.message
  end
end
```

[reproducer.tar.gz](https://github.com/jeremyevans/sequel/files/15201858/reproducer.tar.gz)

### Sequel Version

5.80

**Comment by jeremyevans** [comment]
Can you try this diff and let me know if it fixes it?:

```diff
diff --git a/lib/sequel/adapters/jdbc/sqlanywhere.rb b/lib/sequel/adapters/jdbc/sqlanywhere.rb
index fb20d9c2a..0ca520128 100644
--- a/lib/sequel/adapters/jdbc/sqlanywhere.rb
+++ b/lib/sequel/adapters/jdbc/sqlanywhere.rb
@@ -36,6 +36,10 @@ module Sequel

         private

+        def disconnect_error?(exception, opts)
+          super || exception.message =~ /\AConnection is already closed\.\z/
+        end
+
         def database_exception_use_sqlstates?
           false
         end
```

**Comment by kaisecheng** [comment]
Thanks for the prompt reply.

I tried but sqlanywhere.rb is not loaded for Sybase, hence adding disconnect_error? doesn't help

**Comment by jeremyevans** [comment]
Ah, understood.  Sequel doesn't have a Sybase adapter (it doesn't advertise or ship support for Sybase), only an SQLAnywhere adapter.  You would want to write your own jdbc/sybase adapter and use that (the `disconnect_error?` method definition above may work to fix your issue).  If you don't want to do that, just update the `DB` object directly:

```ruby
def DB.disconnect_error?(exception, opts)
  super || exception.message =~ /\AConnection is already closed\.\z/
end
```
