### ISSUE TITLE
Cannot recover from error: PG::ConnectionBad: PQsocket() can't get socket descriptor

### ISSUE THREAD

**Issue by musaffa** [jeremyevans/sequel#2228]
### Complete Description of Issue

We encounter this error sometimes. After a db query fails with this error, the failed connection is released to the connection pool. Then another query takes up this connection and fails again. This goes on and on.

Examples of repeated failures in Sentry:
![Screenshot from 2024-10-03 22-40-27](https://github.com/user-attachments/assets/d01d32cf-5953-4f34-b50a-10cc9b38d34b)

This issue happens a few times in week or even in a day (of course it depends on the database service we are using). We have a connection validator extension set up which validates connections in every 12 minutes (instead of the default 1 hour). But this is not ideal because whenever this happens the website will be down for 12 minutes.

When this kind of error occurs in a connection, the connection should be disconnected instead of being released to the connection pool where another query will take it up and raise the same error. Or there can be a public API so that we can catch this connection after this kind of error and disconnect it ourselves.

### Full Backtrace of Exception (if any)
```
PG::ConnectionBad: PQsocket() can't get socket descriptor
  from sequel/adapters/postgres.rb:171:in `exec'
  from sequel/adapters/postgres.rb:171:in `block in execute_query'
  from sequel/extensions/error_sql.rb:63:in `log_connection_yield'
  from rom/plugins/relation/sql/instrumentation.rb:73:in `block (2 levels) in define_log_connection_yield'
  from dry/monitor/notifications.rb:11:in `measure'
  from dry/monitor/notifications.rb:41:in `instrument'
  from rom/plugins/relation/sql/instrumentation.rb:72:in `block in define_log_connection_yield'
  from sequel/adapters/postgres.rb:171:in `execute_query'
  from sequel/adapters/postgres.rb:159:in `block in execute'
  from sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
  from sequel/adapters/postgres.rb:159:in `execute'
  from sequel/adapters/postgres.rb:532:in `_execute'
  from sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
  from sequel/adapters/postgres.rb:555:in `check_database_errors'
  from sequel/adapters/postgres.rb:348:in `block in execute'
  from sequel/connection_pool/threaded.rb:88:in `hold'
  from sequel/database/connecting.rb:293:in `synchronize'
  from sequel/adapters/postgres.rb:348:in `execute'
  from sequel/dataset/actions.rb:1189:in `execute'
  from sequel/adapters/postgres.rb:651:in `fetch_rows'
  from sequel/dataset/actions.rb:164:in `each'
  from sequel_pg/sequel_pg.rb:83:in `each'
  from rom/relation.rb:225:in `each'
  from rom/relation.rb:363:in `each'
  from rom/relation.rb:363:in `to_a'
  from rom/relation.rb:363:in `to_a'
  from rom/relation/loaded.rb:38:in `initialize'
  from rom/relation.rb:354:in `new'
  from rom/relation.rb:354:in `call'
  from rom/relation/combined.rb:66:in `call'
  from rom/relation/materializable.rb:15:in `to_a'
  from lib/api/repositories/event.rb:35:in `limit'
  from slices/main/lib/queries/index.rb:43:in `limited_resource'
  from slices/main/lib/queries/index.rb:11:in `call'
  from slices/main/lib/operations/events/index.rb:14:in `call'
  from dry/matcher.rb:42:in `block (3 levels) in for'
  from dry/transaction/callable.rb:35:in `call'
  from dry/transaction/callable.rb:35:in `call'
  from dry/transaction/step_adapters/around.rb:14:in `call'
  from dry/transaction/step_adapters/raw.rb:13:in `call'
  from dry/transaction/step_adapter.rb:43:in `call'
  from dry/transaction/step_adapter.rb:43:in `call'
  from dry/transaction/step.rb:56:in `block in call'
  from dry/transaction/step.rb:63:in `with_broadcast'
  from dry/transaction/step.rb:56:in `call'
  from dry/transaction/stack.rb:21:in `block (3 levels) in compile'
  from dry/monads/right_biased.rb:57:in `bind'
  from dry/transaction/stack.rb:21:in `block (2 levels) in compile'
  from dry/transaction/step.rb:56:in `call'
  from dry/transaction/stack.rb:21:in `block (3 levels) in compile'
  from dry/monads/right_biased.rb:57:in `bind'
  from dry/transaction/stack.rb:21:in `block (2 levels) in compile'
  from dry/transaction/stack.rb:14:in `call'
  from dry/transaction/instance_methods.rb:30:in `call'
  from slices/main/web/controllers/events/index.rb:17:in `call'
  from system/base/application.rb:13:in `controller'
  from slices/main/web/routes/events.rb:7:in `block (3 levels) in <class:Web>'
  from roda/request.rb:531:in `always'
  from roda/plugins/_optimized_matching.rb:124:in `_verb'
  from roda/request.rb:106:in `get'
  from slices/main/web/routes/events.rb:7:in `block (2 levels) in <class:Web>'
  from roda/request.rb:531:in `always'
  from roda/plugins/_optimized_matching.rb:27:in `is'
  from slices/main/web/routes/events.rb:6:in `block in <class:Web>'
  from roda/plugins/named_routes.rb:160:in `route'
  from roda/plugins/multi_route.rb:143:in `block in multi_route'
  from roda/plugins/_optimized_matching.rb:79:in `block in on'
  from roda/request.rb:531:in `always'
  from roda/plugins/_optimized_matching.rb:79:in `on'
  from roda/plugins/multi_route.rb:142:in `multi_route'
  from roda.rb:496:in `block in _roda_handle_main_route'
  from roda.rb:494:in `catch'
  from roda.rb:494:in `_roda_handle_main_route'
  from roda/plugins/direct_call.rb:18:in `call'
  from roda/request.rb:397:in `run'
  from system/api/web.rb:15:in `block (2 levels) in <class:Web>'
  from roda/plugins/_optimized_matching.rb:41:in `block in on'
  from roda/request.rb:531:in `always'
  from roda/plugins/_optimized_matching.rb:41:in `on'
  from system/api/web.rb:14:in `block in <class:Web>'
  from roda.rb:496:in `block in _roda_handle_main_route'
  from roda.rb:494:in `catch'
  from roda.rb:494:in `_roda_handle_main_route'
  from roda/plugins/error_handler.rb:88:in `_roda_handle_main_route'
  from roda.rb:380:in `block in base_rack_app_callable'
  from dry/monitor/rack/middleware.rb:37:in `block in call'
  from dry/monitor/notifications.rb:11:in `measure'
  from dry/monitor/rack/middleware.rb:37:in `call'
  from rack/timeout/core.rb:148:in `block in call'
  from rack/timeout/support/timeout.rb:19:in `timeout'
  from rack/timeout/core.rb:147:in `call'
  from puma/commonlogger.rb:40:in `call'
  from puma/configuration.rb:268:in `call'
  from puma/request.rb:89:in `block in handle_request'
  from puma/thread_pool.rb:343:in `with_force_shutdown'
  from puma/request.rb:88:in `handle_request'
  from puma/server.rb:430:in `process_client'
  from puma/server.rb:233:in `block in run'
  from puma/thread_pool.rb:150:in `block in spawn_thread'
```

### Ruby Version

3.1.2

### Sequel Version

5.74.0

**Comment by jeremyevans** [comment]
Actually, from your updated description, the errors are already recognized as DatabaseDisconnectErrors, so the related connections are already removed from the pool.  If you have a problem with your database that affects all connections in the pool, then you should get 1 DatabaseDisconnectError for each connection, but then new connections should be established automatically.

**Comment by musaffa** [comment]
Thanks for the clarification. Is there any way to know the status of the connections in the connection pool?

**Comment by jeremyevans** [comment]
It's impossible to know the status without actually attempting to use the connections.  Sequel assumes all connections are good by default, and removes connections when it sees they are bad (raising a DatabaseDisconnectError if so).  With the connection_validator extension, you can check that connections are valid before use, and automatically avoid using bad connections.

The best way to avoid the issues you are having is ensuring the application's connection to the database is not subject to disconnects by firewalls or other network devices between the application and the database.

**Comment by musaffa** [comment]
We are hosting our application in fly.io and the database is hosted in AWS. fly.io uses HA proxy for external connections. These external connections are terminated by HA proxy's default limit of 30 minutes. We are not sure whether this is the root of the issue because connection_validator extension checks connections in every 12 minutes in our setup.

**Comment by jeremyevans** [comment]
If your issue is that all connections are terminated after 30 minutes, regardless of whether they are in use, then you probably want to use the connection_expiration extension instead of or in addition to the connection_validator extension.

**Comment by musaffa** [comment]
If a connection is expired, can it still be a valid connection?

**Comment by jeremyevans** [comment]
From the connection_validation extension standpoint, yes.  connection_validation is mostly useful to deal with cases where idle connections are disconnected.  If there is a deadline for all connections, regardless of use, you are better off using connection_expiration (no problem using both).

In your case, let's say a connection is used 25 minutes after created, and again 7 minutes later.  connection_validation will not check for validity, because you are only checking after 12 minutes, and it has been only 7 minutes since it was checked in.  However, because it has been 32 minutes after connection, HA proxy dropped the connection.  With connection_expiration, you could drop all connections after 12 minutes of use, so they never hit the 30 minute mark.

**Comment by musaffa** [comment]
Thank you so much for your valuable insight. I've learned a lot about Sequel's db connections from this conversation.

I'm closing this issue.
