### ISSUE TITLE
sqlite "database is locked" error

### ISSUE THREAD

**Issue by jeremyevans** [jeremyevans/sequel#243]
<b>What steps will reproduce the problem?</b>
1. Access same sqlite file with two different sqlite processes.
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

Exception type: Sequel::Error::InvalidStatement
Exception message: INSERT INTO table1 (xxx) VALUES ('yyy')
database is locked
Exception backtrace:
/usr/local/lib/ruby/gems/1.8/gems/sequel_core-1.4.0/lib/sequel_core/adapters/sqlite.rb:50:in
`execute_insert'
/usr/local/lib/ruby/gems/1.8/gems/sequel_core-1.4.0/lib/sequel_core/adapters/sqlite.rb:171:in
`insert'
/usr/local/lib/ruby/gems/1.8/gems/sequel_core-1.4.0/lib/sequel_core/dataset.rb:172:in
`<<'

<b>What version of the product are you using? On what operating system?</b>
Linux Sequel 1.4.0

<b>Please provide any additional information below.</b>

Everything works fine as long as you have one ruby process. Different
threads are protected with mutexes. But, when you have two ruby programs
accessing same db, you get error.

So, you should put some sensible default for busy timeout when you open db.

I have dirty solution, after I open db, I use:

 DB.pool.hold do |conn|
   conn.busy_timeout(20000)
 end

That solves it.

ActiveRecord has solution to specify timeout for quite a while.

Google Code Info:
Issue #: 218
Author: hrvoje.m...@gmail.com
Created On: 2008-04-23T19:44:56.000Z
Closed On: 2008-04-28T16:07:52.000Z

**Comment by greneholt** [comment]
FYI: The sqlite busy_timeout method shouldn't be used on MRI, as the GIL will not be unlocked while waiting for the database to be unlocked.

See this issue: https://github.com/sparklemotion/sqlite3-ruby/issues/261
