### ISSUE TITLE
SQL Server inserts fail if table has a trigger

### ISSUE THREAD

**Issue by jeremyevans** [jeremyevans/sequel#335]
When inserting records into SQL Server, Sequel uses an OUTPUT clause which results in the following error:

NativeException: com.microsoft.sqlserver.jdbc.SQLServerException: The target table 'SENTINEL_ARRIVE' of the DML statement cannot have
any enabled triggers if the statement contains an OUTPUT clause without INTO clause.:
INSERT INTO [SENTINEL_ARRIVE]([CALL_DATETIME], [CALL_CLI], [CALL_PIN], [CALL_PRODUCT], [CLI_METH
OD], [ENTITY_TYPE], [DT_STAMP], [STATUS], [CLIENT_ID]) OUTPUT [INSERTED].\* VALUES ('2010-09-23 16:03:00.000', N'07877523970', N'1234', N'', N'A', 3, '2010-10-29 10:17:44.777', 0, 1)

Most of our tables have triggers for auditing etc. which makes this construct unusable. Looking at the documentation it seems that the OUTPUT clause of the INSERT statement has so many restrictions that it shouldn't be used in general purpose code.

Regards,
Gary Doades

Google Code Info:
Issue #: 311
Author: g...@gpdnet.co.uk
Created On: 2010-10-29T09:45:18.000Z
Closed On: 2010-10-29T12:46:39.000Z

**Comment by jrgns** [comment]
@jeremyevans I realise this is ages old, but we've run across this issue as well. In general it's not an issue, but it does break if / when triggers are added to tables.

For completeness, here's a [Microsoft blog post](https://blogs.msdn.microsoft.com/sqlprogrammability/2008/07/11/update-with-output-clause-triggers-and-sqlmoreresults/) discussing the issue, and a [StackOverflow question](https://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table) regarding it too.

**Comment by jeremyevans** [comment]
@jrgns Thanks for responding.  I'm aware this is still an issue with SQL Server.  After reviewing the issue, I don't think it makes sense to disable the optimization by default on SQL Server, but I'm certainly willing to accept feedback from other SQL Server users.  It would probably be better to post on the Google Group instead of updating this issue, though.

**Comment by jrgns** [comment]
Posted, thanx @jeremyevans - https://groups.google.com/forum/#!topic/sequel-talk/j-Pnxrycl-U
