### ISSUE TITLE
Sequel doesn't seem to reconnect on "Mysql2::Error: MySQL server has gone away: BEGIN" error

### ISSUE THREAD

**Issue by PatrickLef** [jeremyevans/sequel#368]
I might have missed some settings but it seems like Sequel should reconnect on these errors 

MYSQL_DATABASE_DISCONNECT_ERRORS.match(e.message)
MYSQL_DATABASE_DISCONNECT_ERRORS = /\A(Commands out of sync; you can't run this command now|Can't connect to local MySQL server through socket|MySQL server has gone away)/

Haven't been able to reproduce this in dev environment though. So I will try to upgrade the gems, but since a database restart don't happen so often it might take a while before it happens again.

gem 'sequel', "3.22.0"
gem 'mysql2', "0.2.7"

And full error trace:

 FATAL - [03/Jul/2011 13:23:55] "Mysql2::Error: MySQL server has gone away: BEGIN"
 ERROR - [03/Jul/2011 13:23:55] "Sequel::DatabaseError - Mysql2::Error: MySQL server has gone away:
sequel-3.22.0/lib/sequel/database/logging.rb:53:in `query'
sequel-3.22.0/lib/sequel/database/logging.rb:53:in`send'
sequel-3.22.0/lib/sequel/database/logging.rb:53:in `log_connection_execute'
sequel-3.22.0/lib/sequel/database/logging.rb:32:in`log_yield'
sequel-3.22.0/lib/sequel/database/logging.rb:53:in `log_connection_execute'
sequel-3.22.0/lib/sequel/adapters/shared/mysql.rb:158:in`begin_new_transaction'
sequel-3.22.0/lib/sequel/database/query.rb:274:in `begin_transaction'
sequel-3.22.0/lib/sequel/adapters/shared/mysql.rb:168:in`begin_transaction'
sequel-3.22.0/lib/sequel/database/query.rb:222:in `_transaction'
sequel-3.22.0/lib/sequel/database/query.rb:209:in`transaction'
sequel-3.22.0/lib/sequel/connection_pool/threaded.rb:84:in `hold'
sequel-3.22.0/lib/sequel/database/connecting.rb:226:in`synchronize'
sequel-3.22.0/lib/sequel/database/query.rb:207:in `transaction'

**Comment by iamhabbeboy** [comment]
This is great, you are so wonderful. You solve my biggest problem

**Comment by bougyman** [comment]
Sorry, I know this has been closed a while, but it's happening to me right now. Was there a regression, perhaps?

**Comment by bougyman** [comment]
sequel-4.34.0 here.

**Comment by bougyman** [comment]
Relevant backtrace
```
ruby2.1.x/lib/ruby/gems/2.1.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/adapters/mysql2.rb:80:in `block in _execute'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/database/logging.rb:35:in `log_yield'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/adapters/mysql2.rb:80:in `_execute'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in `block in execute'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:251:in `synchronize'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:36:in `execute'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:965:in `execute'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/adapters/mysql2.rb:197:in `execute'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/adapters/mysql2.rb:156:in `fetch_rows'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:846:in `with_sql_each'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:856:in `with_sql_first'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:664:in `single_record!'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:652:in `single_record'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:194:in `first'
ruby2.1.x/lib/ruby/gems/2.1.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:486:in `first'
```

**Comment by jeremyevans** [comment]
Sequel 4.34.0 is over a year old, please try with the current version, and also try using mysql2 directly to make sure the error is in Sequel and not in the driver.  If you think there is a bug in Sequel, please create a new issue with a minimal, self-contained, reproducible example.

**Comment by Krule** [comment]
Again, is there a possibility of regression for this?

Sequel: 4.48.0
mysql2: 0.4.8

**Backtrace**:

```
Mysql2::Error: MySQL server has gone away
/var/bundle/ruby/2.4.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:120:in `_query'"
/var/bundle/ruby/2.4.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:120:in `block in query'"
/var/bundle/ruby/2.4.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:119:in `handle_interrupt'"
/var/bundle/ruby/2.4.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:119:in `query'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/mysql2.rb:141:in `block in _execute'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/database/logging.rb:45:in `log_connection_yield'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/mysql2.rb:136:in `_execute'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `block in execute'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/database/connecting.rb:301:in `synchronize'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `execute'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:1081:in `execute'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/mysql2.rb:291:in `execute'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/mysql2.rb:254:in `fetch_rows'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:942:in `with_sql_each'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:950:in `with_sql_first'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:748:in `single_record!'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:736:in `single_record'"
/var/bundle/ruby/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:212:in `first'"
```

**Comment by jeremyevans** [comment]
I don't think so.  If I do:

```ruby
DB.synchronize{|c| def c.query(*) raise ::Mysql2::Error, "MySQL server has gone away" end}
DB.get(1)
```

I get: `Sequel::DatabaseDisconnectError: Mysql2::Error: MySQL server has gone away`, so it looks like the disconnection is recognized.  As I stated previously, if you think there is a bug here, please create a new issue with a minimal, self-contained, reproducible example.

**Comment by jeremyevans** [comment]
@Krule looks like you edited your comment after posting it.  Just FYI, Sequel's behavior is to raise the error as a disconnect error, which removes the connection from the pool.  It does not automatically retry the query, as it may not be safe to do so.  You should probably use the connection_validator extension if you want to check connection validity before use, or something like a cron job to make sure connections are not left idle.

**Comment by Krule** [comment]
@jeremyevans Yes, I have added more details as I have investigated the problem and applied the fix which happened to be increasing connection pool and utilising `connection_validator` to check it periodically.

Thank you for your time and sorry for bogus "bug" report. I am really glad it's not a bug.

**Comment by blaskovicz** [comment]
For anyone that gets down this far in the thread, see the [connection_invalidator docs](http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html).

**Comment by tadman** [comment]
You can test that this is working correctly on MySQL by tuning the `wait_timeout` to a very low value, like:

```sql
SET GLOBAL wait_timeout=5;
```

Where idle connections will be closed after 5 seconds. This will surface any connection issues very quickly. The normal default (MariaDB) is 28800s, or 8 hours, meaning you'll hit this with any long-running process.
