### ISSUE TITLE
creation of a PGArray column in a migration not documented

### ISSUE THREAD

**Issue by pvh** [jeremyevans/sequel#476]
I'd like to create an array of text in a column via a migration. I know how to do this via direct SQL, but I can't intuit how to do it with the migration dsl.

``` ruby
Sequel.migration do
  change do
    create_table :once do
      column 'signature', :bytea
      column 'arguments', :array_text # this part is where i am confused :)
    end
  end
end
```

**Comment by agirorn** [comment]
Sorry this just dose not clear things up at all.
Shouldn't there just be a code block in the docs with a concrete example?

**Comment by jeremyevans** [comment]
The schema modification guide makes it fairly clear how to use the type name verbatim.  The only trouble I could see if you didn't know the type name for array type you wanted to use.

Providing concrete examples for every possible case would make the documentation even more voluminous than it already is.  The user who originally had this issue thought linking to the schema modification guide was the correct way to document it, and I agree.  That being said, if you think that is insufficient, please send a pull request with a documentation update.

**Comment by agirorn** [comment]
You're probably right regarding the correct way to document this feature.

I'm leaving this small code block on how to define [PostgreSql Arrays](http://www.postgresql.org/docs/9.4/static/arrays.html) for those like my that don't get this right away.

```ruby
Sequel.migration do
  change do
    create_table :once do
      column 'signature', :bytea
      column 'arguments', 'text[]' # PostgreSql Array
    end
  end
end
```
