### ISSUE TITLE
JSON Serializer on datasets gives unexpected results.

### ISSUE THREAD

**Issue by bryanrite** [jeremyevans/sequel#549]
I have been using the json_serializer plugin for generating JSON for an API.  Everything works great on single instances:

``` ruby
1.9.3p194 :001 > Relationship.first
 => #<Relationship @values={:id=>5, :on_air=>true, :created_at=>2012-09-13 12:47:12 -0700, :updated_at=>nil}> 
1.9.3p194 :002 > Relationship.first.to_json(naked: true, only: :id)
 => "{\"id\":5}"
```

When I want to convert a collection of `Relationship` objects, I get some unexpected results:

``` ruby
1.9.3p194 :004 > Relationship.all.to_json(naked: true, only: :id)
 => "[{\"id\":5,\"on_air\":true,\"created_at\":\"2012-09-13T12:47:12-07:00\",\"updated_at\":null},{\"id\":6,\"on_air\":true,\"created_at\":\"2012-09-13T12:47:55-07:00\",\"updated_at\":null},{\"id\":7,\"on_air\":true,\"created_at\":\"2012-09-13T12:48:29-07:00\",\"updated_at\":null}]" 
```

It generates proper JSON, but does not take options into account.  I understand this is running to_json on an instance of Array.

Using filters as the documentation shows:

``` ruby
1.9.3p194 :005 > Relationship.filter().to_json(naked: true, only: :id)
 => "[{\"json\":\"{\\\"id\\\":5}\"},{\"json\":\"{\\\"id\\\":6}\"},{\"json\":\"{\\\"id\\\":7}\"}]" 
```

Produces a better dataset but not valid JSON.  Looks like its been encoded twice.

Using the `array:` option produces the same as above:

``` ruby
1.9.3p194 :021 > Relationship.to_json(array: Relationship.filter(), naked: true, only: :id)
 => "[{\"json\":\"{\\\"id\\\":5}\"},{\"json\":\"{\\\"id\\\":6}\"},{\"json\":\"{\\\"id\\\":7}\"}]"
```

What I would expect is something more like:

``` ruby
"[{\"id\":5},{\"id\":6},{\"id\":7}]"
```

Is this the intended behaviour?

**Comment by Aryk** [comment]
On the ActiveSupport v5, they provide a way to bypass ActiveSupport#to_json and use the normal to_json via ::JSON.{generate,dump}(obj). From the documentation for AS > version 5:

> It should be noted that when using ::JSON.{generate,dump} directly, ActiveSupport's encoder is bypassed completely.

**Comment by jeremyevans** [comment]
That's a good point, but unfortunately I think changing Sequel's default behavior it would break compatibility who have overwritten `to_json` manually.  However, we can probably make that change in Sequel 5.

**Comment by Aryk** [comment]
Yeah, the whole to_json thing is quite a nasty issue due to ActiveSupport's treatment of things. They are some redeeming qualities however. I like the as_json convention as a precursor to the to_json.

Many times, like in testcases, etc, I want to see the hash version of the json. In your serializer, you essentially create a hash and to_json it (with some idiosyncrasies), but I can't access the actual hash in case I want to make further edits.

Perhaps there is an opportunity to create some kind of ActiveSupport Json Serializer plugin for Sequel that hooks into the as_json method so that I can construct a hash representation but use options like :include and :root.

Thoughts?

**Comment by jeremyevans** [comment]
I'm leery of using any additional parts of ActiveSupport in the plugins/extensions that ship with Sequel (we currently use ActiveModel::Naming in the active_model plugin and ActiveSupport::Duration in the pg_interval plugin).  But that sounds like a good idea for an external plugin.

**Comment by Aryk** [comment]
Makes sense! Will look into making an extension if it becomes a burning problem. For now I'm just using the JSON.dump which seems to be ok...
