### ISSUE TITLE
greater than, less than inequalities used with SQL formula possible?

### ISSUE THREAD

**Issue by troynt** [jeremyevans/sequel#579]
Hello,

I'm attempting to do something like...

SELECT \* FROM foo WHERE  10*field + 1 >= 21;

How do I get Sequel to recognize this?

Does Sequel have the ability to use tokens? e.g. ["10*field + 1 >= ?", 21]

I've spent a lot of time trying to figure this out, it should probably be added to the documentation, if this is  possible.

Thanks,

Troy

**Comment by alexdesi** [comment]
Thanks for your comment @jeremyevans , it is still valuable after so many years 😄 
However the rubyforge links are not valid anymore, 
here are the updated working ones:

Dataset Filtering: https://sequel.jeremyevans.net/rdoc/files/doc/dataset_filtering_rdoc.html
Virtual Row Bloks: https://sequel.jeremyevans.net/rdoc/files/doc/virtual_rows_rdoc.html
Sequel for SQL Users: https://sequel.jeremyevans.net/rdoc/files/doc/sql_rdoc.html
