### ISSUE TITLE
Sequel relies completely on the ruby JSON library

### ISSUE THREAD

**Issue by PetrKaleta** [jeremyevans/sequel#662]
Are you planning to use MultiJson instead of pure ruby JSON? For example in my sinatra app, I am using Oj JSON gem. Why? Because of its excellent performance. But if I'd like to use postgres 9.2 native JSON type, then Sequel is using ruby JSON gem, which is terribly slow. Same issue is with serialised columns, thats why I created my own serialisation format

```
Sequel::Plugins::Serialization.register_format(:oj_json,
                                               lambda{ |value| Oj.dump(value) },
                                               lambda{ |value| Oj.load(value.nil? ? 'null' : value) })
```

Maybe you should consider to use MultiJson, so it will be gem agnostic and every Sequel user should decide which gem to use.

What do you think?

**Comment by backward-crazy-mage-puppy-36** [comment]
@PetrKaleta @jeremyevans how can I setup Sequel to use Oj with https://github.com/jeremyevans/roda-sequel-stack?

**Comment by jeremyevans** [comment]
> @PetrKaleta @jeremyevans how can I setup Sequel to use Oj with https://github.com/jeremyevans/roda-sequel-stack?

You can override `Sequel.parse_json`, `Sequel.json_parser_error_class`, and `Sequel.object_to_json` to use Oj.  For Roda you can set the `:json_parser` and `:json_serializer` application options to use Oj.
