### ISSUE TITLE
Postgresql didn't like single quotation in where clause

### ISSUE THREAD

**Issue by gaku** [jeremyevans/sequel#798]
Postgresql didn't like single quotation in where clause.  When I pass condition using quoted field name, it produces a SQL statement that postgres didn't like.

Environment:
- jruby 1.7.9 (1.9.3p392) 2013-12-06 87b108a on Java HotSpot(TM) 64-Bit Server VM 1.7.051-b13 [darwin-x8664]
- sequel (4.9.0)
- Postgresql 9.3.2

I had a line like this:

```
    login = Login.first({'user_id' => user_id})   # didn't work
```

It resulted in the following error:

```
ERROR -- : Java::OrgPostgresqlUtil::PSQLException: ERROR: invalid input syntax for integer: "user_id"  
  Position: 31: SELECT * FROM "logins" WHERE ('user_id' = 25) LIMIT 1
```

From psql command line, I confirmed that it was a syntax error:

```
psql# SELECT * FROM "logins" WHERE ('user_id' = 25) LIMIT 1;  
ERROR:  invalid input syntax for integer: "user_id"  
```

```
SELECT * FROM "logins" WHERE ('user_id' = 25) LIMIT 1;  
```

or

```
SELECT * FROM "logins" WHERE (user_id = 25) LIMIT 1;  
```

were okay.

I could run it successfully with `:user_id => user_id` instead of `"user_id" => user_id`, but it would be nice if I can use both expressions.

`:user_id => user_id` generated the following SQL:

```
SELECT * FROM "logins" WHERE ("user_id" = 33) LIMIT 1
```

`"user_id" => user_id` generated:

```
SELECT * FROM "logins" WHERE ('user_id' = 33) LIMIT 1
```

**Comment by vbyno** [comment]
What is the best way to serialize all symbol values to strings? I mean, column values, not column names.
`where(category: :category_1)` is transformed to ```WHERE `category`=`category_1` ``` which raises `Mysql2::Error: Unknown column 'category_1'`

**Comment by jeremyevans** [comment]
@vbyno There isn't a way do that.  Symbols represent SQL identifiers in Sequel, not SQL strings, you need to fix your code: `where(category: :category_1.to_s)`
