### ISSUE TITLE
PG::InFailedSqlTransaction after rescuing UniqueConstraintViolation

### ISSUE THREAD

**Issue by elado** [jeremyevans/sequel#908]
After rescuing from `Sequel::UniqueConstraintViolation` I'm getting PG::InFailedSqlTransaction on every following query. Bug?

``` ruby
# migration
Sequel.migration do
  change do
    create_table :models do
      primary_key :id
      String :a, limit: 100, index: {unique: true}
    end
  end
end

# model
class Model < Sequel::Model
end

# code
begin
  Model.create(a: a)
rescue Sequel::UniqueConstraintViolation => e
  puts "x"
end

Model.count # raises PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by wuarmin** [comment]
@jeremyevans I have a similar issue. 


```ruby
def create
    retry_count = 0
    begin
      result = try_create(data, user, legacy_code_parts)
      retry_count += 1
    end while result.failure? && retry_count < MAX_RETRIES
end
```

**Comment by wuarmin** [comment]
@jeremyevans I have a similar issue in specs. I'm using your transaction-code, to rollback after each spec, but if the try_insert is called the second time I get a:

```txt
 # --- Caused by: ---
 # PG::InFailedSqlTransaction:
 #   ERROR:  current transaction is aborted, commands ignored until end of transaction block
 #   /usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:171:in `exec'
```


```ruby
def create
  retry_count = 0
  begin
    result = try_insert
    retry_count += 1
  end while result.failure? && retry_count < 5
end

def try_insert
  Sucess(Model.create(code: gen_new_code))
rescue Sequel::UniqueConstraintViolation
  Failure("code is already taken! Retry!")
end
```

Do you know why that is? 
Thanks

**Comment by jeremyevans** [comment]
You likely need to wrap in a savepoint, as explained above in https://github.com/jeremyevans/sequel/issues/908#issuecomment-61217226

If you still need help, please open a new discussion and provide a minimal self contained reproducible example.

**Comment by wuarmin** [comment]
> You likely need to wrap in a savepoint, as explained above in https://github.com/jeremyevans/sequel/issues/908#issuecomment-61217226

It is wrapped in an `auto_savepoint: true`. If this is not the case, the 1st attempt already fails

**Comment by jeremyevans** [comment]
If you still need help, please open a new discussion and provide a minimal self contained reproducible example.

**Comment by wuarmin** [comment]
Thanks I started a discussion at https://github.com/jeremyevans/sequel/discussions/2206
