### ISSUE TITLE
Wrong query for boolean column in sqlite3

### ISSUE THREAD

**Issue by morgoth** [jeremyevans/sequel#928]
In sqlite3 database I have table `comments` with boolean column `approved`
`DB[:comments].where(approved: true)` generates `"SELECT * FROM 'comments'. WHERE ('approved' = 1)"` which dooesn't work.
It should be `"SELECT * FROM 'comments' WHERE ('approved' = 't')"`

**Comment by jeremyevans** [comment]
Sequel now defaults to using integers for boolean columns, to match SQLite's recommendations (https://www.sqlite.org/datatype3.html).  If you want to use `'t'` and `'f'` for booleans: `DB.integer_booleans = false`.
