### ISSUE TITLE
Schema detection issue with mssql on 4.18.0

### ISSUE THREAD

**Issue by theschoolmaster** [jeremyevans/sequel#930]
Upgrading from 4.17.0 to 4.18.0 affects model schema detection for me.

###### On 4.17.0

    [1] app »  CartItem.db_schema
    = > {
           :cart_id => {
             :db_type => "int",
           :max_chars => nil,
             :default => nil,
          :allow_null => false,
         :column_size => 10,
               :scale => 0,
         :primary_key => false,
                :type => :integer,
        :ruby_default => nil
      },
      :cart_item_id => {
             :db_type => "int",
           :max_chars => nil,
             :default => nil,
          :allow_null => false,
         :column_size => 10,
               :scale => 0,
         :primary_key => false,
                :type => :integer,
        :ruby_default => nil
      },
        :created_at => {
             :db_type => "datetime",
           :max_chars => nil,
             :default => nil,
          :allow_null => true,
         :column_size => 23,
               :scale => 3,
         :primary_key => false,
                :type => :datetime,
        :ruby_default => nil
      },
          :quantity => {
             :db_type => "int",
           :max_chars => nil,
             :default => "(1)",
          :allow_null => false,
         :column_size => 10,
               :scale => 0,
         :primary_key => false,
                :type => :integer,
        :ruby_default => nil
      }, 
    }

###### On 4.18.0

    [1] app »  CartItem.db_schema
    => {
      :cart_item_id => {},
           :cart_id => {},
            :itemno => {},
          :quantity => {},
        :cart_price => {},
        :created_at => {},
        :updated_at => {},
       :cart_credit => {}
    }

I believe this is related to the removal of the JDBC parsing in https://github.com/jeremyevans/sequel/commit/ffd43ab700b1132046d9e6c91cc07b5bb25ee25a

I'm using SQL Server 2000 with Tiny-TDS.  Please let me know what other info would be helpful.

**Comment by jeremyevans** [comment]
This is expected, MSSQL schema detection only works on SQL Server 2005+ I believe.  In general SQL Server 2000 is not supported when using Sequel (and certainly not tested), though most things may still work.

If you want to work around the specific issue, you can remove the MSSQL schema parsing method, and have it fallback to the generic JDBC support: `Sequel::MSSQL::DatabaseMethods.send(:remove_method, :schema_parse_table)`
