### ISSUE TITLE
Sequel failing to report some MS SQL script errors.

### ISSUE THREAD

**Issue by crmckenzie** [jeremyevans/sequel#932]
I have a sql script that I'm executing on MS Sql Server using

    db.run sql

When I run the script in Sql Management Studio I get the following output:

    Msg 2601, Level 14, State 1, Line 34
    Cannot insert duplicate key row in object 'dbo.TABLE1 with unique index       'IDX_TABLE1_FIELD1'. The duplicate key value is (<NULL>).
    The statement has been terminated.
    Msg 515, Level 16, State 2, Line 78
    Cannot insert the value NULL into column 'Field2', table     'TABLE2; column does not allow nulls. INSERT fails.
    The statement has been terminated.

However, when I run the same script using db.run I get no errors. I've verified that the errors are occuring on the Sql Server by attaching SQL Server Profiler.

I have verified that Sequel does trap Sql Server errors of other kinds. It recognizes RAISERROR statements, sql formatting problems, and references to undefined variables. I don't know why it would ignore the above errors.

SQL Server version is: 

Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
	Aug 19 2014 12:21:34 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by jeremyevans** [comment]
Does your `sql` string contain multiple SQL statements separated by semicolons?  `Database#run`'s behavior when doing so is undefined.  It may give an error, it may run only the first statement, it may run all the statements.  I'm guessing on the adapter you are using, it only runs the first statement. `Database#run` is documented to only run SQL statement strings, not multiple SQL statements in a single string.

If your `sql` is a string with a single SQL statement, then please post a self contained example showing the issue, along with a backtrace and SQL log.

**Comment by crmckenzie** [comment]
Thank you for your quick reply :+1: 

I found one ';' in the script and removed it, but have the same behavior. It is a script with multiple sql statements. It sounds like your saying that sql scripts are unsupported by Sequel. If so, do you have a recommendation for another library or gem I could use?

Thanks!

**Comment by jeremyevans** [comment]
Correct, they are unsupported.  If the underlying adapter you are using supports it, you can drop down to the connection level (tiny_tds appears to, but I don't think jdbc does) :

```ruby
DB.synchronize do |conn|
   # some method on the connection object that supports sql scripts
end
```

At that point you are using the connection-specific API, so consult the underlying database driver for details.

If you are using JDBC, from what I've read, you have to parse the string into separate statements submitted individually, similar to how you would do it if you were using Sequel.

**Comment by jeremyevans** [comment]
Also, you might be able to run a system command using the `osql` program with the sql script filename.
