### ISSUE TITLE
dirty plugin: initial_value only works with symbols

### ISSUE THREAD

**Issue by JeanMertz** [jeremyevans/sequel#936]
```
sequel (4.11.0)
postgres (PostgreSQL) 9.2.8
ruby 2.0.0p598 (2014-11-13) [x86_64-darwin14.0.0]
```

expected:

```ruby
initial_value(:eur)
=> 100
```

unexpected:

```ruby
initial_value('eur')
=> 50
```

note that `100` is indeed the initial value, and `50` is actually the *new* value.

**Comment by jeremyevans** [comment]
The `initial_value` method documentation doesn't say that it takes a string, and all the examples show use with a symbol.  It needs to lookup the value in a symbol keyed hash, so if given a string, it would have to convert it to a symbol, with risks denial of service on ruby < 2.2.  The fact that you get the original value when passing a string is just do to the fact that `send` accepts a string.

In any case, this isn't a bug, many things in Sequel that expect symbols will not work the same if you pass strings.  Symbols and strings are different types of objects, and you shouldn't expect them to be treated the same in most cases.
