### ISSUE TITLE
rcte_tree plugin: set :ancestors association for ancestors

### ISSUE THREAD

**Issue by rumpuslabs** [jeremyevans/sequel#948]
Similarly to 20fb4ec50ff8d98fad87ca72eeb0696010f7ed8f but in reverse, it would be nice if the rcte_tree plugin set the :ancestors association for each of the ancestors, since it has already retrieved the necessary information from the database.

Example:
```ruby
m = Model.last
# SELECT * FROM `models` ORDER BY `id` DESC LIMIT 1
# => #<Model @values={:id=>8, :parent_id=>7}>
m.ancestors
# WITH `t` AS (SELECT * FROM `models` WHERE (`id` = 7) UNION ALL SELECT `models`.* FROM `models` INNER JOIN `t` ON (`t`.`parent_id` = `models`.`id`)) SELECT * FROM `t` AS 'models'
# => [#<Model @values={:id=>7, :parent_id=>6}>, #<Model @values={:id=>6, :parent_id=>5}>, #<Model @values={:id=>5, :parent_id=>nil}>]
m.parent
# => #<Account @values={:id=>7, :parent_id=>6}>
# No database query - good
m.parent.parent
# => #<Account @values={:id=>6, :parent_id=>5}>
# No database query - good
m.parent.ancestors
# WITH `t` AS (SELECT * FROM `models` WHERE (`id` = 6) UNION ALL SELECT `models`.* FROM `models` INNER JOIN `t` ON (`t`.`parent_id` = `models`.`id`)) SELECT * FROM `t` AS 'models'
# => [#<Model @values={:id=>6, :parent_id=>5}>, #<Model @values={:id=>5, :parent_id=>nil}>]
# Redundant database query here
```

**Comment by jeremyevans** [comment]
This is different than the change made 20fb4ec, and different from how `descendants` behaves (it sets `parent` and `child` on all descendants, not `descendants`).  The reasoning behind the behavior is the recursive associations should set the nonrecursive associations in the associated objects that it can determine from its own query, not the same recursive associations.  If we wanted to be similar to `descendants`, we'd also have to change `descendants` to also set `descendants` in the associated objects.

In terms of cost/benefit, I'm not sure it's worth it to do have recursive associations set recursive associations in associated objects by default. Do you have a  use case in mind for this?

BTW, this is fairly trivial to implement via an `after_load` hook:

```ruby
plugin :rcte_tree, :ancestors=>{:after_load=>proc do |_, a|
  a.each do |v|
    a = v.associations[:ancestors] = a[1..-1]
  end
  end}
```

**Comment by rumpuslabs** [comment]
My use case is specific to `ancestors` and it's something like this:

```ruby
class Model < Sequel::Model
  plugin :rcte_tree

  def full_name
    [self, *ancestors].map(&:name).reverse.join(":")
  end
end

m = Model.last
# SELECT * FROM `models` ORDER BY `id` DESC LIMIT 1
m.full_name
# WITH `t` AS (SELECT * FROM `models` WHERE (`id` = 3) UNION ALL SELECT `models`.* FROM `models` INNER JOIN `t` ON (`t`.`parent_id` = `models`.`id`)) SELECT * FROM `t` AS 'models'
# => "A:B:C:D"
m.parent.full_name
# WITH `t` AS (SELECT `id` AS 'x_root_x', `models`.* FROM `models` WHERE (`id` IN (2, 1)) UNION ALL SELECT `t`.`x_root_x`, `models`.* FROM `models` INNER JOIN `t` ON (`t`.`parent_id` = `models`.`id`)) SELECT * FROM `t` AS 'models'
# => "A:B:C"
```

I don't have a strong use case for `descendants`.

I didn't realise it would be so easy to do with an `after_load` hook, but is there any reason why that shouldn't be the default behaviour? It seems fairly inexpensive, at least for `ancestors` - similar to setting `parent` for each one.

**Comment by jeremyevans** [comment]
For `ancestors`, it isn't very expensive, but it would be significantly more expensive for `descendants`.  There is no reason that `ancestors` and `descendants` have to be consistent, I guess.  I'll try to implement this tomorrow.

**Comment by jeremyevans** [comment]
It looks like this is not as simple as I thought.  The problem is that the order in ancestors is not guaranteed, you cannot rely on it being in parent, grand parent, great grant parent, etc. order.  So the code I gave you does not work for the general case.  Additionally, the code you are using for `full_name` is relying on undefined behavior.  I don't think your `full_name` implementation will break unless you start to specify an `:order` for the association, though.

Because of this, it is not so simple to set up the ancestors association for all ancestors automatically, and therefore I don't think the benefit is worth the cost.  A better fix for your use case:

```ruby
  def full_name
    ancs = [self]
    while p = parent
      ancs.unshift p
    end
    ancs.map(&:name).join(":")
  end
```

**Comment by rumpuslabs** [comment]
OK so here's what I came up with, it defines `ancestors` recursively to make my definition of `full_name` work regardless of database ordering *and* avoids redundant database calls when calling `parent.ancestors`. It makes use of the fact that the current implementation of `ancestors` sets the `parent` associations all the way up the tree.

```ruby
class Model < Sequel::Model
  # Redefine ancestors to ensure correct ordering and
  # avoid redundant database calls
  def ancestors
    super unless associations.has_key?(:parent) #preload
    parent.nil? ? [] : [parent, *parent.ancestors]
  end
end
```

I'm reasonably happy with this as a solution for my application unless you want to implement something equivalent into Sequel directly.

**Comment by jeremyevans** [comment]
I think that's fine.  A while loop will probably outperform a recursive version, though.
