### ISSUE TITLE
Eager loading with nil foreign key causes a potentially long-running query

### ISSUE THREAD

**Issue by Blargel** [jeremyevans/sequel#952]
I have a ratings table that has a foreign key for the users table. In some cases, I have ratings that have user_id set to null in the database. If I make a dataset that happens to contain only ratings that have no user_id, calling eager(:user) on the dataset will generate this query:

SELECT * FROM "USERS" WHERE ("USERS"."ID" != "USERS"."ID")

On top of obviously getting no results, this query takes longer and longer as the users table grows. It currently takes 7 seconds to complete.

The issue started happening with Sequel 4.10.0 and still exists as of 4.19.0. This was tested against an Oracle database.

**Comment by jeremyevans** [comment]
Thanks for the report. This is probably due to the placeholder literalizer optimization.  It should probably be changed to not issue a query if the related array of keys is empty.  I'll work on that soon.
