### ISSUE TITLE
association selecting the wrong column

### ISSUE THREAD

**Issue by cj** [jeremyevans/sequel#954]
Hi,

We have the following tables.

```
issues
---+-----------------+----------------+
id | company_id | auditor_id |
---+-----------------+----------------+
1  | 10                 | 2
---+-----------------+----------------+

users
---+-----------------+
id | company_id |
---+-----------------+
2  | 15                 |
---+-----------------+

companies
---+--------+
id | name |
---+--------+
10| foo     |
---+--------+
15| bar     |
---+--------+
```

and the following files

```ruby
class SomeApp
  module Models
    class Issue < Sequel::Model
      many_to_one :company, class: 'SomeApp::Models::Company'
      many_to_one :auditor, class: 'SomeApp::Models::User'
    end
  end
end

class SomeApp
  module Models
    class User < Sequel::Model
      many_to_one :company
    end
  end
end

class SomeApp
  module Models
    class Company < Sequel::Model
    end
  end
end

# basic plugins
Sequel::Model.plugin :schema
Sequel::Model.plugin :validation_helpers
Sequel::Model.plugin :nested_attributes
Sequel::Model.plugin :restrict_user

# Auto-manage created_at/updated_at fields
Sequel::Model.plugin :timestamps, :update_on_create => true

Sequel.extension :migration
Sequel.extension :core_extensions

#DB = Sequel.connect(adapter: 'postgres', database: 'db', username: 'user', password: 'pw')
class SomeApp
  DB = Sequel.connect DATABASE_URL unless defined? DB

  # Extensions
  DB.extension :pagination

  DB.loggers << PrettyLogger.logger if RACK_ENV == 'development'
end
```

When we do the following:

```ruby
SomeApp::Models::Issue.association_left_join(:company, :auditor).eager(:company, :auditor).all
```

It will return company id `15` and not `10`, when you remove the `auditor` from the `association_left_join` it will return the correct company `10`

**Comment by jeremyevans** [comment]
This is expected.  The default selection is `*`, so you get all columns from all tables, and if any of the tables have columns with the same name, later columns will override earlier columns.  There are a few things you can do:

1) Use the `table_select` or `column_select` plugins, which change the default selections for models.
2) Use `eager_graph` instead of `association_left_join.eager`.  I can't think of a reason why you would want to do `association_left_join.eager` over `eager_graph`.
3) Set an explicit selection for the dataset: `.select_all(:issues)`

I'm certainly open to pull requests that make the documentation on this more clear.

**Comment by TSMMark** [comment]
@jeremyevans I almost exclusively have positive experiences with Sequel, but this behavior consistently trips up my team and I. It's very easy to make a mistake and never notice. In my opinion, Sequel should warn you or raise an exception if you try to load results and keys are overwritten.

Do you know if anything like this exists? A plugin perhaps? I could not find anything.

If not, I'm more than happy to submit a PR if you could point me in the right direction.

Thanks

**Comment by jeremyevans** [comment]
The table_select and column_select plugins both change the default selection and avoid this issue.

**Comment by TSMMark** [comment]
Thanks, I saw your comment from earlier in this thread. However, I would much prefer a warning / exception approach, rather than altering the way our queries are behaving currently. It seems likely that introducing either of these plugins would have rippling consequences.

**Comment by jeremyevans** [comment]
That would require modifying all of the adapters that Sequel supports to give them the ability to check for duplicate column names, and then adding an extension that would modify behavior to warn/raise in that case.  I'm not opposed to that idea, I'll see if I can implement it before the next release.  I wouldn't be surprised if that warns/raises in a lot of cases that are perfectly fine, but as long as it only affects the people who specifically load the extension, that's acceptable.

**Comment by TSMMark** [comment]
That sounds like a lot of work. Is there a way I can help out?

**Comment by jeremyevans** [comment]
If you want to take a crack that this yourself, modify all of the adapters (lib/sequel/adapters/*.rb) and change `@columns = ...` to `self.columns = ...`.  Add a private columns attr_writer to Sequel::Dataset.  Add a dataset extension that overrides `columns=` and checks that the arguments are unique, and warns/raises if not.  And the usual specs and documentation.  Ideally add support for an environment variable that can be set when running the adapter/integration tests that uses the extension automatically and see if this situation affects any of the existing specs.
