### ISSUE TITLE
Documentation of foreign keys

### ISSUE THREAD

**Issue by contradictioned** [jeremyevans/sequel#956]
Hello,

I just noticed that in the documentation under http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-foreign_key stands that `foreign_key` takes column name and table name as parameters. But right after there is this code example:

    foreign_key :column_name, :unique=>true, :type=>'varchar(16)'

Is this wrong? (If so, I'd be happy to make a correcting pull request)

**Comment by agugaillard** [comment]
When you specify only one parameter, it references to the column of the same table you are on. If you specify two parameters, it looks for the column in that specific table. @jeremyevans Correct me if I'm wrong.

**Comment by jeremyevans** [comment]
For backwards compatibility, if the table argument is not given, foreign_key just creates an `Integer` column not referencing another table.  This is not encouraged in new code, so the documentation should be updated.  I'll take care of this shortly.
