### ISSUE TITLE
Sequel::Model#initialize sometimes raises ArgumentError

### ISSUE THREAD

**Issue by YorickPeterse** [jeremyevans/sequel#960]
Lately I've been seeing errors such as the following pop up in some of our Sequel applications:

    ArgumentError: wrong number of arguments (-8 for 0..1)
    /var/www/contextvoice_collector/deploy-2015-02-23_17_10_41/vendor/bundle/ruby/2.2.0/gems/sequel-4.19.0/lib/sequel/model/base.rb" line 1171 in initialize
    /var/www/contextvoice_collector/deploy-2015-02-23_17_10_41/lib/contextvoice_collector/social_mention_store.rb" line 12 in new
    ...

Which leads to the following code:

https://github.com/jeremyevans/sequel/blob/50f3f08a5725097207fb0bf0a93ffdb6d831e96d/lib/sequel/model/base.rb#L1171

These particular applications rely quite heavily on multi-threading (although models are always eager loaded during boot) and currently run on MRI 2.2. I'm not really sure what's causing this and thus far have been unable to reproduce this reliably, let alone in a standalone script :disappointed: 

Looking at the code I'm not sure how this error can occur, or what the message even means. The code that initializes said model is as following:

    sm = SocialMention.new(
      :connection_id => connection.id,
      :hotel_id      => connection.hotel_id,
      :title         => result["title"],
      :content       => result["content"],
      :mention_id    => result["id"],
      :generator     => result["generator"],
      :url           => result["url"],
      :thumbnail_url => (result["thumbnail"]["url"] rescue nil),
      :published     => Time.at(result["published"].to_i),
      :created_at    => Time.now.utc
    )

This doesn't even pass 8 arguments, nor 8 Hash keys, so where the -8 comes from is a mystery to me.

**Comment by YorickPeterse** [comment]
Seems this can't be triggered by `initialize` somehow _not_ having any arguments, as in that case you'd get an error like so:

    def foo; end
    foo(:a => 10, :b => 20, :c => 10)
    ArgumentError: wrong number of arguments (1 for 0)

**Comment by jeremyevans** [comment]
This does not appear to be a bug in Sequel, but rather in MRI 2.2.  Does it happen on earlier MRI versions?  Are you running the `ruby_2_2` branch from git, or the 2.2.0 release?  If you aren't running the `ruby_2_2` branch, you may want to try that to see if the problem has been fixed.

**Comment by YorickPeterse** [comment]
We're running the 2.2 stable release of MRI (`ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]` to be exact). I've never seen this problem occur on older versions of MRI or other implementations (e.g. Rubinius). 

Are there any parts of `Sequel::Model` that are loaded lazily? I don't think it's the case, but if so that _might_ interfere. My bets however are indeed on an MRI bug, although so far I've only seen it occur in Sequel models (and not other, custom code, yet).

**Comment by YorickPeterse** [comment]
One thought I had was that perhaps this is related to keyword arguments support, but those trigger different errors. For example:

```
~ $ pry
2.2.0p0 > def foo(a:,b:,c:)
2.2.0p0 * end  
=> :foo
2.2.0p0 > foo
ArgumentError: missing keywords: a, b, c
from (pry):1:in `foo'
2.2.0p0 > foo(10, 20, 30)
ArgumentError: wrong number of arguments (3 for 0)
from (pry):1:in `foo'
2.2.0p0 > foo(:a => 10, :b => 20, :c => 30)
=> nil
2.2.0p0 > foo(:a => 10, :b => 20, :c => 30, :d => 40)
ArgumentError: unknown keyword: d
from (pry):1:in `foo'
```

I'll see if I can do some digging in the coming week to figure out if this is actually related to Sequel or if it just happens to trigger it by coincidence.

**Comment by jeremyevans** [comment]
`Sequel::Model` doesn't use autoload, so the only time things would be lazy loaded is if you are loading plugins.  The only plugin that overrides `Sequel::Model#initialize` is `after_initialize`.  But in general, people don't load plugins at runtime, only during application initialization.

Sequel does not use keyword arguments, so this should not be related to any issues with keyword arguments.

I'm going to close this now as it is very unlikely to be a Sequel bug.  If you find more information that makes you think this is a Sequel bug as opposed to a bug in MRI 2.2, please let me know and I'll reopen.
