### ISSUE TITLE
Feature request: 'before_commit' hook

### ISSUE THREAD

**Issue by rumpuslabs** [jeremyevans/sequel#962]
I would like to be able to add a `before_commit` hook that validates all the relationships between my newly created or modified objects right before the transaction is committed.

For example suppose I have this schema:

```ruby
class Transaction < Sequel::Model
  one_to_many :entries

  def validate
    super
    validates_min_length 2, :entries
    errors.add(:entries, "must sum to zero") if entries.inject(0){|s,e|s+e.amount} != 0
  end
end

class Entry < Sequel::Model
  many_to_one :transaction
end
```

Because `Entry` holds the foreign key for `Transaction`, I can't create the `entries` until the `Transaction` is saved, but then my `Transaction#validate` fails when saving the first time and also is not guaranteed to be run after all the `entries` are added.

If I could add a `before_commit` hook to both `Entry` and `Transaction` that made sure that the entries of a transaction all sum to zero any time a `Transaction` or `Entry` is created or modified, this would ensure my database consistent at all times (except during the database transaction while the complete `Transaction` is still being constructed).

**Comment by jeremyevans** [comment]
First, as explained in the contribution guidlines, GitHub Issues should be used only for bug reports, not for requesting features.  Feature requests should be posted on the sequel-talk Google Group.

In terms of validating associated objects at the same time as the current object, the nested_attributes plugin takes care of this use case, or you can implement it yourself using the more low-level instance_hooks plugin.  So I think a before_commit hook may not be necessary.

Note that if you want to ensure data integrity, you should have a deferred database trigger that does the same check.

**Comment by rumpuslabs** [comment]
Thanks, I don't think `instance_hooks` entirely solves my use case but I have started a discussion in the Google Group as you requested.
