### ISSUE TITLE
SQLite3  Autoincrement

### ISSUE THREAD

**Issue by da1l6** [jeremyevans/sequel#965]
With commit e22a22343c0a08d086233705c0c7be8f8dc19a3b the autoincrement keyword of primary keys in SQLite DBs was dropped.
This creates a semantic change in how sqlite assigns the primary key values.
(See: https://www.sqlite.org/autoinc.html)
If rows are deleted the primary key of deleted rows may be reused.
I can confirm that this is the case if the row with the highest primary key is deleted, this key will be reused for the next row inserted.

Pseudocode example:

```ruby
create_table(:test){
primary_key: id
...
}

row1 = Test.new()
...
row1.save #row1id == 1
...
row1.delete

row2 = Test.new()
...
row2.save #row2id == 1 since e22a2234
```
Commit e22a2234 does not really give a reason why this change was made and the code comment is somewhat misleading.

I need the old behaviour of always incrementing primary keys to conform to an external API spec.
With the current sequel code there is no way to achieve it.

To explicitly disable autoincrement one could always always use
```Integer :id, :primary_key => true```
instead.

da1l6

**Comment by jeremyevans** [comment]
Thanks for the report.  IIRC, the change was made to fix some schema modification methods on SQLite after the introduction of `:auto_increment` to the schema hashes.  I wasn't aware it affected SQLite's behavior in terms of allowing primary key values to be reused.  I'll see if I can fix the schema modification methods in a different way, and restore the previous behavior.
