### ISSUE TITLE
Sql Server insert statement without output

### ISSUE THREAD

**Issue by JonathanFrias** [jeremyevans/sequel#967]
I have run into an edge case that's not properly handled when when working with the mssql adapter. The case for which you can issue an insert statement without output support can still returns a result set. I actually found this issue when working with sqlserver view that contains an instead of trigger. See https://msdn.microsoft.com/en-us/library/ms177564.aspx and scroll down to section: `H. Using OUTPUT in an INSTEAD OF trigger`

For a bit more detail, suppose I have a class that corresponds to a sql-server view as such:

```
class Foo < Sequel::Model
	self.dataset = self.dataset.disable_insert_output
end
```

Seeing as this is a view, I have an instead of insert trigger on the table that allows the insertion to occur at the proper table. The instead of query that runs instead is configured to use insert OUTPUT. 

Currently working on a patch that can handle this edge case, but wanted to open up discussion about it as well.

**Comment by jeremyevans** [comment]
This doesn't seem like a bug, as what you are describing is not something that Sequel supports.  If you do come up with a patch that will handle this case without affecting other cases, please submit a pull request and I'll definitely review it.

One simple way to work around it may be to change the SQL generation method in the dataset to  not use an `OUTPUT` clause even if the necessary entry is present in the query.  You could try this:

```ruby
def (Foo.dataset).output_sql; end
```

**Comment by jeremyevans** [comment]
Closing now as this isn't a bug.  If you can't get it to work, please open up a thread on the sequel-talk Google Group and we'll try to come up with a way to handle your need.

**Comment by JonathanFrias** [comment]
Just for completeness since I created this issue, this is the code I ended up using.

```
    class <<instance_dataset
      def insert_select_sql(*values)
        self.insert_sql(*values)
      end
    end
```

Thanks Jeremy!

**Comment by jrgns** [comment]
Leaving this here, would love some contributions to the discussion - https://groups.google.com/forum/#!topic/sequel-talk/j-Pnxrycl-U
