### ISSUE TITLE
CRUD key-value in hstore 

### ISSUE THREAD

**Issue by cookiebody** [jeremyevans/sequel#970]
I can find how to use hstore in [Postgresql's document](http://www.postgresql.org/docs/9.1/static/hstore.html).
Is there any Sequel's way to CRUD hstore?
Especillay, delete/update the key-value in hstore, for example:
```sql
-- delete key
UPDATE tab SET h = delete(h, 'k1');
-- update key
UPDATE tab SET h = h || ('c' => '3');
```

For now, I can find two ways in Sequel, neither that good for me:
1) run raw sql with ```DB.run```
2) delete/update key-value in memory, then update the column:
```ruby
DB[:tab].where(:id => 1).update(:h => Sequel.hstore({'c' => '3'}))
```

**Comment by jeremyevans** [comment]
Use the `pg_hstore_ops` extension: http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pg_hstore_ops_rb.html

```ruby
DB[:tab].update(:h=>Sequel.hstore_op(:h).delete('k1'))
DB[:tab].update(:h=>Sequel.hstore_op(:h).concat('c'=>3))
```

Note that in general when using Sequel, using raw SQL for part of the query is always possible using `Sequel.lit`:

```ruby
DB[:tab].update(:h=>Sequel.lit("delete(h, 'k1')"))
DB[:tab].update(:h=>Sequel.lit("h || ('c1' => '3')"))
```

In the future, note that as mentioned in the contribution guidelines, GitHub Issues should not be used as a help forum.  Questions about how to use Sequel should be asked on IRC or the sequel-talk Google Group.

**Comment by cookiebody** [comment]
Thanks, it works, and really sorry for violating the guidelines.

I read the `pg_hstore_ops` document before, but could not figure out how to use it, there are no example to show how to save changes. I tried Google, but found nothing helpful.
The demo code should be added in document.
