### ISSUE TITLE
Oracle with Ruby 2.2

### ISSUE THREAD

**Issue by MarioRuiz** [jeremyevans/sequel#973]
When trying to connect to oracle using Ruby 2.2.1p85 and Sequel 4.20.0
LoadError: cannot load such file -- oci8lib_220 (Sequel::AdapterNotFound)

I had any problems when using Ruby 2.0

**Comment by jeremyevans** [comment]
Can you connect via oci8 directly?  What happens when you `require 'oci8'`?  This appears to be a driver issue, not an issue with Sequel.

**Comment by MarioRuiz** [comment]
well... I think the problem maybe it is with the Ruby Installer.. now I used the Ruby 2.1 and no problems... so i guess it is related to it.
