### ISSUE TITLE
Class Table Inheritance columns.

### ISSUE THREAD

**Issue by frodsan** [jeremyevans/sequel#974]
Hi Jeremy,

I'm trying to set up the class table inheritance plugin. I found that the `columns` method
in the child class results in duplicated columns:

```ruby
class User < Sequel::Model
end

class Agent < Sequel::Model
end

User.columns
# => [:id, :first_name, :last_name, :email, :created_at, :updated_at]

Agent.columns
# => [:id, :first_name, :last_name, :email, :created_at, :updated_at,
# :first_name, :last_name, :email, :created_at, :updated_at, :phone, :company_name]
```

Is this expected?

Thanks.

**Comment by jeremyevans** [comment]
Are you duplicating the columns in User's table in Agent's table (other than the primary key column)?  If so, that's now how class table inheritance is supposed to be used.  You shouldn't repeat User table's columns in Agent's table, the whole reason for class table inheritance is that the columns for User are inherited in Agent.

If you aren't duplicating the columns in User's table in Agent's table, but you still get duplicates in Agent.columns, can you post a self-contained example showing the problem?  The specs test for the output of columns and don't fail, so I would need to be able to test with a failing example.

**Comment by frodsan** [comment]
Maybe it has to be with [how the dataset is set up](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/plugins/class_table_inheritance.rb#L184...L185).

```
Agent.dataset
=> #<Sequel::Postgres::Dataset: "SELECT \"users\".\"id\", \"users\".\"first_name\", \"users\".\"last_name\", \"users\".\"email\", \"users\".\"type\", \"users\".\"created_at\", \"users\".\"updated_at\", \"agents\".\"first_name\", \"agents\".\"last_name\", \"agents\".\"email\", \"agents\".\"type\", \"agents\".\"created_at\", \"agents\".\"updated_at\", \"agents\".\"phone\", \"agents\".\"dre_license\", \"agents\".\"company_name\" FROM \"users\" INNER JOIN \"agents\" ON (\"agents\".\"id\" = \"users\".\"id\")">

>> Agent.dataset.columns
=> [:id, :first_name, :last_name, :email, :type, :created_at, :updated_at, :first_name, :last_name, :email, :type, :created_at, :updated_at, :phone, :dre_license, :company_name]
```

I changed that line from `self.columns` to `columns` and it gave me correct results:

```
>> Agent.dataset
=> #<Sequel::Postgres::Dataset: "SELECT \"users\".\"id\", \"users\".\"first_name\", \"users\".\"last_name\", \"users\".\"email\", \"users\".\"type\", \"users\".\"created_at\", \"users\".\"updated_at\", \"agents\".\"first_name\", \"agents\".\"last_name\", \"agents\".\"email\", \"agents\".\"type\", \"agents\".\"created_at\", \"agents\".\"updated_at\", \"agents\".\"phone\", \"agents\".\"dre_license\", \"agents\".\"company_name\" FROM \"users\" INNER JOIN \"agents\" ON (\"agents\".\"id\" = \"users\".\"id\")">

>> Agent.columns
=> [:id, :first_name, :last_name, :email, :type, :created_at, :updated_at, :phone, :dre_license, :company_name]
```

I will make a test app.

**Comment by frodsan** [comment]
I created a test app: https://github.com/frodsan/sequel-issue-974

**Comment by jeremyevans** [comment]
You are using PostgreSQL table inheritance, which shouldn't be used with the class_table_inheritance plugin.  With PostgreSQL table inheritance, you can just subclass and use set_dataset in the subclass:

```ruby
class User < Sequel::Model; end
class Agent < User
   set_dataset :agents
end
```

**Comment by frodsan** [comment]
Ok, thank you so much!
