### ISSUE TITLE
Wrong fallback in Sequel.pg_jsonb

### ISSUE THREAD

**Issue by andreas-kopecky** [jeremyevans/sequel#977]
The default return statement in Sequel.pg_jsonb should be Sequel.pg_jsonb_op instead of Sequel.pg_json_op.

Reference: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pg_json.rb#L299

In addition the comments of this method are - strictly speaking - not true since they refer to Sequel::Postgres::JSONXXX instead of Sequel::Postgres::JSONBXXX

**Comment by jeremyevans** [comment]
Good catch, thanks for reporting.  I'm working on a patch for this now, it should be merged soon.

**Comment by andreas-kopecky** [comment]
Thanks! And thanks for creating the by far best ORM i have worked with so
far (and it's been some :) )
Am 17.03.2015 16:10 schrieb "Jeremy Evans" <notifications@github.com>:
