### ISSUE TITLE
Validation on a many-to-many association

### ISSUE THREAD

**Issue by jackfranklin** [jeremyevans/sequel#984]
Hey!

Firstly, thanks for the gem, really enjoying working with it. I've come across a problem that I'm struggling to figure out and any advice or pointers you could give would be great. I might be approaching this from entirely the wrong direction.

I have two models - matches and users, which are a `many_to_many`. I've created the joins table and I can use `match.add_user(user)` successfully to add a user to a match.

However, there are certain conditions (that are irrelevant here) that dictate if a user is able to be added to the match. I figured I could validate this by adding a line to the `validate` method:

```rb
# in Match
def validate
  super
  errors.add(:user, 'is not valid') if any_user_cannot_be_part_of_match?
end
```

Where `any_user_cannot_be_part_of_match?` is defined as:

```rb
users.any? { ... condition ... }
```

However, it isn't working and the user is being added. At the point that validation is called, `users` doesn't contain the new user, just the ones already persisted, and hence that means every new user is always valid.

I tried overriding the `add_user` method:

```rb
def add_user(user)
  errors.add(:user, 'is not valid') if user_is_not_valid?(user)
  super
end
```

But that doesn't seem to have any affect either.

I think I'm probably missing something or doing it wrong - any advice would be great!

EDIT - thinking about the problem a bit more, I think it's an issue because it's a many-to-many, and hence when a new association is added, neither of the models gets saved or updated, so no validation would run. I guess I need someway of validating before the row in the intermediary table is saved.

Thanks :)

**Comment by jeremyevans** [comment]
There are a couple options for what you want.  The first would be adding a before_add hook to the users association, and having it return false if the user is not valid to be added.  The second would be keeping the code in validate, but using the nested_attributes plugin to update the association, as that doesn't save changes unless all associated objects are valid.

In the future, note that as stated in the contribution guidelines, questions about how to use Sequel should be asked on the Google Group or IRC.  GitHub Issues should only be used to report bugs in Sequel.
