### ISSUE TITLE
Do not reconnect to the DB after forking in Unicorn

### ISSUE THREAD

**Issue by generalzhou** [jeremyevans/sequel#985]
Hi Jeremy, I wanted to bring to your attention weird behavior that occurs with establishing DB transactions when using a rails unicorn configuration. Here is the unicorn configuration I am speaking of:

```
before_fork do |server, worker|
  # the following is highly recomended for Rails + "preload_app true"
  # as there's no need for the master process to hold a connection
  DB.disconnect
end

after_fork do |server, worker|
  # the following is *required* for Rails + "preload_app true",
  CONNECT_TO_DB.call
end
```

```
CONNECT_TO_DB = Proc.new do
  DB = Sequel.connect(POSTGRES_URL, max_connections: 2)
  unless %w(development test).include?(ENV['RACK_ENV'])
    DB.extension(:connection_validator)
    DB.pool.connection_validation_timeout = 300
  end
end
```

We have been using this config borrowed from Rails apps on multiple configs without any apparent issue, until we had issues with duplicated rows being created when there was supposed to be a database lock. Looking into this further, we saw that this code:

```
DB.transaction do
  ListingData.for_update.first(id: id)
end
```

correctly leads to this DB log output when using Webrick:

```
INFO -- : (0.000196s) BEGIN
INFO -- : (0.007694s) SELECT * FROM "listings" WHERE ("id" = 'ecc122af-cfba-42e5-90e0-90284c8d3885') LIMIT 1 FOR UPDATE
INFO -- : (0.000243s) COMMIT
```

However, when running Unicorn:

```
INFO -- : (0.001263s) SELECT * FROM "listings" WHERE ("id" = '09f19843-7b12-4d07-8005-71cfd802a6d8') LIMIT 1 FOR UPDATE
```

No transaction is initiated

In fact, even when I explicitly run ```DB.run("BEGIN")``` in Unicorn, no BEGIN message is ever sent to the DB. 

Eventually, we figured out that the offending line was reconnecting to the DB in the after_fork block in the Unicorn config. 

You mention that reconnecting is not necessary in the code order [documentation](http://sequel.jeremyevans.net/rdoc/files/doc/code_order_rdoc.html). I wanted to ask you why this behavior occurs. I also wanted to document this issue in case anyone else comes across this, as reconnecting to the DB after forking is probably something that many people coming to Sequel from ActiveRecord are going to do.

**Comment by bougyman** [comment]
We use a similar config in our rails app and have come across the same thing. With activerecord we must reconnect in the after_fork, with Sequel we do not, and get weird transaction behavior when we try.

**Comment by jeremyevans** [comment]
If you are using preload_app with unicorn, then all you need to do is disconnect in before_fork (which you are doing), what you are doing in after_fork may be messing things up, since you are creating a new Database object, which probably results in DB being a different Database than your model classes use.

In the future, note that questions about how to use Sequel should be asked on the sequel-talk Google Group or IRC.  GitHub Issues should only be used for reporting bugs in Sequel.
