### ISSUE TITLE
not reading proper dataset on load

### ISSUE THREAD

**Issue by anazar** [jeremyevans/sequel#997]
We see a number of issues like this on application load:

```
ERROR Mysql2::Error: Table 'primary_db.histories' doesn't exist: DESCRIBE `histories`
ERROR Mysql2::Error: Table 'primary_db.histories' doesn't exist: SELECT `histories`.* FROM `histories` LIMIT 1
ERROR Mysql2::Error: Table 'primary_db.histories' doesn't exist: SELECT `histories`.* FROM `histories` LIMIT 1
```

In the model we have:
```
set_dataset "other_db__histories".to_sym
```

**Comment by jeremyevans** [comment]
This is expected, as the query to get the schema happens immediately when you create the class.  You should use the following form if you want to avoid the bad queries:

`class History < Sequel::Model(:other_db__histories)`

This sets the dataset before retrieving the schema, which fixes the issue.

**Comment by anazar** [comment]
That makes sense!  Thanks! :+1:
